force-app/main/default/objects/PublicAccessTest__c/PublicAccessTest__c.object-meta.xml
<CustomObject>
    <description>Tests that the Dog/Client team can perform in public.</description>
    <label>PAT</label>
    <nameField>
        <displayFormat>PAT-{0000}</displayFormat>
        <label>Public Access Test Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PATs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PublicAccessTest__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person assessing the team</description>
    <label>Assessor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Public_Access_Tests_Assessor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/DateCompleted__c.field-meta.xml
<CustomField>
    <fullName>DateCompleted__c</fullName>
    <description>Date the test was completed</description>
    <label>Date Completed</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Handler in the team, if not the client</description>
    <label>Handler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Public_Access_Tests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Relative location of the test</description>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the PAT</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Provisionally Passed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Team the test is for</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>PATs</relationshipLabel>
    <relationshipName>PATs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Public Access Test</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
            </value>
            <value>
                <fullName>Recertification</fullName>
            </value>
            <value>
                <fullName>Retest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/ValidUntil__c.field-meta.xml
<CustomField>
    <fullName>ValidUntil__c</fullName>
    <description>Date the test is valid until</description>
    <label>Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Records the Facilitator, Lead, and Client relationship</description>
    <label>Team</label>
    <nameField>
        <displayFormat>Team-{00000}</displayFormat>
        <label>Team Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Handler in the team, if not the client</description>
    <label>Handler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>This status defines the status for the Team, Dog, and Client.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In ADSiM</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Certified-Hold</fullName>
            </value>
            <value>
                <fullName>Decertified</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/test/public-access-tests/TestPublicAccessTestRepository.cls
/**
 * This class contains unit tests for validating the behavior of Apex class PublicAccessTestRepository
 */
@isTest
private class TestPublicAccessTestRepository{
    static PublicAccessTestRepository repo = new PublicAccessTestRepository();
    @isTest
    static void getPassing_returnsEmptyListWhenNone(){
        Id teamId = MockProvider.createId(Team__c.class);
        List<PublicAccessTest__c> actual = repo.getPassing(teamId);
        // assert
        System.assertEquals(0, actual.size(), 'should be an empty list');
    }

    @isTest
    static void getPassing_returnsNoneWhenNonePassing(){
        Date expiration = Date.today().addYears(1);
        Team__c team = TestPatTrigger.setup(expiration);

        PublicAccessTest__c pat = new PublicAccessTest__c(
            Assessor__c = team.Handler__c, 
            DateCompleted__c = Date.today(), 
            Location__c = 'In Person', 
            Status__c = 'Failed', 
            Team__c = team.Id, 
            Type__c = 'Initial', 
            ValidUntil__c = expiration
        );
        insert pat;
        List<PublicAccessTest__c> actual = repo.getPassing(team.Id);
        // assert
        System.assertEquals(0, actual.size(), 'should be an empty list');
    }

    @isTest
    static void getPassing_returnsPassing(){
        Date expiration = Date.today().addYears(1);
        Team__c team = TestPatTrigger.setup(expiration);

        PublicAccessTest__c pat = new PublicAccessTest__c(
            Assessor__c = team.Handler__c, 
            DateCompleted__c = Date.today(), 
            Location__c = 'In Person', 
            Status__c = 'Passed', 
            Team__c = team.Id, 
            Type__c = 'Initial', 
            ValidUntil__c = expiration
        );
        insert pat;
        List<PublicAccessTest__c> result = repo.getPassing(team.Id);
        // assert
        System.assertEquals(1, result.size(), 'should have one element');
        PublicAccessTest__c actual = result[0];
        System.assertEquals(pat.Id, actual.Id, 'pat Ids should match');
        System.assertEquals(pat.DateCompleted__c, actual.DateCompleted__c, 'pat DateCompleted should match');
        System.assertEquals(pat.Type__c, actual.Type__c, 'pat Type should match');
        System.assertEquals(pat.ValidUntil__c, actual.ValidUntil__c, 'pat ValidUntil__c should match');
    }

}