force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>Records for individuals receiving services from Atlas Assistance Dogs</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/ClientApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientApplicationReceived__c</fullName>
    <description
    >The date the most recent version of Client Application was uploaded</description>
    <label>Last Client Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientApplicationVideoReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientApplicationVideoReceived__c</fullName>
    <description>The date the most recent version of a Client Application Video was uploaded</description>
    <label>Client Application Video Received</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientCertAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientCertAgreementReceived__c</fullName>
    <description
    >The date the most recent version of Client Certification Agreement was uploaded</description>
    <label>Last Client Certification Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientCGCFormReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientCGCFormReceived__c</fullName>
    <description>The date the most recent version of Client CGC Form was uploaded</description>
    <label>CGC Form</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientLOMIReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientLOMIReceived__c</fullName>
    <description
    >The date the most recent version of Client LOMI was uploaded</description>
    <label>Last Client LOMI</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientPreApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientPreApplicationReceived__c</fullName>
    <description
    >The date the most recent version of Client Pre Application was uploaded</description>
    <label>Last Client Pre Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientProgAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientProgAgreementReceived__c</fullName>
    <description
    >The date the most recent version of Client Program Agreement was uploaded</description>
    <label>Last Client Program Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientSurveyReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientSurveyReceived__c</fullName>
    <description
    >The date the most recent version of Client Certification Survey was uploaded</description>
    <label>Last Client Certification Survey</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientVAPWReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientVAPWReceived__c</fullName>
    <description
    >The date the most recent version of Client Veteran Paperwork was uploaded</description>
    <label>Last Client Veteran Paperwork</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/ContentVersion/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Board</fullName>
            </value>
            <value>
                <fullName>Na</fullName>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Client</fullName>
                <label>Team Client</label>
            </value>
            <value>
                <fullName>TeamDog</fullName>
                <label>Team Dog</label>
            </value>
            <value>
                <fullName>TeamDog</fullName>
                <label>Team Dog</label>
            </value>
            <value>
                <fullName>Standalone</fullName>
                <label>Standalone Programs</label>
            </value>
            <value>
                <fullName>ADSiM</fullName>
                <label>Assistance Dogs Set in Motion</label>
            </value>
            <value>
                <fullName>Facilitator</fullName>
                <label>Team Facilitator</label>
            </value>
            <value>
                <fullName>Puppy</fullName>
                <label>Puppy Raiser</label>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
                <label>Staff/Contractor</label>
            </value>
            <value>
                <fullName>Dog</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PreApplication</fullName>
                <label>Pre Application</label>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>ContactForm</fullName>
                <label>Contact Form</label>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>CoI</fullName>
                <label>Conflict of Interest</label>
            </value>
            <value>
                <fullName>ToN</fullName>
                <label>Transmission of Notices</label>
            </value>
            <value>
                <fullName>LOMI</fullName>
                <label>Medical Provider Form</label>
            </value>
            <value>
                <fullName>Media</fullName>
                <label>Media Release</label>
            </value>
            <value>
                <fullName>VAPW</fullName>
                <label>Veteran Paperwork</label>
            </value>
            <value>
                <fullName>Survey</fullName>
                <label>Certification Survey</label>
            </value>
            <value>
                <fullName>Reference</fullName>
                <label>Reference Letter</label>
            </value>
            <value>
                <fullName>ClientReference</fullName>
                <label>Client Reference Letter</label>
            </value>
            <value>
                <fullName>ProfReference</fullName>
                <label>Professional Reference Letter</label>
            </value>
            <value>
                <fullName>ProgAgreement</fullName>
                <label>Program Agreement</label>
            </value>
            <value>
                <fullName>CertAgreement</fullName>
                <label>Certification Agreement</label>
            </value>
            <value>
                <fullName>Practicum</fullName>
            </value>
            <value>
                <fullName>InfrNotice</fullName>
                <label>Infraction Notice</label>
            </value>
            <value>
                <fullName>HealthForm</fullName>
                <label>Vet Health Form</label>
            </value>
            <value>
                <fullName>Notes</fullName>
                <label>Interview Notes</label>
            </value>
            <value>
                <fullName>Xray</fullName>
                <label>Vet Xray Report</label>
            </value>
            <value>
                <fullName>VacExams</fullName>
                <label>Vaccinations and Exams</label>
            </value>
            <value>
                <fullName>Resume</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
                <label>Offer Letter</label>
            </value>
            <value>
                <fullName>W4</fullName>
            </value>
            <value>
                <fullName>I9</fullName>
            </value>
            <value>
                <fullName>W9</fullName>
                <label>Contractor W9</label>
            </value>
            <value>
                <fullName>ApplicationVideo</fullName>
                <label>Application Video</label>
            </value>
            <value>
                <fullName>CGCForm</fullName>
                <label>CGC Form</label>
            </value>
            <value>
                <fullName>MentalHealthForm</fullName>
                <label>Mental Health Provider Form</label>
            </value>
            <value>
                <fullName>ProvRelForm</fullName>
                <label>Provider Release Form</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Records the Facilitator, Lead, and Client relationship</description>
    <label>Team</label>
    <nameField>
        <displayFormat>Team-{00000}</displayFormat>
        <label>Team Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client</description>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams (Client)</relationshipLabel>
    <relationshipName>Teams1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/ClientApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientApplicationReceived__c</fullName>
    <description>The date the most recent version of Client Application was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Client Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/ClientApplicationVideoReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientApplicationVideoReceived__c</fullName>
    <description>The date the most recent version of a Client Application Video was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Client Application Video</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/ClientCertAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientCertAgreementReceived__c</fullName>
    <description>The date the most recent version of Client Certification Agreement was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Client Certification Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/ClientCGCFormReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientCGCFormReceived__c</fullName>
    <description>The date the most recent version of Client CGC Form was uploaded</description>
    <label>Last CGC Form</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/ClientLOMIReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientLOMIReceived__c</fullName>
    <description>The date the most recent version of Client LOMI was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Client LOMI</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/ClientMentalHealthFormReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientMentalHealthFormReceived__c</fullName>
    <description>The date the most recent version of Client Mental Health Form was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Mental Health Provider Form</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/ClientPreApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientPreApplicationReceived__c</fullName>
    <description>The date the most recent version of Client Pre Application was uploaded</description>
    <label>Last Client Pre Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/ClientProgAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientProgAgreementReceived__c</fullName>
    <description>The date the most recent version of Client Program Agreement was uploaded</description>
    <label>Last Client Program Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/ClientProvRelFormReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientProvRelFormReceived__c</fullName>
    <description>The date the most recent version of Provider Release Form was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Provider Release Form</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/ClientSurveyReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientSurveyReceived__c</fullName>
    <description>The date the most recent version of Client Certification Survey was uploaded</description>
    <label>Last Client Certification Survey</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/ClientVAPWReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientVAPWReceived__c</fullName>
    <description>The date the most recent version of Client Veteran Paperwork was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Client Veteran Paperwork</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dog on the team</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/test/files/TestClearDateServiceClientFields.cls
@isTest
public with sharing class TestClearDateServiceClientFields {
  private static Dog__c dog;
  private static Contact client;

  private static void createTeamMembers() {
    dog = new Dog__c(Name = 'Fido');
    insert dog;

    client = new Contact(
      FirstName = 'Test',
      LastName = 'Contact',
      Email = 'abc@abc.com'
    );
    insert client;
  }

  @isTest
  public static void clearDate_ClientApplication_SetsDateToNull() {
    ContentVersion cv = new ContentVersion(
      Category__c = 'Client',
      Type__c = 'Application'
    );
    createTeamMembers();
    Team__c record = new Team__c(
      Name = 'Test',
      Client__c = client.Id,
      Dog__c = dog.Id
    );
    insert record;
    ClearDateService.clear(cv, record.Id);

    record = [
      SELECT ClientApplicationReceived__c
      FROM Team__c
      WHERE Id = :record.Id
      LIMIT 1
    ];
    system.assertEquals(
      null,
      record.ClientApplicationReceived__c,
      'ClientApplicationReceived__c not cleared'
    );
  }

  @isTest
  public static void clearDate_ClientApplicationVideo_SetsDateToNull() {
    ContentVersion cv = new ContentVersion(
      Category__c = 'Client',
      Type__c = 'ApplicationVideo'
    );
    createTeamMembers();
    Team__c record = new Team__c(
      Name = 'Test',
      Client__c = client.Id,
      Dog__c = dog.Id
    );
    insert record;
    ClearDateService.clear(cv, record.Id);

    record = [
      SELECT ClientApplicationVideoReceived__c
      FROM Team__c
      WHERE Id = :record.Id
      LIMIT 1
    ];
    system.assertEquals(
      null,
      record.ClientApplicationVideoReceived__c,
      'ClientApplicationVideoReceived__c not cleared'
    );
  }

  @isTest
  public static void clearDate_ClientCGCForm_SetsDateToNull() {
    ContentVersion cv = new ContentVersion(
      Category__c = 'Client',
      Type__c = 'CGCForm'
    );
    createTeamMembers();
    Team__c record = new Team__c(
      Name = 'Test',
      Client__c = client.Id,
      Dog__c = dog.Id
    );
    insert record;
    ClearDateService.clear(cv, record.Id);

    record = [
      SELECT ClientCGCFormReceived__c
      FROM Team__c
      WHERE Id = :record.Id
      LIMIT 1
    ];
    system.assertEquals(
      null,
      record.ClientCGCFormReceived__c,
      'ClientCGCFormReceived__c not cleared'
    );
  }

  @isTest
  public static void clearDate_ClientCertAgreement_SetsDateToNull() {
    ContentVersion cv = new ContentVersion(
      Category__c = 'Client',
      Type__c = 'CertAgreement'
    );
    createTeamMembers();
    Team__c record = new Team__c(
      Name = 'Test',
      Client__c = client.Id,
      Dog__c = dog.Id
    );
    insert record;
    ClearDateService.clear(cv, record.Id);

    record = [
      SELECT ClientCertAgreementReceived__c
      FROM Team__c
      WHERE Id = :record.Id
      LIMIT 1
    ];
    system.assertEquals(
      null,
      record.ClientCertAgreementReceived__c,
      'ClientCertAgreementReceived__c not cleared'
    );
  }

  @isTest
  public static void clearDate_ClientLOMI_SetsDateToNull() {
    ContentVersion cv = new ContentVersion(
      Category__c = 'Client',
      Type__c = 'LOMI'
    );
    createTeamMembers();
    Team__c record = new Team__c(
      Name = 'Test',
      Client__c = client.Id,
      Dog__c = dog.Id
    );
    insert record;
    ClearDateService.clear(cv, record.Id);

    record = [
      SELECT ClientLOMIReceived__c
      FROM Team__c
      WHERE Id = :record.Id
      LIMIT 1
    ];
    system.assertEquals(
      null,
      record.ClientLOMIReceived__c,
      'ClientLOMIReceived__c not cleared'
    );
  }

  @isTest
  public static void clearDate_ClientMentalHealthForm_SetsDateToNull() {
    ContentVersion cv = new ContentVersion(
      Category__c = 'Client',
      Type__c = 'MentalHealthForm'
    );
    createTeamMembers();
    Team__c record = new Team__c(
      Name = 'Test',
      Client__c = client.Id,
      Dog__c = dog.Id
    );
    insert record;
    ClearDateService.clear(cv, record.Id);

    record = [
      SELECT ClientMentalHealthFormReceived__c
      FROM Team__c
      WHERE Id = :record.Id
      LIMIT 1
    ];
    system.assertEquals(
      null,
      record.ClientMentalHealthFormReceived__c,
      'ClientMentalHealthFormReceived__c not cleared'
    );
  }

  @isTest
  public static void clearDate_ClientPreApplication_SetsDateToNull() {
    ContentVersion cv = new ContentVersion(
      Category__c = 'Client',
      Type__c = 'PreApplication'
    );
    createTeamMembers();
    Team__c record = new Team__c(
      Name = 'Test',
      Client__c = client.Id,
      Dog__c = dog.Id
    );
    insert record;
    ClearDateService.clear(cv, record.Id);

    record = [
      SELECT ClientPreApplicationReceived__c
      FROM Team__c
      WHERE Id = :record.Id
      LIMIT 1
    ];
    system.assertEquals(
      null,
      record.ClientPreApplicationReceived__c,
      'ClientPreApplicationReceived__c not cleared'
    );
  }

  @isTest
  public static void clearDate_ClientProgAgreement_SetsDateToNull() {
    ContentVersion cv = new ContentVersion(
      Category__c = 'Client',
      Type__c = 'ProgAgreement'
    );
    createTeamMembers();
    Team__c record = new Team__c(
      Name = 'Test',
      Client__c = client.Id,
      Dog__c = dog.Id
    );
    insert record;
    ClearDateService.clear(cv, record.Id);

    record = [
      SELECT ClientProgAgreementReceived__c
      FROM Team__c
      WHERE Id = :record.Id
      LIMIT 1
    ];
    system.assertEquals(
      null,
      record.ClientProgAgreementReceived__c,
      'ClientProgAgreementReceived__c not cleared'
    );
  }

  @isTest
  public static void clearDate_ClientProvRelForm_SetsDateToNull() {
    ContentVersion cv = new ContentVersion(
      Category__c = 'Client',
      Type__c = 'ProvRelForm'
    );
    createTeamMembers();
    Team__c record = new Team__c(
      Name = 'Test',
      Client__c = client.Id,
      Dog__c = dog.Id
    );
    insert record;
    ClearDateService.clear(cv, record.Id);

    record = [
      SELECT ClientProvRelFormReceived__c
      FROM Team__c
      WHERE Id = :record.Id
      LIMIT 1
    ];
    system.assertEquals(
      null,
      record.ClientProvRelFormReceived__c,
      'ClientProvRelFormReceived__c not cleared'
    );
  }

  @isTest
  public static void clearDate_ClientSurvey_SetsDateToNull() {
    ContentVersion cv = new ContentVersion(
      Category__c = 'Client',
      Type__c = 'Survey'
    );
    createTeamMembers();
    Team__c record = new Team__c(
      Name = 'Test',
      Client__c = client.Id,
      Dog__c = dog.Id
    );
    insert record;
    ClearDateService.clear(cv, record.Id);

    record = [
      SELECT ClientSurveyReceived__c
      FROM Team__c
      WHERE Id = :record.Id
      LIMIT 1
    ];
    system.assertEquals(
      null,
      record.ClientSurveyReceived__c,
      'ClientSurveyReceived__c not cleared'
    );
  }

  @isTest
  public static void clearDate_ClientVAPW_SetsDateToNull() {
    ContentVersion cv = new ContentVersion(
      Category__c = 'Client',
      Type__c = 'VAPW'
    );
    createTeamMembers();
    Team__c record = new Team__c(
      Name = 'Test',
      Client__c = client.Id,
      Dog__c = dog.Id
    );
    insert record;
    ClearDateService.clear(cv, record.Id);

    record = [
      SELECT ClientVAPWReceived__c
      FROM Team__c
      WHERE Id = :record.Id
      LIMIT 1
    ];
    system.assertEquals(
      null,
      record.ClientVAPWReceived__c,
      'ClientVAPWReceived__c not cleared'
    );
  }
}