force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>Records for individuals receiving services from Atlas Assistance Dogs</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Logs made by Client or Team Facilitator</description>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client the log refers to</description>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Logs (Client)</relationshipLabel>
    <relationshipName>LogsClient</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/OtherHours__c.field-meta.xml
<CustomField>
    <fullName>OtherHours__c</fullName>
    <label>Other Hours</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/PublicAccessHours__c.field-meta.xml
<CustomField>
    <fullName>PublicAccessHours__c</fullName>
    <description>Number of Public Access Hours</description>
    <label># Public Access Hours</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/RequestSupportFromAtlas__c.field-meta.xml
<CustomField>
    <fullName>RequestSupportFromAtlas__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request support from Atlas?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/RequestSupportFromTeam__c.field-meta.xml
<CustomField>
    <fullName>RequestSupportFromTeam__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request support from Team?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Satisfaction__c.field-meta.xml
<CustomField>
    <fullName>Satisfaction__c</fullName>
    <label>Client Life Satisfaction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No enjoyment</fullName>
            </value>
            <value>
                <fullName>A little enjoyment</fullName>
            </value>
            <value>
                <fullName>Some enjoyment</fullName>
            </value>
            <value>
                <fullName>Rather much enjoyment</fullName>
            </value>
            <value>
                <fullName>Extreme amount of enjoyment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Stress__c.field-meta.xml
<CustomField>
    <fullName>Stress__c</fullName>
    <label>Stress</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Stress</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/SupportDetails__c.field-meta.xml
<CustomField>
    <fullName>SupportDetails__c</fullName>
    <description>Details of team support request</description>
    <label>Support Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Log__c/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <description>Client log</description>
    <label>Client</label>
</RecordType>

force-app/main/default/globalValueSets/Stress.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not at all</fullName>
        <default>true</default>
        <label>Not at all</label>
    </customValue>
    <customValue>
        <fullName>Only a little</fullName>
    </customValue>
    <customValue>
        <fullName>To some extent</fullName>
    </customValue>
    <customValue>
        <fullName>Rather much</fullName>
    </customValue>
    <customValue>
        <fullName>Very much</fullName>
    </customValue>
    <description>Stress Levels</description>
    <masterLabel>Stress</masterLabel>
</GlobalValueSet>

force-app/main/test/TestLogController.cls
@isTest
public with sharing class TestLogController {
    @isTest
    public static void getRelatedLogs_ReturnsEmptyList_WhenNoLogs() {
        Test.startTest();

        Contact contact = [
            SELECT id
            FROM Contact
            WHERE FirstName = 'Client'
            LIMIT 1
        ];
        List<Log__c> related = LogController.getRelatedLogs(contact.Id);

        Test.stopTest();
        System.assertEquals(0, related.size());
    }

    @isTest
    public static void getRelatedLogs_ReturnsExpectedLogs() {
        Contact contact = [
            SELECT id
            FROM Contact
            WHERE FirstName = 'Client'
            LIMIT 1
        ];

        List<Log__c> logs = new List<Log__c>();
        logs.add(
            new Log__c(
                Date__c = Date.today(),
                Client__c = contact.Id,
                PublicAccessHours__c = 10,
                OtherHours__c = 0,
                Details__c = 'My details',
                RequestSupportFromTeam__c = true,
                SupportDetails__c = 'Support details',
                Stress__c = 'Not at all',
                Satisfaction__c = 'No enjoyment',
                RequestSupportFromAtlas__c = false
            )
        );
        upsert logs;

        Test.startTest();

        List<Log__c> related = LogController.getRelatedLogs(contact.Id);

        Test.stopTest();
        System.assertEquals(1, related.size());
        for (Integer idx = 0; idx < logs.size(); idx++) {
            Log__c expectedLog = logs[0];
            Log__c actual = related[idx];
            System.assertEquals(expectedLog.Date__c, actual.Date__c);
            System.assertEquals(
                expectedLog.PublicAccessHours__c,
                actual.PublicAccessHours__c
            );
            System.assertEquals(
                expectedLog.OtherHours__c,
                actual.OtherHours__c
            );
            System.assertEquals(expectedLog.Details__c, actual.Details__c);
            System.assertEquals(
                expectedLog.RequestSupportFromTeam__c,
                actual.RequestSupportFromTeam__c
            );
            System.assertEquals(
                expectedLog.SupportDetails__c,
                actual.SupportDetails__c
            );
            System.assertEquals(expectedLog.Stress__c, actual.Stress__c);
            System.assertEquals(
                expectedLog.Satisfaction__c,
                actual.Satisfaction__c
            );
            System.assertEquals(
                expectedLog.RequestSupportFromAtlas__c,
                actual.RequestSupportFromAtlas__c
            );
            System.assertEquals(contact.Id, actual.Client__c);
        }
    }
}