force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>Records for individuals receiving services from Atlas Assistance Dogs</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Handler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contacts.recordType-meta.xml
<RecordType>
    <fullName>Contacts</fullName>
    <active>true</active>
    <label>Contacts</label>
</RecordType>

force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Derived from Team.  Do not edit directly.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In ADSiM</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Certified-Active</fullName>
            </value>
            <value>
                <fullName>Certified-OnHold</fullName>
            </value>
            <value>
                <fullName>Decertified</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Records the Facilitator, Lead, and Client relationship</description>
    <label>Team</label>
    <nameField>
        <displayFormat>Team-{00000}</displayFormat>
        <label>Team Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client</description>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams (Client)</relationshipLabel>
    <relationshipName>Teams1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dog on the team</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Facilitator__c.field-meta.xml
<CustomField>
    <fullName>Facilitator__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Facilitator</description>
    <label>Facilitator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams (Facilitator)</relationshipLabel>
    <relationshipName>Teams2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Handler in the team, if not the client</description>
    <label>Handler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/PatCount__c.field-meta.xml
<CustomField>
    <fullName>PatCount__c</fullName>
    <description
    >Number of Public Access Tests the Client-Dog team has taken</description>
    <label>PAT Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/PatValidUntil__c.field-meta.xml
<CustomField>
    <fullName>PatValidUntil__c</fullName>
    <description>Date the Public Access Test expires</description>
    <inlineHelpText>Derived from most recent passed PAT. Do not edit directly.</inlineHelpText>
    <label>PAT Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/PrimaryCertification__c.field-meta.xml
<CustomField>
    <fullName>PrimaryCertification__c</fullName>
    <label>Primary Certification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Certifications</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team__c/fields/SecondaryCertification__c.field-meta.xml
<CustomField>
    <fullName>SecondaryCertification__c</fullName>
    <label>Secondary Certification</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Certifications</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>This status defines the status for the Team, Dog, and Client.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In ADSiM</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Certified-Hold</fullName>
            </value>
            <value>
                <fullName>Decertified</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team__c/fields/TrainingStartDate__c.field-meta.xml
<CustomField>
    <fullName>TrainingStartDate__c</fullName>
    <inlineHelpText>The date when Team Training actually starts.</inlineHelpText>
    <label>Training Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Certifications.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Atlas</fullName>
        <default>true</default>
        <label>Atlas</label>
    </customValue>
    <customValue>
        <fullName>KPA</fullName>
    </customValue>
    <customValue>
        <fullName>CCPDT</fullName>
    </customValue>
    <customValue>
        <fullName>IAABC</fullName>
    </customValue>
    <customValue>
        <fullName>CBCC</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <description>Client Dog Team Certifications</description>
    <masterLabel>Certifications</masterLabel>
</GlobalValueSet>

force-app/main/test/TestTeamController.cls
@isTest
public with sharing class TestTeamController {
    private static Contact debbie;
    private static Contact ken;
    private static Contact wanda;
    private static Dog__c ace;
    private static Team__c team;

    public static Team__c setup() {
        debbie = new Contact(FirstName = 'Debbie', LastName = 'Queen');
        ken = new Contact(FirstName = 'Ken', LastName = 'King');
        wanda = new Contact(FirstName = 'Wanda', LastName = 'Around');
        List<Contact> contacts = new List<Contact>{debbie, ken, wanda};
        insert contacts;

        ace = new Dog__c(Name = 'Ace');
        insert ace;

        team = new Team__c(
            Client__c = ken.Id,
            Dog__c = ace.Id,
            Handler__c = debbie.Id,
            Facilitator__c = wanda.Id,
            Name = 'Camelot',
            PatValidUntil__c = Date.today().addMonths(12),
            PatCount__c = 21,
            PrimaryCertification__c = 'Allergen Alert',
            SecondaryCertification__c = 'Autism',
            Status__c = 'Certified',
            TrainingStartDate__c = Date.today()
        );
        insert team;
        return team;
    }

    private static void teamsMatch(Team__c expected, Object actualObject) {
        Team__c actual = ((TeamRow)actualObject).team;
        System.assertEquals(expected.Id, actual.Id);
        System.assertEquals(expected.Client__c, actual.Client__c);
        System.assertEquals(expected.Dog__c, actual.Dog__c);
        System.assertEquals(expected.Handler__c, actual.Handler__c);
        System.assertEquals(expected.Name, actual.Name);
        System.assertEquals(expected.PatValidUntil__c, actual.PatValidUntil__c);
        System.assertEquals(expected.PatCount__c, actual.PatCount__c);
        System.assertEquals(expected.PrimaryCertification__c, actual.PrimaryCertification__c);
        System.assertEquals(expected.SecondaryCertification__c, actual.SecondaryCertification__c);
        System.assertEquals(expected.Status__c, actual.Status__c);
    }

    @isTest
    public static void getRelatedTeams_ReturnsRelatedToDog() {
        setup();
        RelatedObjects teams = TeamController.getRelatedTeams(ace.Id, 6);
        System.assertEquals(1, teams.items.size());
        System.assertEquals(1, teams.total);
        teamsMatch(team, teams.items[0]);
    }

    @isTest
    public static void getRelatedTeams_ReturnsRelatedToClient() {
        setup();
        RelatedObjects teams = TeamController.getRelatedTeams(ken.Id, 6);
        System.assertEquals(1, teams.items.size());
        System.assertEquals(1, teams.total);
        teamsMatch(team, teams.items[0]);
    }

    @isTest
    public static void getRelatedTeams_ReturnsRelatedToHandler() {
        setup();
        RelatedObjects teams = TeamController.getRelatedTeams(debbie.Id, 6);
        System.assertEquals(1, teams.items.size());
        System.assertEquals(1, teams.total);
        teamsMatch(team, teams.items[0]);
    }

    @isTest
    public static void getRelatedTeams_ReturnsError() {
        Boolean hasError = false;
        try {
            RelatedObjects teams = TeamController.getRelatedTeams('debbie.Id', 6);
        }
        catch (Exception exc) {
            hasError = true;
        }
        System.assert(hasError);
    }
}