force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>Records for individuals receiving services from Atlas Assistance Dogs</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contacts.recordType-meta.xml
<RecordType>
    <fullName>Contacts</fullName>
    <active>true</active>
    <label>Contacts</label>
</RecordType>

force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Logs made by Client or Team Facilitator</description>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client the log refers to</description>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Logs (Client)</relationshipLabel>
    <relationshipName>LogsClient</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/ClientHours__c.field-meta.xml
<CustomField>
    <fullName>ClientHours__c</fullName>
    <description
    >Number of hours the Team Facilitator has worked with the client since the last log</description>
    <label>Hours Worked with Client</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/ClientStress__c.field-meta.xml
<CustomField>
    <fullName>ClientStress__c</fullName>
    <label>Client Stress</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Stress</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Dog the log is referring to</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Facilitator__c.field-meta.xml
<CustomField>
    <fullName>Facilitator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Team Facilitator the log is referring to</description>
    <label>Team Facilitator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Logs (Team Facilitator)</relationshipLabel>
    <relationshipName>LogsFacilitator</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/OtherHours__c.field-meta.xml
<CustomField>
    <fullName>OtherHours__c</fullName>
    <label>Other Hours</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/PublicAccessHours__c.field-meta.xml
<CustomField>
    <fullName>PublicAccessHours__c</fullName>
    <description>Number of Public Access Hours</description>
    <label># Public Access Hours</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/RequestSupportFromAtlas__c.field-meta.xml
<CustomField>
    <fullName>RequestSupportFromAtlas__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request support from Atlas?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/RequestSupportFromTeam__c.field-meta.xml
<CustomField>
    <fullName>RequestSupportFromTeam__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request support from Team?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Satisfaction__c.field-meta.xml
<CustomField>
    <fullName>Satisfaction__c</fullName>
    <label>Client Life Satisfaction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No enjoyment</fullName>
            </value>
            <value>
                <fullName>A little enjoyment</fullName>
            </value>
            <value>
                <fullName>Some enjoyment</fullName>
            </value>
            <value>
                <fullName>Rather much enjoyment</fullName>
            </value>
            <value>
                <fullName>Extreme amount of enjoyment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/SessionType__c.field-meta.xml
<CustomField>
    <fullName>SessionType__c</fullName>
    <label>Session Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
            <value>
                <fullName>General Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Stress__c.field-meta.xml
<CustomField>
    <fullName>Stress__c</fullName>
    <label>Stress</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Stress</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Submitter__c.field-meta.xml
<CustomField>
    <fullName>Submitter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contact submitting the log</description>
    <label>Submitter</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Logs (Submitter)</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/SupportDetails__c.field-meta.xml
<CustomField>
    <fullName>SupportDetails__c</fullName>
    <description>Details of team support request</description>
    <label>Support Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Team the log is referring to</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <description>Client log</description>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Records the Facilitator, Lead, and Client relationship</description>
    <label>Team</label>
    <nameField>
        <displayFormat>Team-{00000}</displayFormat>
        <label>Team Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client</description>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams (Client)</relationshipLabel>
    <relationshipName>Teams1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dog on the team</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Facilitator__c.field-meta.xml
<CustomField>
    <fullName>Facilitator__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Facilitator</description>
    <label>Facilitator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams (Facilitator)</relationshipLabel>
    <relationshipName>Teams2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Stress.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not at all</fullName>
        <default>true</default>
        <label>Not at all</label>
    </customValue>
    <customValue>
        <fullName>Only a little</fullName>
    </customValue>
    <customValue>
        <fullName>To some extent</fullName>
    </customValue>
    <customValue>
        <fullName>Rather much</fullName>
    </customValue>
    <customValue>
        <fullName>Very much</fullName>
    </customValue>
    <description>Stress Levels</description>
    <masterLabel>Stress</masterLabel>
</GlobalValueSet>

force-app/main/test/logs/TestLogController.cls
@isTest
public with sharing class TestLogController {
  private static final String CLIENT_NAME = 'Client';
  private static final String SUBMITTER_NAME = 'Submitter';
  private static final String FACILITATOR_NAME = 'Facilitator';
  private static final String SOMEONE_ELSE = 'Debbie';
  private static final String DOG_NAME = 'Fido';

  private static Contact client;
  private static Contact submitter;
  private static Contact facilitator;
  private static Contact other;
  private static Dog__c dog;
  private static ID CLIENT_ID;
  private static ID FACILITATOR_ID;

  @testSetup
  static void setup() {
    List<Contact> contacts = new List<Contact>();
    contacts.add(new Contact(FirstName = CLIENT_NAME, LastName = 'Ace'));
    contacts.add(new Contact(FirstName = SUBMITTER_NAME, LastName = 'Smith'));
    contacts.add(
      new Contact(FirstName = FACILITATOR_NAME, LastName = 'Washington')
    );
    contacts.add(new Contact(FirstName = SOMEONE_ELSE, LastName = 'Walker'));
    insert contacts;

    dog = new Dog__c(Name = DOG_NAME);
    insert dog;

    Map<String, Schema.RecordTypeInfo> recordTypes = Schema.SObjectType.Log__c.getRecordTypeInfosByName();
    CLIENT_ID = recordTypes.get('Client').getRecordTypeId();
    FACILITATOR_ID = recordTypes.get('Team Facilitator').getRecordTypeId();
  }

  static void getContacts() {
    client = [
      SELECT id
      FROM Contact
      WHERE FirstName = :CLIENT_NAME
      LIMIT 1
    ];

    submitter = [
      SELECT id
      FROM Contact
      WHERE FirstName = :SUBMITTER_NAME
      LIMIT 1
    ];

    facilitator = [
      SELECT id
      FROM Contact
      WHERE FirstName = :FACILITATOR_NAME
      LIMIT 1
    ];

    other = [
      SELECT id
      FROM Contact
      WHERE FirstName = :SOMEONE_ELSE
      LIMIT 1
    ];

    dog = [SELECT Id, Name FROM Dog__c WHERE Name = :DOG_NAME LIMIT 1];
  }

  private static void logsMatch(Log__c expected, Log__c actual) {
    System.assertEquals(expected.Team__c, actual.Team__c);
    System.assertEquals(expected.ClientHours__c, actual.ClientHours__c);
    System.assertEquals(expected.ClientStress__c, actual.ClientStress__c);
    System.assertEquals(expected.Date__c, actual.Date__c);
    System.assertEquals(expected.Details__c, actual.Details__c);
    System.assertEquals(expected.OtherHours__c, actual.OtherHours__c);
    System.assertEquals(
      expected.PublicAccessHours__c,
      actual.PublicAccessHours__c
    );
    System.assertEquals(
      expected.RequestSupportFromAtlas__c,
      actual.RequestSupportFromAtlas__c
    );
    System.assertEquals(
      expected.RequestSupportFromTeam__c,
      actual.RequestSupportFromTeam__c
    );
    System.assertEquals(expected.Satisfaction__c, actual.Satisfaction__c);
    System.assertEquals(expected.SessionType__c, actual.SessionType__c);
    System.assertEquals(expected.Stress__c, actual.Stress__c);
    System.assertEquals(expected.Submitter__c, actual.Submitter__c);
    System.assertEquals(expected.SupportDetails__c, actual.SupportDetails__c);
    System.assertEquals(expected.Facilitator__c, actual.Facilitator__c);
  }

  @isTest
  public static void getRelatedLogs_ReturnsEmptyList_WhenNoLogs() {
    Test.startTest();

    Contact contact = [
      SELECT id
      FROM Contact
      WHERE FirstName = :CLIENT_NAME
      LIMIT 1
    ];
    RelatedObjects relatedObjects = LogController.getRelatedLogs(
      contact.Id,
      'Client',
      6
    );
    Test.stopTest();
    System.assertEquals(0, relatedObjects.items.size());
  }

  @isTest
  public static void getRelatedLogs_ThrowsException_WhenNoContactId() {
    Test.startTest();

    Boolean exceptionThrown = false;
    try {
      RelatedObjects related = LogController.getRelatedLogs(
        'dog.Id',
        'Client',
        6
      );
    } catch (Exception exc) {
      exceptionThrown = true;
    }

    Test.stopTest();
    System.assert(exceptionThrown);
  }

  @isTest
  public static void getRelatedLogs_ForContact_ReturnsExpectedLogs() {
    getContacts();
    Map<String, Schema.RecordTypeInfo> recordTypes = Schema.SObjectType.Log__c.getRecordTypeInfosByName();
    CLIENT_ID = recordTypes.get('Client').getRecordTypeId();
    FACILITATOR_ID = recordTypes.get('Team Facilitator').getRecordTypeId();
    Team__c team = new Team__c(
      Client__c = client.Id,
      Dog__c = dog.Id,
      Name = 'PeteLatimer_Ace'
    );
    insert team;
    Team__c team2 = new Team__c(
      Client__c = submitter.Id,
      Dog__c = dog.Id,
      Name = 'MykaBerring_Ace'
    );
    insert team2;

    List<Log__c> logs = new List<Log__c>();
    logs.add(
      new Log__c(
        ClientHours__c = 22,
        ClientStress__c = 'Only a little',
        Date__c = Date.today(),
        Details__c = 'My details',
        OtherHours__c = 5,
        PublicAccessHours__c = 10,
        RequestSupportFromAtlas__c = false,
        RequestSupportFromTeam__c = true,
        Satisfaction__c = 'No enjoyment',
        SessionType__c = 'In Person',
        Stress__c = 'Not at all',
        Submitter__c = client.Id,
        SupportDetails__c = 'Support details',
        Facilitator__c = facilitator.Id,
        RecordTypeId = CLIENT_ID,
        Team__c = team.Id
      )
    );
    logs.add(
      new Log__c(
        ClientHours__c = 22,
        ClientStress__c = 'Only a little',
        Date__c = Date.today(),
        Details__c = 'My details',
        OtherHours__c = 5,
        PublicAccessHours__c = 10,
        RequestSupportFromAtlas__c = false,
        RequestSupportFromTeam__c = true,
        Satisfaction__c = 'No enjoyment',
        SessionType__c = 'In Person',
        Stress__c = 'Not at all',
        Submitter__c = submitter.Id,
        SupportDetails__c = 'Support details',
        Facilitator__c = other.Id,
        Team__c = team2.Id,
        RecordTypeId = CLIENT_ID
      )
    );
    insert logs;

    Test.startTest();

    RelatedObjects related = LogController.getRelatedLogs(
      client.Id,
      'Client',
      6
    );

    Test.stopTest();
    System.assertEquals(1, related.items.size());
    for (Integer idx = 0; idx < related.items.size(); idx++) {
      Log__c expectedLog = logs[0];
      LogInfo actual = (LogInfo) related.items[idx];
      logsMatch(expectedLog, actual.log);
    }
  }

  @isTest
  public static void getRelatedLogs_ForDog_ReturnsExpectedLogs() {
    getContacts();
    Map<String, Schema.RecordTypeInfo> recordTypes = Schema.SObjectType.Log__c.getRecordTypeInfosByName();
    CLIENT_ID = recordTypes.get('Client').getRecordTypeId();
    FACILITATOR_ID = recordTypes.get('Team Facilitator').getRecordTypeId();
    Team__c team = new Team__c(
      Client__c = client.Id,
      Dog__c = dog.Id,
      Name = 'PeteLatimer_Ace'
    );
    insert team;
    Team__c team2 = new Team__c(
      Client__c = submitter.Id,
      Dog__c = dog.Id,
      Name = 'MykaBerring_Ace'
    );
    insert team2;

    List<Log__c> logs = new List<Log__c>();
    logs.add(
      new Log__c(
        ClientHours__c = 22,
        ClientStress__c = 'Only a little',
        Date__c = Date.today(),
        Details__c = 'My details',
        OtherHours__c = 5,
        PublicAccessHours__c = 10,
        RequestSupportFromAtlas__c = false,
        RequestSupportFromTeam__c = true,
        Satisfaction__c = 'No enjoyment',
        SessionType__c = 'In Person',
        Stress__c = 'Not at all',
        Submitter__c = submitter.Id,
        SupportDetails__c = 'Support details',
        Facilitator__c = facilitator.Id,
        RecordTypeId = CLIENT_ID,
        Team__c = team.Id
      )
    );
    logs.add(
      new Log__c(
        ClientHours__c = 22,
        ClientStress__c = 'Only a little',
        Date__c = Date.today(),
        Details__c = 'My details',
        OtherHours__c = 5,
        PublicAccessHours__c = 10,
        RequestSupportFromAtlas__c = false,
        RequestSupportFromTeam__c = true,
        Satisfaction__c = 'No enjoyment',
        SessionType__c = 'In Person',
        Stress__c = 'Not at all',
        Submitter__c = client.Id,
        SupportDetails__c = 'Support details',
        Facilitator__c = other.Id,
        RecordTypeId = CLIENT_ID,
        Team__c = team2.Id
      )
    );
    insert logs;

    Test.startTest();

    RelatedObjects related = LogController.getRelatedLogs(dog.Id, 'Client', 6);

    Test.stopTest();
    System.assertEquals(logs.size(), related.items.size());
    for (Integer idx = 0; idx < related.items.size(); idx++) {
      Log__c expectedLog = logs[idx];
      LogInfo actual = (LogInfo) related.items[idx];
      logsMatch(expectedLog, actual.log);
    }
  }

  @isTest
  public static void getRelatedLogs_ForTeam_ReturnsExpectedLogs() {
    getContacts();
    Map<String, Schema.RecordTypeInfo> recordTypes = Schema.SObjectType.Log__c.getRecordTypeInfosByName();
    CLIENT_ID = recordTypes.get('Client').getRecordTypeId();
    FACILITATOR_ID = recordTypes.get('Team Facilitator').getRecordTypeId();
    Team__c team = new Team__c(
      Client__c = client.Id,
      Dog__c = dog.Id,
      Name = 'PeteLatimer_Ace'
    );
    insert team;
    Team__c team2 = new Team__c(
      Client__c = submitter.Id,
      Dog__c = dog.Id,
      Name = 'MykaBerring_Ace'
    );
    insert team2;

    List<Log__c> logs = new List<Log__c>();
    logs.add(
      new Log__c(
        ClientHours__c = 22,
        ClientStress__c = 'Only a little',
        Date__c = Date.today(),
        Details__c = 'My details',
        OtherHours__c = 5,
        PublicAccessHours__c = 10,
        RequestSupportFromAtlas__c = false,
        RequestSupportFromTeam__c = true,
        Satisfaction__c = 'No enjoyment',
        SessionType__c = 'In Person',
        Stress__c = 'Not at all',
        Submitter__c = submitter.Id,
        SupportDetails__c = 'Support details',
        Facilitator__c = facilitator.Id,
        RecordTypeId = CLIENT_ID,
        Team__c = team.Id
      )
    );
    logs.add(
      new Log__c(
        ClientHours__c = 22,
        ClientStress__c = 'Only a little',
        Date__c = Date.today(),
        Details__c = 'My details',
        OtherHours__c = 5,
        PublicAccessHours__c = 10,
        RequestSupportFromAtlas__c = false,
        RequestSupportFromTeam__c = true,
        Satisfaction__c = 'No enjoyment',
        SessionType__c = 'In Person',
        Stress__c = 'Not at all',
        Submitter__c = client.Id,
        SupportDetails__c = 'Support details',
        Facilitator__c = other.Id,
        Team__c = team2.Id
      )
    );
    insert logs;

    Test.startTest();

    RelatedObjects related = LogController.getRelatedLogs(team.Id, 'Client', 6);

    Test.stopTest();
    System.assertEquals(1, related.items.size());
    for (Integer idx = 0; idx < related.items.size(); idx++) {
      Log__c expectedLog = logs[0];
      LogInfo actual = (LogInfo) related.items[idx];
      logsMatch(expectedLog, actual.log);
    }
  }
}