force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>Records for individuals receiving services from Atlas Assistance Dogs</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connects the Client to their contact record</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Place/person to contact this person</description>
    <inlineHelpText>Select Guardian to contact this person through their guardian, Home for personal email/phone</inlineHelpText>
    <label>Contact At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
                <default>true</default>
                <label>Home</label>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Derived from Team.  Do not edit directly.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In ADSiM</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Certified-Active</fullName>
            </value>
            <value>
                <fullName>Certified-OnHold</fullName>
            </value>
            <value>
                <fullName>Decertified</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DogRelationship__c/DogRelationship__c.object-meta.xml
<CustomObject>
    <description>Connection between a dog and a contact</description>
    <label>Dog Relationship</label>
    <nameField>
        <displayFormat>DR-{00000}</displayFormat>
        <label>Dog Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dogs Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DogRelationship__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Dogs</relationshipLabel>
    <relationshipName>DogsContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DogRelationship__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A dog for this contact</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>Humans</relationshipLabel>
    <relationshipName>DogsContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DogRelationship__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
    >Team the dog and human are on.  Only valid if the relationship is dog-client or dog-trainer.</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Dogs Relationships</relationshipLabel>
    <relationshipName>Dogs_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DogRelationship__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Relationship types between a dog and contact</description>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Veterinarian</fullName>
            </value>
            <value>
                <fullName>Handler</fullName>
            </value>
            <value>
                <fullName>Facilitator</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Records the Facilitator, Lead, and Client relationship</description>
    <label>Team</label>
    <nameField>
        <displayFormat>Team-{00000}</displayFormat>
        <label>Team Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client</description>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams (Client)</relationshipLabel>
    <relationshipName>Teams1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dog on the team</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>This status defines the status for the Team, Dog, and Client.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In ADSiM</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Certified-Hold</fullName>
            </value>
            <value>
                <fullName>Decertified</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/test/dogs/TestDogRepository.cls
/**
 * This class contains unit tests for the DogRepository class
 */
@isTest
private class TestDogRepository {
  static DogRepository repo = new DogRepository();

  @isTest
  static void getById_returnsNull_whenNoDog() {
    Dog__c actual = repo.getById(MockProvider.createId(Dog__c.class));
    System.assertEquals(null, actual, 'not null');
  }

  @isTest
  static void getById_returnsDog_whenMatch() {
    Dog__c dog = new Dog__c(Name = 'fido');
    insert dog;
    //act
    Dog__c actual = repo.getById(dog.Id);
    //assert
    System.assertEquals(dog.Id, actual.Id, 'wrong id');
    System.assertEquals(dog.Name, actual.Name, 'wrong name');
  }

  @isTest
  static void modify_updatesDog() {
    Dog__c dog = new Dog__c(Name = 'fido');
    insert dog;
    dog.Status__c = 'Onboarding';
    //act
    Dog__c actual = repo.modify(dog);
    //assert
    Dog__c updated = [SELECT Status__c FROM Dog__c WHERE Id = :dog.Id];
    System.assertEquals(dog, actual, 'did not return updated record');
    System.assertEquals(
      dog.Status__c,
      updated.Status__c,
      'not saved to database'
    );
  }

  @isTest
  static void getRelationships_returnsEmpty_whenNone() {
    List<DogRelationship__c> actual = repo.getRelationships(
      MockProvider.createId(Contact.class),
      MockProvider.createId(Dog__c.class)
    );
    System.assertEquals(
      new List<DogRelationShip__c>(),
      actual,
      'unexpected result'
    );
  }

  @isTest
  static void getRelationships_returnsRelationship() {
    Team__c team = TestTeam.create();
    List<DogRelationship__c> actual = repo.getRelationships(
      team.Client__c,
      team.Dog__c
    );
    System.assertEquals(1, actual.size(), 'more relationships than expected');
    DogRelationship__c relationship = actual[0];
    System.assertEquals(
      team.Client__c,
      relationship.Contact__c,
      'wrong contact'
    );
    System.assertEquals(team.Dog__c, relationship.Dog__c, 'wrong dog');
    System.assertEquals('Client', relationship.Type__c, 'wrong status');
  }

  @isTest
  static void createRelationship_creates() {
    Contact wanda = new Contact(FirstName = 'Wanda', LastName = 'Around');
    insert wanda;

    Dog__c ace = new Dog__c(Name = 'Ace');
    insert ace;
    DogRelationship__c actual = repo.createRelationship(
      new DogRelationship__c(
        Contact__c = wanda.Id,
        Dog__c = ace.Id,
        Type__c = 'Owner'
      )
    );
    //assert
    System.assertNotEquals(null, actual.Id, 'no id assigned');
    DogRelationship__c relate = [
      SELECT Id, Contact__c, Dog__c, Type__c
      FROM DogRelationship__c
      WHERE Id = :actual.Id
    ];
    System.assertEquals(wanda.Id, relate.Contact__c, 'wring contact');
    System.assertEquals(ace.Id, relate.Dog__c, 'wrong dog');
    System.assertEquals('Owner', relate.Type__c, 'wrong type');
  }

  @isTest
  static void modifyRelationship_modifies() {
    Contact wanda = new Contact(FirstName = 'Wanda', LastName = 'Around');
    insert wanda;

    Dog__c ace = new Dog__c(Name = 'Ace');
    insert ace;
    DogRelationship__c relate = new DogRelationship__c(
      Contact__c = wanda.Id,
      Dog__c = ace.Id,
      Type__c = 'Owner'
    );
    insert relate;

    relate.Type__c = 'Handler';
    // act
    DogRelationship__c actual = repo.modifyRelationship(relate);
    // assert
    System.assertEquals(
      relate.Type__c,
      actual.Type__c,
      'did not return updated'
    );
    DogRelationship__c stored = [
      SELECT Id, Type__c
      FROM DogRelationship__c
      WHERE Id = :actual.Id
    ];
    System.assertEquals(relate.Type__c, stored.Type__c, 'did not store type');
  }
}