force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>Records for individuals receiving services from Atlas Assistance Dogs</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PublicAccessTest__c/PublicAccessTest__c.object-meta.xml
<CustomObject>
    <description>Tests that the Dog/Client team can perform in public.</description>
    <label>PAT</label>
    <nameField>
        <displayFormat>PAT-{0000}</displayFormat>
        <label>Public Access Test Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PATs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PublicAccessTest__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client being assessed in the PAT</description>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PATs (Client)</relationshipLabel>
    <relationshipName>Public_Access_Tests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/DateCompleted__c.field-meta.xml
<CustomField>
    <fullName>DateCompleted__c</fullName>
    <description>Date the test was completed</description>
    <label>Date Completed</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Team the test is for</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>PATs</relationshipLabel>
    <relationshipName>PATs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Public Access Test</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
            </value>
            <value>
                <fullName>Recertification</fullName>
            </value>
            <value>
                <fullName>Retest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/ValidUntil__c.field-meta.xml
<CustomField>
    <fullName>ValidUntil__c</fullName>
    <description>Date the test is valid until</description>
    <label>Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Records the Facilitator, Lead, and Client relationship</description>
    <label>Team</label>
    <nameField>
        <displayFormat>Team-{00000}</displayFormat>
        <label>Team Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client</description>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams (Client)</relationshipLabel>
    <relationshipName>Teams1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/InitialCertificationDate__c.field-meta.xml
<CustomField>
    <fullName>InitialCertificationDate__c</fullName>
    <label>Initial Certification Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/PatValidUntil__c.field-meta.xml
<CustomField>
    <fullName>PatValidUntil__c</fullName>
    <description>Date the Public Access Test expires</description>
    <inlineHelpText>Derived from most recent passed PAT. Do not edit directly.</inlineHelpText>
    <label>PAT Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/test/teams/TestTeamService.cls
/**
 * This class contains unit tests for validating the behavior of Apex class TeamService.
 *
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestTeamService {
    private static MockProvider mocks;
    private static TeamService service;
    private static TeamRepository teamRepo;
    private static PublicAccessTestRepository patRepo;
    private static DogRepository dogRepo;
    private static RelationshipRepository relationshipRepo;
    private static ContactRepository contactRepo;
    private static EmailService emailSrv;
    // references to mocks

    private static List<Id> patids = new List<Id>{ 'a19E1000003lL45IAE' };
    
    private static void makeData(){
        mocks = new MockProvider();
        teamRepo = (TeamRepository)mocks.createMock(TeamRepository.class);
        dogRepo = (DogRepository)mocks.createMock(DogRepository.class);
        patRepo = (PublicAccessTestRepository)mocks.createMock(PublicAccessTestRepository.class);
        relationshipRepo = (RelationshipRepository)mocks.createMock(RelationshipRepository.class);
        ContactRepo = (ContactRepository)mocks.createMock(ContactRepository.class);
        emailSrv = (EmailService)mocks.createMock(EmailService.class);
        service = new TeamService(teamRepo, patRepo, relationshipRepo, emailSrv, dogRepo, contactRepo);
    }

    @isTest
    static void updatePatInformation_doesNothing_whenNoTeams() {
        // Arrange
        makeData();
        List<Team__c> teams = new List<Team__c>();
        mocks.expectedCalls.add(new MockCallData(teamRepo, 'getPatStatus', teams));
        mocks.expectedCalls.add(new MockCallData(patRepo, 'getPassing', new PublicAccessTest__c[]{}));

        // Act
        service.updatePatInformation(new Set<Id>());

        // Assert
        System.assert(!mocks.actualCalls.isEmpty());
        
        // the last call would be to update the teams
        MockCallData data = mocks.actualCalls[mocks.actualCalls.size() - 1];
        List<Team__c> actual = (List<Team__c>)data.args[0];
        System.assert(actual.isEmpty());
    }

    @isTest
    static void updatePatInformation_clearsDates_whenNoPats() {
        // Arrange
        makeData();
        List<Team__c> teams = new List<Team__c>{
            new Team__c(Id = MockProvider.teamids[0], Client__c = MockProvider.contactids[0], InitialCertificationDate__c = Date.today(), PatValidUntil__c = Date.today().addYears(1))
        };
        mocks.expectedCalls.add(new MockCallData(teamRepo, 'getPatStatus', teams));
        mocks.expectedCalls.add(new MockCallData(patRepo, 'getPassing', new PublicAccessTest__c[]{}));

        // Act
        service.updatePatInformation(new Set<Id>{ MockProvider.teamids[0] });

        // Assert
        System.assert(!mocks.actualCalls.isEmpty());
        
        // the last call would be to update the teams
        MockCallData data = mocks.actualCalls[mocks.actualCalls.size() - 1];
        List<Team__c> actual = (List<Team__c>)data.args[0];
        System.assertEquals(1, actual.size());
        System.assertEquals(null, actual[0].InitialCertificationDate__c);
        System.assertEquals(null, actual[0].PatValidUntil__c);
    }

    @isTest
    static void updatePatInformation_setsInitialCert_whenInitialPat() {
        // Arrange
        makeData();
        List<Team__c> teams = new List<Team__c>{
            new Team__c(Id = MockProvider.teamids[0], Client__c = MockProvider.contactids[0], InitialCertificationDate__c = null, PatValidUntil__c = null)
        };
        mocks.expectedCalls.add(new MockCallData(teamRepo, 'getPatStatus', teams));
        PublicAccessTest__c pat = new PublicAccessTest__c(Id = patids[0], Type__c = 'Initial', DateCompleted__c = Date.today(), ValidUntil__c = Date.today().addYears(1));
        mocks.expectedCalls.add(new MockCallData(patRepo, 'getPassing', new PublicAccessTest__c[] { pat }));

        // Act
        service.updatePatInformation(new Set<Id>{ MockProvider.teamids[0] });

        // Assert
        System.assert(!mocks.actualCalls.isEmpty());
        
        // the last call would be to update the teams
        MockCallData data = mocks.actualCalls[mocks.actualCalls.size() - 1];
        List<Team__c> actual = (List<Team__c>)data.args[0];
        System.assertEquals(1, actual.size());
        System.assertEquals(pat.DateCompleted__c, actual[0].InitialCertificationDate__c);
    }

    @isTest
    static void updatePatInformation_setsValidUntil() {
        // Arrange
        makeData();
        List<Team__c> teams = new List<Team__c>{
            new Team__c(Id = MockProvider.teamids[0], Client__c = MockProvider.contactids[0], InitialCertificationDate__c = null, PatValidUntil__c = null)
        };
        mocks.expectedCalls.add(new MockCallData(teamRepo, 'getPatStatus', teams));
        PublicAccessTest__c pat = new PublicAccessTest__c(Id = patids[0], Type__c = 'Initial', DateCompleted__c = Date.today(), ValidUntil__c = Date.today().addYears(1));
        mocks.expectedCalls.add(new MockCallData(patRepo, 'getPassing', new PublicAccessTest__c[] { pat }));

        // Act
        service.updatePatInformation(new Set<Id>{ MockProvider.teamids[0] });

        // Assert
        System.assert(!mocks.actualCalls.isEmpty());
        
        // the last call would be to update the teams
        MockCallData data = mocks.actualCalls[mocks.actualCalls.size() - 1];
        List<Team__c> actual = (List<Team__c>)data.args[0];
        System.assertEquals(1, actual.size());
        System.assertEquals(pat.ValidUntil__c, actual[0].PatValidUntil__c);
    }
}