force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>Records for individuals receiving services from Atlas Assistance Dogs</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/ClientCertificationValidUntil__c.field-meta.xml
<CustomField>
    <fullName>ClientCertificationValidUntil__c</fullName>
    <description>Date that the client certification is valid until</description>
    <label>Client Certification Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientStatus__c.field-meta.xml
<CustomField>
    <fullName>ClientStatus__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <inlineHelpText>Derived from Team. Do not edit directly.</inlineHelpText>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In ADSiM</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Certified-Hold</fullName>
            </value>
            <value>
                <fullName>Decertified</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Not Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Derived from Team.  Do not edit directly.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In ADSiM</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Certified-Active</fullName>
            </value>
            <value>
                <fullName>Certified-OnHold</fullName>
            </value>
            <value>
                <fullName>Decertified</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Records the Facilitator, Lead, and Client relationship</description>
    <label>Team</label>
    <nameField>
        <displayFormat>Team-{00000}</displayFormat>
        <label>Team Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client</description>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams (Client)</relationshipLabel>
    <relationshipName>Teams1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dog on the team</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/InitialCertificationDate__c.field-meta.xml
<CustomField>
    <fullName>InitialCertificationDate__c</fullName>
    <label>Initial Certification Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/PatCount__c.field-meta.xml
<CustomField>
    <fullName>PatCount__c</fullName>
    <description
    >Number of Public Access Tests the Client-Dog team has taken</description>
    <label>PAT Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/PatValidUntil__c.field-meta.xml
<CustomField>
    <fullName>PatValidUntil__c</fullName>
    <description>Date the Public Access Test expires</description>
    <inlineHelpText>Derived from most recent passed PAT. Do not edit directly.</inlineHelpText>
    <label>PAT Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>This status defines the status for the Team, Dog, and Client.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In ADSiM</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Certified-Hold</fullName>
            </value>
            <value>
                <fullName>Decertified</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/test/teams/TestTeamRepository.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestTeamRepository {

    private static Contact joe;
    private static Dog__c boomer;
    private static Team__c team;

    private static void setup() {
        joe = new Contact(
            FirstName = 'Joe',
            LastName = 'Blow',
            ClientStatus__c = 'Onboarding',
            ClientCertificationValidUntil__c = Date.today().addMonths(3));
        insert joe;
        boomer = new Dog__c(Name = 'Boomer', Status__c = 'Onboarding');
        insert boomer;
        team = new Team__c(
            Name = 'Joe_Boomer',
            Client__c = joe.Id,
            Dog__c = boomer.Id
        );
        insert team;
    }

    @isTest
    static void create() {
        // Arrange
        setup();
        Team__c expected = new Team__c(
            Name = 'Joe_Boomer2',
            Client__c = joe.Id,
            Dog__c = boomer.Id,
            Status__c = 'Certified'
        );
        // Act
        TeamRepository repo = new TeamRepository();
        Team__c actual = repo.create(expected);
        // Assert
        System.assertNotEquals(team.Id, actual.Id);
        System.assertNotEquals(null, actual.Id);
        System.assertEquals(expected.Name, actual.Name);
        System.assertEquals(expected.Client__c, actual.Client__c);
        System.assertEquals(expected.Dog__c, actual.Dog__c);
        System.assertEquals(expected.Status__c, actual.Status__c);
    }

    @isTest
    static void getCertificationStatus_returnsUnsetCertificationStatus() {
        // Arrange
        setup();
        // Act
        TeamRepository repo = new TeamRepository();
        Team__c actual = repo.getCertificationStatus(new Set<Id> { team.Id })[0];
        // Assert
        System.assertEquals(joe.Id, actual.Client__c);
        System.assertEquals(null, actual.InitialCertificationDate__c);
        System.assertEquals(null, actual.PatValidUntil__c);
        System.assertEquals(null, actual.PatCount__c);
    }

    @isTest
    static void getCertificationStatus_returnsCertificationStatus() {
        // Arrange
        setup();
        team.InitialCertificationDate__c = Date.today().addDays(-22);
        team.PatValidUntil__c = Date.today().addMonths(10);
        team.PatCount__c = 5;
        update team;
        // Act
        TeamRepository repo = new TeamRepository();
        Team__c actual = repo.getCertificationStatus(new Set<Id> { team.Id })[0];
        // Assert
        System.assertEquals(joe.Id, actual.Client__c);
        System.assertEquals(team.InitialCertificationDate__c, actual.InitialCertificationDate__c);
        System.assertEquals(team.PatValidUntil__c, actual.PatValidUntil__c);
        System.assertEquals(team.PatCount__c, actual.PatCount__c);
    }

    @isTest
    static void modify_updates() {
        // Arrange
        setup();
        team.InitialCertificationDate__c = Date.today().addDays(-22);
        team.PatValidUntil__c = Date.today().addMonths(10);
        team.PatCount__c = 5;
        // Act
        TeamRepository repo = new TeamRepository();
        Team__c[] result = repo.modify(new Team__c[] { team });
        // Assert
        Team__c actual = result[0];
        System.assertEquals(team.InitialCertificationDate__c, actual.InitialCertificationDate__c);
        System.assertEquals(team.PatValidUntil__c, actual.PatValidUntil__c);
        System.assertEquals(team.PatCount__c, actual.PatCount__c);
    }

    @isTest
    static void modify_returnsNull_whenNull() {
        // Act
        TeamRepository repo = new TeamRepository();
        Team__c[] actual = repo.modify(null);
        // Assert
        System.assertEquals(null, actual);
    }

    @isTest
    static void modify_returnsEmpty_whenEmpty() {
        // Act
        TeamRepository repo = new TeamRepository();
        Team__c[] actual = repo.modify(new List<Team__c>());
        // Assert
        System.assert(actual.isEmpty());
    }
}