force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>Records for individuals receiving services from Atlas Assistance Dogs</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Logs made by Client or Team Facilitator</description>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client the log refers to</description>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Logs (Client)</relationshipLabel>
    <relationshipName>LogsClient</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Dog the log is referring to</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Facilitator__c.field-meta.xml
<CustomField>
    <fullName>Facilitator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Team Facilitator the log is referring to</description>
    <label>Team Facilitator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Logs (Team Facilitator)</relationshipLabel>
    <relationshipName>LogsFacilitator</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/OtherHours__c.field-meta.xml
<CustomField>
    <fullName>OtherHours__c</fullName>
    <label>Other Hours</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/PublicAccessHours__c.field-meta.xml
<CustomField>
    <fullName>PublicAccessHours__c</fullName>
    <description>Number of Public Access Hours</description>
    <label># Public Access Hours</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Submitter__c.field-meta.xml
<CustomField>
    <fullName>Submitter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contact submitting the log</description>
    <label>Submitter</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Logs (Submitter)</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Team the log is referring to</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <description>Client log</description>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Log__c/recordTypes/TeamFacilitator.recordType-meta.xml
<RecordType>
    <fullName>TeamFacilitator</fullName>
    <active>true</active>
    <description>Team Facilitator log</description>
    <label>Team Facilitator</label>
</RecordType>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Records the Facilitator, Lead, and Client relationship</description>
    <label>Team</label>
    <nameField>
        <displayFormat>Team-{00000}</displayFormat>
        <label>Team Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client</description>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams (Client)</relationshipLabel>
    <relationshipName>Teams1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dog on the team</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Facilitator__c.field-meta.xml
<CustomField>
    <fullName>Facilitator__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Facilitator</description>
    <label>Facilitator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams (Facilitator)</relationshipLabel>
    <relationshipName>Teams2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/test/logs/TestLogRepository.cls
/**
 * This class contains unit tests for validating the behavior of LogRepository
 */
@isTest
private class TestLogRepository {
  public static ID CLIENT_ID;
  public static ID FACILITATOR_ID;

  @testSetup
  static void setup() {
    Map<String, Schema.RecordTypeInfo> recordTypes = Schema.SObjectType.Log__c.getRecordTypeInfosByName();
    CLIENT_ID = recordTypes.get('Client').getRecordTypeId();
    FACILITATOR_ID = recordTypes.get('Team Facilitator').getRecordTypeId();
  }

  @isTest
  static void getRecent_returnsEmpty_whenNoClientLogs() {
    LogRepository repository = new LogRepository();

    Test.startTest();
    List<Log__c> logs = repository.getRecent('Client', 1);
    Test.stopTest();

    System.assert(logs.isEmpty(), 'No logs should be returned');
  }

  @isTest
  static void getRecent_returnsEmpty_whenNoFacilitatorLogs() {
    LogRepository repository = new LogRepository();

    Test.startTest();
    List<Log__c> logs = repository.getRecent('TeamFacilitator', 1);
    Test.stopTest();

    System.assert(logs.isEmpty(), 'No logs should be returned');
  }

  @isTest
  static void getRecent_returnsEmpty_whenNoFacilitatorLogsButClientLogs() {
    setup();
    Team__c team = TestTeam.create();
    Log__c log = new Log__c(
      Team__c = team.Id,
      OtherHours__c = 3,
      PublicAccessHours__c = 2,
      Submitter__c = team.Client__c,
      RecordTypeId = CLIENT_ID
    );
    insert log;
    LogRepository repository = new LogRepository();

    Test.startTest();
    List<Log__c> logs = repository.getRecent('TeamFacilitator', 1);
    Test.stopTest();

    System.assert(logs.isEmpty(), 'No logs should be returned');
  }

  @isTest
  static void getRecent_returnsEmpty_whenNoClientLogsButFacilitatorLogs() {
    setup();
    Team__c team = TestTeam.create();
    Log__c log = new Log__c(
      Team__c = team.Id,
      OtherHours__c = 3,
      PublicAccessHours__c = 2,
      Submitter__c = team.Client__c,
      RecordTypeId = FACILITATOR_ID
    );
    insert log;
    LogRepository repository = new LogRepository();

    Test.startTest();
    List<Log__c> logs = repository.getRecent('Client', 1);
    Test.stopTest();

    System.assert(logs.isEmpty(), 'No logs should be returned');
  }

  @isTest
  static void getRecent_returnsEmpty_whenNoClientLogsAfterDate() {
    setup();
    Team__c team = TestTeam.create();
    Log__c log = new Log__c(
      Team__c = team.Id,
      OtherHours__c = 3,
      PublicAccessHours__c = 2,
      Submitter__c = team.Client__c,
      RecordTypeId = CLIENT_ID,
      Date__c = Date.today().addDays(-2)
    );
    insert log;
    LogRepository repository = new LogRepository();

    Test.startTest();
    List<Log__c> logs = repository.getRecent('Client', 1);
    Test.stopTest();

    System.assert(logs.isEmpty(), 'No logs should be returned');
  }

  @isTest
  static void getRecent_returnsEmpty_whenNoFacilitatorLogsAfterDate() {
    setup();
    Team__c team = TestTeam.create();
    Log__c log = new Log__c(
      Team__c = team.Id,
      OtherHours__c = 3,
      PublicAccessHours__c = 2,
      Submitter__c = team.Client__c,
      RecordTypeId = FACILITATOR_ID,
      Date__c = Date.today().addDays(-2)
    );
    insert log;
    LogRepository repository = new LogRepository();

    Test.startTest();
    List<Log__c> logs = repository.getRecent('TeamFacilitator', 1);
    Test.stopTest();

    System.assert(logs.isEmpty(), 'No logs should be returned');
  }

  @isTest
  static void getRecent_returnsLogs_whenFacilitatorLog() {
    setup();
    Team__c team = TestTeam.create();
    Log__c log = new Log__c(
      Team__c = team.Id,
      OtherHours__c = 3,
      PublicAccessHours__c = 2,
      Submitter__c = team.Client__c,
      RecordTypeId = FACILITATOR_ID,
      Date__c = Date.today().addDays(-2)
    );
    insert log;
    LogRepository repository = new LogRepository();

    Test.startTest();
    List<Log__c> logs = repository.getRecent('TeamFacilitator', 3);
    Test.stopTest();

    System.assertEquals(1, logs.size(), 'Just the one log should be returned');
    Team__c actual = logs[0].Team__r;
    System.Assert.areEqual(
      team.Client__c,
      actual.Client__c,
      'Team should be returned'
    );
    System.Assert.areEqual(team.Name, actual.Name, 'Team should be returned');
    System.Assert.areEqual(
      team.Dog__c,
      actual.Dog__c,
      'Team should be returned'
    );
    System.assertEquals(
      team.Facilitator__c,
      actual.Facilitator__c,
      'Team should be returned'
    );
  }
}