force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>Records for individuals receiving services from Atlas Assistance Dogs</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/ClientApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientApplicationReceived__c</fullName>
    <description
    >The date the most recent version of Client Application was uploaded</description>
    <label>Last Client Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientApplicationVideoReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientApplicationVideoReceived__c</fullName>
    <description>The date the most recent version of a Client Application Video was uploaded</description>
    <label>Client Application Video Received</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientCertAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientCertAgreementReceived__c</fullName>
    <description
    >The date the most recent version of Client Certification Agreement was uploaded</description>
    <label>Last Client Certification Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientCGCFormReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientCGCFormReceived__c</fullName>
    <description>The date the most recent version of Client CGC Form was uploaded</description>
    <label>CGC Form</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientLOMIReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientLOMIReceived__c</fullName>
    <description
    >The date the most recent version of Client LOMI was uploaded</description>
    <label>Last Client LOMI</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientPreApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientPreApplicationReceived__c</fullName>
    <description
    >The date the most recent version of Client Pre Application was uploaded</description>
    <label>Last Client Pre Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientProgAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientProgAgreementReceived__c</fullName>
    <description
    >The date the most recent version of Client Program Agreement was uploaded</description>
    <label>Last Client Program Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientSurveyReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientSurveyReceived__c</fullName>
    <description
    >The date the most recent version of Client Certification Survey was uploaded</description>
    <label>Last Client Certification Survey</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientVAPWReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientVAPWReceived__c</fullName>
    <description
    >The date the most recent version of Client Veteran Paperwork was uploaded</description>
    <label>Last Client Veteran Paperwork</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Records the Facilitator, Lead, and Client relationship</description>
    <label>Team</label>
    <nameField>
        <displayFormat>Team-{00000}</displayFormat>
        <label>Team Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client</description>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams (Client)</relationshipLabel>
    <relationshipName>Teams1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/ClientApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientApplicationReceived__c</fullName>
    <description>The date the most recent version of Client Application was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Client Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/ClientApplicationVideoReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientApplicationVideoReceived__c</fullName>
    <description>The date the most recent version of a Client Application Video was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Client Application Video</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/ClientCertAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientCertAgreementReceived__c</fullName>
    <description>The date the most recent version of Client Certification Agreement was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Client Certification Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/ClientCGCFormReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientCGCFormReceived__c</fullName>
    <description>The date the most recent version of Client CGC Form was uploaded</description>
    <label>Last CGC Form</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/ClientLOMIReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientLOMIReceived__c</fullName>
    <description>The date the most recent version of Client LOMI was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Client LOMI</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/ClientPreApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientPreApplicationReceived__c</fullName>
    <description>The date the most recent version of Client Pre Application was uploaded</description>
    <label>Last Client Pre Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/ClientProgAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientProgAgreementReceived__c</fullName>
    <description>The date the most recent version of Client Program Agreement was uploaded</description>
    <label>Last Client Program Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/ClientSurveyReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientSurveyReceived__c</fullName>
    <description>The date the most recent version of Client Certification Survey was uploaded</description>
    <label>Last Client Certification Survey</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/ClientVAPWReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientVAPWReceived__c</fullName>
    <description>The date the most recent version of Client Veteran Paperwork was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Client Veteran Paperwork</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dog on the team</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/test/TestFileServiceClientFields.cls
@isTest
public with sharing class TestFileServiceClientFields {

    private static Dog__c dog;
    private static Contact client;

    private static void createTeamMembers() {
        dog = new Dog__c(Name = 'Fido');
        insert dog;

        client = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert client;
    }

    @isTest
    public static void updateDate_ClientApplication_SetsDateWhenNull() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id);
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'Application', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientApplicationReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientApplicationReceived__c,
            'ClientApplicationReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_ClientApplication_SetsDateWhenNewer() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id, ClientApplicationReceived__c = Date.today().addDays(-1));
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'Application', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientApplicationReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientApplicationReceived__c,
            'ClientApplicationReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_ClientApplication_LeavesDateWhenOlder() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id, ClientApplicationReceived__c = Date.today());
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'Application', Date.today().addDays(-1), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientApplicationReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientApplicationReceived__c,
            'ClientApplicationReceived__c set to an older date'
        );
    }

    @isTest
    public static void updateDate_ClientApplicationVideo_SetsDateWhenNull() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id);
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'ApplicationVideo', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientApplicationVideoReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientApplicationVideoReceived__c,
            'ClientApplicationVideoReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_ClientApplicationVideo_SetsDateWhenNewer() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id, ClientApplicationVideoReceived__c = Date.today().addDays(-1));
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'ApplicationVideo', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientApplicationVideoReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientApplicationVideoReceived__c,
            'ClientApplicationVideoReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_ClientApplicationVideo_LeavesDateWhenOlder() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id, ClientApplicationVideoReceived__c = Date.today());
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'ApplicationVideo', Date.today().addDays(-1), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientApplicationVideoReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientApplicationVideoReceived__c,
            'ClientApplicationVideoReceived__c set to an older date'
        );
    }

    @isTest
    public static void updateDate_ClientCGCForm_SetsDateWhenNull() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id);
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'CGCForm', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientCGCFormReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientCGCFormReceived__c,
            'ClientCGCFormReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_ClientCGCForm_SetsDateWhenNewer() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id, ClientCGCFormReceived__c = Date.today().addDays(-1));
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'CGCForm', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientCGCFormReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientCGCFormReceived__c,
            'ClientCGCFormReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_ClientCGCForm_LeavesDateWhenOlder() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id, ClientCGCFormReceived__c = Date.today());
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'CGCForm', Date.today().addDays(-1), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientCGCFormReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientCGCFormReceived__c,
            'ClientCGCFormReceived__c set to an older date'
        );
    }

    @isTest
    public static void updateDate_ClientCertAgreement_SetsDateWhenNull() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id);
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'CertAgreement', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientCertAgreementReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientCertAgreementReceived__c,
            'ClientCertAgreementReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_ClientCertAgreement_SetsDateWhenNewer() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id, ClientCertAgreementReceived__c = Date.today().addDays(-1));
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'CertAgreement', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientCertAgreementReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientCertAgreementReceived__c,
            'ClientCertAgreementReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_ClientCertAgreement_LeavesDateWhenOlder() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id, ClientCertAgreementReceived__c = Date.today());
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'CertAgreement', Date.today().addDays(-1), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientCertAgreementReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientCertAgreementReceived__c,
            'ClientCertAgreementReceived__c set to an older date'
        );
    }

    @isTest
    public static void updateDate_ClientLOMI_SetsDateWhenNull() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id);
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'LOMI', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientLOMIReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientLOMIReceived__c,
            'ClientLOMIReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_ClientLOMI_SetsDateWhenNewer() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id, ClientLOMIReceived__c = Date.today().addDays(-1));
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'LOMI', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientLOMIReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientLOMIReceived__c,
            'ClientLOMIReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_ClientLOMI_LeavesDateWhenOlder() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id, ClientLOMIReceived__c = Date.today());
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'LOMI', Date.today().addDays(-1), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientLOMIReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientLOMIReceived__c,
            'ClientLOMIReceived__c set to an older date'
        );
    }

    @isTest
    public static void updateDate_ClientPreApplication_SetsDateWhenNull() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id);
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'PreApplication', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientPreApplicationReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientPreApplicationReceived__c,
            'ClientPreApplicationReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_ClientPreApplication_SetsDateWhenNewer() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id, ClientPreApplicationReceived__c = Date.today().addDays(-1));
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'PreApplication', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientPreApplicationReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientPreApplicationReceived__c,
            'ClientPreApplicationReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_ClientPreApplication_LeavesDateWhenOlder() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id, ClientPreApplicationReceived__c = Date.today());
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'PreApplication', Date.today().addDays(-1), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientPreApplicationReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientPreApplicationReceived__c,
            'ClientPreApplicationReceived__c set to an older date'
        );
    }

    @isTest
    public static void updateDate_ClientProgAgreement_SetsDateWhenNull() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id);
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'ProgAgreement', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientProgAgreementReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientProgAgreementReceived__c,
            'ClientProgAgreementReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_ClientProgAgreement_SetsDateWhenNewer() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id, ClientProgAgreementReceived__c = Date.today().addDays(-1));
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'ProgAgreement', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientProgAgreementReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientProgAgreementReceived__c,
            'ClientProgAgreementReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_ClientProgAgreement_LeavesDateWhenOlder() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id, ClientProgAgreementReceived__c = Date.today());
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'ProgAgreement', Date.today().addDays(-1), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientProgAgreementReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientProgAgreementReceived__c,
            'ClientProgAgreementReceived__c set to an older date'
        );
    }

    @isTest
    public static void updateDate_ClientSurvey_SetsDateWhenNull() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id);
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'Survey', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientSurveyReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientSurveyReceived__c,
            'ClientSurveyReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_ClientSurvey_SetsDateWhenNewer() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id, ClientSurveyReceived__c = Date.today().addDays(-1));
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'Survey', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientSurveyReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientSurveyReceived__c,
            'ClientSurveyReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_ClientSurvey_LeavesDateWhenOlder() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id, ClientSurveyReceived__c = Date.today());
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'Survey', Date.today().addDays(-1), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientSurveyReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientSurveyReceived__c,
            'ClientSurveyReceived__c set to an older date'
        );
    }

    @isTest
    public static void updateDate_ClientVAPW_SetsDateWhenNull() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id);
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'VAPW', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientVAPWReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientVAPWReceived__c,
            'ClientVAPWReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_ClientVAPW_SetsDateWhenNewer() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id, ClientVAPWReceived__c = Date.today().addDays(-1));
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'VAPW', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientVAPWReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientVAPWReceived__c,
            'ClientVAPWReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_ClientVAPW_LeavesDateWhenOlder() {
        createTeamMembers();
        Team__c record = new Team__c(Name = 'Test', Client__c = client.Id, Dog__c = dog.Id, ClientVAPWReceived__c = Date.today());
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Client', 'VAPW', Date.today().addDays(-1), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ClientVAPWReceived__c
            FROM Team__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ClientVAPWReceived__c,
            'ClientVAPWReceived__c set to an older date'
        );
    }
}