force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>Records for individuals receiving services from Atlas Assistance Dogs</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Handler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Logs made by Client or Team Facilitator</description>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client the log refers to</description>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Logs (Client)</relationshipLabel>
    <relationshipName>LogsClient</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/ClientHours__c.field-meta.xml
<CustomField>
    <fullName>ClientHours__c</fullName>
    <description
    >Number of hours the Team Facilitator has worked with the client since the last log</description>
    <label>Hours Worked with Client</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/ClientStress__c.field-meta.xml
<CustomField>
    <fullName>ClientStress__c</fullName>
    <label>Client Stress</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Stress</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/DidMeetThisWeek__c.field-meta.xml
<CustomField>
    <fullName>DidMeetThisWeek__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Did you meet with your TF this week?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Dog the log is referring to</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Facilitator__c.field-meta.xml
<CustomField>
    <fullName>Facilitator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Team Facilitator the log is referring to</description>
    <label>Team Facilitator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Logs (Team Facilitator)</relationshipLabel>
    <relationshipName>LogsFacilitator</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/FirstAidDetails__c.field-meta.xml
<CustomField>
    <fullName>FirstAidDetails__c</fullName>
    <description>Details of First Aid session</description>
    <label>First Aid Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>
    

force-app/main/default/objects/Log__c/fields/FirstAidSuppliesUsed__c.field-meta.xml
<CustomField>
    <fullName>FirstAidSuppliesUsed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Did you use First Aid Supplies?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <description>Handler(s) the log pertains to</description>
    <label>Handler(s)</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/OtherHours__c.field-meta.xml
<CustomField>
    <fullName>OtherHours__c</fullName>
    <label>Other Hours</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/PublicAccessHours__c.field-meta.xml
<CustomField>
    <fullName>PublicAccessHours__c</fullName>
    <description>Number of Public Access Hours</description>
    <label># Public Access Hours</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/RequestSupportFromAtlas__c.field-meta.xml
<CustomField>
    <fullName>RequestSupportFromAtlas__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request support from Atlas?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/RequestSupportFromTeam__c.field-meta.xml
<CustomField>
    <fullName>RequestSupportFromTeam__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request support from Team?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Satisfaction__c.field-meta.xml
<CustomField>
    <fullName>Satisfaction__c</fullName>
    <label>Client Life Satisfaction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No enjoyment</fullName>
            </value>
            <value>
                <fullName>A little enjoyment</fullName>
            </value>
            <value>
                <fullName>Some enjoyment</fullName>
            </value>
            <value>
                <fullName>Rather much enjoyment</fullName>
            </value>
            <value>
                <fullName>Extreme amount of enjoyment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/SessionType__c.field-meta.xml
<CustomField>
    <fullName>SessionType__c</fullName>
    <label>Session Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
            <value>
                <fullName>General Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Stress__c.field-meta.xml
<CustomField>
    <fullName>Stress__c</fullName>
    <label>Stress</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Stress</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Submitter__c.field-meta.xml
<CustomField>
    <fullName>Submitter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contact submitting the log</description>
    <label>Submitter</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Logs (Submitter)</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/SupportDetails__c.field-meta.xml
<CustomField>
    <fullName>SupportDetails__c</fullName>
    <description>Details of team support request</description>
    <label>Support Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Team the log is referring to</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Records the Facilitator, Lead, and Client relationship</description>
    <label>Team</label>
    <nameField>
        <displayFormat>Team-{00000}</displayFormat>
        <label>Team Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client</description>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams (Client)</relationshipLabel>
    <relationshipName>Teams1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dog on the team</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Facilitator__c.field-meta.xml
<CustomField>
    <fullName>Facilitator__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Facilitator</description>
    <label>Facilitator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams (Facilitator)</relationshipLabel>
    <relationshipName>Teams2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Handler in the team, if not the client</description>
    <label>Handler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Stress.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not at all</fullName>
        <default>true</default>
        <label>Not at all</label>
    </customValue>
    <customValue>
        <fullName>Only a little</fullName>
    </customValue>
    <customValue>
        <fullName>To some extent</fullName>
    </customValue>
    <customValue>
        <fullName>Rather much</fullName>
    </customValue>
    <customValue>
        <fullName>Very much</fullName>
    </customValue>
    <description>Stress Levels</description>
    <masterLabel>Stress</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/logs/LogController.cls
public with sharing class LogController {
  @AuraEnabled(Cacheable=true)
  public static RelatedObjects getRelatedLogs(
    Id recordId,
    String recordType,
    Integer max
  ) {
    if (max == null) {
      max = 6;
    }
    string objName = recordId.getSObjectType().getDescribe().getName();
    if (objName == Team__c.class.getName()) {
      return getTeamLogs(recordId, recordType, max);
    }
    RelatedObjects related = new RelatedObjects();
    try {
      List<Log__c> logs = [
        SELECT
          ClientHours__c,
          ClientStress__c,
          Date__c,
          Details__c,
          DidMeetThisWeek__c,
          Facilitator__c,
          Facilitator__r.Name,
          FirstAidSuppliesUsed__c,
          FirstAidDetails__c,
          Name,
          OtherHours__c,
          PublicAccessHours__c,
          RequestSupportFromAtlas__c,
          RequestSupportFromTeam__c,
          Satisfaction__c,
          SessionType__c,
          Stress__c,
          Submitter__c,
          Submitter__r.Name,
          SupportDetails__c,
          Team__c,
          Team__r.Client__c,
          Team__r.Client__r.Name,
          Team__r.Dog__c,
          Team__r.Dog__r.Name,
          Team__r.Handler__c,
          Team__r.Handler__r.Name,
          Team__r.Name,
          RecordTypeId
        FROM Log__c
        WHERE
          (Team__r.Client__c = :recordId
          OR Submitter__c = :recordId
          OR Facilitator__c = :recordId
          OR Team__r.Dog__c = :recordId)
          AND RecordType.DeveloperName = :recordType
        ORDER BY Date__c DESC NULLS LAST
        LIMIT :max
      ];
      for (Log__c log : logs) {
        LogInfo item = new LogInfo();
        item.log = log;
        item.clientName = log.Team__r.Client__r.Name;
        item.facilitatorName = log.Facilitator__r.Name;
        item.handlerName = log.Team__r.Handler__r.Name;
        item.submitterName = log.Submitter__r.Name;
        item.teamName = log.Team__r.Name;
        related.items.add(item);
      }
      related.total = [
        SELECT COUNT()
        FROM Log__c
        WHERE
          (Team__r.Client__c = :recordId
          OR Submitter__c = :recordId
          OR Facilitator__c = :recordId
          OR Team__r.Dog__c = :recordId)
          AND RecordType.DeveloperName = :recordType
      ];
      return related;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
  @AuraEnabled(Cacheable=true)
  public static RelatedObjects getTeamLogs(
    Id recordId,
    String recordType,
    Integer max
  ) {
    if (max == null) {
      max = 6;
    }
    RelatedObjects related = new RelatedObjects();
    try {
      List<Log__c> logs = [
        SELECT
          ClientHours__c,
          ClientStress__c,
          Date__c,
          Details__c,
          DidMeetThisWeek__c,
          Facilitator__c,
          Facilitator__r.Name,
          FirstAidSuppliesUsed__c,
          FirstAidDetails__c,
          Name,
          OtherHours__c,
          PublicAccessHours__c,
          RequestSupportFromAtlas__c,
          RequestSupportFromTeam__c,
          Satisfaction__c,
          SessionType__c,
          Stress__c,
          Submitter__c,
          Submitter__r.Name,
          SupportDetails__c,
          Team__c,
          Team__r.Client__c,
          Team__r.Client__r.Name,
          Team__r.Dog__c,
          Team__r.Dog__r.Name,
          Team__r.Handler__c,
          Team__r.Handler__r.Name,
          Team__r.Name,
          RecordTypeId
        FROM Log__c
        WHERE Team__c = :recordId AND RecordType.DeveloperName = :recordType
        ORDER BY Date__c DESC NULLS LAST
        LIMIT :max
      ];
      for (Log__c log : logs) {
        LogInfo item = new LogInfo();
        item.log = log;
        item.clientName = log.Team__r.Client__r.Name;
        item.facilitatorName = log.Facilitator__r.Name;
        item.handlerName = log.Team__r.Handler__r.Name;
        item.submitterName = log.Submitter__r.Name;
        item.teamName = log.Team__r.Name;
        related.items.add(item);
      }
      related.total = [
        SELECT COUNT()
        FROM Log__c
        WHERE Team__c = :recordId AND RecordType.DeveloperName = :recordType
      ];
      return related;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}