force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>Records for individuals receiving services from Atlas Assistance Dogs</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Derived from Team.  Do not edit directly.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In ADSiM</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Certified-Active</fullName>
            </value>
            <value>
                <fullName>Certified-OnHold</fullName>
            </value>
            <value>
                <fullName>Decertified</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/PublicAccessTest__c.object-meta.xml
<CustomObject>
    <description>Tests that the Dog/Client team can perform in public.</description>
    <label>PAT</label>
    <nameField>
        <displayFormat>PAT-{0000}</displayFormat>
        <label>Public Access Test Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PATs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PublicAccessTest__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person assessing the team</description>
    <label>Assessor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Public_Access_Tests_Assessor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/AssessorComments__c.field-meta.xml
<CustomField>
    <fullName>AssessorComments__c</fullName>
    <description>Comments from the person assessing the team</description>
    <label>Assessor Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client being assessed in the PAT</description>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PATs (Client)</relationshipLabel>
    <relationshipName>Public_Access_Tests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/DateCompleted__c.field-meta.xml
<CustomField>
    <fullName>DateCompleted__c</fullName>
    <description>Date the test was completed</description>
    <label>Date Completed</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Dog in the PAT team</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>PATs</relationshipLabel>
    <relationshipName>Public_Access_Tests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Handler in the team, if not the client</description>
    <label>Handler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Public_Access_Tests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Relative location of the test</description>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/ReviewComments__c.field-meta.xml
<CustomField>
    <fullName>ReviewComments__c</fullName>
    <description>Comments made by the client</description>
    <label>Review Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the PAT</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Provisionally Passed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Public Access Test</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
            </value>
            <value>
                <fullName>Recertification</fullName>
            </value>
            <value>
                <fullName>Retest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PublicAccessTestController.cls
public with sharing class PublicAccessTestController {
    @AuraEnabled(Cacheable=true)
    public static List<PublicAccessTest__c> getRelatedPats(id contactId) {
        try {
            return [
                SELECT
                    Assessor__c,
                    AssessorComments__c,
                    Client__c,
                    DateCompleted__c,
                    Dog__c,
                    Dog__r.Name,
                    Handler__c,
                    Location__c,
                    ReviewComments__c,
                    Status__c,
                    Type__c
                FROM PublicAccessTest__c
                WHERE
                    Assessor__c = :contactId
                    OR Client__c = :contactId
                    OR Handler__c = :contactId
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(Cacheable=true)
    public static PublicAccessTest__c getPat(id recordId) {
        try {
            return [
                SELECT
                    Assessor__c,
                    AssessorComments__c,
                    Client__c,
                    DateCompleted__c,
                    Dog__c,
                    Handler__c,
                    Location__c,
                    ReviewComments__c,
                    Status__c,
                    Type__c
                FROM PublicAccessTest__c
                WHERE Id = :recordId
                LIMIT 1
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void createPat(PublicAccessTest__c record) {
        try {
            insert record;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void updatePat(PublicAccessTest__c record) {
        try {
            update record;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void deletePat(Id recordId) {
        try {
            PublicAccessTest__c pat = [
                SELECT Id
                FROM PublicAccessTest__c
                WHERE Id = :recordId
            ];
            delete pat;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}