force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>Records for individuals receiving services from Atlas Assistance Dogs</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/ClientCertificationValidUntil__c.field-meta.xml
<CustomField>
    <fullName>ClientCertificationValidUntil__c</fullName>
    <description>Date that the client certification is valid until</description>
    <label>Client Certification Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Handler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contacts.recordType-meta.xml
<RecordType>
    <fullName>Contacts</fullName>
    <active>true</active>
    <label>Contacts</label>
</RecordType>

force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Derived from Team.  Do not edit directly.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In ADSiM</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Certified-Active</fullName>
            </value>
            <value>
                <fullName>Certified-OnHold</fullName>
            </value>
            <value>
                <fullName>Decertified</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/PublicAccessTest__c.object-meta.xml
<CustomObject>
    <description>Tests that the Dog/Client team can perform in public.</description>
    <label>PAT</label>
    <nameField>
        <displayFormat>PAT-{0000}</displayFormat>
        <label>Public Access Test Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PATs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PublicAccessTest__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person assessing the team</description>
    <label>Assessor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Public_Access_Tests_Assessor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client being assessed in the PAT</description>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PATs (Client)</relationshipLabel>
    <relationshipName>Public_Access_Tests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/DateCompleted__c.field-meta.xml
<CustomField>
    <fullName>DateCompleted__c</fullName>
    <description>Date the test was completed</description>
    <label>Date Completed</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Dog in the PAT team</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>PATs</relationshipLabel>
    <relationshipName>Public_Access_Tests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Handler in the team, if not the client</description>
    <label>Handler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Public_Access_Tests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Relative location of the test</description>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the PAT</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Provisionally Passed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Team the test is for</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>PATs</relationshipLabel>
    <relationshipName>PATs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Public Access Test</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
            </value>
            <value>
                <fullName>Recertification</fullName>
            </value>
            <value>
                <fullName>Retest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/ValidUntil__c.field-meta.xml
<CustomField>
    <fullName>ValidUntil__c</fullName>
    <description>Date the test is valid until</description>
    <label>Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Records the Facilitator, Lead, and Client relationship</description>
    <label>Team</label>
    <nameField>
        <displayFormat>Team-{00000}</displayFormat>
        <label>Team Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client</description>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams (Client)</relationshipLabel>
    <relationshipName>Teams1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dog on the team</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Handler in the team, if not the client</description>
    <label>Handler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/PatCount__c.field-meta.xml
<CustomField>
    <fullName>PatCount__c</fullName>
    <description
    >Number of Public Access Tests the Client-Dog team has taken</description>
    <label>PAT Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/PatValidUntil__c.field-meta.xml
<CustomField>
    <fullName>PatValidUntil__c</fullName>
    <description>Date the Public Access Test expires</description>
    <inlineHelpText>Derived from most recent passed PAT. Do not edit directly.</inlineHelpText>
    <label>PAT Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/PrimaryCertification__c.field-meta.xml
<CustomField>
    <fullName>PrimaryCertification__c</fullName>
    <label>Primary Certification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Certifications</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team__c/fields/SecondaryCertification__c.field-meta.xml
<CustomField>
    <fullName>SecondaryCertification__c</fullName>
    <label>Secondary Certification</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Certifications</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>This status defines the status for the Team, Dog, and Client.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In ADSiM</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Certified-Hold</fullName>
            </value>
            <value>
                <fullName>Decertified</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Certifications.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Atlas</fullName>
        <default>true</default>
        <label>Atlas</label>
    </customValue>
    <customValue>
        <fullName>KPA</fullName>
    </customValue>
    <customValue>
        <fullName>CCPDT</fullName>
    </customValue>
    <customValue>
        <fullName>IAABC</fullName>
    </customValue>
    <customValue>
        <fullName>CBCC</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <description>Client Dog Team Certifications</description>
    <masterLabel>Certifications</masterLabel>
</GlobalValueSet>

force-app/main/test/public-access-tests/TestPatTrigger.cls
@IsTest
public with sharing class TestPatTrigger {
  private static Team__c team;
  private static PublicAccessTest__c pat;
  private static Contact ken;
  private static Contact debbie;
  private static Dog__c ace;

  private static void setup(Date expiration) {
    List<Contact> contacts = new List<Contact>();
    debbie = new Contact(FirstName = 'Debbie', LastName = 'Queen');
    ken = new Contact(FirstName = 'Ken', LastName = 'King');
    contacts.add(debbie);
    contacts.add(ken);
    insert contacts;

    ace = new Dog__c(Name = 'Ace');
    insert ace;

    team = new Team__c(
      Client__c = contacts[1].Id,
      Dog__c = ace.Id,
      Handler__c = contacts[0].Id,
      Name = 'Camelot',
      PatValidUntil__c = expiration.addMonths(5),
      PatCount__c = 21,
      PrimaryCertification__c = 'Allergen Alert',
      SecondaryCertification__c = 'Autism'
    );
    insert team;

    pat = new PublicAccessTest__c(
      Assessor__c = ken.Id,
      DateCompleted__c = Date.today(),
      Location__c = 'In Person',
      Status__c = 'Passed',
      Team__c = team.Id,
      Type__c = 'Initial',
      ValidUntil__c = expiration
    );
  }

  private static Contact getContact(Id contactId) {
    return [
      SELECT Id, ClientCertificationValidUntil__c
      FROM Contact
      WHERE Id = :contactId
    ];
  }

  private static Team__c getTeam(Id teamId) {
    return [
      SELECT id, PatValidUntil__c, Client__c, PatCount__c
      FROM Team__c
      WHERE Id = :teamId
      LIMIT 1
    ];
  }

  @isTest
  static void insert_setsValidUntil_whenPatValidSet() {
    Date expiration = Date.today().addMonths(12);
    setup(expiration);

    // Act
    Test.startTest();
    Database.SaveResult result = Database.insert(pat, false);
    Test.stopTest();

    // Assert
    System.assert(result.isSuccess());
    System.assert(result.getErrors().size() == 0);
    Team__c team = getTeam(team.Id);
    Contact contact = getContact(team.Client__c);
    System.assertEquals(expiration, team.PatValidUntil__c);
    System.assertEquals(expiration, contact.ClientCertificationValidUntil__c);
    System.assertEquals(1, team.PatCount__c);
  }

  @isTest
  static void update_updates_whenPatValidSetBackward() {
    Date expiration = Date.today().addMonths(12);
    setup(expiration);
    insert pat;

    pat.ValidUntil__c = Date.today().addDays(200);

    // Act
    Test.startTest();
    Database.SaveResult result = Database.update(pat, false);
    Test.stopTest();

    // Assert
    System.assert(result.isSuccess());
    System.assert(result.getErrors().size() == 0);
    Team__c team = getTeam(team.Id);
    Contact contact = getContact(team.Client__c);
    System.assertEquals(pat.ValidUntil__c, team.PatValidUntil__c);
    System.assertEquals(
      contact.ClientCertificationValidUntil__c,
      team.PatValidUntil__c
    );
    System.assertEquals(1, team.PatCount__c);
  }

  @isTest
  static void delete_clears_whenPatDeleted() {
    Date expiration = Date.today().addMonths(12);
    setup(expiration);
    insert pat;

    // Act
    Test.startTest();
    Database.DeleteResult result = Database.delete(pat, false);
    Test.stopTest();

    // Assert
    System.assert(result.isSuccess());
    System.assert(result.getErrors().size() == 0);
    Team__c team = getTeam(team.Id);
    Contact contact = getContact(team.Client__c);
    System.assertEquals(null, team.PatValidUntil__c);
    System.assertEquals(null, contact.ClientCertificationValidUntil__c);
    System.assertEquals(0, team.PatCount__c);
  }

  @isTest
  static void insert_Several_CountsPassing() {
    Date expiration = Date.today().addMonths(12);
    setup(expiration);

    // Insert more
    List<PublicAccessTest__c> pats = new List<PublicAccessTest__c>{
      pat,
      new PublicAccessTest__c(
        Assessor__c = ken.Id,
        DateCompleted__c = Date.today().addMonths(-37),
        Location__c = 'In Person',
        Status__c = 'Failed',
        Team__c = team.Id,
        Type__c = 'Initial'
      ),
      new PublicAccessTest__c(
        Assessor__c = ken.Id,
        DateCompleted__c = Date.today().addMonths(-36),
        Location__c = 'In Person',
        Status__c = 'Passed',
        Team__c = team.Id,
        Type__c = 'Retest',
        ValidUntil__c = Date.today().addMonths(-24)
      ),
      new PublicAccessTest__c(
        Assessor__c = ken.Id,
        DateCompleted__c = Date.today().addMonths(-24),
        Location__c = 'In Person',
        Status__c = 'Passed',
        Team__c = team.Id,
        Type__c = 'Recertification',
        ValidUntil__c = Date.today().addMonths(-12)
      ),
      new PublicAccessTest__c(
        Assessor__c = ken.Id,
        DateCompleted__c = Date.today().addMonths(-12),
        Location__c = 'In Person',
        Status__c = 'Passed',
        Team__c = team.Id,
        Type__c = 'Recertification',
        ValidUntil__c = Date.today()
      )
    };

    // Act
    Test.startTest();
    List<Database.SaveResult> results = Database.insert(pats, false);
    Test.stopTest();

    // Assert
    for (Database.SaveResult result : results) {
      System.assert(result.isSuccess());
      System.assert(result.getErrors().size() == 0);
    }
    Team__c team = getTeam(team.Id);
    Contact contact = getContact(team.Client__c);
    System.assertEquals(expiration, team.PatValidUntil__c);
    System.assertEquals(expiration, contact.ClientCertificationValidUntil__c);
    System.assertEquals(pats.size() - 1, team.PatCount__c);
  }

  @isTest
  static void insert_MultipleTeams_CountsPassing() {
    Date expiration = Date.today().addMonths(12);
    setup(expiration);
    Date expiration2 = Date.today().addMonths(1);

    Team__c team2 = new Team__c(
      Client__c = debbie.Id,
      Dog__c = ace.Id,
      Handler__c = ken.Id,
      Name = 'Deb_Ace',
      PatValidUntil__c = expiration.addMonths(5),
      PatCount__c = 0,
      PrimaryCertification__c = 'Allergen Alert',
      SecondaryCertification__c = 'Autism'
    );
    insert team2;

    // Insert more
    List<PublicAccessTest__c> pats = new List<PublicAccessTest__c>{
      pat,
      new PublicAccessTest__c(
        Assessor__c = ken.Id,
        DateCompleted__c = Date.today().addMonths(-37),
        Location__c = 'In Person',
        Status__c = 'Failed',
        Team__c = team2.Id,
        Type__c = 'Initial'
      ),
      new PublicAccessTest__c(
        Assessor__c = ken.Id,
        DateCompleted__c = Date.today().addMonths(-36),
        Location__c = 'In Person',
        Status__c = 'Passed',
        Team__c = team.Id,
        Type__c = 'Retest',
        ValidUntil__c = Date.today().addMonths(-24)
      ),
      new PublicAccessTest__c(
        Assessor__c = ken.Id,
        DateCompleted__c = Date.today().addMonths(-11),
        Location__c = 'In Person',
        Status__c = 'Passed',
        Team__c = team2.Id,
        Type__c = 'Recertification',
        ValidUntil__c = expiration2
      ),
      new PublicAccessTest__c(
        Assessor__c = ken.Id,
        DateCompleted__c = Date.today().addMonths(-12),
        Location__c = 'In Person',
        Status__c = 'Pending Review',
        Team__c = team.Id,
        Type__c = 'Recertification',
        ValidUntil__c = Date.today()
      )
    };

    // Act
    Test.startTest();
    List<Database.SaveResult> results = Database.insert(pats, false);
    Test.stopTest();

    // Assert
    for (Database.SaveResult result : results) {
      System.assert(result.isSuccess());
      System.assert(result.getErrors().size() == 0);
    }
    Team__c team = getTeam(team.Id);
    Contact contact = getContact(team.Client__c);
    System.assertEquals(expiration, team.PatValidUntil__c);
    System.assertEquals(expiration, contact.ClientCertificationValidUntil__c);
    System.assertEquals(2, team.PatCount__c);

    team = getTeam(team2.Id);
    contact = getContact(team.Client__c);
    System.assertEquals(expiration2, team.PatValidUntil__c);
    System.assertEquals(expiration2, contact.ClientCertificationValidUntil__c);
    System.assertEquals(1, team.PatCount__c);
  }

  @isTest
  static void delete_updatesToLatest_whenPatDeleted() {
    Date expiration = Date.today().addMonths(12);
    setup(expiration);

    // Insert more
    List<PublicAccessTest__c> pats = new List<PublicAccessTest__c>{
      pat,
      new PublicAccessTest__c(
        Assessor__c = ken.Id,
        DateCompleted__c = Date.today().addMonths(-37),
        Location__c = 'In Person',
        Status__c = 'Failed',
        Team__c = team.Id,
        Type__c = 'Initial'
      ),
      new PublicAccessTest__c(
        Assessor__c = ken.Id,
        DateCompleted__c = Date.today().addMonths(-36),
        Location__c = 'In Person',
        Status__c = 'Passed',
        Team__c = team.Id,
        Type__c = 'Retest',
        ValidUntil__c = Date.today().addMonths(-24)
      ),
      new PublicAccessTest__c(
        Assessor__c = ken.Id,
        DateCompleted__c = Date.today().addMonths(-24),
        Location__c = 'In Person',
        Status__c = 'Passed',
        Team__c = team.Id,
        Type__c = 'Recertification',
        ValidUntil__c = Date.today().addMonths(-12)
      ),
      new PublicAccessTest__c(
        Assessor__c = ken.Id,
        DateCompleted__c = Date.today(),
        Location__c = 'In Person',
        Status__c = 'Passed',
        Team__c = team.Id,
        Type__c = 'Recertification',
        ValidUntil__c = Date.today().addMonths(24)
      )
    };
    insert pats;

    // Act
    Test.startTest();
    Database.DeleteResult result = Database.delete(pats[4], false);
    Test.stopTest();

    // Assert
    System.assert(result.isSuccess());
    System.assert(result.getErrors().size() == 0);
    Team__c team = getTeam(team.Id);
    Contact contact = getContact(team.Client__c);
    System.assertEquals(expiration, team.PatValidUntil__c);
    System.assertEquals(expiration, contact.ClientCertificationValidUntil__c);
    System.assertEquals(pats.size() - 2, team.PatCount__c);
  }

  @isTest
  static void update_ToDifferentTeam_UpdatesBothTeams() {
    Date expiration = Date.today().addMonths(12);
    setup(expiration);
    insert pat;

    Team__c team2 = new Team__c(
      Client__c = debbie.Id,
      Dog__c = ace.Id,
      Handler__c = ken.Id,
      Name = 'Deb_Ace',
      PatValidUntil__c = expiration.addMonths(5),
      PatCount__c = 0,
      PrimaryCertification__c = 'Allergen Alert',
      SecondaryCertification__c = 'Autism'
    );
    insert team2;

    pat.Team__c = team2.Id;

    // Act
    Test.startTest();
    Database.SaveResult result = Database.update(pat, false);
    Test.stopTest();

    // Assert
    System.assert(result.isSuccess());
    System.assert(result.getErrors().size() == 0);
    Team__c team = getTeam(team.Id);
    Contact contact = getContact(team.Client__c);
    System.assertEquals(null, team.PatValidUntil__c);
    System.assertEquals(null, contact.ClientCertificationValidUntil__c);
    System.assertEquals(0, team.PatCount__c);

    team = getTeam(team2.Id);
    contact = getContact(team.Client__c);
    System.assertEquals(expiration, team.PatValidUntil__c);
    System.assertEquals(expiration, contact.ClientCertificationValidUntil__c);
    System.assertEquals(1, team.PatCount__c);
  }
}