force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>Records for individuals receiving services from Atlas Assistance Dogs</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connects the Client to their contact record</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientCertificationValidUntil__c.field-meta.xml
<CustomField>
    <fullName>ClientCertificationValidUntil__c</fullName>
    <description>Date that the client certification is valid until</description>
    <label>Client Certification Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientInitialCertificationDate__c.field-meta.xml
<CustomField>
    <fullName>ClientInitialCertificationDate__c</fullName>
    <description>Date that the client was first certified.</description>
    <inlineHelpText>Derived from Team Initial Certification Date. Do not edit directly.</inlineHelpText>
    <label>Client Initial Certification Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientStatus__c.field-meta.xml
<CustomField>
    <fullName>ClientStatus__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <inlineHelpText>Derived from Team. Do not edit directly.</inlineHelpText>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In ADSiM</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Certified-Hold</fullName>
            </value>
            <value>
                <fullName>Decertified</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Not Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Place/person to contact this person</description>
    <inlineHelpText>Select Guardian to contact this person through their guardian, Home for personal email/phone</inlineHelpText>
    <label>Contact At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
                <default>true</default>
                <label>Home</label>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Derived from Team.  Do not edit directly.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In ADSiM</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Certified-Active</fullName>
            </value>
            <value>
                <fullName>Certified-OnHold</fullName>
            </value>
            <value>
                <fullName>Decertified</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DogRelationship__c/DogRelationship__c.object-meta.xml
<CustomObject>
    <description>Connection between a dog and a contact</description>
    <label>Dog Relationship</label>
    <nameField>
        <displayFormat>DR-{00000}</displayFormat>
        <label>Dog Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dogs Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DogRelationship__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Dogs</relationshipLabel>
    <relationshipName>DogsContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DogRelationship__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A dog for this contact</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>Humans</relationshipLabel>
    <relationshipName>DogsContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DogRelationship__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
    >Team the dog and human are on.  Only valid if the relationship is dog-client or dog-trainer.</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Dogs Relationships</relationshipLabel>
    <relationshipName>Dogs_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DogRelationship__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Relationship types between a dog and contact</description>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Veterinarian</fullName>
            </value>
            <value>
                <fullName>Handler</fullName>
            </value>
            <value>
                <fullName>Facilitator</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/PublicAccessTest__c.object-meta.xml
<CustomObject>
    <description>Tests that the Dog/Client team can perform in public.</description>
    <label>PAT</label>
    <nameField>
        <displayFormat>PAT-{0000}</displayFormat>
        <label>Public Access Test Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PATs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PublicAccessTest__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client being assessed in the PAT</description>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PATs (Client)</relationshipLabel>
    <relationshipName>Public_Access_Tests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Dog in the PAT team</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>PATs</relationshipLabel>
    <relationshipName>Public_Access_Tests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the PAT</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Provisionally Passed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Team the test is for</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>PATs</relationshipLabel>
    <relationshipName>PATs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Public Access Test</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
            </value>
            <value>
                <fullName>Recertification</fullName>
            </value>
            <value>
                <fullName>Retest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/ValidUntil__c.field-meta.xml
<CustomField>
    <fullName>ValidUntil__c</fullName>
    <description>Date the test is valid until</description>
    <label>Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Records the Facilitator, Lead, and Client relationship</description>
    <label>Team</label>
    <nameField>
        <displayFormat>Team-{00000}</displayFormat>
        <label>Team Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client</description>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams (Client)</relationshipLabel>
    <relationshipName>Teams1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dog on the team</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/InitialCertificationDate__c.field-meta.xml
<CustomField>
    <fullName>InitialCertificationDate__c</fullName>
    <label>Initial Certification Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/PatValidUntil__c.field-meta.xml
<CustomField>
    <fullName>PatValidUntil__c</fullName>
    <description>Date the Public Access Test expires</description>
    <inlineHelpText>Derived from most recent passed PAT. Do not edit directly.</inlineHelpText>
    <label>PAT Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>This status defines the status for the Team, Dog, and Client.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In ADSiM</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Certified-Hold</fullName>
            </value>
            <value>
                <fullName>Decertified</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/teams/TeamService.cls
public inherited sharing class TeamService{
  public TeamService(){
    this.patRepo = new PublicAccessTestRepository();
    this.dogRepo = new DogRepository();
    this.contactRepo = new ContactRepository();
    this.teamRepo = new TeamRepository();
    this.relationshipRepo = new RelationshipRepository();
    this.emailServ = new EmailService();
  }

  @TestVisible
  private TeamService(TeamRepository teamRepo, PublicAccessTestRepository patRepo, RelationshipRepository relationshipRepo, EmailService emailServ, DogRepository dogRepo, ContactRepository contactRepo){
    this.patRepo = patRepo;
    this.dogRepo = dogRepo;
    this.contactRepo = contactRepo;
    this.teamRepo = teamRepo;
    this.relationshipRepo = relationshipRepo;
    this.emailServ = emailServ;
  }

  private PublicAccessTestRepository patRepo;
  private ContactRepository contactRepo;
  private DogRepository dogRepo;
  private TeamRepository teamRepo;
  private RelationshipRepository relationshipRepo;
  private EmailService emailServ;
  // Set the dog/client relationship.
  // This is meant to be called from the team update trigger.
  public void setClientDogRelationShip(Team__c newTeam){
    // See if there is an existing relationship between the dog and client
    List<DogRelationShip__c> relationShips = dogRepo.getRelationships(newTeam.Client__c, newTeam.Dog__c);

    if (relationShips.size() == 0){
      DogRelationShip__c relationShip = new DogRelationShip__c(
        Contact__c = newTeam.Client__c, 
        Dog__c = newTeam.Dog__c, 
        Type__c = 'Client'
      );
      dogRepo.createRelationship(relationShip);
    } else{
      // add client to the type if not already there
      for (DogRelationShip__c relationShip : relationShips){
        if (relationShip.Type__c != null && relationShip.Type__c.contains('Client')){
          return;
        }
      }
      // otherwise, add Client to the first relationship (should be the only one)
      DogRelationShip__c relationShip = relationShips[0];
      if (String.isBlank(relationShip.Type__c)){
        relationShip.Type__c = 'Client';
      } else{
        relationShip.Type__c = relationShip.Type__c + ';Client';
      }
      dogRepo.modifyRelationship(relationShip);
    }
  }

  // Update client status.  This is meant to be called from the team update trigger.
  public void updateClientStatus(Team__c team){
    Contact client = contactRepo.getClientStatus(team.Client__c);

    if (client != null){
      Dog__c dog = dogRepo.getById(team.Dog__c);
      client.ClientCertificationValidUntil__c = team.PatValidUntil__c;
      client.ClientStatus__c = team.Status__c;
      client.ClientInitialCertificationDate__c = team.InitialCertificationDate__c;
      client.ClientFacilitatorAvailability__c = team.FacilitatorAvailability__c;
      if (dog != null){
        client.ClientDog__c = dog.Name;
      }
      contactRepo.modify(client);
    }
  }

  // Update client status.  This is meant to be called from the team update trigger.
  public void updateDogStatus(Team__c team){
    Dog__c dog = dogRepo.getById(team.Dog__c);

    if (dog != null){
      dog.Status__c = team.Status__c;
      dog.XrayRequired__c = team.XrayRequired__c;
      dogRepo.modify(dog);
    }
  }

  // Update PAT information
  public void updatePatInformation(Set<Id> teamIds){
    List<Team__c> teams = teamRepo.getByIds(teamIds);

    for (Team__c team : teams){
      List<PublicAccessTest__c> passingPats = patRepo.getPassing(team.Id);
      if (passingPats.isEmpty()){
        team.PatValidUntil__c = null;
      } else if (team.PatValidUntil__c != passingPats[0].ValidUntil__c){
        team.PatValidUntil__c = passingPats[0].ValidUntil__c;
      }
      team.PatCount__c = passingPats.size();
    }

    teamRepo.modify(teams);
  }

  // Set InitialCertificationDate when first ClientCertAgreementReceived.
  // Called from TeamTriggerBefore
  public void setTeamHandler(List<Team__c> teams) {
    for (Team__c team : teams) {
      if (team.ClientCertAgreementReceived__c != null && team.InitialCertificationDate__c == null) {
        team.InitialCertificationDate__c = team.ClientCertAgreementReceived__c;
      }
    }
  }

  // Set the client/facilitator relationship.
  // This is meant to be called from the team update trigger.
  public void setClientFacilitatorRelationShip(Team__c newTeam){
    if (newTeam.Facilitator__c == null)
      return;
    // nothing to do
    // See if there is an existing relationship between the client and facilitator
    List<npe4__Relationship__c> relationShips = relationshipRepo.getForPair(newTeam.Client__c, newTeam.Facilitator__c, 'Team Faciliator');

    // see if there is an existing relationship object to use
    for (npe4__Relationship__c relationShip : relationShips){
      if (relationShip.npe4__Status__c == 'Current'){
        return;
      }
      // Set the status to current if not
      relationShip.npe4__Status__c = 'Current';
      relationshipRepo.modify(relationShip);
      return;
    }
    // if we made it to here, there isn't an existing relationship, so create a new one
    npe4__Relationship__c relationShip = new npe4__Relationship__c(
      npe4__Contact__c = newTeam.Client__c, 
      npe4__RelatedContact__c = newTeam.Facilitator__c, 
      npe4__Type__c = 'Team Faciliator', 
      npe4__Status__c = 'Current'
    );
    relationshipRepo.create(relationShip);
  }

}