force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>Records for individuals receiving services from Atlas Assistance Dogs</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dog__c/fields/HealthFormReceived__c.field-meta.xml
<CustomField>
    <fullName>HealthFormReceived__c</fullName>
    <description
    >The date the most recent version of Vet Health Form was uploaded</description>
    <label>Last  Vet Health Form</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/XrayReceived__c.field-meta.xml
<CustomField>
    <fullName>XrayReceived__c</fullName>
    <description
    >The date the most recent version of Vet Xray Report was uploaded</description>
    <label>Last  Vet Xray Report</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Records the Facilitator, Lead, and Client relationship</description>
    <label>Team</label>
    <nameField>
        <displayFormat>Team-{00000}</displayFormat>
        <label>Team Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client</description>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams (Client)</relationshipLabel>
    <relationshipName>Teams1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dog on the team</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/HealthFormReceived__c.field-meta.xml
<CustomField>
    <fullName>HealthFormReceived__c</fullName>
    <description>The date the most recent version of Vet Health Form was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Vet Health Form</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/XrayReceived__c.field-meta.xml
<CustomField>
    <fullName>XrayReceived__c</fullName>
    <description>The date the most recent version of Vet Xray Report was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Vet Xray Report</label>
    <type>Date</type>
</CustomField>

force-app/main/test/files/TestFileServiceTeamDogFields.cls
@isTest
public with sharing class TestFileServiceTeamDogFields {
  private static Dog__c dog;
  private static Contact client;

  private static void createTeamMembers() {
    dog = new Dog__c(Name = 'Fido');
    insert dog;

    client = new Contact(
      FirstName = 'Test',
      LastName = 'Contact',
      Email = 'abc@abc.com'
    );
    insert client;
  }

  @isTest
  public static void updateDate_TeamDogHealthForm_SetsDateWhenNull() {
    createTeamMembers();
    Team__c record = new Team__c(
      Name = 'Test',
      Client__c = client.Id,
      Dog__c = dog.Id
    );
    insert record;
    ContentVersion cv = TestFileServiceFields.createLink(
      'TeamDog',
      'HealthForm',
      Date.today(),
      record.Id
    );
    FileService.updateDate(cv, record.Id);

    record = [
      SELECT HealthFormReceived__c
      FROM Team__c
      WHERE Id = :record.Id
      LIMIT 1
    ];
    system.assertEquals(
      Date.today(),
      record.HealthFormReceived__c,
      'HealthFormReceived__c not set'
    );
  }

  @isTest
  public static void updateDate_TeamDogHealthForm_SetsDateWhenNewer() {
    createTeamMembers();
    Team__c record = new Team__c(
      Name = 'Test',
      Client__c = client.Id,
      Dog__c = dog.Id,
      HealthFormReceived__c = Date.today().addDays(-1)
    );
    insert record;
    ContentVersion cv = TestFileServiceFields.createLink(
      'TeamDog',
      'HealthForm',
      Date.today(),
      record.Id
    );
    FileService.updateDate(cv, record.Id);

    record = [
      SELECT HealthFormReceived__c
      FROM Team__c
      WHERE Id = :record.Id
      LIMIT 1
    ];
    system.assertEquals(
      Date.today(),
      record.HealthFormReceived__c,
      'HealthFormReceived__c not set'
    );
  }

  @isTest
  public static void updateDate_TeamDogHealthForm_LeavesDateWhenOlder() {
    createTeamMembers();
    Team__c record = new Team__c(
      Name = 'Test',
      Client__c = client.Id,
      Dog__c = dog.Id,
      HealthFormReceived__c = Date.today()
    );
    insert record;
    ContentVersion cv = TestFileServiceFields.createLink(
      'TeamDog',
      'HealthForm',
      Date.today().addDays(-1),
      record.Id
    );
    FileService.updateDate(cv, record.Id);

    record = [
      SELECT HealthFormReceived__c
      FROM Team__c
      WHERE Id = :record.Id
      LIMIT 1
    ];
    system.assertEquals(
      Date.today(),
      record.HealthFormReceived__c,
      'HealthFormReceived__c set to an older date'
    );
  }

  @isTest
  public static void updateDate_TeamDogXray_SetsDateWhenNull() {
    createTeamMembers();
    Team__c record = new Team__c(
      Name = 'Test',
      Client__c = client.Id,
      Dog__c = dog.Id
    );
    insert record;
    ContentVersion cv = TestFileServiceFields.createLink(
      'TeamDog',
      'Xray',
      Date.today(),
      record.Id
    );
    FileService.updateDate(cv, record.Id);

    record = [
      SELECT XrayReceived__c
      FROM Team__c
      WHERE Id = :record.Id
      LIMIT 1
    ];
    system.assertEquals(
      Date.today(),
      record.XrayReceived__c,
      'XrayReceived__c not set'
    );
  }

  @isTest
  public static void updateDate_TeamDogXray_SetsDateWhenNewer() {
    createTeamMembers();
    Team__c record = new Team__c(
      Name = 'Test',
      Client__c = client.Id,
      Dog__c = dog.Id,
      XrayReceived__c = Date.today().addDays(-1)
    );
    insert record;
    ContentVersion cv = TestFileServiceFields.createLink(
      'TeamDog',
      'Xray',
      Date.today(),
      record.Id
    );
    FileService.updateDate(cv, record.Id);

    record = [
      SELECT XrayReceived__c
      FROM Team__c
      WHERE Id = :record.Id
      LIMIT 1
    ];
    system.assertEquals(
      Date.today(),
      record.XrayReceived__c,
      'XrayReceived__c not set'
    );
  }

  @isTest
  public static void updateDate_TeamDogXray_LeavesDateWhenOlder() {
    createTeamMembers();
    Team__c record = new Team__c(
      Name = 'Test',
      Client__c = client.Id,
      Dog__c = dog.Id,
      XrayReceived__c = Date.today()
    );
    insert record;
    ContentVersion cv = TestFileServiceFields.createLink(
      'TeamDog',
      'Xray',
      Date.today().addDays(-1),
      record.Id
    );
    FileService.updateDate(cv, record.Id);

    record = [
      SELECT XrayReceived__c
      FROM Team__c
      WHERE Id = :record.Id
      LIMIT 1
    ];
    system.assertEquals(
      Date.today(),
      record.XrayReceived__c,
      'XrayReceived__c set to an older date'
    );
  }
}