force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <description>Track progress toward a certification or renewal.  CEUs are be associated with certifications</description>
    <label>Certification</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Trainer or Facilitator</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Certifications</relationshipLabel>
    <relationshipName>Certifications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Certification status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Facilitator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEU__c/CEU__c.object-meta.xml
<CustomObject>
    <label>CEU</label>
    <nameField>
        <displayFormat>CEU-{0000}</displayFormat>
        <label>CEU Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CEUs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CEU__c/fields/Authority__c.field-meta.xml
<CustomField>
    <fullName>Authority__c</fullName>
    <label>CUE Authority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Atlas</fullName>
                <default>true</default>
                <label>Atlas</label>
            </value>
            <value>
                <fullName>KPA</fullName>
            </value>
            <value>
                <fullName>CCPDT</fullName>
            </value>
            <value>
                <fullName>IAABC</fullName>
            </value>
            <value>
                <fullName>CBCC</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEU__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CEUs</relationshipLabel>
    <relationshipName>CEUs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CEU__c/fields/DateCompleted__c.field-meta.xml
<CustomField>
    <fullName>DateCompleted__c</fullName>
    <label>Date Completed</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CEU__c/fields/DateSubmitted__c.field-meta.xml
<CustomField>
    <fullName>DateSubmitted__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date Submitted</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CEU__c/fields/ProgramHours__c.field-meta.xml
<CustomField>
    <fullName>ProgramHours__c</fullName>
    <label>Program Hours</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CEU__c/fields/ProgramTitle__c.field-meta.xml
<CustomField>
    <fullName>ProgramTitle__c</fullName>
    <label>Program Title</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEU__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Requested CEUs</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CEU__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attendee</fullName>
            </value>
            <value>
                <fullName>Presenter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEU__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Place/person to contact this person</description>
    <inlineHelpText>Select Guardian to contact this person through their guardian, Home for personal email/phone</inlineHelpText>
    <label>Contact At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
                <default>true</default>
                <label>Home</label>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contacts.recordType-meta.xml
<RecordType>
    <fullName>Contacts</fullName>
    <active>true</active>
    <label>Contacts</label>
</RecordType>

force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Derived from Team.  Do not edit directly.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In ADSiM</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Certified-Active</fullName>
            </value>
            <value>
                <fullName>Certified-OnHold</fullName>
            </value>
            <value>
                <fullName>Decertified</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/test/certifications/TestCeuController.cls
@isTest
public with sharing class TestCeuController {
  private static Contact ace;
  private static Contact cookie;
  private static CEU__c aceCeu;
  private static CEU__c cookieCeu1;
  private static CEU__c cookieCeu2;

  static void setup() {
    List<Contact> contacts = new List<Contact>();
    ace = new Contact(FirstName = 'Ace', LastName = 'GSD');
    cookie = new Contact(FirstName = 'Cookie', LastName = 'Monster');
    contacts.add(ace);
    contacts.add(cookie);
    insert contacts;

    List<CEU__c> ceus = new List<CEU__c>();
    aceCeu = new CEU__c(
      Authority__c = 'Atlas',
      Comments__c = 'Comments1',
      DateCompleted__c = Date.today().addMonths(-1),
      DateSubmitted__c = Date.today().addMonths(-1),
      ProgramHours__c = 20,
      ProgramTitle__c = 'A Day in the Life of a Dog',
      Quantity__c = 20,
      Role__c = 'Presenter',
      Status__c = 'Approved',
      Contact__c = ace.Id
    );
    ceus.add(aceCeu);

    cookieCeu1 = new CEU__c(
      Authority__c = 'KPA',
      Comments__c = 'Comments2',
      DateCompleted__c = Date.today().addMonths(-2),
      DateSubmitted__c = Date.today().addMonths(-2),
      ProgramHours__c = 10,
      ProgramTitle__c = 'A Day in the Life of a Trainer',
      Quantity__c = 2,
      Role__c = 'Attendee',
      Status__c = 'Pending',
      Contact__c = cookie.Id
    );
    ceus.add(cookieCeu1);

    cookieCeu2 = new CEU__c(
      Authority__c = 'CCPDT',
      Comments__c = 'Comments3',
      DateCompleted__c = Date.today().addMonths(-3),
      DateSubmitted__c = Date.today().addMonths(-3),
      ProgramHours__c = 30,
      ProgramTitle__c = 'A Day in the Life of a Cookie',
      Quantity__c = 3,
      Role__c = 'Attendee',
      Status__c = 'Denied',
      Contact__c = cookie.Id
    );
    ceus.add(cookieCeu2);

    insert ceus;
  }

  private static void ceusMatch(CEU__c expected, CEU__c actual) {
    System.assertEquals(
      expected.Authority__c,
      actual.Authority__c,
      'authority mismatch'
    );
    System.assertEquals(
      expected.Comments__c,
      actual.Comments__c,
      'comments mismatch'
    );
    System.assertEquals(
      expected.DateCompleted__c,
      actual.DateCompleted__c,
      'date completed mismatch'
    );
    System.assertEquals(
      expected.DateSubmitted__c,
      actual.DateSubmitted__c,
      'date submitted mismatch'
    );
    System.assertEquals(
      expected.ProgramHours__c,
      actual.ProgramHours__c,
      'program hours mismatch'
    );
    System.assertEquals(
      expected.ProgramTitle__c,
      actual.ProgramTitle__c,
      'program title mismatch'
    );
    System.assertEquals(
      expected.Quantity__c,
      actual.Quantity__c,
      'quantity mismatch'
    );
    System.assertEquals(expected.Role__c, actual.Role__c, 'role mismatch');
    System.assertEquals(
      expected.Contact__c,
      actual.Contact__c,
      'contact mismatch'
    );
  }

  @isTest
  public static void getRelatedCeus_ReturnsRelated() {
    setup();
    RelatedObjects ceus = CEUController.getRelatedCeus(ace.Id, 10);

    System.assertEquals(1, ceus.items.size(), 'Wrong number of CEUs');
    System.assertEquals(1, ceus.total, 'wrong CEU total');
    CEU__c ceu = (CEU__c) ceus.items[0];
    ceusMatch(aceCeu, ceu);
  }

  @isTest
  public static void getRelatedCeus_ReturnsRelatedList() {
    setup();
    RelatedObjects ceus = CEUController.getRelatedCeus(cookie.Id, 5);

    System.assertEquals(2, ceus.items.size(), 'Wrong number of CEUs');
    System.assertEquals(2, ceus.total);
    ceusMatch(cookieCeu1, (CEU__c) ceus.items[0]);
    ceusMatch(cookieCeu2, (CEU__c) ceus.items[1]);
  }

  @isTest
  public static void getRelatedCeus_ReturnsRelatedList_whenCertification() {
    setup();
    Certification__c cert = new Certification__c(
      Contact__c = cookie.Id,
      Type__c = 'Trainer',
      Start__c = Date.today().addMonths(-6),
      End__c = Date.today().addMonths(6)
    );
    insert cert; // the trigger will connect the CEUs to the cert
    RelatedObjects ceus = CEUController.getRelatedCeus(cert.Id, 5);

    System.assertEquals(2, ceus.items.size(), 'Wrong number of CEUs');
    System.assertEquals(2, ceus.total, 'wrong total');
    ceusMatch(cookieCeu1, (CEU__c) ceus.items[0]);
    ceusMatch(cookieCeu2, (CEU__c) ceus.items[1]);
  }

  static MockProvider mocks;
  static CeuRepository ceuRepo;

  static void makeData() {
    mocks = new MockProvider();
    ceuRepo = (CeuRepository) mocks.createMock(CeuRepository.class);
  }

  @isTest
  static void getRelatedCeus_setsMax_whenNull() {
    makeData();
    CeuController.setRepo(ceuRepo);
    mocks.expectedCalls.add(
      new MockCallData(ceuRepo, 'getForContact', new List<Ceu__c>())
    );
    //act
    RelatedObjects ceus = CEUController.getRelatedCeus(
      MockProvider.createId(Contact.class),
      null
    );
    //assert
    System.assertEquals(6, mocks.actualCalls[0].args[1], 'wrong max');
  }

  @isTest
  static void getRelatedCeus_getsForCert_whenIdForCert() {
    makeData();
    CeuController.setRepo(ceuRepo);
    mocks.expectedCalls.add(
      new MockCallData(ceuRepo, 'getForCertification', new List<Ceu__c>())
    );
    //act
    RelatedObjects ceus = CEUController.getRelatedCeus(
      MockProvider.createId(Certification__c.class),
      null
    );
    //assert
    System.assertEquals(
      1,
      mocks.actualCalls[0].args.size(),
      'wrong number of args'
    );
  }

  @isTest
  static void getRelatedCeus_returnsEmpty_whenIdForOtherObject() {
    makeData();
    CeuController.setRepo(ceuRepo);
    mocks.expectedCalls.add(
      new MockCallData(ceuRepo, 'getForCertification', new List<Ceu__c>())
    );
    //act
    RelatedObjects ceus = CEUController.getRelatedCeus(
      MockProvider.createId(Dog__c.class),
      null
    );
    //assert
    System.assertEquals(
      0,
      ceus.total,
      'wrong number of ceus'
    );
  }
}