force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <description>Track progress toward a certification or renewal.  CEUs are be associated with certifications</description>
    <label>Certification</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>TODAY() &gt;= Start__c &amp;&amp; TODAY() &lt;= End__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Trainer or Facilitator</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Certifications</relationshipLabel>
    <relationshipName>Certifications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Certification status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification__c/fields/TotalCeus__c.field-meta.xml
<CustomField>
    <fullName>TotalCeus__c</fullName>
    <description>Total Accepted CEUs for the certification</description>
    <label>Total CEUs</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Facilitator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEU__c/CEU__c.object-meta.xml
<CustomObject>
    <label>CEU</label>
    <nameField>
        <displayFormat>CEU-{0000}</displayFormat>
        <label>CEU Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CEUs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CEU__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CEUs</relationshipLabel>
    <relationshipName>CEUs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CEU__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CeuCertification__c/CeuCertification__c.object-meta.xml
<CustomObject>
    <description>Linking table for CEUs and Certifications</description>
    <label>CEU Certification</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>CeuCertification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CEU Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CeuCertification__c/fields/Certification__c.field-meta.xml
<CustomField>
    <fullName>Certification__c</fullName>
    <label>Certification</label>
    <referenceTo>Certification__c</referenceTo>
    <relationshipLabel>CEU Certifications</relationshipLabel>
    <relationshipName>CEU_Certifications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CeuCertification__c/fields/CEU__c.field-meta.xml
<CustomField>
    <fullName>CEU__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CEU</label>
    <referenceTo>CEU__c</referenceTo>
    <relationshipLabel>CEU Certifications</relationshipLabel>
    <relationshipName>CEU_Certifications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Place/person to contact this person</description>
    <inlineHelpText>Select Guardian to contact this person through their guardian, Home for personal email/phone</inlineHelpText>
    <label>Contact At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
                <default>true</default>
                <label>Home</label>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contacts.recordType-meta.xml
<RecordType>
    <fullName>Contacts</fullName>
    <active>true</active>
    <label>Contacts</label>
</RecordType>

force-app/main/default/classes/certifications/CertificationRepository.cls
public inherited sharing class CertificationRepository {
    public CertificationRepository() {

    }
    public List<Certification__c> getForContact(Id contactId) {
        return [SELECT Active__c, Contact__c, End__c, Start__c, TotalCeus__c, Type__c FROM Certification__c WHERE Contact__c = :contactId];
    }
    public List<Certification__c> getForContacts(List<Contact> contacts) {
        Set<Id> contactIds = new Set<Id>();
        for (Contact person: contacts) {
            contactIds.add(person.Id);
        }
        return getForContacts(contactIds);
    }
    public List<Certification__c> getForContacts(Set<Id> contactIds) {
        return [SELECT Active__c, Contact__c, End__c, Start__c, TotalCeus__c, Type__c FROM Certification__c WHERE Contact__c IN :contactIds];
    }
    public Certification__c create(Certification__c certs) {
        if (certs == null) return null;
        insert certs;
        return certs;
    }
    public List<Certification__c> create(List<Certification__c> certs) {
        if (certs == null) return null;
        insert certs;
        return certs;
    }
    public List<Certification__c> modify(List<Certification__c> certs) {
        if (certs == null) return null;
        update certs;
        return certs;
    }
    public Certification__c modify(Certification__c certs) {
        if (certs == null) return null;
        update certs;
        return certs;
    }
    public List<CeuCertification__c> create(List<CeuCertification__c> ccs) {
        if (ccs == null) return null;
        insert ccs;
        return ccs;
    }
    public CeuCertification__c get(Id ceuId, Id certificationId) {
        if (ceuId == null || certificationId == null) return null;
        return [SELECT Ceu__c, Certification__c FROM CeuCertification__c WHERE Ceu__c = :ceuId AND Certification__c = :certificationId LIMIT 1];
    }
    public void remove(List<CeuCertification__c> ccs) {
        delete ccs;
    }
    public Certification__c getActiveCert(Id contactId, String type) {
        return [SELECT Id, Contact__c FROM Certification__c WHERE Status__c = 'Active' AND Type__c = :type AND Contact__c = :contactId];
    }
    public Certification__c[] getActiveFacilitatorCerts() {
        return [SELECT Id, Contact__c FROM Certification__c WHERE Status__c = 'Active' AND Type__c = 'Facilitator'];
    }
}