force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <description>Track progress toward a certification or renewal.  CEUs are be associated with certifications</description>
    <label>Certification</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <label>Total CEUs</label>
    <summarizedField>CeuCertification__c.Approved__c</summarizedField>
    <summaryForeignKey>CeuCertification__c.Certification__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Trainer or Facilitator</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Certifications</relationshipLabel>
    <relationshipName>Certifications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Certification status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Facilitator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEU__c/CEU__c.object-meta.xml
<CustomObject>
    <label>CEU</label>
    <nameField>
        <displayFormat>CEU-{0000}</displayFormat>
        <label>CEU Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CEUs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CEU__c/fields/Authority__c.field-meta.xml
<CustomField>
    <fullName>Authority__c</fullName>
    <label>CUE Authority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Atlas</fullName>
                <default>true</default>
                <label>Atlas</label>
            </value>
            <value>
                <fullName>KPA</fullName>
            </value>
            <value>
                <fullName>CCPDT</fullName>
            </value>
            <value>
                <fullName>IAABC</fullName>
            </value>
            <value>
                <fullName>CBCC</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEU__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CEUs</relationshipLabel>
    <relationshipName>CEUs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CEU__c/fields/DateCompleted__c.field-meta.xml
<CustomField>
    <fullName>DateCompleted__c</fullName>
    <label>Date Completed</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CEU__c/fields/DateSubmitted__c.field-meta.xml
<CustomField>
    <fullName>DateSubmitted__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date Submitted</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CEU__c/fields/ProgramDate__c.field-meta.xml
<CustomField>
    <fullName>ProgramDate__c</fullName>
    <label>Program Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CEU__c/fields/ProgramHours__c.field-meta.xml
<CustomField>
    <fullName>ProgramHours__c</fullName>
    <label>Program Hours</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CEU__c/fields/ProgramTitle__c.field-meta.xml
<CustomField>
    <fullName>ProgramTitle__c</fullName>
    <label>Program Title</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEU__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Requested CEUs</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CEU__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attendee</fullName>
            </value>
            <value>
                <fullName>Presenter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEU__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CeuCertification__c/CeuCertification__c.object-meta.xml
<CustomObject>
    <description>Linking table for CEUs and Certifications</description>
    <label>CEU Certification</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>CeuCertification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CEU Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CeuCertification__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <label>Approved</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CeuCertification__c/fields/Certification__c.field-meta.xml
<CustomField>
    <fullName>Certification__c</fullName>
    <label>Certification</label>
    <referenceTo>Certification__c</referenceTo>
    <relationshipLabel>CEU Certifications</relationshipLabel>
    <relationshipName>CEU_Certifications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CeuCertification__c/fields/CEU__c.field-meta.xml
<CustomField>
    <fullName>CEU__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CEU</label>
    <referenceTo>CEU__c</referenceTo>
    <relationshipLabel>CEU Certifications</relationshipLabel>
    <relationshipName>CEU_Certifications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Place/person to contact this person</description>
    <inlineHelpText>Select Guardian to contact this person through their guardian, Home for personal email/phone</inlineHelpText>
    <label>Contact At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
                <default>true</default>
                <label>Home</label>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contacts.recordType-meta.xml
<RecordType>
    <fullName>Contacts</fullName>
    <active>true</active>
    <label>Contacts</label>
</RecordType>

force-app/main/test/certifications/TestCertificationService.cls
/**
 * This class contains unit tests for validating the behavior of CertificationService
 */
@isTest
private class TestCertificationService {
  private static MockProvider mocks;
  private static CertificationService service;
  private static EmailService emailSrv;
  private static CertificationRepository certRepo;
  // references to mocks

  static void makeData() {
    mocks = new MockProvider();
    emailSrv = (EmailService) mocks.createMock(EmailService.class);
    certRepo = (CertificationRepository) mocks.createMock(
      CertificationRepository.class
    );
    service = new CertificationService(certRepo, emailSrv);
  }

  @isTest
  static void sortCeus_handlesEmptyList() {
    makeData();
    // act
    Map<Id, List<Ceu__c>> actual = service.sortCeus(new List<Ceu__c>());
    System.assert(actual.isEmpty(), 'map is not empty');
  }

  @isTest
  static void sortCeus_handlesListWithOneContactsCeus() {
    makeData();
    List<Ceu__c> ceus = new List<Ceu__c>();
    Id contactId = MockProvider.createId(Contact.class);
    for (integer i = 0; i < 5; i++) {
      ceus.add(
        new CEU__c(
          Authority__c = 'Atlas',
          Comments__c = 'Comments1',
          DateCompleted__c = Date.today().addMonths(-1),
          DateSubmitted__c = Date.today().addMonths(-1),
          ProgramDate__c = Date.today().addDays(-22),
          ProgramHours__c = 20,
          ProgramTitle__c = 'A Day in the Life of a Dog',
          Quantity__c = 20,
          Role__c = 'Presenter',
          Status__c = 'Approved',
          Contact__c = contactId
        )
      );
    }

    // act
    Map<Id, List<CEU__c>> actual = service.sortCeus(ceus);
    System.assertEquals(
      ceus.size(),
      actual.get(contactId).size(),
      'map does not have contact id'
    );
  }

  @isTest
  static void sortCeus_handlesListWithBunchOfContactsCeus() {
    makeData();
    List<Ceu__c> ceus = new List<Ceu__c>();
    for (integer i = 0; i < 5; i++) {
      Id contactId = MockProvider.createId(Contact.class);
      ceus.add(
        new CEU__c(
          Authority__c = 'Atlas',
          Comments__c = 'Comments1',
          DateCompleted__c = Date.today().addMonths(-1),
          DateSubmitted__c = Date.today().addMonths(-1),
          ProgramDate__c = Date.today().addDays(-22),
          ProgramHours__c = 20,
          ProgramTitle__c = 'A Day in the Life of a Dog',
          Quantity__c = 20,
          Role__c = 'Presenter',
          Status__c = 'Approved',
          Contact__c = contactId
        )
      );
    }

    // act
    Map<Id, List<CEU__c>> actual = service.sortCeus(ceus);
    System.assertEquals(
      ceus.size(),
      actual.keySet().size(),
      'map does not have all contacts'
    );
    for (List<Ceu__c> cs : actual.values()) {
      System.assertEquals(1, cs.size());
    }
  }

  @isTest
  static void sortCertifications_handlesEmptyList() {
    makeData();
    // act
    Map<Id, List<Certification__c>> actual = service.sortCertifications(
      new List<Certification__c>()
    );
    System.assert(actual.isEmpty(), 'map is not empty');
  }

  @isTest
  static void sortCertifications_handlesListWithOneContactsCertifications() {
    makeData();
    List<Certification__c> certs = new List<Certification__c>();
    Id contactId = MockProvider.createId(Contact.class);
    for (integer i = 0; i < 5; i++) {
      certs.add(
        new Certification__c(
          Type__c = 'Trainer',
          Status__c = 'Completed',
          Start__c = Date.today().addMonths(-1),
          End__c = Date.today().addMonths(-1),
          Contact__c = contactId
        )
      );
    }

    // act
    Map<Id, List<Certification__c>> actual = service.sortCertifications(certs);
    System.assertEquals(
      certs.size(),
      actual.get(contactId).size(),
      'map does not have contact id'
    );
  }

  @isTest
  static void sortCertifications_handlesListWithBunchOfContactsCertifications() {
    makeData();
    List<Certification__c> certs = new List<Certification__c>();
    for (integer i = 0; i < 5; i++) {
      Id contactId = MockProvider.createId(Contact.class);
      certs.add(
        new Certification__c(
          Type__c = 'Facilitator',
          Status__c = 'Active',
          Start__c = Date.today().addMonths(-1),
          End__c = Date.today().addMonths(-1),
          Contact__c = contactId
        )
      );
    }

    // act
    Map<Id, List<Certification__c>> actual = service.sortCertifications(certs);
    System.assertEquals(
      certs.size(),
      actual.keySet().size(),
      'map does not have all contacts'
    );
    for (List<Certification__c> cs : actual.values()) {
      System.assertEquals(1, cs.size());
    }
  }

  @isTest
  static void addCeus_stops_whenNoCertifications() {
    makeData();
    mocks.expectedCalls.add(
      new MockCallData(certRepo, 'getForContacts', new List<Certification__c>())
    );
    // act
    service.addCeus(new List<Ceu__c>());
    // assert
    MockCallData createCall = mocks.actualCalls[1];
    System.assertEquals('create', createCall.methodName, 'wrong method');
    System.assertEquals(
      new List<CeuCertification__c>(),
      createCall.args[0],
      'wrong data'
    );
    System.assertEquals(2, mocks.actualCalls.size(), 'wrong number of calls');
  }

  static void addCeusDoesNotAddWhenOutside(Integer outside) {
    makeData();
    Id contactId = MockProvider.createId(Contact.class);
    Date startDate = Date.today().addMonths(-2);
    Date endDate = startDate.addYears(1);
    Date ceuDate = endDate.addDays(outside);
    if (outside < 0) {
        ceuDate = startDate.addDays(outside);
    }
    mocks.expectedCalls.add(
      new MockCallData(
        certRepo,
        'getForContacts',
        new List<Certification__c>{
          new Certification__c(
            Contact__c = contactId,
            Start__c = startDate,
            End__c = endDate,
            Type__c = 'Trainer'
          )
        }
      )
    );
    // act
    service.addCeus(
      new List<Ceu__c>{
        new Ceu__c(
          Contact__c = contactId,
          DateCompleted__c = ceuDate
        )
      }
    );
    // assert
    MockCallData createCall = mocks.actualCalls[1];
    System.assertEquals('create', createCall.methodName, 'wrong method');
    System.assertEquals(
      new List<CeuCertification__c>(),
      createCall.args[0],
      'wrong data'
    );
    System.assertEquals(2, mocks.actualCalls.size(), 'wrong number of calls');
  }

  @isTest
  static void addCeus_stops_whenCertificationsDayBefore() {
    addCeusDoesNotAddWhenOutside(-1);
  }

  @isTest
  static void addCeus_stops_whenCertificationsWeekBefore() {
    addCeusDoesNotAddWhenOutside(-7);
  }

  @isTest
  static void addCeus_stops_whenCertificationsDayAfter() {
    addCeusDoesNotAddWhenOutside(1);
  }

  @isTest
  static void addCeus_stops_whenCertificationsMonthsAfter() {
    addCeusDoesNotAddWhenOutside(60);
  }

  static void addCeusAddConnector(Integer days) {
  makeData();
    Id contactId = MockProvider.createId(Contact.class);
    Date startDate = Date.today().addMonths(-2);
    Date endDate = startDate.addYears(1);
    Id certId = MockProvider.createId(Certification__c.class);
    Id ceuId = MockProvider.createId(Ceu__c.class);
    mocks.expectedCalls.add(
      new MockCallData(
        certRepo,
        'getForContacts',
        new List<Certification__c>{
          new Certification__c(
            Contact__c = contactId,
            Start__c = startDate,
            End__c = endDate,
            Type__c = 'Trainer',
            Id = certId
          )
        }
      )
    );
    // act
    service.addCeus(
      new List<Ceu__c>{
        new Ceu__c(
          Contact__c = contactId,
          DateCompleted__c = startDate.addDays(1),
          Id = ceuId,
          Quantity__c = 5,
          Status__c = 'Approved'
        )
      }
    );
    // assert
    MockCallData createCall = mocks.actualCalls[1];
    System.assertEquals('create', createCall.methodName, 'wrong method');
    System.assertEquals(
      new List<CeuCertification__c>{
        new CeuCertification__c(Ceu__c = ceuId, Certification__c = certId, Approved__c = 5)
      },
      createCall.args[0],
      'wrong data'
    );
    System.assertEquals(2, mocks.actualCalls.size(), 'wrong number of calls');
  }

  @isTest
  static void addCeus_adds_whenCertificationInRangeBy1Day() {
    addCeusAddConnector(1);
  }

  @isTest
  static void addCeus_adds_whenCertificationInRangeBy0Days() {
    addCeusAddConnector(0);
  }

  @isTest
  static void addCeus_adds_whenCertificationInRangeBy364Days() {
    addCeusAddConnector(364);
  }

  @isTest
  static void addCeus_adds_whenCertificationInRangeBy365Days() {
    addCeusAddConnector(365);
  }
}