force-app/main/default/objects/ContentVersion/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PreApplication</fullName>
                <label>Pre Application</label>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>ContactForm</fullName>
                <label>Contact Form</label>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>CoI</fullName>
                <label>Conflict of Interest</label>
            </value>
            <value>
                <fullName>ToN</fullName>
                <label>Transmission of Notices</label>
            </value>
            <value>
                <fullName>LOMI</fullName>
                <label>Medical Provider Form</label>
            </value>
            <value>
                <fullName>Media</fullName>
                <label>Media Release</label>
            </value>
            <value>
                <fullName>VAPW</fullName>
                <label>Veteran Paperwork</label>
            </value>
            <value>
                <fullName>Survey</fullName>
                <label>Certification Survey</label>
            </value>
            <value>
                <fullName>Reference</fullName>
                <label>Reference Letter</label>
            </value>
            <value>
                <fullName>ClientReference</fullName>
                <label>Client Reference Letter</label>
            </value>
            <value>
                <fullName>ProfReference</fullName>
                <label>Professional Reference Letter</label>
            </value>
            <value>
                <fullName>ProgAgreement</fullName>
                <label>Program Agreement</label>
            </value>
            <value>
                <fullName>CertAgreement</fullName>
                <label>Certification Agreement</label>
            </value>
            <value>
                <fullName>Practicum</fullName>
            </value>
            <value>
                <fullName>InfrNotice</fullName>
                <label>Infraction Notice</label>
            </value>
            <value>
                <fullName>HealthForm</fullName>
                <label>Vet Health Form</label>
            </value>
            <value>
                <fullName>Notes</fullName>
                <label>Interview Notes</label>
            </value>
            <value>
                <fullName>Xray</fullName>
                <label>Vet Xray Report</label>
            </value>
            <value>
                <fullName>VacExams</fullName>
                <label>Vaccinations and Exams</label>
            </value>
            <value>
                <fullName>Resume</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
                <label>Offer Letter</label>
            </value>
            <value>
                <fullName>W4</fullName>
            </value>
            <value>
                <fullName>I9</fullName>
            </value>
            <value>
                <fullName>W9</fullName>
                <label>Contractor W9</label>
            </value>
            <value>
                <fullName>ApplicationVideo</fullName>
                <label>Application Video</label>
            </value>
            <value>
                <fullName>CGCForm</fullName>
                <label>CGC Form</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/UserType__c.field-meta.xml
<CustomField>
    <fullName>UserType__c</fullName>
    <label>UserType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facilitator</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Board Member</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Lead Facilitator</fullName>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/retrieveFiles.cls
public with sharing class retrieveFiles {
    public retrieveFiles() {

    }

    @AuraEnabled
    public static list<contentversion> accountFilesRetrieve(Id accountId,String userType,String docType){
       system.debug('Account Id '+accountId);
        system.debug('userType '+userType);
        system.debug('docType '+docType);
        
        
       Id parentId = accountId;
       list<id> lstConDocs = new list<id>();
        for(ContentDocumentLink cntLink : [Select Id, ContentDocumentId From ContentDocumentLink Where LinkedEntityId =:parentId]) {
            lstConDocs.add(cntLink.ContentDocumentId);
        }
        
        system.debug('lstConDocs'+lstConDocs);
        if(!lstConDocs.isEmpty()) {
           
            return [SELECT  Title, ContentDocumentId,Type__c,UserType__c,CreatedDate 
                    FROM ContentVersion 
                    WHERE ContentDocumentId IN :lstConDocs 
                    AND UserType__c =:userType
                    AND Type__c = :docType
                    ];
        }
        else {
            return null;
        }
     
    }
    @AuraEnabled
    public static void updateRecords(Id accountId,String userType,String docType,String docName,List<Id> docId){
        system.debug('Account Id update'+accountId);
        system.debug('userType update '+userType);
        system.debug('docType update '+docType);
        system.debug('docName update '+docName);
        system.debug('docId update '+docId);
        Id parentId = accountId;
        List<ContentVersion> cvListUpdate = new  List<ContentVersion>();
        List<ContentVersion> cvList = [SELECT  Title, ContentDocumentId,Type__c,UserType__c 
                                       FROM ContentVersion 
                                       WHERE ContentDocumentId IN: docId];
        for(ContentVersion cv:cvList){
            cv.Type__c = docType;
            cv.UserType__c = userType;
            cvListUpdate.add(cv);
        }
        try{
        update cvListUpdate;
        }
         catch(DmlException ex){
            throw new AuraHandledException(ex.getMessage());
        }
    }
    
    @AuraEnabled
    public static String deleteRecords(List<String> docIds ){
        system.debug('docIds'+docIds);
         try{
            delete [SELECT Id FROM ContentDocument WHERE Id=:docIds];
            return 'SUCCESS';
        }
        catch(Exception ex){
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static list<contentversion> retrieveAllData(Id accountId){
        Id parentId = accountId;
       list<id> lstConDocs = new list<id>();
        for(ContentDocumentLink cntLink : [Select Id, ContentDocumentId From ContentDocumentLink Where LinkedEntityId =:parentId]) {
            lstConDocs.add(cntLink.ContentDocumentId);
        }
        
        system.debug('lstConDocs'+lstConDocs);
        if(!lstConDocs.isEmpty()) {
           
            return [SELECT  Title, ContentDocumentId,Type__c,UserType__c,CreatedDate 
                    FROM ContentVersion 
                    WHERE ContentDocumentId IN :lstConDocs 
                   
                    ];
        }
        else {
            return null;
        }
        
    }
}