force-app/main/default/objects/CategoryRule__c/CategoryRule__c.object-meta.xml
<CustomObject>
    <description>Defines which objects and positions have file categories</description>
    <label>Category Rule</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Category Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Category Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CategoryRule__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>File categories valid for this object/position</description>
    <label>Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CategoryRule__c/fields/GroupName__c.field-meta.xml
<CustomField>
    <fullName>GroupName__c</fullName>
    <description>Members of this group have access to this category.  If no groups are specified, only System Admins can see files with this category</description>
    <label>Group</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CategoryRule__c/fields/ReadOnly__c.field-meta.xml
<CustomField>
    <fullName>ReadOnly__c</fullName>
    <defaultValue>false</defaultValue>
    <description>User cannot upload a file with this object/category, if true, user can only view and update files with this category</description>
    <label>Read Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Positions__c.field-meta.xml
<CustomField>
    <fullName>Positions__c</fullName>
    <description>Positions available</description>
    <label>Positions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Positions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/globalValueSets/Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Volunteer</fullName>
    </customValue>
    <customValue>
        <fullName>Board</fullName>
    </customValue>
    <customValue>
        <fullName>Client</fullName>
    </customValue>
    <customValue>
        <fullName>Standalone</fullName>
        <label>Standalone Programs</label>
    </customValue>
    <customValue>
        <fullName>ADSiM</fullName>
        <label>Assistance Dogs Set in Motion</label>
    </customValue>
    <customValue>
        <fullName>Facilitator</fullName>
        <label>Team Facilitator</label>
    </customValue>
    <customValue>
        <fullName>Puppy</fullName>
        <label>Puppy Raiser</label>
    </customValue>
    <customValue>
        <fullName>Trainer</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
    </customValue>
    <customValue>
        <fullName>Dog</fullName>
    </customValue>
    <description>file category</description>
    <masterLabel>Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Positions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Volunteer</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Board Member</fullName>
    </customValue>
    <customValue>
        <fullName>Trainer</fullName>
    </customValue>
    <customValue>
        <fullName>Client</fullName>
    </customValue>
    <customValue>
        <fullName>Donor</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
        <label>Staff/Contractor</label>
    </customValue>
    <customValue>
        <fullName>Puppy Raiser</fullName>
    </customValue>
    <customValue>
        <fullName>Standalone</fullName>
    </customValue>
    <customValue>
        <fullName>TSiM</fullName>
    </customValue>
    <description>Positions a contact can have</description>
    <masterLabel>Positions</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/category-rules/CategoryRuleService.cls
public inherited sharing class CategoryRuleService {
  private UserRepository userRepo = new UserRepository();
  private CategoryRuleRepository repo = new CategoryRuleRepository();
  public CategoryRuleService() {
    userRepo = new UserRepository();
    repo = new CategoryRuleRepository();
  }
  @TestVisible
  private CategoryRuleService(
    UserRepository uRepo,
    CategoryRuleRepository crRepo
  ) {
    userRepo = uRepo;
    repo = crRepo;
  }
  public List<String> getAllowedCategoriesForUser() {
    List<String> groupNames = userRepo.getGroupNames(UserInfo.getUserId());

    // get the categories that work for the object
    List<CategoryRule__c> rules = repo.getAll();
    List<String> categories = new List<String>();
    for (CategoryRule__c rule : rules) {
      if (
        String.isBlank(rule.GroupName__c) ||
        groupNames.contains(rule.GroupName__c)
      ) {
        categories.addAll(rule.Category__c.split(';'));
      }
    }
    return categories;
  }

  public Set<String> getAllowedCategoriesForObject(
    Id recordId,
    Boolean isUpload
  ) {
    if (isUpload == null)
      isUpload = false;
    string objLabel = recordId.getSObjectType().getDescribe().getLabel();

    List<String> groupNames = userRepo.getGroupNames(UserInfo.getUserId());

    // get the categories that work for the object from atlas1
    Set<String> allCategories = CategoryRuleController.getCategorySetForObject(
      recordId
    );

    Set<String> categories = new Set<String>();
    // only allow the categories that match the groups the user is in
    List<CategoryRule__c> rules = repo.getForGroupNames(
      objLabel,
      allCategories,
      groupNames
    );

    for (CategoryRule__c rule : rules) {
      if (
        ((isUpload && rule.ReadOnly__c != true) || !isUpload) &&
        rule.Category__c != null
      ) {
        categories.addAll(rule.Category__c.split(';'));
      }
    }

    return categories;
  }

  public Set<String> getCategorySetForObject(Id recordId) {
    string objLabel = recordId.getSObjectType().getDescribe().getLabel();

    // get the categories that work for the object
    List<CategoryRule__c> rules = repo.getCategoriesForObject(objLabel);
    Set<String> categories = new Set<String>();
    for (CategoryRule__c rule : rules) {
      categories.addAll(rule.Category__c.split(';'));
    }

    // If the object is a Contact, we also check positions
    List<String> positions = new List<String>();
    if (objLabel == Contact.class.getName()) {
      Contact person = [
        SELECT Id, Positions__c
        FROM Contact
        WHERE Id = :recordId
      ];
      if (person.Positions__c != null) {
        positions = person.Positions__c.split(';');
      }

      rules = repo.getCategoriesForObject('Contact', positions);
      for (CategoryRule__c rule : rules) {
        categories.addAll(rule.Category__c.split(';'));
      }
    }
    return categories;
  }

  public List<Option> getCategoryEntriesForObject(
    Id recordId,
    Boolean isUpload
  ) {
    // See what categories the user has access to
    Set<String> categories = getAllowedCategoriesForObject(recordId, isUpload);

    // Map in the types for each allowed category
    Map<string, string> categoryEntries = FileController.getEntryMap(
      CategoryRule__c.Category__c.getDescribe()
    );
    List<Option> entries = new List<Option>();
    for (string category : categories) {
      Option option = new Option(category, categoryEntries.get(category));
      entries.add(option);
    }
    entries.sort();
    return entries;
  }
}