force-app/main/default/objects/CategoryRule__c/CategoryRule__c.object-meta.xml
<CustomObject>
    <description>Defines which objects and positions have file categories</description>
    <label>Category Rule</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Category Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Category Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CategoryRule__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>File categories valid for this object/position</description>
    <label>Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CategoryRule__c/fields/GroupName__c.field-meta.xml
<CustomField>
    <fullName>GroupName__c</fullName>
    <description>Members of this group have access to this category.  If no groups are specified, only System Admins can see files with this category</description>
    <label>Group</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CategoryRule__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>Object name</description>
    <inlineHelpText>If the object name is part of a managed package, include its namespace (i.e. atlas1__)</inlineHelpText>
    <label>Object</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CategoryRule__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position value if applicable</description>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Positions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CategoryRule__c/fields/ReadOnly__c.field-meta.xml
<CustomField>
    <fullName>ReadOnly__c</fullName>
    <defaultValue>false</defaultValue>
    <description>User cannot upload a file with this object/category, if true, user can only view and update files with this category</description>
    <label>Read Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Volunteer</fullName>
    </customValue>
    <customValue>
        <fullName>Board</fullName>
    </customValue>
    <customValue>
        <fullName>Client</fullName>
    </customValue>
    <customValue>
        <fullName>Standalone</fullName>
        <label>Standalone Programs</label>
    </customValue>
    <customValue>
        <fullName>ADSiM</fullName>
        <label>Assistance Dogs Set in Motion</label>
    </customValue>
    <customValue>
        <fullName>Facilitator</fullName>
        <label>Team Facilitator</label>
    </customValue>
    <customValue>
        <fullName>Puppy</fullName>
        <label>Puppy Raiser</label>
    </customValue>
    <customValue>
        <fullName>Trainer</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
    </customValue>
    <customValue>
        <fullName>Dog</fullName>
    </customValue>
    <description>file category</description>
    <masterLabel>Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Positions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Volunteer</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Board Member</fullName>
    </customValue>
    <customValue>
        <fullName>Trainer</fullName>
    </customValue>
    <customValue>
        <fullName>Client</fullName>
    </customValue>
    <customValue>
        <fullName>Donor</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
        <label>Staff/Contractor</label>
    </customValue>
    <customValue>
        <fullName>Puppy Raiser</fullName>
    </customValue>
    <customValue>
        <fullName>Standalone</fullName>
    </customValue>
    <customValue>
        <fullName>TSiM</fullName>
    </customValue>
    <description>Positions a contact can have</description>
    <masterLabel>Positions</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/category-rules/CategoryRuleRepository.cls
public with sharing class CategoryRuleRepository {
    public CategoryRule__c[] getAll() {
        return [SELECT Category__c, GroupName__c, ReadOnly__c FROM CategoryRule__c];
    }
    public CategoryRule__c[] getForGroupNames(String objLabel, Set<String> allCategories, List<String> groupNames) {
        return [
            SELECT Category__c, GroupName__c, ReadOnly__c
            FROM CategoryRule__c
            WHERE (GroupName__c IN :groupNames OR GroupName__c = null OR GroupName__c = '')
            AND Object__c = :objLabel
            AND Category__c IN :allCategories
        ];
    }
    public CategoryRule__c[] getCategoriesForObject(String objLabel) {
        return [
            SELECT Category__c
            FROM CategoryRule__c
            WHERE Object__c = :objLabel AND Position__c = NULL
        ];
    }
    public CategoryRule__c[] getCategoriesForObject(String objLabel, List<String> positions) {
        return [SELECT Category__c FROM CategoryRule__c WHERE Object__c = :objLabel AND Position__c IN :positions];
    }
}