force-app/main/default/objects/CategoryRule__c/CategoryRule__c.object-meta.xml
<CustomObject>
    <description>Defines which objects and positions have file categories</description>
    <label>Category Rule</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Category Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Category Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CategoryRule__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>File categories valid for this object/position</description>
    <label>Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CategoryRule__c/fields/GroupName__c.field-meta.xml
<CustomField>
    <fullName>GroupName__c</fullName>
    <description>Members of this group have access to this category.  If no groups are specified, only System Admins can see files with this category</description>
    <label>Group</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CategoryRule__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>Object name</description>
    <inlineHelpText>If the object name is part of a managed package, include its namespace (i.e. atlas1__)</inlineHelpText>
    <label>Object</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CategoryRule__c/fields/ReadOnly__c.field-meta.xml
<CustomField>
    <fullName>ReadOnly__c</fullName>
    <defaultValue>false</defaultValue>
    <description>User cannot upload a file with this object/category, if true, user can only view and update files with this category</description>
    <label>Read Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Volunteer</fullName>
    </customValue>
    <customValue>
        <fullName>Board</fullName>
    </customValue>
    <customValue>
        <fullName>Client</fullName>
    </customValue>
    <customValue>
        <fullName>Standalone</fullName>
        <label>Standalone Programs</label>
    </customValue>
    <customValue>
        <fullName>ADSiM</fullName>
        <label>Assistance Dogs Set in Motion</label>
    </customValue>
    <customValue>
        <fullName>Facilitator</fullName>
        <label>Team Facilitator</label>
    </customValue>
    <customValue>
        <fullName>Puppy</fullName>
        <label>Puppy Raiser</label>
    </customValue>
    <customValue>
        <fullName>Trainer</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
    </customValue>
    <customValue>
        <fullName>Dog</fullName>
    </customValue>
    <description>file category</description>
    <masterLabel>Category</masterLabel>
</GlobalValueSet>

force-app/main/test/category-rules/TestCategoryRuleRepository.cls
/**
 * This class contains unit tests for the CategoryRuleRepository
 */
@isTest
private class TestCategoryRuleRepository {
    static CategoryRuleRepository repo = new CategoryRuleRepository();

    @isTest
    static void getAllReturnsEmptyWhenNoRecords() {
        List<CategoryRule__c> actual = repo.getAll();
        System.assertEquals(new List<CategoryRule__c>(), actual, 'not an empty list');
    }

    @isTest
    static void getAllReturnsAllRecords() {
        List<CategoryRule__c> rules = new List<CategoryRule__c>{
            new CategoryRule__c(Category__c = 'Board', GroupName__c = 'group1', Object__c = 'Contact', ReadOnly__c = true),
            new CategoryRule__c(Category__c = 'Dog', GroupName__c = 'group2', Object__c = 'Dog__c', ReadOnly__c = false),
            new CategoryRule__c(Category__c = 'Trainer', GroupName__c = 'group3', Object__c = 'Contact')
        };
        insert rules;
        List<CategoryRule__c> actual = repo.getAll();
        System.assertEquals(rules.size(), actual.size(), 'missed some');
    }
}