force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>This object contains course records relating to various record types within the contact object</description>
    <label>Course</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Course Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <label>Course Name</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/Course_Master__c.object-meta.xml
<CustomObject>
    <label>Course Master</label>
    <nameField>
        <label>Course Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Master__c/fields/Client_Course__c.field-meta.xml
<CustomField>
    <fullName>Client_Course__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Client Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Common_Course__c.field-meta.xml
<CustomField>
    <fullName>Common_Course__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Common Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Course_SIS_Section_SIS_Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_SIS_Section_SIS_Course_Name__c</fullName>
    <formula>Course_SIS__c &amp;&quot;-&quot;&amp; Section_SIS__c &amp;&quot;-&quot;&amp; Course_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course SIS Section SIS Course Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Expected_Completion__c.field-meta.xml
<CustomField>
    <fullName>Expected_Completion__c</fullName>
    <description>Expected Completion in Weeks</description>
    <label>Expected Completion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Facilitator_Course__c.field-meta.xml
<CustomField>
    <fullName>Facilitator_Course__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Facilitator Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Trainer_Course__c.field-meta.xml
<CustomField>
    <fullName>Trainer_Course__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trainer Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/Courses_Taken__c.object-meta.xml
<CustomObject>
    <label>Course Assignment</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Courses Taken Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Courses_Taken__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Course Taken</relationshipLabel>
    <relationshipName>Course_Taken</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Formula-AccountName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Assigned_Date__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Date__c</fullName>
    <label>Assigned Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Taken</relationshipLabel>
    <relationshipName>Course_Taken</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Course_Description__c.field-meta.xml
<CustomField>
    <fullName>Course_Description__c</fullName>
    <formula>Course_Name__r.Course_SIS_Section_SIS_Course_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course Name</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Taken</relationshipLabel>
    <relationshipName>Course_Taken</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Expected_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Completion_Date__c</fullName>
    <label>Expected Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Replaced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CourseAssigned.cls
public with sharing class CourseAssigned{
	@AuraEnabled(cacheable = true)
	public static List<Courses_Taken__c> getAssignedCourse(Id recordId){
		system.debug('print recordId' + recordId);
		List<Courses_Taken__c> returnList = new List<Courses_Taken__c>([SELECT Id, Course_Description__c, Course__c, Status__c, Course__r.Course_SIS_Section_SIS_Course_Name__c
		                                                                FROM Courses_Taken__c
		                                                                where Account__c = :recordId]);
		system.debug('returnList' + returnList);
		return returnList;
	}

	@AuraEnabled(cacheable = true)
	public static List<Course_Master__c> getMasterCourses(){

		return [SELECT Id, Course_SIS_Section_SIS_Course_Name__c, Name
		        FROM Course_Master__c
		        where Active__c = true];
	}

	@AuraEnabled(cacheable = true)
	public static List<Course_Master__c> getCommonCourses(){
		return [SELECT Id, Course_SIS_Section_SIS_Course_Name__c
		        FROM Course_Master__c
		        where Active__c = true and Common_Course__c = true];
	}

	@AuraEnabled(cacheable = true)
	public static List<Course_Master__c> getCourses(String typeOfUser){
		system.debug('typeOfUser' + typeOfUser);
		List<Course_Master__c> commonCourseList = new List<Course_Master__c>([SELECT Id, Course_SIS_Section_SIS_Course_Name__c
		                                                                      FROM Course_Master__c
		                                                                      where Active__c = true and Common_Course__c = true]);
		List<Course_Master__c> courseList = new List<Course_Master__c>();
		List<Course_Master__c> finalList = new List<Course_Master__c>();

		if (typeOfUser == 'Facilitator' || typeOfUser == 'Lead Facilitator'){
			courseList = [SELECT Id, Course_SIS_Section_SIS_Course_Name__c
			              FROM Course_Master__c
			              where Active__c = true and Facilitator_Course__c = true];

			courseList.addAll(commonCourseList);

		} else if (typeOfUser == 'Volunteer' || typeOfUser == 'Board Member'){
			courseList = commonCourseList;
		} else if (typeOfUser == 'Trainer'){
			courseList = [SELECT Id, Course_SIS_Section_SIS_Course_Name__c
			              FROM Course_Master__c
			              where Active__c = true and Trainer_Course__c = true and Common_Course__c = true];
			courseList.addAll(commonCourseList);
		} else if (typeOfUser == 'Client'){
			courseList = [SELECT Id, Course_SIS_Section_SIS_Course_Name__c
			              FROM Course_Master__c
			              where Active__c = true and Client_Course__c = true and Common_Course__c = true];
			courseList.addAll(commonCourseList);
		}

		system.debug('courseList' + courseList);
		return courseList;
	}

	@AuraEnabled
	public static void updateRecords(Id accId, List<String> sobList){
		system.debug('sobList' + sobList);
		system.debug('accId' + accId);
		//Set<String> newList = new Set<String>(sobList);

		// system.debug('newList'+newList);
		//String accId;
		List<Courses_Taken__c> createList = new List<Courses_Taken__c>();
		List<Course_Master__c> cmasterList = [SELECT Id, Expected_Completion__c
		                                      FROM Course_Master__c
		                                      where id in :sobList];
		List<Courses_Taken__c> checkList = new List<Courses_Taken__c>([SELECT Id, Status__c, Course_Name__c
		                                                               from Courses_Taken__c
		                                                               where Account_Name__c = :accId]);
		Map<Id, String> mapCTList = new Map<Id, String>();
		system.debug('checkList' + checkList);
		for (Courses_Taken__c chcourseTaken : checkList){
			mapCTList.put(chcourseTaken.Course_Name__c, chcourseTaken.Status__c);
		}
		system.debug('mapCTList' + mapCTList);
		if (!sobList.isEmpty()){
			for (Course_Master__c ct : cmasterList){
				if (!mapCTList.containsKey(ct.Id)){
					Courses_Taken__c createCoursesTaken = new Courses_Taken__c();
					createCoursesTaken.Course__c = ct.Id;
					createCoursesTaken.Status__c = 'Assigned';
					createCoursesTaken.Account__c = accId;
					Date todaysDate = date.today();
					Integer daysCount = (Integer)ct.Expected_Completion__c * 7;
					createCoursesTaken.Expected_Completion_Date__c = todaysDate.adddays(daysCount);
					createCoursesTaken.Assigned_Date__c = date.today();
					createList.add(createCoursesTaken);
				}
			}
		}
		system.debug('insert' + createList);
		if (!createList.isEmpty())
			insert createList;
		//system.debug('updateList'+updateList);
		// update updateList;
	}
}