force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>false</active>
    <description>Client Record Type</description>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Trainer.recordType-meta.xml
<RecordType>
    <fullName>Trainer</fullName>
    <active>false</active>
    <description>Trainer Record Type</description>
    <label>Trainer</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Positions__c.field-meta.xml
<CustomField>
    <fullName>Positions__c</fullName>
    <description>Positions available</description>
    <label>Positions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Positions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/npe4__Relationship__c/fields/npe4__Status__c.field-meta.xml
<CustomField>
    <fullName>npe4__Status__c</fullName>
    <description>Status of the Relationship.</description>
    <inlineHelpText>Status of the Relationship.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
                <default>true</default>
                <label>Current</label>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe4__Relationship__c/fields/npe4__Type__c.field-meta.xml
<CustomField>
    <fullName>npe4__Type__c</fullName>
    <description
  >Field that describes how the Related Contact is connected to the Contact.</description>
    <inlineHelpText
  >Field that describes how the Related Contact is connected to the Contact.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Friend</fullName>
            </value>
            <value>
                <fullName>Family</fullName>
            </value>
            <value>
                <fullName>Coworker</fullName>
            </value>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Son</fullName>
            </value>
            <value>
                <fullName>Daughter</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Aunt</fullName>
            </value>
            <value>
                <fullName>Uncle</fullName>
            </value>
            <value>
                <fullName>Husband</fullName>
            </value>
            <value>
                <fullName>Wife</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Cousin</fullName>
            </value>
            <value>
                <fullName>Grandmother</fullName>
            </value>
            <value>
                <fullName>Grandfather</fullName>
            </value>
            <value>
                <fullName>Grandparent</fullName>
            </value>
            <value>
                <fullName>Grandson</fullName>
            </value>
            <value>
                <fullName>Granddaughter</fullName>
            </value>
            <value>
                <fullName>Grandchild</fullName>
            </value>
            <value>
                <fullName>Employer</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Facilitator</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Team Faciliator</fullName>
            </value>
            <value>
                <fullName>Team Facilitator Lead</fullName>
            </value>
            <value>
                <fullName>Volunteer Lead</fullName>
            </value>
            <value>
                <fullName>Primary Emergency Contact</fullName>
            </value>
            <value>
                <fullName>Secondary Emergency Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Positions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Volunteer</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Board Member</fullName>
    </customValue>
    <customValue>
        <fullName>Trainer</fullName>
    </customValue>
    <customValue>
        <fullName>Client</fullName>
    </customValue>
    <customValue>
        <fullName>Donor</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
        <label>Staff/Contractor</label>
    </customValue>
    <customValue>
        <fullName>Puppy Raiser</fullName>
    </customValue>
    <customValue>
        <fullName>Standalone</fullName>
    </customValue>
    <customValue>
        <fullName>TSiM</fullName>
    </customValue>
    <description>Positions a contact can have</description>
    <masterLabel>Positions</masterLabel>
</GlobalValueSet>

force-app/main/test/relationships/TestRelationshipRepository.cls
/**
 * This class contains unit tests for RelationshipRepository
 */
@isTest
private class TestRelationshipRepository {
  static RelationshipRepository repo = new RelationshipRepository();

  @isTest
  static void getForPair_returnsEmpty_whenBadIds() {
    List<npe4__Relationship__c> actual = repo.getForPair(
      MockProvider.createId(Dog__c.class),
      MockProvider.createId(Account.class),
      'made-up'
    );
    System.assertEquals(0, actual.size(), 'should be empty');
  }
  @isTest
  static void getForPair_returnsEmpty_whenNoRelationship() {
    Contact ace = new Contact(FirstName = 'Ace', LastName = 'GSD');
    Contact cookie = new Contact(FirstName = 'Cookie', LastName = 'Monster');
    insert new List<Contact>{ ace, cookie };

    List<npe4__Relationship__c> actual = repo.getForPair(
      ace.Id,
      cookie.Id,
      'made-up'
    );
    System.assertEquals(0, actual.size(), 'should be empty');
  }
  @isTest
  static void getForPair_returnsEmpty_whenRelationshipTypeDoesntMatch() {
    Contact ace = new Contact(FirstName = 'Ace', LastName = 'GSD');
    Contact cookie = new Contact(FirstName = 'Cookie', LastName = 'Monster');
    insert new List<Contact>{ ace, cookie };

    npe4__Relationship__c relate = new npe4__Relationship__c(
      npe4__Contact__c = ace.Id,
      npe4__Type__c = 'Spouse',
      npe4__Status__c = 'Current',
      npe4__RelatedContact__c = cookie.Id
    );
    insert relate;

    List<npe4__Relationship__c> actual = repo.getForPair(
      ace.Id,
      cookie.Id,
      'made-up'
    );
    System.assertEquals(0, actual.size(), 'should be empty');
  }
  @isTest
  static void getForPair_returnsRelationship_whenRelationshipTypeMatches() {
    Contact ace = new Contact(FirstName = 'Ace', LastName = 'GSD');
    Contact cookie = new Contact(FirstName = 'Cookie', LastName = 'Monster');
    insert new List<Contact>{ ace, cookie };

    npe4__Relationship__c relate = new npe4__Relationship__c(
      npe4__Contact__c = ace.Id,
      npe4__Type__c = 'Spouse',
      npe4__Status__c = 'Current',
      npe4__RelatedContact__c = cookie.Id
    );
    insert relate;

    List<npe4__Relationship__c> result = repo.getForPair(
      ace.Id,
      cookie.Id,
      'Spouse'
    );
    System.assertEquals(1, result.size(), 'should have one record');
    npe4__Relationship__c actual = result[0];
    System.assertEquals(
      relate.npe4__Contact__c,
      actual.npe4__Contact__c,
      'wrong contact'
    );
    System.assertEquals(
      relate.npe4__RelatedContact__c,
      actual.npe4__RelatedContact__c,
      'wrong related contact'
    );
    System.assertEquals(
      relate.npe4__Type__c,
      actual.npe4__Type__c,
      'wrong type'
    );
    System.assertEquals(
      relate.npe4__Status__c,
      actual.npe4__Status__c,
      'wrong status'
    );
  }
  @isTest
  static void getCurrentRelated_returnsRelationship_whenRelationshipTypeMatches() {
    Contact ace = new Contact(FirstName = 'Ace', LastName = 'GSD');
    Contact cookie = new Contact(
      FirstName = 'Cookie',
      LastName = 'Monster',
      Email = 'cookie@test.com',
      Phone = '800-555-1234'
    );
    insert new List<Contact>{ ace, cookie };

    npe4__Relationship__c relate = new npe4__Relationship__c(
      npe4__Contact__c = ace.Id,
      npe4__Type__c = 'Spouse',
      npe4__Status__c = 'Current',
      npe4__RelatedContact__c = cookie.Id
    );
    insert relate;

    List<npe4__Relationship__c> result = repo.getCurrentRelated(
      ace.Id,
      'Spouse'
    );
    System.assertEquals(1, result.size(), 'should have one record');
    npe4__Relationship__c actual = result[0];
    System.assertEquals(
      cookie.Email,
      actual.npe4__RelatedContact__r.Email,
      'no email'
    );
    System.assertEquals(
      cookie.Phone,
      actual.npe4__RelatedContact__r.Phone,
      'no phone'
    );
    System.assertEquals(
      relate.npe4__RelatedContact__c,
      actual.npe4__RelatedContact__c,
      'wrong related contact'
    );
    System.assertEquals(
      relate.npe4__Type__c,
      actual.npe4__Type__c,
      'wrong type'
    );
  }
  @isTest
  static void getCurrentRelated_returnsRelationship_whenNoType() {
    Contact ace = new Contact(
      FirstName = 'Ace',
      LastName = 'GSD',
      Email = 'ace@test.com',
      Phone = '888-555-1234'
    );
    Contact cookie = new Contact(
      FirstName = 'Cookie',
      LastName = 'Monster',
      Email = 'cookie@test.com',
      Phone = '800-555-1234'
    );
    insert new List<Contact>{ ace, cookie };

    npe4__Relationship__c relate = new npe4__Relationship__c(
      npe4__Contact__c = ace.Id,
      npe4__Type__c = 'Husband',
      npe4__Status__c = 'Current',
      npe4__RelatedContact__c = cookie.Id
    );
    insert relate;

    List<npe4__Relationship__c> result = repo.getCurrentRelated(cookie.Id);
    System.assertEquals(1, result.size(), 'should have one record');
    npe4__Relationship__c actual = result[0];
    System.assertEquals(
      cookie.Email,
      actual.npe4__RelatedContact__r.Email,
      'no email'
    );
    System.assertEquals(
      cookie.Phone,
      actual.npe4__RelatedContact__r.Phone,
      'no phone'
    );
    System.assertEquals(ace.Email, actual.npe4__Contact__r.Email, 'no email');
    System.assertEquals(ace.Phone, actual.npe4__Contact__r.Phone, 'no phone');
    System.assertEquals(
      relate.npe4__RelatedContact__c,
      actual.npe4__RelatedContact__c,
      'wrong related contact'
    );
    System.assertEquals(
      relate.npe4__Type__c,
      actual.npe4__Type__c,
      'wrong type'
    );
  }
  static void getSharingPositionsReturnsPositions(String relationship) {
    Contact ace = new Contact(
      FirstName = 'Ace',
      LastName = 'GSD',
      Email = 'ace@test.com',
      Positions__c = 'Client'
    );
    Contact cookie = new Contact(
      FirstName = 'Cookie',
      LastName = 'Monster',
      Email = 'cookie@test.com',
      Phone = '800-555-1234'
    );
    insert new List<Contact>{ ace, cookie };

    npe4__Relationship__c relate = new npe4__Relationship__c(
      npe4__Contact__c = ace.Id,
      npe4__Type__c = relationship,
      npe4__Status__c = 'Current',
      npe4__RelatedContact__c = cookie.Id
    );
    insert relate;

    List<npe4__Relationship__c> result = repo.getSharingPositions(cookie.Id);
    System.assertEquals(1, result.size(), 'should have one record');
    npe4__Relationship__c actual = result[0];
    System.assertEquals(
      ace.Positions__c,
      actual.npe4__Contact__r.Positions__c,
      'no positions'
    );
  }

  @isTest
  static void getSharingPositions_returnsEmergencyContacts() {
    getSharingPositionsReturnsPositions('Primary Emergency Contact');
  }

  @isTest
  static void getSharingPositions_returnsSecondEmergencyContacts() {
    getSharingPositionsReturnsPositions('Secondary Emergency Contact');
  }

  @isTest
  static void getSharingPositions_returnsGuardianContacts() {
    getSharingPositionsReturnsPositions('Guardian');
  }

  static void getSharingPositionsReturnsEmpty(String status) {
    Contact ace = new Contact(
      FirstName = 'Ace',
      LastName = 'GSD',
      Email = 'ace@test.com',
      Positions__c = 'Client'
    );
    Contact cookie = new Contact(
      FirstName = 'Cookie',
      LastName = 'Monster',
      Email = 'cookie@test.com',
      Phone = '800-555-1234'
    );
    insert new List<Contact>{ ace, cookie };

    npe4__Relationship__c relate = new npe4__Relationship__c(
      npe4__Contact__c = ace.Id,
      npe4__Type__c = 'Guardian',
      npe4__Status__c = status,
      npe4__RelatedContact__c = cookie.Id
    );
    insert relate;

    List<npe4__Relationship__c> result = repo.getSharingPositions(cookie.Id);
    System.assertEquals(0, result.size(), 'should be empty');
  }

  @isTest
  static void getSharingPositionsReturnsEmptyWhenFormer() {
    getSharingPositionsReturnsEmpty('Former');
  }

  @isTest
  static void getSharingPositionsReturnsEmptyWhenNoStatus() {
    getSharingPositionsReturnsEmpty(null);
  }

  static void getCurrentRelatedReturnsEmpty(String status) {
    Contact ace = new Contact(
      FirstName = 'Ace',
      LastName = 'GSD',
      Email = 'ace@test.com',
      Positions__c = 'Client'
    );
    Contact cookie = new Contact(
      FirstName = 'Cookie',
      LastName = 'Monster',
      Email = 'cookie@test.com',
      Phone = '800-555-1234'
    );
    insert new List<Contact>{ ace, cookie };

    npe4__Relationship__c relate = new npe4__Relationship__c(
      npe4__Contact__c = ace.Id,
      npe4__Type__c = 'Guardian',
      npe4__Status__c = status,
      npe4__RelatedContact__c = cookie.Id
    );
    insert relate;

    List<npe4__Relationship__c> result = repo.getCurrentRelated(
      new Set<Id>{ cookie.Id },
      'Guardian'
    );
    System.assertEquals(0, result.size(), 'should be empty');
  }

  @isTest
  static void getCurrentRelated_returnsEmpty_whenNull() {
    getCurrentRelatedReturnsEmpty(null);
  }

  @isTest
  static void getCurrentRelated_returnsEmpty_whenFormer() {
    getCurrentRelatedReturnsEmpty('Former');
  }

  @isTest
  static void getCurrentRelated_returnsEmpty_whenTypeDiffers() {
    Contact ace = new Contact(
      FirstName = 'Ace',
      LastName = 'GSD',
      Email = 'ace@test.com',
      Positions__c = 'Client'
    );
    Contact cookie = new Contact(
      FirstName = 'Cookie',
      LastName = 'Monster',
      Email = 'cookie@test.com',
      Phone = '800-555-1234'
    );
    insert new List<Contact>{ ace, cookie };

    npe4__Relationship__c relate = new npe4__Relationship__c(
      npe4__Contact__c = ace.Id,
      npe4__Type__c = 'Guardian',
      npe4__Status__c = 'Current',
      npe4__RelatedContact__c = cookie.Id
    );
    insert relate;

    List<npe4__Relationship__c> result = repo.getCurrentRelated(
      new Set<Id>{ cookie.Id },
      'Trainer'
    );
    System.assertEquals(0, result.size(), 'should be empty');
  }

  @isTest
  static void getCurrentRelated_returnsList_whenMatch() {
    Contact ace = new Contact(
      FirstName = 'Ace',
      LastName = 'GSD',
      Email = 'ace@test.com',
      Positions__c = 'Client'
    );
    Contact cookie = new Contact(
      FirstName = 'Cookie',
      LastName = 'Monster',
      Email = 'cookie@test.com',
      Phone = '800-555-1234'
    );
    insert new List<Contact>{ ace, cookie };

    npe4__Relationship__c relate = new npe4__Relationship__c(
      npe4__Contact__c = ace.Id,
      npe4__Type__c = 'Guardian',
      npe4__Status__c = 'Current',
      npe4__RelatedContact__c = cookie.Id
    );
    insert relate;

    List<npe4__Relationship__c> result = repo.getCurrentRelated(
      new Set<Id>{ cookie.Id },
      'Guardian'
    );
    System.assertEquals(1, result.size(), 'should have one record');
    npe4__Relationship__c actual = result[0];
    System.assertEquals(cookie.Id, actual.npe4__Contact__c, 'wrong contact');
    System.assertEquals(
      ace.Id,
      actual.npe4__RelatedContact__c,
      'wrong related contact'
    );
  }

  @isTest
  static void create_inserts() {
    Contact ace = new Contact(
      FirstName = 'Ace',
      LastName = 'GSD',
      Email = 'ace@test.com',
      Positions__c = 'Client'
    );
    Contact cookie = new Contact(
      FirstName = 'Cookie',
      LastName = 'Monster',
      Email = 'cookie@test.com',
      Phone = '800-555-1234'
    );
    insert new List<Contact>{ ace, cookie };

    npe4__Relationship__c relate = new npe4__Relationship__c(
      npe4__Contact__c = ace.Id,
      npe4__Type__c = 'Guardian',
      npe4__Status__c = 'Current',
      npe4__RelatedContact__c = cookie.Id
    );
    // Act
    npe4__Relationship__c result = repo.create(relate);

    npe4__Relationship__c actual = [
      SELECT
        npe4__Contact__c,
        npe4__Type__c,
        npe4__Status__c,
        npe4__RelatedContact__c
      FROM npe4__Relationship__c
      WHERE Id = :result.Id
    ];
    System.assertEquals(result, actual, 'record should match');
  }

  @isTest
  static void modify_updates() {
    Contact ace = new Contact(
      FirstName = 'Ace',
      LastName = 'GSD',
      Email = 'ace@test.com',
      Positions__c = 'Client'
    );
    Contact cookie = new Contact(
      FirstName = 'Cookie',
      LastName = 'Monster',
      Email = 'cookie@test.com',
      Phone = '800-555-1234'
    );
    insert new List<Contact>{ ace, cookie };

    npe4__Relationship__c relate = new npe4__Relationship__c(
      npe4__Contact__c = ace.Id,
      npe4__Type__c = 'Guardian',
      npe4__Status__c = 'Current',
      npe4__RelatedContact__c = cookie.Id
    );
    insert relate;

    relate.npe4__Status__c = 'Former';
    // Act
    npe4__Relationship__c result = repo.modify(relate);

    npe4__Relationship__c actual = [
      SELECT
        npe4__Contact__c,
        npe4__Type__c,
        npe4__Status__c,
        npe4__RelatedContact__c
      FROM npe4__Relationship__c
      WHERE Id = :result.Id
    ];
    System.assertEquals(result, actual, 'record should match');
  }
}