force-app/main/default/objects/BackgroundCheck__c/BackgroundCheck__c.object-meta.xml
<CustomObject>
    <description>Background check record</description>
    <label>Background Check</label>
    <nameField>
        <displayFormat>BC-{0000}</displayFormat>
        <label>Background Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Background Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BackgroundCheck__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contact the background check is for</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Background Checks</relationshipLabel>
    <relationshipName>BackgroundChecks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BackgroundCheck__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date background check was requested</description>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BackgroundCheck__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BackgroundCheck__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Criminal</fullName>
                <default>true</default>
                <label>Criminal</label>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/BoardCoIReceived__c.field-meta.xml
<CustomField>
    <fullName>BoardCoIReceived__c</fullName>
    <description
    >The date the most recent version of Board Conflict of Interest was uploaded</description>
    <label>Last Board Conflict of Interest</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Place/person to contact this person</description>
    <inlineHelpText>Select Guardian to contact this person through their guardian, Home for personal email/phone</inlineHelpText>
    <label>Contact At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
                <default>true</default>
                <label>Home</label>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/FacilitatorPracticumReceived__c.field-meta.xml
<CustomField>
    <fullName>FacilitatorPracticumReceived__c</fullName>
    <description
    >The date the most recent version of Team Facilitator Practicum was uploaded</description>
    <label>Last Facilitator Practicum</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/VolunteerApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>VolunteerApplicationReceived__c</fullName>
    <description>The date the most recent version of Volunteer Application was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Volunteer Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/ContentVersion/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Board</fullName>
            </value>
            <value>
                <fullName>Na</fullName>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Client</fullName>
                <label>Team Client</label>
            </value>
            <value>
                <fullName>TeamDog</fullName>
                <label>Team Dog</label>
            </value>
            <value>
                <fullName>TeamDog</fullName>
                <label>Team Dog</label>
            </value>
            <value>
                <fullName>Standalone</fullName>
                <label>Standalone Programs</label>
            </value>
            <value>
                <fullName>ADSiM</fullName>
                <label>Assistance Dogs Set in Motion</label>
            </value>
            <value>
                <fullName>Facilitator</fullName>
                <label>Team Facilitator</label>
            </value>
            <value>
                <fullName>Puppy</fullName>
                <label>Puppy Raiser</label>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
                <label>Staff/Contractor</label>
            </value>
            <value>
                <fullName>Dog</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Document Date</description>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PreApplication</fullName>
                <label>Pre Application</label>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>ContactForm</fullName>
                <label>Contact Form</label>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>CoI</fullName>
                <label>Conflict of Interest</label>
            </value>
            <value>
                <fullName>ToN</fullName>
                <label>Transmission of Notices</label>
            </value>
            <value>
                <fullName>LOMI</fullName>
                <label>Medical Provider Form</label>
            </value>
            <value>
                <fullName>Media</fullName>
                <label>Media Release</label>
            </value>
            <value>
                <fullName>VAPW</fullName>
                <label>Veteran Paperwork</label>
            </value>
            <value>
                <fullName>Survey</fullName>
                <label>Certification Survey</label>
            </value>
            <value>
                <fullName>Reference</fullName>
                <label>Reference Letter</label>
            </value>
            <value>
                <fullName>ClientReference</fullName>
                <label>Client Reference Letter</label>
            </value>
            <value>
                <fullName>ProfReference</fullName>
                <label>Professional Reference Letter</label>
            </value>
            <value>
                <fullName>ProgAgreement</fullName>
                <label>Program Agreement</label>
            </value>
            <value>
                <fullName>CertAgreement</fullName>
                <label>Certification Agreement</label>
            </value>
            <value>
                <fullName>Practicum</fullName>
            </value>
            <value>
                <fullName>InfrNotice</fullName>
                <label>Infraction Notice</label>
            </value>
            <value>
                <fullName>HealthForm</fullName>
                <label>Vet Health Form</label>
            </value>
            <value>
                <fullName>Notes</fullName>
                <label>Interview Notes</label>
            </value>
            <value>
                <fullName>Xray</fullName>
                <label>Vet Xray Report</label>
            </value>
            <value>
                <fullName>VacExams</fullName>
                <label>Vaccinations and Exams</label>
            </value>
            <value>
                <fullName>Resume</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
                <label>Offer Letter</label>
            </value>
            <value>
                <fullName>W4</fullName>
            </value>
            <value>
                <fullName>I9</fullName>
            </value>
            <value>
                <fullName>W9</fullName>
                <label>Contractor W9</label>
            </value>
            <value>
                <fullName>ApplicationVideo</fullName>
                <label>Application Video</label>
            </value>
            <value>
                <fullName>CGCForm</fullName>
                <label>CGC Form</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Derived from Team.  Do not edit directly.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In ADSiM</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Certified-Active</fullName>
            </value>
            <value>
                <fullName>Certified-OnHold</fullName>
            </value>
            <value>
                <fullName>Decertified</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dog__c/fields/VacExamsReceived__c.field-meta.xml
<CustomField>
    <fullName>VacExamsReceived__c</fullName>
    <description
    >The date the most recent version of Vaccinations and Exams was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last  Vaccinations and Exams</label>
    <type>Date</type>
</CustomField>

force-app/main/test/files/TestFileService.cls
@isTest
public with sharing class TestFileService {
    public static ContentVersion createLink(
        string category,
        string type,
        Date docDate,
        Id recordId
    ) {
        ContentVersion cv = new ContentVersion(
            Title = 'Test Category Type',
            PathOnClient = 'TestDocument3.jpg',
            Origin = 'H',
            VersionData = Blob.valueOf('Document Body 3'),
            Category__c = category,
            Type__c = type,
            Date__c = docDate
        );
        insert cv;

        // insert will fill in the Id, but not the ContentDecumentId
        cv = [
            SELECT Id, ContentDocumentId, Category__c, Type__c, Date__c
            FROM ContentVersion
            WHERE Id = :cv.Id
            LIMIT 1
        ];

        ContentDocumentLink link = new ContentDocumentLink(
            ContentDocumentId = cv.ContentDocumentId,
            LinkedEntityId = recordId
        );
        insert link;

        return cv;
    }

    @isTest
    public static void updateDates_Ignores_WhenNullList() {
        FileService.updateDates((List<ContentVersion>)null);
        // no assert here.  Test passes if no exception
    }
    
    @isTest
    public static void updateDates_Ignores_WhenEmptyList() {
        FileService.updateDates(new List<ContentVersion>());
        // no assert here.  Test passes if no exception
    }

    @isTest
    public static void updateDate_Ignores_WhenNoCatType() {
        Contact contact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            Email = 'test@test.com'
        );
        insert contact;

        BackgroundCheck__c bgCheck = new BackgroundCheck__c(
            Contact__c = contact.Id,
            Date__c = Date.today(),
            Status__c = 'Pass'
        );
        insert bgCheck;

        ContentVersion cv = createLink(null, null, Date.today().addDays(-1), bgCheck.Id);

        FileService.updateDate(cv, bgCheck.Id);
        // no assert here.  Test passes if no exception
    }

    @isTest
    public static void updateDate_FindsLinkedDog() {
        Dog__c dog = new Dog__c(Name = 'Fido', VacExamsReceived__c = null);
        insert dog;
        ContentVersion cv = createLink('Dog', 'VacExams', Date.today(), dog.Id);

        // Act
        FileService.updateDate(cv);

        // Assert
        dog = [
            SELECT VacExamsReceived__c
            FROM Dog__c
            WHERE Id = :dog.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            dog.VacExamsReceived__c,
            'VacExamsReceived not set'
        );
    }

    @isTest
    public static void updateDate_FindsLinkedContact() {
        Contact contact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            Email = 'abc@abc.com'
        );
        insert contact;
        ContentVersion cv = createLink('Volunteer', 'Application', Date.today(), contact.Id);

        // Act
        FileService.updateDate(cv);

        // Assert
        contact = [
            SELECT VolunteerApplicationReceived__c
            FROM Contact
            WHERE Id = :contact.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            contact.VolunteerApplicationReceived__c,
            'VolunteerApplicationReceived not set'
        );
    }

    @isTest
    public static void updateDates_UpdatesAllDates_WhenDog() {
        Dog__c record = new Dog__c(Name = 'Fido');
        insert record;
        List<ContentVersion> cvs = new List<ContentVersion>();
        cvs.add(createLink('Dog', 'VacExams', Date.today().addDays(-1), record.Id));
        FileService.updateDates(cvs);
        record = [
            SELECT VacExamsReceived__c
            FROM Dog__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today().addDays(-1),
            record.VacExamsReceived__c,
            'VacExamsReceived__c not set'
        );
    }


    @isTest
    public static void updateDates_UpdatesAllDates_WhenContact() {
        Contact record = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            Email = 'abc@abc.com'
        );
        insert record;
        List<ContentVersion> cvs = new List<ContentVersion>();
        cvs.add(createLink('Board', 'CoI', Date.today(), record.Id));
        cvs.add(createLink('Volunteer', 'Application', Date.today().addDays(-1), record.Id));
        cvs.add(createLink('Facilitator', 'Practicum', Date.today().addDays(-2), record.Id));
        FileService.updateDates(cvs);
        record = [
            SELECT BoardCoIReceived__c, VolunteerApplicationReceived__c, FacilitatorPracticumReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.BoardCoIReceived__c,
            'BoardCoIReceived__c not set'
        );
        system.assertEquals(
            Date.today().addDays(-1),
            record.VolunteerApplicationReceived__c,
            'VolunteerApplicationReceived__c not set'
        );
        system.assertEquals(
            Date.today().addDays(-2),
            record.FacilitatorPracticumReceived__c,
            'FacilitatorPracticumReceived__c not set'
        );
    }
}