force-app/main/default/objects/BackgroundCheck__c/BackgroundCheck__c.object-meta.xml
<CustomObject>
    <description>Background check record</description>
    <label>Background Check</label>
    <nameField>
        <displayFormat>BC-{0000}</displayFormat>
        <label>Background Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Background Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BackgroundCheck__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contact the background check is for</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Background Checks</relationshipLabel>
    <relationshipName>BackgroundChecks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BackgroundCheck__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date background check was requested</description>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BackgroundCheck__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BackgroundCheck__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Criminal</fullName>
                <default>true</default>
                <label>Criminal</label>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Place/person to contact this person</description>
    <inlineHelpText>Select Guardian to contact this person through their guardian, Home for personal email/phone</inlineHelpText>
    <label>Contact At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
                <default>true</default>
                <label>Home</label>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/VolunteerAccess__c.field-meta.xml
<CustomField>
    <fullName>VolunteerAccess__c</fullName>
    <label>Volunteer Access</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operations- Master Docs - READ ONLY</fullName>
            </value>
            <value>
                <fullName>Operations- Financial</fullName>
            </value>
            <value>
                <fullName>Operations- Client</fullName>
            </value>
            <value>
                <fullName>Operations- Volunteer and Staff</fullName>
            </value>
            <value>
                <fullName>Operations- Trainer</fullName>
            </value>
            <value>
                <fullName>Board - READ ONLY</fullName>
            </value>
            <value>
                <fullName>Board</fullName>
            </value>
            <value>
                <fullName>Sensitive Info- Volunteer and Staff</fullName>
            </value>
            <value>
                <fullName>Sensitive Info- Trainer</fullName>
            </value>
            <value>
                <fullName>Sensitive Info- Board</fullName>
            </value>
            <value>
                <fullName>Active Projects- Academy</fullName>
            </value>
            <value>
                <fullName>Active Projects- ADI</fullName>
            </value>
            <value>
                <fullName>Active Projects- Branding and Marketing</fullName>
            </value>
            <value>
                <fullName>Active Projects- Client Certification</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Community Outreach and Education</fullName>
                <label>Active Projects- Community Outreach and Education</label>
            </value>
            <value>
                <fullName>Active Projects- Dog Availability</fullName>
            </value>
            <value>
                <fullName>Active Projects- Fund Development</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Governance, Compliance and Operations</fullName>
                <label
                >Active Projects- Governance, Compliance and Operations</label>
            </value>
            <value>
                <fullName>Active Projects- Research and Development</fullName>
            </value>
            <value>
                <fullName>Active Projects- Scholarships</fullName>
            </value>
            <value>
                <fullName>Active Projects- State Registration</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Team Facilitator Certification</fullName>
                <label>Active Projects- Team Facilitator Certification</label>
            </value>
            <value>
                <fullName>Active Projects- Technology Infrastructure</fullName>
            </value>
            <value>
                <fullName>Active Projects- Trainer Certification</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Volunteer Recruitment and Retention</fullName>
                <label
                >Active Projects- Volunteer Recruitment and Retention</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/background-checks/BackgroundCheckRepository.cls
public inherited sharing class BackgroundCheckRepository {
  public BackgroundCheckRepository() {
  }

  public BackgroundCheck__c[] getMatchingChecksForContacts(
    Set<Id> contactIds,
    Date threshold
  ) {
    return [
      SELECT Id, Date__c, Contact__c, Type__c, Contact__r.Name
      FROM BackgroundCheck__c
      WHERE
        Contact__c IN :contactIds
        AND Date__c > :threshold
        // AND Status__c = 'Pass' We are not checking status at this time
        AND ((Contact__r.VolunteerAccess__c INCLUDES ('Credit Check Required')
        AND Type__c = 'Credit')
        OR (Contact__r.VolunteerAccess__c INCLUDES ('Background Check Required')
        AND Type__c = 'Criminal'))
      ORDER BY Date__c DESC // get the most recent first
    ];
  }
}