force-app/main/default/objects/BackgroundCheck__c/BackgroundCheck__c.object-meta.xml
<CustomObject>
    <description>Background check record</description>
    <label>Background Check</label>
    <nameField>
        <displayFormat>BC-{0000}</displayFormat>
        <label>Background Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Background Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BackgroundCheck__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Criminal</fullName>
                <default>true</default>
                <label>Criminal</label>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/ContentVersion/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Board</fullName>
            </value>
            <value>
                <fullName>Na</fullName>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Client</fullName>
                <label>Team Client</label>
            </value>
            <value>
                <fullName>TeamDog</fullName>
                <label>Team Dog</label>
            </value>
            <value>
                <fullName>TeamDog</fullName>
                <label>Team Dog</label>
            </value>
            <value>
                <fullName>Standalone</fullName>
                <label>Standalone Programs</label>
            </value>
            <value>
                <fullName>ADSiM</fullName>
                <label>Assistance Dogs Set in Motion</label>
            </value>
            <value>
                <fullName>Facilitator</fullName>
                <label>Team Facilitator</label>
            </value>
            <value>
                <fullName>Puppy</fullName>
                <label>Puppy Raiser</label>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
                <label>Staff/Contractor</label>
            </value>
            <value>
                <fullName>Dog</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PreApplication</fullName>
                <label>Pre Application</label>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>ContactForm</fullName>
                <label>Contact Form</label>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>CoI</fullName>
                <label>Conflict of Interest</label>
            </value>
            <value>
                <fullName>ToN</fullName>
                <label>Transmission of Notices</label>
            </value>
            <value>
                <fullName>LOMI</fullName>
                <label>Medical Provider Form</label>
            </value>
            <value>
                <fullName>Media</fullName>
                <label>Media Release</label>
            </value>
            <value>
                <fullName>VAPW</fullName>
                <label>Veteran Paperwork</label>
            </value>
            <value>
                <fullName>Survey</fullName>
                <label>Certification Survey</label>
            </value>
            <value>
                <fullName>Reference</fullName>
                <label>Reference Letter</label>
            </value>
            <value>
                <fullName>ClientReference</fullName>
                <label>Client Reference Letter</label>
            </value>
            <value>
                <fullName>ProfReference</fullName>
                <label>Professional Reference Letter</label>
            </value>
            <value>
                <fullName>ProgAgreement</fullName>
                <label>Program Agreement</label>
            </value>
            <value>
                <fullName>CertAgreement</fullName>
                <label>Certification Agreement</label>
            </value>
            <value>
                <fullName>Practicum</fullName>
            </value>
            <value>
                <fullName>InfrNotice</fullName>
                <label>Infraction Notice</label>
            </value>
            <value>
                <fullName>HealthForm</fullName>
                <label>Vet Health Form</label>
            </value>
            <value>
                <fullName>Notes</fullName>
                <label>Interview Notes</label>
            </value>
            <value>
                <fullName>Xray</fullName>
                <label>Vet Xray Report</label>
            </value>
            <value>
                <fullName>VacExams</fullName>
                <label>Vaccinations and Exams</label>
            </value>
            <value>
                <fullName>Resume</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
                <label>Offer Letter</label>
            </value>
            <value>
                <fullName>W4</fullName>
            </value>
            <value>
                <fullName>I9</fullName>
            </value>
            <value>
                <fullName>W9</fullName>
                <label>Contractor W9</label>
            </value>
            <value>
                <fullName>ApplicationVideo</fullName>
                <label>Application Video</label>
            </value>
            <value>
                <fullName>CGCForm</fullName>
                <label>CGC Form</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PublicAccessTest__c/PublicAccessTest__c.object-meta.xml
<CustomObject>
    <description>Tests that the Dog/Client team can perform in public.</description>
    <label>PAT</label>
    <nameField>
        <displayFormat>PAT-{0000}</displayFormat>
        <label>Public Access Test Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PATs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PublicAccessTest__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Dog in the PAT team</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>PATs</relationshipLabel>
    <relationshipName>Public_Access_Tests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Public Access Test</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
            </value>
            <value>
                <fullName>Recertification</fullName>
            </value>
            <value>
                <fullName>Retest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/test/TestFileController.cls
@isTest
public with sharing class TestFileController {
    private Contact jill;
    private Dog__c rover;
    private PublicAccessTest__c pat;
    private BackgroundCheck__c check;

    private static List<ContentVersion> insertRecords() {
        List<ContentVersion> documents = new List<ContentVersion>();
        documents.add(
            new ContentVersion(
                Title = 'TestDocument1',
                PathOnClient = 'TestDocument1.jpg',
                Origin = 'H',
                VersionData = Blob.valueOf('Document Body 1'),
                Category__c = 'Volunteer',
                Type__c = 'Agreement'
            )
        );
        documents.add(
            new ContentVersion(
                Title = 'TestDocument2',
                PathOnClient = 'TestDocument2.jpg',
                Origin = 'H',
                VersionData = Blob.valueOf('Document Body 2'),
                Category__c = 'Board',
                Type__c = 'CoI'
            )
        );
        documents.add(
            new ContentVersion(
                Title = 'TestDocument3',
                PathOnClient = 'TestDocument3.jpg',
                Origin = 'H',
                VersionData = Blob.valueOf('Document Body 3'),
                Category__c = 'Staff',
                Type__c = 'Resume'
            )
        );
        insert documents;

        documents = [
            SELECT
                Id,
                ContentDocumentId,
                Title,
                PathOnClient,
                Origin,
                VersionData,
                Category__c,
                Type__c,
                CreatedDate
            FROM ContentVersion
        ];
        return documents;
    }

    @isTest
    public static void updateRecords_SetsAllDocsToSameCategoryAndType() {
        List<ContentVersion> documents = insertRecords();
        List<Id> docIds = new List<Id>();
        for (ContentVersion cv : documents) {
            docIds.add(cv.ContentDocumentId);
        }

        Test.startTest();
        FileController.updateRecords('Trainer', 'Infraction Notice', docIds);
        Test.stopTest();

        List<ContentVersion> results = [
            SELECT Id, Category__c, Type__c
            FROM ContentVersion
        ];

        for (ContentVersion actual : results) {
            System.assertEquals('Trainer', actual.Category__c);
            System.assertEquals('Infraction Notice', actual.Type__c);
        }
    }

    @isTest
    public static void updateRecords_ThrowsException_WhenNullList() {
        Boolean thrown = false;
        Test.startTest();
        try {
            FileController.updateRecords(
                'Trainer',
                'Trainer Infraction notices as applicable',
                null
            );
        } catch (AuraHandledException e) {
            thrown = true;
        }
        Test.stopTest();

        System.assert(thrown);
    }

    @isTest
    public static void updateRecords_HandlesEmptyList() {
        Test.startTest();
        FileController.updateRecords(
            'Trainer',
            'Trainer Infraction notices as applicable',
            new List<Id>()
        );
        Test.stopTest();
    }

    @isTest
    public static void updateRecords_HandlesNullParameters() {
        Test.startTest();
        FileController.updateRecords(null, null, new List<Id>());
        Test.stopTest();
    }

    @isTest
    public static void updateRecords_Returns_WhenNoMatches() {
        Dog__c ace = new Dog__c(Name = 'Ace');
        insert ace;
        Test.startTest();
        FileController.updateRecords(
            'Dog',
            'Vet Health Form',
            new List<Id>{ ace.Id }
        );
        Test.stopTest();
    }

    @isTest
    public static void updateRecords_ThrowsException_WhenInvalidType() {
        ContentVersion cv = new ContentVersion(
            Title = 'TestDocument1',
            PathOnClient = 'TestDocument1.jpg',
            Origin = 'H',
            VersionData = Blob.valueOf('Document Body 1'),
            Category__c = 'Volunteer',
            Type__c = 'Agreement'
        );
        insert cv;

        cv = [SELECT ContentDocumentId FROM ContentVersion LIMIT 1];

        Boolean thrown = false;

        Test.startTest();
        try {
            FileController.updateRecords(
                'Doggie',
                'Health Form',
                new List<Id>{ cv.ContentDocumentId }
            );
        } catch (AuraHandledException e) {
            thrown = true;
        }

        Test.stopTest();

        System.assert(thrown);
    }

    @isTest
    public static void deleteRecords_ThrowsException_WhenNullList() {
        Boolean thrown = false;

        Test.startTest();
        try {
            FileController.deleteRecords(null);
        } catch (AuraHandledException e) {
            thrown = true;
        }

        Test.stopTest();

        System.assert(thrown);
    }

    @isTest
    public static void deleteRecords_HandlesEmptyList() {
        List<ContentVersion> documents = insertRecords();

        Test.startTest();
        FileController.deleteRecords(new List<Id>());
        Test.stopTest();

        List<ContentVersion> remaining = [SELECT Id FROM ContentVersion];
        System.assertEquals(documents.size(), remaining.size());
    }

    @isTest
    public static void deleteRecords_DeletesExpectedRecords() {
        List<ContentVersion> documents = insertRecords();

        // delete all but the first document
        List<Id> ids = new List<Id>();
        for (Integer idx = 1; idx < documents.size(); idx++) {
            ids.add(documents[idx].ContentDocumentId);
        }
        Test.startTest();
        FileController.deleteRecords(ids);
        Test.stopTest();

        List<ContentVersion> remaining = [SELECT Id FROM ContentVersion];
        System.assertEquals(1, remaining.size());
        System.assertEquals(documents[0].Id, remaining[0].Id);
    }

    @isTest
    public static void deleteRecord_ThrowsException_WhenNullId() {
        Boolean thrown = false;

        Test.startTest();
        try {
            FileController.deleteRecord(null);
        } catch (AuraHandledException e) {
            thrown = true;
        }

        Test.stopTest();

        System.assert(thrown);
    }

    @isTest
    public static void deleteRecord_HandlesBadId() {
        List<ContentVersion> documents = insertRecords();

        Test.startTest();
        FileController.deleteRecord(documents[0].Id);
        Test.stopTest();

        List<ContentVersion> remaining = [SELECT Id FROM ContentVersion];
        System.assertEquals(documents.size(), remaining.size());
    }

    @isTest
    public static void deleteRecord_DeletesExpectedRecord() {
        List<ContentVersion> documents = insertRecords();
        Test.startTest();
        FileController.deleteRecord(documents[0].ContentDocumentId);
        Test.stopTest();

        List<ContentVersion> remaining = [SELECT Id FROM ContentVersion];
        System.assertEquals(documents.size() - 1, remaining.size());
        for (ContentVersion actual : remaining) {
            System.assertNotEquals(documents[0].Id, actual.Id);
        }
    }

    @isTest
    public static void getContentVersion_ThrowsException_WhenIdNull() {
        Boolean thrown = false;

        Test.startTest();
        try {
            FileController.getContentVersion(null);
        } catch (AuraHandledException e) {
            thrown = true;
        }

        Test.stopTest();

        System.assert(thrown);
    }

    @isTest
    public static void getContentVersion_ThrowsException_WhenNoRecord() {
        List<ContentVersion> documents = insertRecords();
        Boolean thrown = false;

        Test.startTest();
        try {
            FileController.getContentVersion(documents[0].ContentDocumentId);
        } catch (AuraHandledException e) {
            thrown = true;
        }

        Test.stopTest();

        System.assert(thrown);
    }

    @isTest
    public static void getContentVersion_ReturnsRecordData() {
        List<ContentVersion> documents = insertRecords();

        Test.startTest();
        ContentVersion actual = FileController.getContentVersion(
            documents[0].Id
        );
        Test.stopTest();

        ContentVersion expected = documents[0];
        System.assertEquals(expected.Id, actual.Id);
        System.assertEquals(expected.Title, actual.Title);
        System.assertEquals(
            expected.ContentDocumentId,
            actual.ContentDocumentId
        );
        System.assertEquals(expected.Type__c, actual.Type__c);
        System.assertEquals(expected.Category__c, actual.Category__c);
        System.assertEquals(expected.CreatedDate, actual.CreatedDate);
    }

    @isTest
    public static void updateContentVersion_ThrowsException_WhenNullId() {
        Boolean thrown = false;
        Test.startTest();
        try {
            FileController.updateContentVersion(
                'Trainer',
                'Trainer Infraction notices as applicable',
                null
            );
        } catch (AuraHandledException e) {
            thrown = true;
        }
        Test.stopTest();

        System.assert(thrown);
    }

    @isTest
    public static void updateContentVersion_ThrowsException_WhenBadId() {
        Dog__c ace = new Dog__c(Name = 'Ace');
        insert ace;
        Boolean thrown = false;
        Test.startTest();
        try {
            FileController.updateContentVersion(
                'Trainer',
                'Trainer Infraction notices as applicable',
                ace.Id
            );
        } catch (AuraHandledException e) {
            thrown = true;
        }

        Test.stopTest();

        System.assert(thrown);
    }

    @isTest
    public static void updateContentVersion_HandlesNullParameters() {
        Dog__c ace = new Dog__c(Name = 'Ace');
        insert ace;
        Boolean thrown = false;
        Test.startTest();
        try {
            FileController.updateContentVersion(null, null, ace.Id);
        } catch (AuraHandledException e) {
            thrown = true;
        }
        Test.stopTest();

        System.assert(thrown);
    }

    @isTest
    public static void updateContentVersion_ThrowsException_WhenNoMatch() {
        Dog__c ace = new Dog__c(Name = 'Ace');
        insert ace;
        Boolean thrown = false;
        Test.startTest();
        try {
            FileController.updateContentVersion(
                'Dog',
                'Vet Health Form',
                ace.Id
            );
        } catch (AuraHandledException e) {
            thrown = true;
        }
        Test.stopTest();

        System.assert(thrown);
    }

    @isTest
    public static void updateContentVersion_ThrowsException_WhenInvalidType() {
        ContentVersion cv = new ContentVersion(
            Title = 'TestDocument1',
            PathOnClient = 'TestDocument1.jpg',
            Origin = 'H',
            VersionData = Blob.valueOf('Document Body 1'),
            Category__c = 'Volunteer',
            Type__c = 'Application'
        );
        insert cv;

        cv = [SELECT ContentDocumentId FROM ContentVersion LIMIT 1];

        Boolean thrown = false;

        Test.startTest();
        try {
            FileController.updateContentVersion(
                'Doggie',
                'Health Form',
                cv.ContentDocumentId
            );
        } catch (AuraHandledException e) {
            thrown = true;
        }

        Test.stopTest();

        System.assert(thrown);
    }

    @isTest
    public static void getRelatedFiles_ThrowsException_WhenNullRecord() {
        Boolean thrown = false;

        Test.startTest();
        try {
            FileController.getRelatedFiles(null);
        } catch (AuraHandledException e) {
            thrown = true;
        }

        Test.stopTest();

        System.assert(thrown);
    }

    @isTest
    public static void getRelatedFiles_ReturnsEmptyList_WhenNoRecords() {
        Dog__c ace = new Dog__c(Name = 'Ace');
        insert ace;

        Test.startTest();
        List<ContentVersion> related = FileController.getRelatedFiles(ace.Id);

        Test.stopTest();

        System.assert(related.isEmpty());
    }

    @isTest
    public static void getRelatedFiles_ReturnsRelatedRecords() {
        Dog__c ace = new Dog__c(Name = 'Ace');
        insert ace;

        List<ContentVersion> documents = insertRecords();

        // delete all but the first document
        List<Id> ids = new List<Id>();
        for (Integer idx = 0; idx < documents.size(); idx++) {
            ids.add(documents[idx].ContentDocumentId);
        }

        FileController.relateFiles(ids, ace.Id);

        Test.startTest();
        List<ContentVersion> related = FileController.getRelatedFiles(ace.Id);

        Test.stopTest();

        System.assertEquals(documents.size(), related.size());
    }

    @isTest
    public static void relateFile_ThrowsException_WhenNullDocumentId() {
        Dog__c ace = new Dog__c(Name = 'Ace');
        insert ace;

        Boolean thrown = false;

        Test.startTest();
        try {
            ContentVersion result = FileController.relateFile(null, ace.Id);
        } catch (AuraHandledException e) {
            thrown = true;
        }

        Test.stopTest();

        System.assert(thrown);
    }

    @isTest
    public static void relateFile_ThrowsException_WhenNullId() {
        List<ContentVersion> documents = insertRecords();

        Boolean thrown = false;

        Test.startTest();
        try {
            ContentVersion result = FileController.relateFile(
                documents[0].ContentDocumentId,
                null
            );
        } catch (AuraHandledException e) {
            thrown = true;
        }

        Test.stopTest();

        System.assert(thrown);
    }

    @isTest
    public static void relateFile_RelatesDocument() {
        Dog__c ace = new Dog__c(Name = 'Ace');
        insert ace;
        List<ContentVersion> documents = insertRecords();
        ContentVersion document = documents[0];

        Test.startTest();
        ContentVersion result = FileController.relateFile(
            document.ContentDocumentId,
            ace.Id
        );
        Test.stopTest();

        ContentDocumentLink link = [
            SELECT ContentDocumentId, LinkedEntityId
            FROM ContentDocumentLink
            WHERE
                ContentDocumentId = :document.ContentDocumentId
                AND LinkedEntityId = :ace.Id
            LIMIT 1
        ];
        System.assert(link != null);
        System.assertEquals(
            document.ContentDocumentId,
            result.ContentDocumentId
        );
        System.assertEquals(document.Title, result.Title);
        System.assertEquals(document.CreatedDate, result.CreatedDate);
    }

    @isTest
    public static void relateFiles_ThrowsException_WhenNullList() {
        Dog__c ace = new Dog__c(Name = 'Ace');
        insert ace;

        Boolean thrown = false;

        Test.startTest();
        try {
            FileController.relateFiles(null, ace.Id);
        } catch (AuraHandledException e) {
            thrown = true;
        }

        Test.stopTest();

        System.assert(thrown);
    }

    @isTest
    public static void relateFiles_ThrowsException_WhenNullId() {
        List<ContentVersion> documents = insertRecords();
        List<Id> docIds = new List<Id>();
        for (ContentVersion cv : documents) {
            docIds.add(cv.ContentDocumentId);
        }

        Boolean thrown = false;

        Test.startTest();
        try {
            FileController.relateFiles(docIds, null);
        } catch (AuraHandledException e) {
            thrown = true;
        }

        Test.stopTest();

        System.assert(thrown);
    }

    @isTest
    public static void relateFiles_DoesNothing_WhenNoRelatedDocuments() {
        Dog__c ace = new Dog__c(Name = 'Ace');
        insert ace;

        Test.startTest();
        FileController.relateFiles(new List<Id>(), ace.Id);
        Test.stopTest();

        List<ContentDocumentLink> links = [
            SELECT ContentDocumentId, LinkedEntityId
            FROM ContentDocumentLink
            WHERE LinkedEntityId = :ace.Id
        ];
        System.assert(links.isEmpty());
    }

    @isTest
    public static void relateFiles_RelatesDocuments() {
        Dog__c ace = new Dog__c(Name = 'Ace');
        insert ace;
        List<ContentVersion> documents = insertRecords();
        List<Id> docIds = new List<Id>();
        for (ContentVersion cv : documents) {
            docIds.add(cv.ContentDocumentId);
        }

        Test.startTest();
        FileController.relateFiles(docIds, ace.Id);
        Test.stopTest();

        List<ContentDocumentLink> links = [
            SELECT ContentDocumentId, LinkedEntityId
            FROM ContentDocumentLink
            WHERE LinkedEntityId = :ace.Id
        ];
        System.assertEquals(docIds.size(), links.size());
    }
}