force-app/main/default/objects/BackgroundCheck__c/BackgroundCheck__c.object-meta.xml
<CustomObject>
    <description>Background check record</description>
    <label>Background Check</label>
    <nameField>
        <displayFormat>BC-{0000}</displayFormat>
        <label>Background Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Background Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BackgroundCheck__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contact the background check is for</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Background Checks</relationshipLabel>
    <relationshipName>BackgroundChecks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BackgroundCheck__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date background check was requested</description>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BackgroundCheck__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Criminal</fullName>
                <default>true</default>
                <label>Criminal</label>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Place/person to contact this person</description>
    <inlineHelpText>Select Guardian to contact this person through their guardian, Home for personal email/phone</inlineHelpText>
    <label>Contact At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
                <default>true</default>
                <label>Home</label>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/VolunteerAccess__c.field-meta.xml
<CustomField>
    <fullName>VolunteerAccess__c</fullName>
    <label>Volunteer Access</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operations- Master Docs - READ ONLY</fullName>
            </value>
            <value>
                <fullName>Operations- Financial</fullName>
            </value>
            <value>
                <fullName>Operations- Client</fullName>
            </value>
            <value>
                <fullName>Operations- Volunteer and Staff</fullName>
            </value>
            <value>
                <fullName>Operations- Trainer</fullName>
            </value>
            <value>
                <fullName>Board - READ ONLY</fullName>
            </value>
            <value>
                <fullName>Board</fullName>
            </value>
            <value>
                <fullName>Sensitive Info- Volunteer and Staff</fullName>
            </value>
            <value>
                <fullName>Sensitive Info- Trainer</fullName>
            </value>
            <value>
                <fullName>Sensitive Info- Board</fullName>
            </value>
            <value>
                <fullName>Active Projects- Academy</fullName>
            </value>
            <value>
                <fullName>Active Projects- ADI</fullName>
            </value>
            <value>
                <fullName>Active Projects- Branding and Marketing</fullName>
            </value>
            <value>
                <fullName>Active Projects- Client Certification</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Community Outreach and Education</fullName>
                <label>Active Projects- Community Outreach and Education</label>
            </value>
            <value>
                <fullName>Active Projects- Dog Availability</fullName>
            </value>
            <value>
                <fullName>Active Projects- Fund Development</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Governance, Compliance and Operations</fullName>
                <label
                >Active Projects- Governance, Compliance and Operations</label>
            </value>
            <value>
                <fullName>Active Projects- Research and Development</fullName>
            </value>
            <value>
                <fullName>Active Projects- Scholarships</fullName>
            </value>
            <value>
                <fullName>Active Projects- State Registration</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Team Facilitator Certification</fullName>
                <label>Active Projects- Team Facilitator Certification</label>
            </value>
            <value>
                <fullName>Active Projects- Technology Infrastructure</fullName>
            </value>
            <value>
                <fullName>Active Projects- Trainer Certification</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Volunteer Recruitment and Retention</fullName>
                <label
                >Active Projects- Volunteer Recruitment and Retention</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contacts.recordType-meta.xml
<RecordType>
    <fullName>Contacts</fullName>
    <active>true</active>
    <label>Contacts</label>
</RecordType>

force-app/main/test/background-checks/TestBackgroundCheckService.cls
@isTest
public with sharing class TestBackgroundCheckService {
    private static MockProvider mocks;
    private static BackgroundCheckService service;
    private static ContactRepository contactRepo;
    private static BackgroundCheckRepository bgcRepo;
    private static TaskRepository taskRepo;
    // references to mocks
    
    private static void makeData(){
        mocks = new MockProvider();
        contactRepo = (ContactRepository)mocks.createMock(ContactRepository.class);
        bgcRepo = (BackgroundCheckRepository)mocks.createMock(BackgroundCheckRepository.class);
        taskRepo = (TaskRepository)mocks.createMock(TaskRepository.class);
        service = new BackgroundCheckService(bgcRepo, contactRepo, taskRepo);
    }

    private static final String[] contactIds = MockCallData.contactIds;
    private static final String[] bgcids = new String[]{
        'a11Oz000001M1EbIAK',
        'a11Oz000001M1EcIAK',
        'a11Oz000001M1EdIAK',
        'a11Oz000001M1EeIAK',
        'a11Oz000001M1EfIAK',
        'a11Oz000001M1EgIAK',
        'a11Oz000001M1EhIAK',
        'a11Oz000001M1EiIAK',
        'a11Oz000001M1EjIAK',
        'a11Oz000001M1EkIAK', 
        'a11Oz000001M1ElIAK' 
    };
    
    @isTest
    static void createReminderTask_createsNoTasksWhenNoContactsWithAccess() {
        makeData();
        mocks.expectedCalls.add(new MockCallData(contactRepo, 'getContactsNeedingBackgroundChecks', new List<Contact>()));
        mocks.expectedCalls.add(new MockCallData(bgcRepo, 'getMatchingChecksForContacts', new List<BackgroundCheck__c>()));
         // Act
        service.createReminderTask();
        
        // Assert
        System.assert(!mocks.actualCalls.isEmpty());
        // the first call would be to get contacts
        MockCallData getContacts = mocks.actualCalls[0];
        System.assertEquals('getContactsNeedingBackgroundChecks', getContacts.methodName);
        
        // see if there is a call to create tasks, if there is, there should be no tasks
        for (MockCallData call : mocks.actualCalls) {
            if (call.obj == taskRepo && call.methodName == 'create') {
                System.assert(((List<Task>)call.args[0]).isEmpty());
            }
        }
    }

    private static Contact[] createContactsWithAccess() {
        Contact[] contacts = new Contact[] {
            new Contact(
                Id = contactIds[0],
                FirstName = 'Bluey',
                LastName = 'Heeler',
                Email = 'bluey@test.com',
                VolunteerAccess__c = 'Credit Check Required'
            ),
            new Contact(
                Id = contactIds[1],
                FirstName = 'Bingo',
                LastName = 'Heeler',
                Email = 'bingo@test.com',
                VolunteerAccess__c = 'Background Check Required'
            ),
            new Contact(
                Id = contactIds[2],
                FirstName = 'Chilli',
                LastName = 'Heeler',
                Email = 'chilli@test.com',
                VolunteerAccess__c = 'Background Check Required'
            ),
            new Contact(
                Id = contactIds[3],
                FirstName = 'Bandit',
                LastName = 'Heeler',
                Email = 'bandit@test.com',
                VolunteerAccess__c = 'Background Check Required;Credit Check Required'
            )
        };

        return contacts;
    }

    @isTest
    public static void createReminderTask_createsTasksWhenContactsWithAccess() {
        makeData();
        mocks.expectedCalls.add(new MockCallData(contactRepo, 'getContactsNeedingBackgroundChecks', createContactsWithAccess()));
        mocks.expectedCalls.add(new MockCallData(bgcRepo, 'getMatchingChecksForContacts', new List<BackgroundCheck__c>()));
        // Act
        service.createReminderTask();

        // see if there is a call to create tasks, if there is, there should be no tasks
        for (MockCallData call : mocks.actualCalls) {
            if (call.obj == taskRepo && call.methodName == 'create') {
                System.assertEquals(5, ((List<Task>)call.args[0]).size());
            }
        }
    }

    @isTest
    public static void createReminderTask_createsNoTasksWhenContactsWithAccessUpToDate() {
        makeData();
        Contact[] contacts = createContactsWithAccess();
        mocks.expectedCalls.add(new MockCallData(contactRepo, 'getContactsNeedingBackgroundChecks', contacts));
        mocks.expectedCalls.add(new MockCallData(bgcRepo, 'getMatchingChecksForContacts', new List<BackgroundCheck__c>{
            new BackgroundCheck__c(Contact__c = contacts[0].id, Date__c = Date.today().addMonths(-3), Type__c = 'Credit'),
            new BackgroundCheck__c(Contact__c = contacts[1].id, Date__c = Date.today().addMonths(-4), Type__c = 'Criminal'),
            new BackgroundCheck__c(Contact__c = contacts[2].id, Date__c = Date.today().addMonths(-5), Type__c = 'Criminal'),
            new BackgroundCheck__c(Contact__c = contacts[3].id, Date__c = Date.today().addMonths(-6), Type__c = 'Credit'),
            new BackgroundCheck__c(Contact__c = contacts[3].id, Date__c = Date.today().addMonths(-7), Type__c = 'Criminal')
        }));
        // Act
        service.createReminderTask();

        // see if there is a call to create tasks, if there is, there should be no tasks
        for (MockCallData call : mocks.actualCalls) {
            if (call.obj == taskRepo && call.methodName == 'create') {
                System.assert(((List<Task>)call.args[0]).isEmpty());
            }
        }
    }

    @isTest
    public static void createReminderTask_createsTaskWhenContactWithAccessNeedsNew() {
        makeData();
        // Get the group to assign the task to
        Group adminGroup = [
            SELECT Id
            FROM Group
            WHERE Name = 'Background Check Administrator' AND Type = 'Queue'
        ];
        Contact[] contacts = createContactsWithAccess();
        Contact bandit = contacts[3];
        mocks.expectedCalls.add(new MockCallData(contactRepo, 'getContactsNeedingBackgroundChecks', contacts));
        mocks.expectedCalls.add(new MockCallData(bgcRepo, 'getMatchingChecksForContacts', new List<BackgroundCheck__c>{
            new BackgroundCheck__c(Contact__c = contacts[0].id, Date__c = Date.today().addMonths(-3), Type__c = 'Credit'),
            new BackgroundCheck__c(Contact__c = contacts[1].id, Date__c = Date.today().addMonths(-4), Type__c = 'Criminal'),
            new BackgroundCheck__c(Contact__c = contacts[2].id, Date__c = Date.today().addMonths(-5), Type__c = 'Criminal'),
            new BackgroundCheck__c(Contact__c = contacts[3].id, Date__c = Date.today().addMonths(-6), Type__c = 'Credit')
        }));
        // Act
        service.createReminderTask();

        // see if there is a call to create tasks, if there is, there should be no tasks
        for (MockCallData call : mocks.actualCalls) {
            if (call.obj == taskRepo && call.methodName == 'create') {
                System.assertEquals(1, ((List<Task>)call.args[0]).size());
                Task task = ((List<Task>)call.args[0])[0];
                System.assertEquals(bandit.Id, task.WhoId);
                System.assert(task.Subject.contains('Order background check'));
                System.assertEquals(adminGroup.Id, task.OwnerId);
                System.assertEquals(Date.today().addMonths(1), task.ActivityDate);
            }
        }
    }

    @isTest
    public static void createReminderTask_createsTaskWhenOtherContactWithAccessNeedsNew() {
        makeData();
        // Get the group to assign the task to
        Group adminGroup = [
            SELECT Id
            FROM Group
            WHERE Name = 'Background Check Administrator' AND Type = 'Queue'
        ];
        Contact[] contacts = createContactsWithAccess();
        Contact bandit = contacts[3];
        mocks.expectedCalls.add(new MockCallData(contactRepo, 'getContactsNeedingBackgroundChecks', contacts));
        mocks.expectedCalls.add(new MockCallData(bgcRepo, 'getMatchingChecksForContacts', new List<BackgroundCheck__c>{
            new BackgroundCheck__c(Contact__c = contacts[0].id, Date__c = Date.today().addMonths(-3), Type__c = 'Credit'),
            new BackgroundCheck__c(Contact__c = contacts[1].id, Date__c = Date.today().addMonths(-4), Type__c = 'Criminal'),
            new BackgroundCheck__c(Contact__c = contacts[2].id, Date__c = Date.today().addMonths(-5), Type__c = 'Criminal'),
            new BackgroundCheck__c(Contact__c = contacts[3].id, Date__c = Date.today().addMonths(-6), Type__c = 'Criminal')
        }));
        // Act
        service.createReminderTask();

        // see if there is a call to create tasks, if there is, there should be no tasks
        for (MockCallData call : mocks.actualCalls) {
            if (call.obj == taskRepo && call.methodName == 'create') {
                System.assertEquals(1, ((List<Task>)call.args[0]).size());
                Task task = ((List<Task>)call.args[0])[0];
                System.assertEquals(bandit.Id, task.WhoId);
                System.assert(task.Subject.contains('Order credit check'));
                System.assertEquals(adminGroup.Id, task.OwnerId);
                System.assertEquals(Date.today().addMonths(1), task.ActivityDate);
            }
        }
    }
  
}