force-app/main/default/objects/BackgroundCheck__c/BackgroundCheck__c.object-meta.xml
<CustomObject>
    <description>Background check record</description>
    <label>Background Check</label>
    <nameField>
        <displayFormat>BC-{0000}</displayFormat>
        <label>Background Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Background Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BackgroundCheck__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contact the background check is for</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Background Checks</relationshipLabel>
    <relationshipName>BackgroundChecks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BackgroundCheck__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date background check was requested</description>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BackgroundCheck__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BackgroundCheck__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Criminal</fullName>
                <default>true</default>
                <label>Criminal</label>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Place/person to contact this person</description>
    <inlineHelpText>Select Guardian to contact this person through their guardian, Home for personal email/phone</inlineHelpText>
    <label>Contact At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
                <default>true</default>
                <label>Home</label>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/VolunteerAccess__c.field-meta.xml
<CustomField>
    <fullName>VolunteerAccess__c</fullName>
    <label>Volunteer Access</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operations- Master Docs - READ ONLY</fullName>
            </value>
            <value>
                <fullName>Operations- Financial</fullName>
            </value>
            <value>
                <fullName>Operations- Client</fullName>
            </value>
            <value>
                <fullName>Operations- Volunteer and Staff</fullName>
            </value>
            <value>
                <fullName>Operations- Trainer</fullName>
            </value>
            <value>
                <fullName>Board - READ ONLY</fullName>
            </value>
            <value>
                <fullName>Board</fullName>
            </value>
            <value>
                <fullName>Sensitive Info- Volunteer and Staff</fullName>
            </value>
            <value>
                <fullName>Sensitive Info- Trainer</fullName>
            </value>
            <value>
                <fullName>Sensitive Info- Board</fullName>
            </value>
            <value>
                <fullName>Active Projects- Academy</fullName>
            </value>
            <value>
                <fullName>Active Projects- ADI</fullName>
            </value>
            <value>
                <fullName>Active Projects- Branding and Marketing</fullName>
            </value>
            <value>
                <fullName>Active Projects- Client Certification</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Community Outreach and Education</fullName>
                <label>Active Projects- Community Outreach and Education</label>
            </value>
            <value>
                <fullName>Active Projects- Dog Availability</fullName>
            </value>
            <value>
                <fullName>Active Projects- Fund Development</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Governance, Compliance and Operations</fullName>
                <label
                >Active Projects- Governance, Compliance and Operations</label>
            </value>
            <value>
                <fullName>Active Projects- Research and Development</fullName>
            </value>
            <value>
                <fullName>Active Projects- Scholarships</fullName>
            </value>
            <value>
                <fullName>Active Projects- State Registration</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Team Facilitator Certification</fullName>
                <label>Active Projects- Team Facilitator Certification</label>
            </value>
            <value>
                <fullName>Active Projects- Technology Infrastructure</fullName>
            </value>
            <value>
                <fullName>Active Projects- Trainer Certification</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Volunteer Recruitment and Retention</fullName>
                <label
                >Active Projects- Volunteer Recruitment and Retention</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/test/background-checks/TestBackgroundCheckRepository.cls
@isTest
private class TestBackgroundCheckRepository {

    @isTest
    static void getMatchingChecksForContacts_returnsEmpty_whenContactsIsNull() {
        BackgroundCheckRepository repo = new BackgroundCheckRepository();

        List<BackgroundCheck__c> result = repo.getMatchingChecksForContacts(null, null);

        System.assert(result.isEmpty());
    }
    @isTest
    static void getMatchingChecksForContacts_returnsEmpty_whenContactsIsEmpty() {
        BackgroundCheckRepository repo = new BackgroundCheckRepository();

        List<BackgroundCheck__c> result = repo.getMatchingChecksForContacts(new Set<Id>(), null);

        System.assert(result.isEmpty());
    }
    @isTest
    static void getMatchingChecksForContacts_returnsEmpty_whenContactsAndDateAreEmpty() {
        BackgroundCheckRepository repo = new BackgroundCheckRepository();

        List<BackgroundCheck__c> result = repo.getMatchingChecksForContacts(new Set<Id>(), Date.today());

        System.assert(result.isEmpty());
    }
    @isTest
    static void getMatchingChecksForContacts_returnsEmpty_whenContactsButNoBgChecks() {
        BackgroundCheckRepository repo = new BackgroundCheckRepository();
        List<Id> contactIds = MockCallData.contactids;

        List<BackgroundCheck__c> result = repo.getMatchingChecksForContacts(new Set<Id>(contactIds), Date.today());

        System.assert(result.isEmpty());
    }
    @isTest
    static void getMatchingChecksForContacts_returnsEmpty_whenCheckBeforeThreshold() {
        BackgroundCheckRepository repo = new BackgroundCheckRepository();
        Date threshold = Date.today().addMonths(-11);
        Contact bluey = new Contact(
            FirstName = 'Bluey',
            LastName = 'Heeler',
            Email = 'bluey@test.com',
            VolunteerAccess__c = 'Credit Check Required'
        );
        insert bluey;
        BackgroundCheck__c check = new BackgroundCheck__c(
            Contact__c = bluey.Id,
            Status__c = 'Pass',
            Type__c = 'Credit',
            Date__c = threshold.addDays(-1)
        );
        insert check;

        List<BackgroundCheck__c> result = repo.getMatchingChecksForContacts(new Set<Id>{ bluey.Id }, threshold);

        System.assert(result.isEmpty());
    }
    @isTest
    static void getMatchingChecksForContacts_returnsEmpty_whenCheckAtThreshold() {
        BackgroundCheckRepository repo = new BackgroundCheckRepository();
        Date threshold = Date.today().addMonths(-11);
        Contact bluey = new Contact(
            FirstName = 'Bluey',
            LastName = 'Heeler',
            Email = 'bluey@test.com',
            VolunteerAccess__c = 'Credit Check Required'
        );
        insert bluey;
        BackgroundCheck__c check = new BackgroundCheck__c(
            Contact__c = bluey.Id,
            Status__c = 'Pass',
            Type__c = 'Credit',
            Date__c = threshold
        );
        insert check;

        List<BackgroundCheck__c> result = repo.getMatchingChecksForContacts(new Set<Id>{ bluey.Id }, threshold);

        System.assert(result.isEmpty());
    }
    @isTest
    static void getMatchingChecksForContacts_returnsCheck_whenCheckAfterThreshold() {
        BackgroundCheckRepository repo = new BackgroundCheckRepository();
        Date threshold = Date.today().addMonths(-11);
        Contact bluey = new Contact(
            FirstName = 'Bluey',
            LastName = 'Heeler',
            Email = 'bluey@test.com',
            VolunteerAccess__c = 'Credit Check Required'
        );
        insert bluey;
        BackgroundCheck__c check = new BackgroundCheck__c(
            Contact__c = bluey.Id,
            Status__c = 'Pass',
            Type__c = 'Credit',
            Date__c = threshold.addDays(1)
        );
        insert check;

        List<BackgroundCheck__c> result = repo.getMatchingChecksForContacts(new Set<Id>{ bluey.Id }, threshold);

        System.assertEquals(1, result.size());
    }
    @isTest
    static void getMatchingChecksForContacts_returnsEmpty_whenTypeMisMatch() {
        BackgroundCheckRepository repo = new BackgroundCheckRepository();
        Date threshold = Date.today().addMonths(-11);
        Contact bluey = new Contact(
            FirstName = 'Bluey',
            LastName = 'Heeler',
            Email = 'bluey@test.com',
            VolunteerAccess__c = 'Credit Check Required'
        );
        Contact bingo = new Contact(
            FirstName = 'Bingo',
            LastName = 'Heeler',
            Email = 'bingo@test.com',
            VolunteerAccess__c = 'Background Check Required'
        );

        insert new Contact[]{ bluey, bingo };
        BackgroundCheck__c check1 = new BackgroundCheck__c(
            Contact__c = bluey.Id,
            Type__c = 'Criminal',
            Date__c = threshold.addDays(1)
        );
        BackgroundCheck__c check2 = new BackgroundCheck__c(
            Contact__c = bingo.Id,
            Type__c = 'Credit',
            Date__c = threshold.addDays(1)
        );
        insert new BackgroundCheck__c[] { check1, check2 };

        List<BackgroundCheck__c> result = repo.getMatchingChecksForContacts(new Set<Id>{ bingo.Id, bluey.Id }, threshold);

        System.assert(result.isEmpty());
    }
    @isTest
    static void getMatchingChecksForContacts_returnsCheck_whenTypeMatch() {
        BackgroundCheckRepository repo = new BackgroundCheckRepository();
        Date threshold = Date.today().addMonths(-11);
        Contact bluey = new Contact(
            FirstName = 'Bluey',
            LastName = 'Heeler',
            Email = 'bluey@test.com',
            VolunteerAccess__c = 'Credit Check Required'
        );
        Contact bingo = new Contact(
            FirstName = 'Bingo',
            LastName = 'Heeler',
            Email = 'bingo@test.com',
            VolunteerAccess__c = 'Background Check Required'
        );

        insert new Contact[]{ bluey, bingo };
        BackgroundCheck__c check1 = new BackgroundCheck__c(
            Contact__c = bingo.Id,
            Type__c = 'Criminal',
            Date__c = threshold.addDays(1)
        );
        BackgroundCheck__c check2 = new BackgroundCheck__c(
            Contact__c = bluey.Id,
            Type__c = 'Credit',
            Date__c = threshold.addDays(1)
        );
        insert new BackgroundCheck__c[] { check1, check2 };

        List<BackgroundCheck__c> result = repo.getMatchingChecksForContacts(new Set<Id>{ bingo.Id, bluey.Id }, threshold);

        System.assertEquals(2, result.size());
    }
    @isTest
    static void getMatchingChecksForContacts_returnsCheck_whenBothRequired() {
        BackgroundCheckRepository repo = new BackgroundCheckRepository();
        Date threshold = Date.today().addMonths(-11);
        Contact bluey = new Contact(
            FirstName = 'Bluey',
            LastName = 'Heeler',
            Email = 'bluey@test.com',
            VolunteerAccess__c = 'Credit Check Required;Background Check Required'
        );
        insert bluey;
        BackgroundCheck__c check = new BackgroundCheck__c(
            Contact__c = bluey.Id,
            Status__c = 'Pass',
            Type__c = 'Credit',
            Date__c = threshold.addDays(1)
        );
        insert check;

        List<BackgroundCheck__c> result = repo.getMatchingChecksForContacts(new Set<Id>{ bluey.Id }, threshold);

        System.assertEquals(1, result.size());
    }
    @isTest
    static void getMatchingChecksForContacts_returnsCriminalCheck_whenBothRequired() {
        BackgroundCheckRepository repo = new BackgroundCheckRepository();
        Date threshold = Date.today().addMonths(-11);
        Contact bluey = new Contact(
            FirstName = 'Bluey',
            LastName = 'Heeler',
            Email = 'bluey@test.com',
            VolunteerAccess__c = 'Credit Check Required;Background Check Required'
        );
        insert bluey;
        BackgroundCheck__c check = new BackgroundCheck__c(
            Contact__c = bluey.Id,
            Status__c = 'Pass',
            Type__c = 'Criminal',
            Date__c = threshold.addDays(1)
        );
        insert check;

        List<BackgroundCheck__c> result = repo.getMatchingChecksForContacts(new Set<Id>{ bluey.Id }, threshold);

        System.assertEquals(1, result.size());
    }
    @isTest
    static void getMatchingChecksForContacts_returnsChecks_whenBothRequired() {
        BackgroundCheckRepository repo = new BackgroundCheckRepository();
        Date threshold = Date.today().addMonths(-11);
        Contact bluey = new Contact(
            FirstName = 'Bluey',
            LastName = 'Heeler',
            Email = 'bluey@test.com',
            VolunteerAccess__c = 'Credit Check Required;Background Check Required'
        );
        insert bluey;
        BackgroundCheck__c[] checks = new BackgroundCheck__c[]{
            new BackgroundCheck__c(
                Contact__c = bluey.Id,
                Status__c = 'Pass',
                Type__c = 'Credit',
                Date__c = threshold.addDays(1)
            ),
            new BackgroundCheck__c(
                Contact__c = bluey.Id,
                Status__c = 'Pass',
                Type__c = 'Criminal',
                Date__c = threshold.addDays(1)
            )
        };
        insert checks;

        List<BackgroundCheck__c> result = repo.getMatchingChecksForContacts(new Set<Id>{ bluey.Id }, threshold);

        System.assertEquals(2, result.size());
    }
}