force-app/main/default/objects/BackgroundCheck__c/BackgroundCheck__c.object-meta.xml
<CustomObject>
    <description>Background check record</description>
    <label>Background Check</label>
    <nameField>
        <displayFormat>BC-{0000}</displayFormat>
        <label>Background Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Background Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BackgroundCheck__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contact the background check is for</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Background Checks</relationshipLabel>
    <relationshipName>BackgroundChecks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BackgroundCheck__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date background check was requested</description>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BackgroundCheck__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BackgroundCheck__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Criminal</fullName>
                <default>true</default>
                <label>Criminal</label>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/background-checks/BackgroundCheckController.cls
public with sharing class BackgroundCheckController {
  // This method is used by the related list component, and needs more than just the background check
  @AuraEnabled(Cacheable=true)
  public static RelatedObjects getRelatedChecks(Id contactId, Integer max) {
    if (max == null) {
      max = 6;
    }
    try {
      RelatedObjects related = new RelatedObjects();
      List<BackgroundCheck__c> checks = [
        SELECT Name, Contact__c, Date__c, Notes__c, Status__c, Type__c
        FROM BackgroundCheck__c
        WHERE Contact__c = :contactId
        LIMIT :max
      ];
            related.total = [
                SELECT COUNT()
                FROM BackgroundCheck__c
                WHERE Contact__c = :contactId
            ];

      for (BackgroundCheck__c bgc : checks) {
        BackgroundCheck outCheck = new BackgroundCheck();
        outCheck.check = bgc;
        outCheck.noFile = true;
        RelatedObjects files = FileController.getAllRelatedFiles(bgc.Id, 1);
        if (files != null && !files.items.isEmpty()) {
                    FileInfo info = (FileInfo)files.items[0];
          outCheck.documentId = info.cv.ContentDocumentId;
          outCheck.fileName = info.cv.Title;
          outCheck.noFile = false;
        }
        related.items.add(outCheck);
      }
      return related;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}