force-app/main/default/objects/BackgroundCheck__c/BackgroundCheck__c.object-meta.xml
<CustomObject>
    <description>Background check record</description>
    <label>Background Check</label>
    <nameField>
        <displayFormat>BC-{0000}</displayFormat>
        <label>Background Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Background Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BackgroundCheck__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contact the background check is for</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Background Checks</relationshipLabel>
    <relationshipName>BackgroundChecks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BackgroundCheck__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date background check was requested</description>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BackgroundCheck__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BackgroundCheck__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Criminal</fullName>
                <default>true</default>
                <label>Criminal</label>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Place/person to contact this person</description>
    <inlineHelpText>Select Guardian to contact this person through their guardian, Home for personal email/phone</inlineHelpText>
    <label>Contact At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
                <default>true</default>
                <label>Home</label>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/VolunteerAccess__c.field-meta.xml
<CustomField>
    <fullName>VolunteerAccess__c</fullName>
    <label>Volunteer Access</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operations- Master Docs - READ ONLY</fullName>
            </value>
            <value>
                <fullName>Operations- Financial</fullName>
            </value>
            <value>
                <fullName>Operations- Client</fullName>
            </value>
            <value>
                <fullName>Operations- Volunteer and Staff</fullName>
            </value>
            <value>
                <fullName>Operations- Trainer</fullName>
            </value>
            <value>
                <fullName>Board - READ ONLY</fullName>
            </value>
            <value>
                <fullName>Board</fullName>
            </value>
            <value>
                <fullName>Sensitive Info- Volunteer and Staff</fullName>
            </value>
            <value>
                <fullName>Sensitive Info- Trainer</fullName>
            </value>
            <value>
                <fullName>Sensitive Info- Board</fullName>
            </value>
            <value>
                <fullName>Active Projects- Academy</fullName>
            </value>
            <value>
                <fullName>Active Projects- ADI</fullName>
            </value>
            <value>
                <fullName>Active Projects- Branding and Marketing</fullName>
            </value>
            <value>
                <fullName>Active Projects- Client Certification</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Community Outreach and Education</fullName>
                <label>Active Projects- Community Outreach and Education</label>
            </value>
            <value>
                <fullName>Active Projects- Dog Availability</fullName>
            </value>
            <value>
                <fullName>Active Projects- Fund Development</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Governance, Compliance and Operations</fullName>
                <label
                >Active Projects- Governance, Compliance and Operations</label>
            </value>
            <value>
                <fullName>Active Projects- Research and Development</fullName>
            </value>
            <value>
                <fullName>Active Projects- Scholarships</fullName>
            </value>
            <value>
                <fullName>Active Projects- State Registration</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Team Facilitator Certification</fullName>
                <label>Active Projects- Team Facilitator Certification</label>
            </value>
            <value>
                <fullName>Active Projects- Technology Infrastructure</fullName>
            </value>
            <value>
                <fullName>Active Projects- Trainer Certification</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Volunteer Recruitment and Retention</fullName>
                <label
                >Active Projects- Volunteer Recruitment and Retention</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contacts.recordType-meta.xml
<RecordType>
    <fullName>Contacts</fullName>
    <active>true</active>
    <label>Contacts</label>
</RecordType>

force-app/main/default/objects/ContentVersion/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Document Date</description>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PreApplication</fullName>
                <label>Pre Application</label>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>ContactForm</fullName>
                <label>Contact Form</label>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>CoI</fullName>
                <label>Conflict of Interest</label>
            </value>
            <value>
                <fullName>ToN</fullName>
                <label>Transmission of Notices</label>
            </value>
            <value>
                <fullName>LOMI</fullName>
                <label>Medical Provider Form</label>
            </value>
            <value>
                <fullName>Media</fullName>
                <label>Media Release</label>
            </value>
            <value>
                <fullName>VAPW</fullName>
                <label>Veteran Paperwork</label>
            </value>
            <value>
                <fullName>Survey</fullName>
                <label>Certification Survey</label>
            </value>
            <value>
                <fullName>Reference</fullName>
                <label>Reference Letter</label>
            </value>
            <value>
                <fullName>ClientReference</fullName>
                <label>Client Reference Letter</label>
            </value>
            <value>
                <fullName>ProfReference</fullName>
                <label>Professional Reference Letter</label>
            </value>
            <value>
                <fullName>ProgAgreement</fullName>
                <label>Program Agreement</label>
            </value>
            <value>
                <fullName>CertAgreement</fullName>
                <label>Certification Agreement</label>
            </value>
            <value>
                <fullName>Practicum</fullName>
            </value>
            <value>
                <fullName>InfrNotice</fullName>
                <label>Infraction Notice</label>
            </value>
            <value>
                <fullName>HealthForm</fullName>
                <label>Vet Health Form</label>
            </value>
            <value>
                <fullName>Notes</fullName>
                <label>Interview Notes</label>
            </value>
            <value>
                <fullName>Xray</fullName>
                <label>Vet Xray Report</label>
            </value>
            <value>
                <fullName>VacExams</fullName>
                <label>Vaccinations and Exams</label>
            </value>
            <value>
                <fullName>Resume</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
                <label>Offer Letter</label>
            </value>
            <value>
                <fullName>W4</fullName>
            </value>
            <value>
                <fullName>I9</fullName>
            </value>
            <value>
                <fullName>W9</fullName>
                <label>Contractor W9</label>
            </value>
            <value>
                <fullName>ApplicationVideo</fullName>
                <label>Application Video</label>
            </value>
            <value>
                <fullName>CGCForm</fullName>
                <label>CGC Form</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/test/TestBackgroundCheckController.cls
@isTest
public class TestBackgroundCheckController {
    @isTest
    public static void getRelatedChecks_ReturnsEmptyList_WhenNone() {
        Contact contact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            Email = 'test@test.com'
        );
        insert contact;

        Test.startTest();
        RelatedObjects checks = BackgroundCheckController.getRelatedChecks(
            contact.Id,
            6
        );
        Test.stopTest();

        System.assertEquals(0, checks.items.size());
        System.assertEquals(0, checks.total);
    }

    private static Contact jack;
    private static Contact jill;

    private static void insertContacts() {
        List<Contact> contacts = new List<Contact>();
        contacts.add(
            new Contact(
                FirstName = 'Jack',
                LastName = 'Contact',
                Email = 'jack@test.com',
                VolunteerAccess__c = ''
            )
        );
        contacts.add(
            new Contact(
                FirstName = 'Jill',
                LastName = 'Contact',
                Email = 'jill@test.com',
                VolunteerAccess__c = ''
            )
        );
        insert contacts;

        jack = contacts[0];
        jill = contacts[1];
    }

    private static void insertContactsWithAccess() {
        jack = new Contact(
            FirstName = 'Jack',
            LastName = 'Contact',
            Email = 'jack@test.com',
            VolunteerAccess__c = 'Credit Check Required'
        );

        jill = new Contact(
            FirstName = 'Jill',
            LastName = 'Contact',
            Email = 'jill@test.com',
            VolunteerAccess__c = 'Background Check Required'
        );

        insert new List<Contact>{ jack, jill };
    }

    @isTest
    public static void getRelatedChecks_ReturnsEmptyList_WhenNoneForThisContact() {
        insertContacts();

        BackgroundCheck__c bgCheck = new BackgroundCheck__c(
            Contact__c = jill.Id,
            Date__c = Date.today(),
            Status__c = 'Pass'
        );
        insert bgCheck;

        Test.startTest();
        RelatedObjects checks = BackgroundCheckController.getRelatedChecks(
            jack.Id,
            6
        );
        Test.stopTest();

        System.assertEquals(0, checks.items.size());
        System.assertEquals(0, checks.total);
    }

    @isTest
    public static void getRelatedChecks_ReturnsList_WhenOneForThisContact() {
        insertContacts();

        BackgroundCheck__c bgCheck = new BackgroundCheck__c(
            Contact__c = jill.Id,
            Date__c = Date.today(),
            Status__c = 'Pass'
        );
        insert bgCheck;

        Test.startTest();
        RelatedObjects checks = BackgroundCheckController.getRelatedChecks(
            jill.Id,
            6
        );
        Test.stopTest();

        System.assertEquals(1, checks.items.size());
        System.assertEquals(1, checks.total);
        BackgroundCheck__c check = ((BackgroundCheck) checks.items[0]).check;
        System.assertEquals(bgCheck.Date__c, check.Date__c);
        System.assertEquals('Criminal', check.Type__c);
        System.assertEquals('Pass', check.Status__c);
    }

    @isTest
    public static void getRelatedChecks_IncludesRelatedFile() {
        insertContacts();

        BackgroundCheck__c bgCheck = new BackgroundCheck__c(
            Contact__c = jill.Id,
            Date__c = Date.today(),
            Status__c = 'Pass',
            Type__c = 'Credit'
        );
        insert bgCheck;

        ContentVersion document = new ContentVersion(
            Title = 'TestDocument',
            PathOnClient = 'TestDocument.jpg',
            Origin = 'H',
            VersionData = Blob.valueOf('Document Body')
        );
        insert document;

        Id contentDocumentId = [
            SELECT ContentDocumentId
            FROM ContentVersion
            WHERE Id = :document.Id
        ]
        .ContentDocumentId;
        FileController.relateFile(contentDocumentId, bgCheck.Id, Date.today());

        Test.startTest();
        RelatedObjects checks = BackgroundCheckController.getRelatedChecks(
            jill.Id,
            6
        );
        Test.stopTest();

        System.assertEquals(1, checks.items.size());
        System.assertEquals(1, checks.total);
        BackgroundCheck info = (BackgroundCheck) checks.items[0];
        BackgroundCheck__c check = info.check;
        System.assertEquals(contentDocumentId, info.documentId);
        System.assertEquals('Pass', check.Status__c);
        System.assertEquals('Credit', check.Type__c);
        System.assertEquals(Date.today(), check.Date__c);
        System.assertEquals(document.Title, info.fileName);
    }

    @isTest
    public static void createReminderTask_createsNoTasksWhenNoContactsWithAccess() {
        insertContacts();

        Test.startTest();
        BackgroundCheckController.createReminderTask();
        Test.stopTest();

        Task[] tasks = [SELECT Id FROM Task];
        System.assertEquals(0, tasks.size());
    }

    @isTest
    public static void createReminderTask_createsTasksWhenContactsWithAccess() {
        insertContactsWithAccess();

        Test.startTest();
        BackgroundCheckController.createReminderTask();
        Test.stopTest();

        Task[] tasks = [SELECT Id FROM Task];
        System.assertEquals(2, tasks.size());
    }

    @isTest
    public static void createReminderTask_createsNoTasksWhenContactsWithAccessUpToDate() {
        insertContactsWithAccess();
        update new List<Contact>{ jill, jack };

        List<BackgroundCheck__c> bgChecks = new List<BackgroundCheck__c> {
            new BackgroundCheck__c(
            Contact__c = jill.Id,
            Date__c = Date.today().addMonths(-10),
            Status__c = 'Pass',
            Type__c = 'Credit'
        ),
        new BackgroundCheck__c(
            Contact__c = jack.Id,
            Date__c = Date.today().addMonths(-9),
            Status__c = 'Pass',
            Type__c = 'Criminal'
        )};
        insert bgChecks;

        Test.startTest();
        BackgroundCheckController.createReminderTask();
        Test.stopTest();

        Task[] tasks = [SELECT Id FROM Task];
        System.assertEquals(0, tasks.size());
    }

    @isTest
    public static void createReminderTask_createsTaskWhenContactWithAccessNeedsNew() {
        insertContactsWithAccess();
        update new List<Contact>{ jill, jack };
        Group adminGroup = [SELECT Id FROM Group WHERE Name = 'Background Check Administrator' AND Type = 'Queue'];

        List<BackgroundCheck__c> bgChecks = new List<BackgroundCheck__c> {
            new BackgroundCheck__c(
            Contact__c = jill.Id,
            Date__c = Date.today().addMonths(-12),
            Status__c = 'Pass',
            Type__c = 'Credit'
        ),
        new BackgroundCheck__c(
            Contact__c = jack.Id,
            Date__c = Date.today().addMonths(-9),
            Status__c = 'Pass',
            Type__c = 'Criminal'
        )};
        insert bgChecks;

        Test.startTest();
        BackgroundCheckController.createReminderTask();
        Test.stopTest();

        Task[] tasks = [SELECT Id, OwnerId, Subject, WhoId, ActivityDate FROM Task];
        System.assertEquals(1, tasks.size());
        Task reminder = tasks[0];
        System.assertEquals(jill.Id, reminder.WhoId);
        System.assert(reminder.Subject.contains('Order background check'));
        System.assertEquals(adminGroup.Id, reminder.OwnerId);
        System.assertEquals(Date.today().addMonths(1), reminder.ActivityDate);
    }

    @isTest
    public static void createReminderTask_createsTaskWhenOtherContactWithAccessNeedsNew() {
        insertContactsWithAccess();
        update new List<Contact>{ jill, jack };
        Group adminGroup = [SELECT Id FROM Group WHERE Name = 'Background Check Administrator' AND Type = 'Queue'];

        List<BackgroundCheck__c> bgChecks = new List<BackgroundCheck__c> {
            new BackgroundCheck__c(
            Contact__c = jill.Id,
            Date__c = Date.today().addMonths(-10),
            Status__c = 'Pass',
            Type__c = 'Credit'
        ),
        new BackgroundCheck__c(
            Contact__c = jack.Id,
            Date__c = Date.today().addMonths(-11).addDays(-1),
            Status__c = 'Pass',
            Type__c = 'Criminal'
        )};
        insert bgChecks;

        Test.startTest();
        BackgroundCheckController.createReminderTask();
        Test.stopTest();

        Task[] tasks = [SELECT Id, OwnerId, Subject, WhoId, ActivityDate FROM Task];
        System.assertEquals(1, tasks.size());
        Task reminder = tasks[0];
        System.assertEquals(jack.Id, reminder.WhoId);
        System.assert(reminder.Subject.contains('Order background check'));
        System.assertEquals(adminGroup.Id, reminder.OwnerId);
        System.assertEquals(Date.today().addMonths(1), reminder.ActivityDate);
    }
}