force-app/main/default/objects/AtlasSettings__c/AtlasSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for the Atlas Assistance Dogs app</description>
    <label>Atlas Settings</label>
</CustomObject>

force-app/main/default/objects/Contact/fields/Positions__c.field-meta.xml
<CustomField>
    <fullName>Positions__c</fullName>
    <description>Positions available</description>
    <label>Positions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Positions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/StaffStatus__c.field-meta.xml
<CustomField>
    <fullName>StaffStatus__c</fullName>
    <label>Staff Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/TrainerCertAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>TrainerCertAgreementReceived__c</fullName>
    <description>The date the most recent version of Trainer Certification Agreement was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Trainer Certification Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TrainerCertValidUntil__c.field-meta.xml
<CustomField>
    <fullName>TrainerCertValidUntil__c</fullName>
    <description>The date the Trainer Certification is valid to</description>
    <label>Trainer Certification Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TrainerInitialCertificationDate__c.field-meta.xml
<CustomField>
    <fullName>TrainerInitialCertificationDate__c</fullName>
    <description>Date that the Trainer was first certified.</description>
    <label>Trainer Initial Certification Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/globalValueSets/Positions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Volunteer</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Board Member</fullName>
    </customValue>
    <customValue>
        <fullName>Trainer</fullName>
    </customValue>
    <customValue>
        <fullName>Client</fullName>
    </customValue>
    <customValue>
        <fullName>Donor</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
        <label>Staff/Contractor</label>
    </customValue>
    <customValue>
        <fullName>Puppy Raiser</fullName>
    </customValue>
    <customValue>
        <fullName>Standalone</fullName>
    </customValue>
    <customValue>
        <fullName>TSiM</fullName>
    </customValue>
    <description>Positions a contact can have</description>
    <masterLabel>Positions</masterLabel>
</GlobalValueSet>

force-app/main/test/contacts/TestContactService.cls
@isTest
private class TestContactService {
  private static MockProvider mocks;
  private static ContactService service;
  private static ContactRepository contactRepo;
  private static RelationshipRepository relationshipRepo;
  private static EmailService emailSrv;
  private static CertificationRepository certRepo;
  // references to mocks

  private static void makeData() {
    mocks = new MockProvider();
    contactRepo = (ContactRepository) mocks.createMock(ContactRepository.class);
    relationshipRepo = (RelationshipRepository) mocks.createMock(
      RelationshipRepository.class
    );
    emailSrv = (EmailService) mocks.createMock(EmailService.class);
    certRepo = (CertificationRepository) mocks.createMock(CertificationRepository.class);
    service = new ContactService(contactRepo, relationshipRepo, emailSrv, certRepo);
  }

  @isTest
  static void getPositionStatusForContact_returnsEmptyList_whenNoPositions() {
    makeData();
    mocks.expectedCalls.add(
      new MockCallData(
        contactRepo,
        'getPositionStatusForContact',
        new Contact()
      )
    );
    // Act
    List<PositionStatus> result = service.getPositionStatusForContact(
      MockProvider.contactids[0]
    );
    // Assert
    System.assert(result.isEmpty());
  }

  @isTest
  static void getPositionStatusForContact_returnsActive_whenStaffEmployee() {
    makeData();
    mocks.expectedCalls.add(
      new MockCallData(
        contactRepo,
        'getPositionStatusForContact',
        new Contact(Positions__c = 'Staff', StaffStatus__c = 'Employee')
      )
    );
    // Act
    List<PositionStatus> result = service.getPositionStatusForContact(
      MockProvider.contactids[0]
    );
    // Assert
    System.assertEquals(1, result.size());
    PositionStatus actual = result[0];
    System.assertEquals('Staff', actual.position);
    System.assertEquals('Active', actual.status);
  }

  @isTest
  static void getPositionStatusForContact_returnsActive_whenStaffContractor() {
    makeData();
    mocks.expectedCalls.add(
      new MockCallData(
        contactRepo,
        'getPositionStatusForContact',
        new Contact(Positions__c = 'Staff', StaffStatus__c = 'Contractor')
      )
    );
    // Act
    List<PositionStatus> result = service.getPositionStatusForContact(
      MockProvider.contactids[0]
    );
    // Assert
    System.assertEquals(1, result.size());
    PositionStatus actual = result[0];
    System.assertEquals('Staff', actual.position);
    System.assertEquals('Active', actual.status);
  }

  @isTest
  static void getPositionStatusForContact_returnsInactive_whenStaffInactive() {
    makeData();
    mocks.expectedCalls.add(
      new MockCallData(
        contactRepo,
        'getPositionStatusForContact',
        new Contact(Positions__c = 'Staff', StaffStatus__c = 'Inactive')
      )
    );
    // Act
    List<PositionStatus> result = service.getPositionStatusForContact(
      MockProvider.contactids[0]
    );
    // Assert
    System.assertEquals(1, result.size());
    PositionStatus actual = result[0];
    System.assertEquals('Staff', actual.position);
    System.assertEquals('Inactive', actual.status);
  }

  @isTest
  static void getPositionStatusForContact_returnsNone_whenStaffNone() {
    makeData();
    mocks.expectedCalls.add(
      new MockCallData(
        contactRepo,
        'getPositionStatusForContact',
        new Contact(Positions__c = 'Staff', StaffStatus__c = 'None')
      )
    );
    // Act
    List<PositionStatus> result = service.getPositionStatusForContact(
      MockProvider.contactids[0]
    );
    // Assert
    System.assertEquals(1, result.size());
    PositionStatus actual = result[0];
    System.assertEquals('Staff', actual.position);
    System.assertEquals('None', actual.status);
  }
/*
  @isTest
  static void updateCertValidUntil_changesTrainerCertValidUntil_when30daysBefore() {
    AtlasSettings__c settings = AtlasSettings__c.getOrgDefaults();
    upsert settings;
    Date received = Date.newInstance(2022, 12, 25);

    Contact joe = new Contact(
      Id = MockCallData.contactids[0],
      Email = 'joe-blow@pump.com',
      FirstName = 'Joe',
      LastName = 'Blow',
      Positions__c = 'Trainer',
      TrainerInitialCertificationDate__c = received,
      TrainerCertAgreementReceived__c = received,
      TrainerCertValidUntil__c = received.addYears(1)
    );

    joe.TrainerCertAgreementReceived__c = received.addYears(1).addDays(-30);

    // Act
    Test.startTest();
    Database.SaveResult result = Database.update(joe, true);
    Test.stopTest();

    // Assert
    System.assert(result.isSuccess());
    Contact saved = [
      SELECT id, TrainerInitialCertificationDate__c, TrainerCertValidUntil__c
      FROM Contact
      WHERE id = :result.getId()
    ];
    System.assert(result.getErrors().size() == 0);
    System.assertEquals(received, saved.TrainerInitialCertificationDate__c);
    System.assertEquals(received.addYears(2), saved.TrainerCertValidUntil__c);
  }*/
}