force-app/main/default/objects/AtlasSettings__c/AtlasSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for the Atlas Assistance Dogs app</description>
    <label>Atlas Settings</label>
</CustomObject>

force-app/main/default/objects/AtlasSettings__c/fields/DogExamRenewalYears__c.field-meta.xml
<CustomField>
    <fullName>DogExamRenewalYears__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Years between dog physical exams</description>
    <label>Dog Exam Renewal Years</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AtlasSettings__c/fields/RabiesRenewalYears__c.field-meta.xml
<CustomField>
    <fullName>RabiesRenewalYears__c</fullName>
    <defaultValue>3</defaultValue>
    <description>Years before a rabies vaccine needs to be renewed.</description>
    <label>Rabies Renewal Years</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AtlasSettings__c/fields/VaccineRenewalYears__c.field-meta.xml
<CustomField>
    <fullName>VaccineRenewalYears__c</fullName>
    <defaultValue>1</defaultValue>
    <description
    >Years before a vaccine needs to be renewed since the last dose</description>
    <label>Vaccine Renewal Years</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dog__c/fields/PhysicalExamDue__c.field-meta.xml
<CustomField>
    <fullName>PhysicalExamDue__c</fullName>
    <description>Date the next physical examination is due</description>
    <label>Physical Exam Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/PhysicalExamLatest__c.field-meta.xml
<CustomField>
    <fullName>PhysicalExamLatest__c</fullName>
    <description>Most recent Physical exam</description>
    <inlineHelpText>Most recent Physical exam</inlineHelpText>
    <label>Most Recent Physical Exam</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/VaccineDueDistemper__c.field-meta.xml
<CustomField>
    <fullName>VaccineDueDistemper__c</fullName>
    <description>Date next Distemper vaccination is due</description>
    <label>Distemper Vaccine Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/VaccineDueHepatitis__c.field-meta.xml
<CustomField>
    <fullName>VaccineDueHepatitis__c</fullName>
    <description>Date next Hepatitis/Adenovirus vaccination is due</description>
    <label>Hepatitis/Adenovirus Vaccination Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/VaccineDueParainfluenza__c.field-meta.xml
<CustomField>
    <fullName>VaccineDueParainfluenza__c</fullName>
    <description>Date next Parainfluenza vaccine is due</description>
    <label>Parainfluenza Vaccine Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/VaccineDueParvovirus__c.field-meta.xml
<CustomField>
    <fullName>VaccineDueParvovirus__c</fullName>
    <description>Date next Parvovirus vaccination is due</description>
    <label>Parvovirus Vaccine Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/VaccineDueRabies__c.field-meta.xml
<CustomField>
    <fullName>VaccineDueRabies__c</fullName>
    <description>Date next Rabies vaccination is due</description>
    <label>Rabies Vaccine Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/VaccineLatestDistemper__c.field-meta.xml
<CustomField>
    <fullName>VaccineLatestDistemper__c</fullName>
    <description>Most recent distemper vaccination date</description>
    <inlineHelpText>Most Recent Distemper Vaccine</inlineHelpText>
    <label>Most Recent Distemper Vaccine</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/VaccineLatestHepatitis__c.field-meta.xml
<CustomField>
    <fullName>VaccineLatestHepatitis__c</fullName>
    <description>Most recent Hepatitis/Adenovirus vaccination date</description>
    <inlineHelpText
    >Latest  Hepatitis/Adenovirus vaccination date</inlineHelpText>
    <label>Most Recent Hepatitis Vaccine</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/VaccineLatestParainfluenza__c.field-meta.xml
<CustomField>
    <fullName>VaccineLatestParainfluenza__c</fullName>
    <description>Most recent Parainfluenza vaccination date</description>
    <inlineHelpText>Most recent Parainfluenza vaccine Date</inlineHelpText>
    <label>Most Recent Parainfluenza Vaccine</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/VaccineLatestParvovirus__c.field-meta.xml
<CustomField>
    <fullName>VaccineLatestParvovirus__c</fullName>
    <description>Most recent Parvovirus vaccine date</description>
    <inlineHelpText>Most recent Parvovirus Vaccine date</inlineHelpText>
    <label>Most Recent Parvovirus Vaccine</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/VaccineLatestRabies__c.field-meta.xml
<CustomField>
    <fullName>VaccineLatestRabies__c</fullName>
    <description>Most Recent Rabies vaccination Date</description>
    <inlineHelpText>Most recent Rabies vaccination date</inlineHelpText>
    <label>Most Recent Rabies Vaccine</label>
    <type>Date</type>
</CustomField>

force-app/main/test/TestDogTrigger.cls
@isTest
public with sharing class TestDogTrigger {
    public TestDogTrigger() {
    }

    @isTest
    static void TestInsertDogWithLatestVaccinesAndExam() {
        // Arrange
        // Create a Dog__c with all latest shots and exam
        Date exam = Date.newInstance(2021, 1, 10);
        Dog__c dog = new Dog__c(
            Name = 'Labrador',
            VaccineLatestDistemper__c = exam,
            VaccineLatestHepatitis__c = exam,
            VaccineLatestParainfluenza__c = exam,
            VaccineLatestParvovirus__c = exam,
            VaccineLatestRabies__c = exam,
            PhysicalExamLatest__c = exam
        );

        AtlasSettings__c settings = new AtlasSettings__c();
        upsert settings;

        // Act
        Test.startTest();
        Database.SaveResult result = Database.insert(dog, false);
        Test.stopTest();

        // Assert
        settings = AtlasSettings__c.getOrgDefaults();
        System.assert(result.isSuccess());
        Dog__c saved = [
            SELECT
                VaccineDueDistemper__c,
                VaccineDueHepatitis__c,
                VaccineDueParainfluenza__c,
                VaccineDueParvovirus__c,
                VaccineDueRabies__c,
                PhysicalExamDue__c
            FROM Dog__c
            WHERE id = :result.getId()
        ][0];
        Date vaccineDue = exam.addYears(
            (Integer) settings.VaccineRenewalYears__c
        );
        System.assert(result.getErrors().size() == 0);
        System.assertEquals(vaccineDue, saved.VaccineDueDistemper__c);
        System.assertEquals(vaccineDue, saved.VaccineDueHepatitis__c);
        System.assertEquals(vaccineDue, saved.VaccineDueParainfluenza__c);
        System.assertEquals(vaccineDue, saved.VaccineDueParvovirus__c);
        System.assertEquals(
            exam.addYears((Integer) settings.RabiesRenewalYears__c),
            saved.VaccineDueRabies__c
        );
        System.assertEquals(
            exam.addYears((Integer) settings.DogExamRenewalYears__c),
            saved.PhysicalExamDue__c
        );
    }

    @isTest
    static void TestInsertDogWithNoSettings() {
        // Test data setup
        // Create a Dog__c with all latest shots and exam, but settings not created yet
        Date exam = Date.newInstance(2021, 1, 10);
        Dog__c dog = new Dog__c(
            Name = 'Labrador',
            VaccineLatestDistemper__c = exam,
            VaccineLatestHepatitis__c = exam,
            VaccineLatestParainfluenza__c = exam,
            VaccineLatestParvovirus__c = exam,
            VaccineLatestRabies__c = exam,
            PhysicalExamLatest__c = exam
        );

        // Act
        Test.startTest();
        Database.SaveResult result = Database.insert(dog, false);
        Test.stopTest();

        // Assert
        System.assert(result.isSuccess());
        AtlasSettings__c settings = AtlasSettings__c.getOrgDefaults();
        System.assertNotEquals(null, settings);
    }
}