force-app/main/default/objects/AtlasSettings__c/AtlasSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for the Atlas Assistance Dogs app</description>
    <label>Atlas Settings</label>
</CustomObject>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Place/person to contact this person</description>
    <inlineHelpText>Select Guardian to contact this person through their guardian, Home for personal email/phone</inlineHelpText>
    <label>Contact At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
                <default>true</default>
                <label>Home</label>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>This field is configured in NPSP Settings &gt; Relationships &gt; Relationships as the Gender field. Do not delete this field unless you remove the reference or select another Gender field there.</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Positions__c.field-meta.xml
<CustomField>
    <fullName>Positions__c</fullName>
    <description>Positions available</description>
    <label>Positions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Positions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/PreferredName__c.field-meta.xml
<CustomField>
    <fullName>PreferredName__c</fullName>
    <description>Contact Preferred Name</description>
    <inlineHelpText>This defaults to the contact&apos;s first name, and will be filled in as such if left empty.</inlineHelpText>
    <label>Preferred Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Pronoun__c.field-meta.xml
<CustomField>
    <fullName>Pronoun__c</fullName>
    <label>Pronoun</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Pronouns</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/PronounOther__c.field-meta.xml
<CustomField>
    <fullName>PronounOther__c</fullName>
    <label>Specified Pronoun</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dog__c/fields/AgeYears__c.field-meta.xml
<CustomField>
    <fullName>AgeYears__c</fullName>
    <description>Current Age of Dog</description>
    <formula>(Today() -  Birthdate__c) / 365</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age (Years)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <inlineHelpText>Format m/d/yyyy</inlineHelpText>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/Breed__c.field-meta.xml
<CustomField>
    <fullName>Breed__c</fullName>
    <description>Describes the dog&apos;s breed</description>
    <label>Breed</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program the dog is in training for/certified for</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assistance Dogs Set In Motion</fullName>
            </value>
            <value>
                <fullName>Team Certification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Derived from Team.  Do not edit directly.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In ADSiM</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Certified-Active</fullName>
            </value>
            <value>
                <fullName>Certified-OnHold</fullName>
            </value>
            <value>
                <fullName>Decertified</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DogRelationship__c/DogRelationship__c.object-meta.xml
<CustomObject>
    <description>Connection between a dog and a contact</description>
    <label>Dog Relationship</label>
    <nameField>
        <displayFormat>DR-{00000}</displayFormat>
        <label>Dog Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dogs Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DogRelationship__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Dogs</relationshipLabel>
    <relationshipName>DogsContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DogRelationship__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A dog for this contact</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>Humans</relationshipLabel>
    <relationshipName>DogsContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DogRelationship__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Relationship types between a dog and contact</description>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Veterinarian</fullName>
            </value>
            <value>
                <fullName>Handler</fullName>
            </value>
            <value>
                <fullName>Facilitator</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Atlas Program</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramAssignment__c/ProgramAssignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Program Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramAssignment__c/fields/AssignedDate__c.field-meta.xml
<CustomField>
    <fullName>AssignedDate__c</fullName>
    <label>Assigned Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/CompletionDate__c.field-meta.xml
<CustomField>
    <fullName>CompletionDate__c</fullName>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assigned Programs</relationshipLabel>
    <relationshipName>AssignedProgram</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/ExpectedCompletion__c.field-meta.xml
<CustomField>
    <fullName>ExpectedCompletion__c</fullName>
    <description>Expected completion date</description>
    <label>Expected Completion</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Positions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Volunteer</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Board Member</fullName>
    </customValue>
    <customValue>
        <fullName>Trainer</fullName>
    </customValue>
    <customValue>
        <fullName>Client</fullName>
    </customValue>
    <customValue>
        <fullName>Donor</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
        <label>Staff/Contractor</label>
    </customValue>
    <customValue>
        <fullName>Puppy Raiser</fullName>
    </customValue>
    <customValue>
        <fullName>Standalone</fullName>
    </customValue>
    <customValue>
        <fullName>TSiM</fullName>
    </customValue>
    <description>Positions a contact can have</description>
    <masterLabel>Positions</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Pronouns.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>They/Them</fullName>
    </customValue>
    <customValue>
        <fullName>He/Him</fullName>
    </customValue>
    <customValue>
        <fullName>She/Her</fullName>
    </customValue>
    <customValue>
        <fullName>Prefer to self-describe</fullName>
    </customValue>
    <customValue>
        <fullName>Prefer not to answer</fullName>
    </customValue>
    <description>Pronouns for a contact</description>
    <masterLabel>Pronouns</masterLabel>
</GlobalValueSet>

force-app/main/test/TestProgramAssignmentController.cls
@isTest
private class TestProgramAssignmentController {
 
    @TestSetup
    static void makeData() {
        AtlasSettings__c settings = new AtlasSettings__c();
        upsert settings;

        List<Contact> conLst = new List<Contact>();

        Contact con = new Contact(
            FirstName = 'Trainer',
            LastName = 'Contact',
            Email = 'trainer@abc.com',
            Positions__c = 'Trainer;Client',
            PreferredName__c = 'Trainer',
            Pronoun__c = 'He/Him'
        );

        conLst.add(con);

        Contact con2 = new Contact(
            FirstName = 'Client',
            LastName = 'TestData',
            Email = 'client@abc.com',
            Positions__c = 'Trainer;Volunteer',
            PreferredName__c = 'Trainer',
            Pronoun__c = 'He/Him',
            PronounOther__c = 'Xe/Xim'           
        );

        conLst.add(con2);

        insert conLst;

        TestProgramAssignmentTrigger.setProgramDurations();
    }

    @isTest
    public static void getProgramAssignments_ReturnsAssignments() {
        Contact client = [SELECT FirstName, LastName, Id FROM Contact WHERE Email = 'client@abc.com'];
        Contact trainer = [SELECT FirstName, LastName, Id FROM Contact WHERE Email = 'trainer@abc.com'];
        List<ProgramAssignment__c> pas = new List<ProgramAssignment__c>();
        pas.add(new ProgramAssignment__c(
            Contact__c = client.Id,
            AssignedDate__c = Date.today().addYears(-1),
            CompletionDate__c = Date.today().addMonths(-10),
            ExpectedCompletion__c = Date.today().addMonths(-9),
            Program__c = [SELECT Id FROM Program__c WHERE Name = 'Volunteer' LIMIT 1].Id,
            Status__c = 'Completed'
        ));
        pas.add(new ProgramAssignment__c(
            Contact__c = client.Id,
            AssignedDate__c = Date.today().addYears(-1),
            ExpectedCompletion__c = Date.today().addMonths(1),
            Program__c = [SELECT Id FROM Program__c WHERE Name = 'Medical Disability' LIMIT 1].Id,
            Status__c = 'In Progress'
        ));
        pas.add(new ProgramAssignment__c(
            Contact__c = trainer.Id,
            AssignedDate__c = Date.today().addYears(-3),
            ExpectedCompletion__c = Date.today().addMonths(-16),
            Program__c = [SELECT Id FROM Program__c WHERE Name = 'Client' LIMIT 1].Id,
            Status__c = 'Discontinued'
        ));
        insert pas;

        Test.startTest();
        List<ProgramAssignment__c> clientPas = ProgramAssignmentController.getProgramAssignments(client.Id);
        Test.stopTest();

        System.assertEquals(2, clientPas.size(), 'Returned wrong number of records');
    }

    @isTest
    public static void getProgramAssignments_ReturnsNoAssignments_WhenIdNull() {
        Test.startTest();
        List<ProgramAssignment__c> clientPas = ProgramAssignmentController.getProgramAssignments(null);
        Test.stopTest();

        System.assertEquals(new List<ProgramAssignment__c>(), clientPas);
    }

    @isTest
    public static void getProgramAssignments_ThrowsException_WhenIdInvalid() {
        boolean thrown = false;
        Test.startTest();
        try {
            List<ProgramAssignment__c> clientPas = ProgramAssignmentController.getProgramAssignments('null');
        }
        catch (Exception exc) {
            thrown = true;
        }
        Test.stopTest();

        System.assert(thrown);
    }

    private static Dog__c ace;
    private static Dog__c cookie;
    private static Dog__c theo;
    private static Contact client;
    private static Contact trainer;
    private static Contact becky;

    private static Dog__c getDogAge(Dog__c dog) {
        return [SELECT Name, Breed__c, AgeYears__c, Gender__c FROM Dog__c WHERE Id = :dog.Id LIMIT 1];
    }

    private static void setupDogs() {
        ace = new Dog__c(
            Name = 'Ace',
            Breed__c = 'German Shepherd Dog',
            Birthdate__c = Date.today().addYears(-3),
            Gender__c = 'Female'
        );
        cookie = new Dog__c(
            Name = 'Cookie',
            Breed__c = 'Britany',
            Birthdate__c = Date.today().addYears(-13),
            Gender__c = 'Female'
        );
        theo = new Dog__c(
            Name = 'Theodore',
            Breed__c = 'Labrador',
            Birthdate__c = Date.today().addYears(-10),
            Gender__c = 'Male'
        );
        List<Dog__c> dogs = new List<Dog__c>{ ace, cookie, theo };
        insert dogs;

        ace = getDogAge(ace);
        cookie = getDogAge(cookie);
        theo = getDogAge(theo);

        client = [SELECT FirstName, LastName, Email, PreferredName__c, Pronoun__c, PronounOther__c, Id FROM Contact WHERE Email = 'client@abc.com'];
        trainer = [SELECT FirstName, LastName, Email, PreferredName__c, Pronoun__c, PronounOther__c, Id FROM Contact WHERE Email = 'trainer@abc.com'];
        becky = new Contact(
            FirstName = 'Becky',
            LastName = 'Robinson',
            Email = 'becky@abc.com',
            Positions__c = 'Client',
            PreferredName__c = 'Becky',
            Pronoun__c = 'She/Her'
        );
        insert becky;

        List<DogRelationship__c> relationships = new List<DogRelationship__c>();
        relationships.add(new DogRelationship__c(
            Dog__c = ace.Id,
            Contact__c = client.Id,
            Type__c = 'Owner'
        ));
        relationships.add(new DogRelationship__c(
            Dog__c = cookie.Id,
            Contact__c = trainer.Id,
            Type__c = 'Client'
        ));
        relationships.add(new DogRelationship__c(
            Dog__c = theo.Id,
            Contact__c = becky.Id,
            Type__c = 'Handler'
        ));
        insert relationships;
    }

    private static void assertReportData(ProgramReportRow row, ProgramAssignment__c pa, Contact contact, Dog__c dog) {
        System.assertEquals(pa.Status__c, row.pa.Status__c);
        System.assertEquals(pa.AssignedDate__c, row.pa.AssignedDate__c);
        System.assertEquals(contact.FirstName, row.contact.FirstName);
        System.assertEquals(contact.LastName, row.contact.LastName);
        System.assertEquals(contact.PreferredName__c, row.contact.PreferredName__c);
        System.assertEquals(contact.Pronoun__c, row.contact.Pronoun__c);
        System.assertEquals(contact.Email, row.contact.Email);

        System.assertEquals(dog.Name, row.dog.Name);
        System.assertEquals(dog.AgeYears__c, row.dog.AgeYears__c, 'Age does not match');
        System.assertEquals(dog.Breed__c, row.dog.Breed__c, 'Breed does not match');
        System.assertEquals(dog.Gender__c, row.dog.Gender__c, 'Genter does not match');
    }

    @isTest
    public static void getReport_ReturnsReportData() {
        string program = 'Teams Set in Motion Client';
        setupDogs();
        Program__c tsim = [SELECT Id FROM Program__c WHERE Name = :program LIMIT 1];
        List<ProgramAssignment__c> pas = new List<ProgramAssignment__c>();
        pas.add(new ProgramAssignment__c(
            Contact__c = client.Id,
            AssignedDate__c = Date.today().addYears(-1),
            CompletionDate__c = Date.today().addMonths(-10),
            ExpectedCompletion__c = Date.today().addMonths(-9),
            Program__c = tsim.Id,
            Status__c = 'In Progress'
        ));
        pas.add(new ProgramAssignment__c(
            Contact__c = trainer.Id,
            AssignedDate__c = Date.today().addYears(-1),
            ExpectedCompletion__c = Date.today().addMonths(1),
            Program__c = tsim.Id,
            Status__c = 'In Progress'
        ));
        pas.add(new ProgramAssignment__c(
            Contact__c = becky.Id,
            AssignedDate__c = Date.today().addYears(-3),
            ExpectedCompletion__c = Date.today().addMonths(-16),
            Program__c = tsim.Id,
            Status__c = 'Pending'
        ));
        pas.add(new ProgramAssignment__c(
            Contact__c = trainer.Id,
            AssignedDate__c = Date.today().addYears(-3),
            ExpectedCompletion__c = Date.today().addMonths(-16),
            Program__c = [SELECT Id FROM Program__c WHERE Name = 'Client' LIMIT 1].Id,
            Status__c = 'Completed'
        ));
        insert pas;

        Test.startTest();
        RelatedObjects report = ProgramAssignmentController.getReport(program);
        Test.stopTest();

        System.assertEquals(3, report.total, 'Returned wrong total');
        System.assertEquals(3, report.items.size(), 'Returned wrong number of records');
        assertReportData((ProgramReportRow)report.items[0], pas[0], client, ace);
        assertReportData((ProgramReportRow)report.items[1], pas[1], trainer, cookie);
        assertReportData((ProgramReportRow)report.items[2], pas[2], becky, theo);
    }
}