force-app/main/default/objects/AtlasSettings__c/AtlasSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for the Atlas Assistance Dogs app</description>
    <label>Atlas Settings</label>
</CustomObject>

force-app/main/default/objects/AtlasSettings__c/fields/BackgroundCheckRenewalYears__c.field-meta.xml
<CustomField>
    <fullName>BackgroundCheckRenewalYears__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Years between background checks</description>
    <label>Background Check Renewal Years</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BackgroundCheck__c/BackgroundCheck__c.object-meta.xml
<CustomObject>
    <description>Background check record</description>
    <label>Background Check</label>
    <nameField>
        <displayFormat>BC-{0000}</displayFormat>
        <label>Background Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Background Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BackgroundCheck__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contact the background check is for</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Background Checks</relationshipLabel>
    <relationshipName>BackgroundChecks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BackgroundCheck__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date background check was requested</description>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BackgroundCheck__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BackgroundCheck__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Criminal</fullName>
                <default>true</default>
                <label>Criminal</label>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Place/person to contact this person</description>
    <inlineHelpText>Select Guardian to contact this person through their guardian, Home for personal email/phone</inlineHelpText>
    <label>Contact At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
                <default>true</default>
                <label>Home</label>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>50000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Contact/fields/VolunteerAccess__c.field-meta.xml
<CustomField>
    <fullName>VolunteerAccess__c</fullName>
    <label>Volunteer Access</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operations- Master Docs - READ ONLY</fullName>
            </value>
            <value>
                <fullName>Operations- Financial</fullName>
            </value>
            <value>
                <fullName>Operations- Client</fullName>
            </value>
            <value>
                <fullName>Operations- Volunteer and Staff</fullName>
            </value>
            <value>
                <fullName>Operations- Trainer</fullName>
            </value>
            <value>
                <fullName>Board - READ ONLY</fullName>
            </value>
            <value>
                <fullName>Board</fullName>
            </value>
            <value>
                <fullName>Sensitive Info- Volunteer and Staff</fullName>
            </value>
            <value>
                <fullName>Sensitive Info- Trainer</fullName>
            </value>
            <value>
                <fullName>Sensitive Info- Board</fullName>
            </value>
            <value>
                <fullName>Active Projects- Academy</fullName>
            </value>
            <value>
                <fullName>Active Projects- ADI</fullName>
            </value>
            <value>
                <fullName>Active Projects- Branding and Marketing</fullName>
            </value>
            <value>
                <fullName>Active Projects- Client Certification</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Community Outreach and Education</fullName>
                <label>Active Projects- Community Outreach and Education</label>
            </value>
            <value>
                <fullName>Active Projects- Dog Availability</fullName>
            </value>
            <value>
                <fullName>Active Projects- Fund Development</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Governance, Compliance and Operations</fullName>
                <label
                >Active Projects- Governance, Compliance and Operations</label>
            </value>
            <value>
                <fullName>Active Projects- Research and Development</fullName>
            </value>
            <value>
                <fullName>Active Projects- Scholarships</fullName>
            </value>
            <value>
                <fullName>Active Projects- State Registration</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Team Facilitator Certification</fullName>
                <label>Active Projects- Team Facilitator Certification</label>
            </value>
            <value>
                <fullName>Active Projects- Technology Infrastructure</fullName>
            </value>
            <value>
                <fullName>Active Projects- Trainer Certification</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Volunteer Recruitment and Retention</fullName>
                <label
                >Active Projects- Volunteer Recruitment and Retention</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contacts.recordType-meta.xml
<RecordType>
    <fullName>Contacts</fullName>
    <active>true</active>
    <label>Contacts</label>
</RecordType>

force-app/main/default/classes/BackgroundCheckController.cls
public with sharing class BackgroundCheckController {
    // This method is used by the related list component, and needs more than just the background check
    @AuraEnabled(Cacheable=true)
    public static RelatedObjects getRelatedChecks(Id contactId, Integer max) {
        if (max == null) {
            max = 6;
        }
        try {
            RelatedObjects related = new RelatedObjects();
            List<BackgroundCheck__c> checks = [
                SELECT Name, Contact__c, Date__c, Notes__c, Status__c, Type__c
                FROM BackgroundCheck__c
                WHERE Contact__c = :contactId
                LIMIT :max
            ];
            related.total = [
                SELECT COUNT()
                FROM BackgroundCheck__c
                WHERE Contact__c = :contactId
            ];

            for (BackgroundCheck__c bgc : checks) {
                BackgroundCheck outCheck = new BackgroundCheck();
                outCheck.check = bgc;
                outCheck.noFile = true;
                RelatedObjects files = FileController.getAllRelatedFiles(
                    bgc.Id,
                    1
                );
                if (files != null && !files.items.isEmpty()) {
                    FileInfo info = (FileInfo) files.items[0];
                    outCheck.documentId = info.cv.ContentDocumentId;
                    outCheck.fileName = info.cv.Title;
                    outCheck.noFile = false;
                }
                related.items.add(outCheck);
            }
            return related;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public static void createReminderTask() {
        AtlasSettings__c settings = AtlasSettings__c.getOrgDefaults();
        // check to see if this setting is missing
        if (settings.BackgroundCheckRenewalYears__c == null) {
            settings.BackgroundCheckRenewalYears__c = 1;
            upsert settings;
        }

        // find the cutoff for which background checks to remind
        Date threshold = Date.today()
            .addYears(-1 * (Integer) settings.BackgroundCheckRenewalYears__c)
            .addMonths(1);
        System.debug(threshold);

        // Get the group to assign the task to
        Group adminGroup = [
            SELECT Id
            FROM Group
            WHERE Name = 'Background Check Administrator' AND Type = 'Queue'
        ];

        // Make sure we only have one Background check per contact
        Set<Id> contactIds = new Set<Id>();
        // Check for any cantacts that need background checks
        Contact[] contacts = [
            SELECT Id, Name
            FROM Contact
            WHERE
                VolunteerAccess__c = 'Credit Check Required'
                OR VolunteerAccess__c = 'Background Check Required'
        ];

        for (Contact person : contacts) {
            contactIds.add(person.Id);
        }

        BackgroundCheck__c[] checks = [
            SELECT Id, Date__c, Contact__c, Contact__r.Name
            FROM BackgroundCheck__c
            WHERE
                Contact__c IN :contactIds
                AND Date__c > :threshold
                AND (Contact__r.VolunteerAccess__c = 'Credit Check Required'
                OR Contact__r.VolunteerAccess__c = 'Background Check Required')
            ORDER BY Date__c DESC // get the most recent first
        ];
        System.debug(checks);
        // Remove the contacts with recent-enough background checks from the list
        for (BackgroundCheck__c check : checks) {
            contactIds.remove(check.Contact__c);
        }

        // Create a list of Tasks
        Task[] tasks = new List<Task>();
        for (Id contactId : contactIds) {
            tasks.add(
                new Task(
                    OwnerId = adminGroup.Id,
                    Subject = 'Order background check',
                    Status = 'Open',
                    Priority = 'Normal',
                    WhoId = contactId,
                    ActivityDate = Date.today().addMonths(1)
                )
            );
        }

        insert tasks;
    }
}