force-app/main/default/objects/AtlasSettings__c/AtlasSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for the Atlas Assistance Dogs app</description>
    <label>Atlas Settings</label>
</CustomObject>

force-app/main/default/objects/Contact/fields/Positions__c.field-meta.xml
<CustomField>
    <fullName>Positions__c</fullName>
    <description>Positions available</description>
    <label>Positions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Positions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/globalValueSets/Positions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Volunteer</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Board Member</fullName>
    </customValue>
    <customValue>
        <fullName>Trainer</fullName>
    </customValue>
    <customValue>
        <fullName>Client</fullName>
    </customValue>
    <customValue>
        <fullName>Donor</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
        <label>Staff/Contractor</label>
    </customValue>
    <customValue>
        <fullName>Puppy Raiser</fullName>
    </customValue>
    <customValue>
        <fullName>Standalone</fullName>
    </customValue>
    <customValue>
        <fullName>TSiM</fullName>
    </customValue>
    <description>Positions a contact can have</description>
    <masterLabel>Positions</masterLabel>
</GlobalValueSet>

force-app/main/test/TestContactController.cls
@isTest
private class TestContactController {
    @isTest
    public static void getContacts() {
        Test.startTest();

        PagedResult res = ContactController.getPagedContacts('Test', 1);
        System.assertEquals(res.records.size(), 2);

        List<Contact> conList2 = ContactController.getContactsByName('Test');
        System.assertEquals(conList2.size(), 2);

        List<Contact> conList3 = ContactController.getContactsWithPosition(
            'Trainer'
        );
        System.assertEquals(conList3.size(), 2);

        Test.stopTest();
    }

    @TestSetup
    static void makeData() {
        AtlasSettings__c settings = new AtlasSettings__c();
        upsert settings;

        List<Contact> conLst = new List<Contact>();

        Contact con = new Contact();

        con.FirstName = 'Test';
        con.LastName = 'Contact';
        con.Email = 'abc@abc.com';
        con.Positions__c = 'Trainer;Client';

        conLst.add(con);

        Contact con2 = new Contact();

        con2.FirstName = 'Client';
        con2.LastName = 'TestData';
        con2.Email = 'abcde@abc.com';
        con2.Positions__c = 'Trainer;Volunteer';

        conLst.add(con2);

        insert conLst;
    }
}