force-app/main/default/objects/AtlasSettings__c/AtlasSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for the Atlas Assistance Dogs app</description>
    <label>Atlas Settings</label>
</CustomObject>

force-app/main/default/objects/AtlasSettings__c/fields/CertRenewalYears__c.field-meta.xml
<CustomField>
    <fullName>CertRenewalYears__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Years between Certification renewals</description>
    <label>Certification Renewal Years</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AtlasSettings__c/fields/EarlyRenewal__c.field-meta.xml
<CustomField>
    <fullName>EarlyRenewal__c</fullName>
    <defaultValue>90</defaultValue>
    <description>Number of days leeway before expiration dates to increment valid until</description>
    <label>Early Renewal Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AtlasSettings__c/fields/RenewalLeeway__c.field-meta.xml
<CustomField>
    <fullName>RenewalLeeway__c</fullName>
    <defaultValue>30</defaultValue>
    <description>Number of days leeway after expiration dates to extend certification by a year</description>
    <label>Renewal Leeway</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <description>Track progress toward a certification or renewal.  CEUs are be associated with certifications</description>
    <label>Certification</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <label>Total CEUs</label>
    <summarizedField>CeuCertification__c.Approved__c</summarizedField>
    <summaryForeignKey>CeuCertification__c.Certification__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Trainer or Facilitator</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Certifications</relationshipLabel>
    <relationshipName>Certifications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Certification status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Facilitator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEU__c/CEU__c.object-meta.xml
<CustomObject>
    <label>CEU</label>
    <nameField>
        <displayFormat>CEU-{0000}</displayFormat>
        <label>CEU Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CEUs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CEU__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CEUs</relationshipLabel>
    <relationshipName>CEUs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CEU__c/fields/DateCompleted__c.field-meta.xml
<CustomField>
    <fullName>DateCompleted__c</fullName>
    <label>Date Completed</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CEU__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Requested CEUs</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CEU__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CeuCertification__c/CeuCertification__c.object-meta.xml
<CustomObject>
    <description>Linking table for CEUs and Certifications</description>
    <label>CEU Certification</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>CeuCertification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CEU Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CeuCertification__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <label>Approved</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CeuCertification__c/fields/Certification__c.field-meta.xml
<CustomField>
    <fullName>Certification__c</fullName>
    <label>Certification</label>
    <referenceTo>Certification__c</referenceTo>
    <relationshipLabel>CEU Certifications</relationshipLabel>
    <relationshipName>CEU_Certifications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CeuCertification__c/fields/CEU__c.field-meta.xml
<CustomField>
    <fullName>CEU__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CEU</label>
    <referenceTo>CEU__c</referenceTo>
    <relationshipLabel>CEU Certifications</relationshipLabel>
    <relationshipName>CEU_Certifications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Place/person to contact this person</description>
    <inlineHelpText>Select Guardian to contact this person through their guardian, Home for personal email/phone</inlineHelpText>
    <label>Contact At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
                <default>true</default>
                <label>Home</label>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/certifications/CertificationService.cls
public inherited sharing class CertificationService {
  private CertificationRepository certRepo;
  private EmailService emailServ;
  public CertificationService() {
    certRepo = new CertificationRepository();
    emailServ = new EmailService();
  }

  @TestVisible
  private CertificationService(
    CertificationRepository certRepo,
    EmailService emailServ
  ) {
    this.certRepo = certRepo;
    this.emailServ = emailServ;
  }

  public static Map<Id, List<Ceu__c>> sortCeus(List<Ceu__c> ceus) {
    Map<Id, List<Ceu__c>> contactCeuIds = new Map<Id, List<Ceu__c>>();
    for (Ceu__c ceu : ceus) {
      if (contactCeuIds.containsKey(ceu.Contact__c)) {
        List<Ceu__c> contactCeus = contactCeuIds.get(ceu.Contact__c);
        contactCeus.add(ceu);
      } else {
        contactCeuIds.put(ceu.Contact__c, new List<Ceu__c>{ ceu });
      }
    }
    return contactCeuIds;
  }

  public static Map<Id, List<Certification__c>> sortCertifications(
    List<Certification__c> ceus
  ) {
    Map<Id, List<Certification__c>> contactCeuIds = new Map<Id, List<Certification__c>>();
    for (Certification__c ceu : ceus) {
      if (contactCeuIds.containsKey(ceu.Contact__c)) {
        List<Certification__c> contactCeus = contactCeuIds.get(ceu.Contact__c);
        contactCeus.add(ceu);
      } else {
        contactCeuIds.put(ceu.Contact__c, new List<Certification__c>{ ceu });
      }
    }
    return contactCeuIds;
  }

  // add CEUs to the appropriate certifications
  public void addCeus(List<Ceu__c> ceus) {
    Map<Id, List<Ceu__c>> contactCeuIds = sortCeus(ceus);
    List<Certification__c> certs = certRepo.getForContacts(
      contactCeuIds.keySet()
    );
    List<CeuCertification__c> ccs = new List<CeuCertification__c>();
    for (Certification__c cert : certs) {
      List<Ceu__c> contactCeus = contactCeuIds.get(cert.Contact__c);
      for (Ceu__c ceu1 : contactCeus) {
        if (
          ceu1.DateCompleted__c >= cert.Start__c &&
          ceu1.DateCompleted__c <= cert.End__c
        ) {
          CeuCertification__c cc = new CeuCertification__c(
            Ceu__c = ceu1.Id,
            Certification__c = cert.Id
          );
          if (ceu1.Status__c == 'Approved') {
            cc.Approved__c = ceu1.Quantity__c;
          }
          ccs.add(cc);
        }
      }
    }
    certRepo.create(ccs);
    certRepo.modify(certs);
  }

  // Since there is a rollup summary an Approved, check that it is set properly
  // We will not worry about changing the certification at this time, since
  // that is not likely to happen
  public void updateCeus(List<Ceu__c> ceus, Map<Id, Ceu__c> old) {
    List<CeuCertification__c> ccs = certRepo.getCeuCerts(ceus);

    for (CeuCertification__c cc : ccs) {
      if (cc.Ceu__r.Status__c == 'Approved') {
        cc.Approved__c = cc.Ceu__r.Quantity__c;
      } else {
        cc.Approved__c = 0;
      }
    }
    certRepo.modify(ccs);
  }

  private class Dates {
    public Integer years { get; set; }
    public Integer early { get; set; }
    public Integer leeway { get; set; }
    public Dates() {
      // check to see if settings are missing
      Boolean updateSettings = false;
      AtlasSettings__c settings = AtlasSettings__c.getOrgDefaults();
      if (settings.CertRenewalYears__c == null) {
        // TODO: get default value
        settings.CertRenewalYears__c = 1;
        updateSettings = true;
      }
      if (settings.EarlyRenewal__c == null) {
        // TODO: get default value
        settings.EarlyRenewal__c = 90;
        updateSettings = true;
      }
      if (settings.RenewalLeeway__c == null) {
        // TODO: get default value
        settings.RenewalLeeway__c = 30;
        updateSettings = true;
      }
      if (updateSettings) {
        upsert settings;
      }
      this.years = (Integer) settings.CertRenewalYears__c;
      this.early = (Integer) settings.EarlyRenewal__c;
      this.leeway = (Integer) settings.RenewalLeeway__c;
    }
  }

  public Certification__c updateCert(
    Contact person,
    String type,
    Date validUntil,
    Date certDate
  ) {
    Certification__c cert = certRepo.getActiveCert(person.Id, type);
    Dates dates = new Dates();
    if (cert == null) {
      if (validUntil == null) {
        // create cert and exit
        cert = certRepo.create(
          new Certification__c(
            Contact__c = person.Id,
            Type__c = type,
            Status__c = 'Active',
            Start__c = certDate,
            End__c = certDate.addYears(dates.years)
          )
        );
        return cert;
      } else {
        // create cert for current validUntil and continue
        cert = certRepo.create(
          new Certification__c(
            Contact__c = person.Id,
            Type__c = type,
            Status__c = 'Active',
            Start__c = validUntil.addYears(-dates.years),
            End__c = validUntil
          )
        );
      }
    }
    Integer days = certDate.daysBetween(cert.End__c);
    if (days >= -dates.early && days <= dates.leeway) {
      // complete old cert
      cert.Status__c = 'Complete';
      certRepo.modify(cert);

      cert = certRepo.create(
        new Certification__c(
          Contact__c = person.Id,
          Type__c = type,
          Status__c = 'Active',
          Start__c = cert.End__c,
          End__c = cert.End__c.addYears(dates.years)
        )
      );
      return cert;
    }
    if (days > dates.leeway) {
      // complete old cert and start new one
      // complete old cert
      cert.Status__c = 'Complete';
      certRepo.modify(cert);

      cert = certRepo.create(
        new Certification__c(
          Contact__c = person.Id,
          Type__c = type,
          Status__c = 'Active',
          Start__c = certDate,
          End__c = certDate.addYears(dates.years)
        )
      );
      return cert;
    }
    return null;
  }

  public void remindFacilitatorsToGetCeus() {
    Certification__c[] certs = certRepo.getActiveFacilitatorCerts();

    if (certs.isEmpty()) {
      return;
    }
    // Remind the contact for these certs to get their CEUs
    Id orgAddressId = emailServ.getOrgEmailAddressId();
    EmailTemplate template = emailServ.getTemplate('FacilitatorCeuReminder');

    List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
    for (Certification__c cert : certs) {
      Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
      if (orgAddressId != null) {
        mail.setOrgWideEmailAddressId(orgAddressId);
      }
      mail.setTargetObjectId(cert.Contact__c);
      mail.setWhatId(cert.Id);
      mail.setTemplateId(template.Id);

      // Record ID for which letter will be generated
      mail.setBccSender(false);
      mail.setUseSignature(false);
      if (orgAddressId == null) {
        mail.setSenderDisplayName('Atlas Assistance Dogs');
      }
      mail.setSaveAsActivity(false);
      emails.add(mail);
    }
    emailServ.sendEmail(emails);
  }
}