force-app/main/default/objects/AtlasSettings__c/AtlasSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for the Atlas Assistance Dogs app</description>
    <label>Atlas Settings</label>
</CustomObject>

force-app/main/default/objects/AtlasSettings__c/fields/PageSize__c.field-meta.xml
<CustomField>
    <fullName>PageSize__c</fullName>
    <defaultValue>10</defaultValue>
    <description>Number of records in paged tables</description>
    <label>Page Size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Place/person to contact this person</description>
    <inlineHelpText>Select Guardian to contact this person through their guardian, Home for personal email/phone</inlineHelpText>
    <label>Contact At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
                <default>true</default>
                <label>Home</label>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Positions__c.field-meta.xml
<CustomField>
    <fullName>Positions__c</fullName>
    <description>Positions available</description>
    <label>Positions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Positions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contacts.recordType-meta.xml
<RecordType>
    <fullName>Contacts</fullName>
    <active>true</active>
    <label>Contacts</label>
</RecordType>

force-app/main/default/objects/ContactLog__c/ContactLog__c.object-meta.xml
<CustomObject>
    <label>Contact Log</label>
    <nameField>
        <label>Related Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ContactLog__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact associated with a log</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Logs</relationshipLabel>
    <relationshipName>Contact_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContactLog__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Log</label>
    <referenceTo>Log__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>ContactLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContactLog__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>How a contact is associated with the record</description>
    <label>Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitter</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Team Facilitator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Logs made by Client or Team Facilitator</description>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/OtherHours__c.field-meta.xml
<CustomField>
    <fullName>OtherHours__c</fullName>
    <label>Other Hours</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/PublicAccessHours__c.field-meta.xml
<CustomField>
    <fullName>PublicAccessHours__c</fullName>
    <description>Number of Public Access Hours</description>
    <label># Public Access Hours</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/RequestSupportFromAtlas__c.field-meta.xml
<CustomField>
    <fullName>RequestSupportFromAtlas__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request support from Atlas?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/RequestSupportFromTeam__c.field-meta.xml
<CustomField>
    <fullName>RequestSupportFromTeam__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request support from Team?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Satisfaction__c.field-meta.xml
<CustomField>
    <fullName>Satisfaction__c</fullName>
    <label>Client Life Satisfaction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No enjoyment</fullName>
            </value>
            <value>
                <fullName>A little enjoyment</fullName>
            </value>
            <value>
                <fullName>Some enjoyment</fullName>
            </value>
            <value>
                <fullName>Rather much enjoyment</fullName>
            </value>
            <value>
                <fullName>Extreme amount of enjoyment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Stress__c.field-meta.xml
<CustomField>
    <fullName>Stress__c</fullName>
    <label>Stress</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Stress</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/SupportDetails__c.field-meta.xml
<CustomField>
    <fullName>SupportDetails__c</fullName>
    <description>Details of team support request</description>
    <label>Support Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/globalValueSets/Positions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Volunteer</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Board Member</fullName>
    </customValue>
    <customValue>
        <fullName>Trainer</fullName>
    </customValue>
    <customValue>
        <fullName>Client</fullName>
    </customValue>
    <customValue>
        <fullName>Donor</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
        <label>Staff/Contractor</label>
    </customValue>
    <customValue>
        <fullName>Puppy Raiser</fullName>
    </customValue>
    <customValue>
        <fullName>Standalone</fullName>
    </customValue>
    <customValue>
        <fullName>TSiM</fullName>
    </customValue>
    <description>Positions a contact can have</description>
    <masterLabel>Positions</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Stress.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not at all</fullName>
        <default>true</default>
        <label>Not at all</label>
    </customValue>
    <customValue>
        <fullName>Only a little</fullName>
    </customValue>
    <customValue>
        <fullName>To some extent</fullName>
    </customValue>
    <customValue>
        <fullName>Rather much</fullName>
    </customValue>
    <customValue>
        <fullName>Very much</fullName>
    </customValue>
    <description>Stress Levels</description>
    <masterLabel>Stress</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContactController.cls
/* Methods for finding and updating contacts */
public inherited sharing class ContactController {
    // Get the page size if available.  If not defined, return the default.
    private static Integer getPageSize() {
        AtlasSettings__c settings = AtlasSettings__c.getInstance();
        if (settings == null) {
            settings = new AtlasSettings__c();
        }
        return (Integer) settings.PageSize__c;
    }

    @AuraEnabled(cacheable=true)
    public static PagedResult getPagedContacts(
        String searchKey,
        Integer pageNumber
    ) {
        String searchId = searchKey.trim();
        String searchCriteria = (String.isBlank(searchId)
            ? '%'
            : '%' + searchId + '%');

        Integer pageSize = getPageSize();
        Integer offset = (pageNumber - 1) * pageSize;

        pagedResult result = new pagedResult();
        result.pageNumber = pageNumber;
        result.pageSize = pageSize;
        result.totalItemCount = Database.countQuery(
            'SELECT count() FROM Contact'
        );

        String query = 'SELECT Id, Name FROM Contact Where Name Like :searchCriteria WITH SECURITY_ENFORCED ORDER BY Name LIMIT :pageSize OFFSET :offset';
        List<Contact> records = Database.query(query);

        result.records = records;

        return result;
    }

    @AuraEnabled(cacheable=true)
    public static List<Contact> getContactsWithPosition(String position) {
        return [
            SELECT Id, Name
            FROM Contact
            WHERE Positions__c INCLUDES (:position)
            WITH SECURITY_ENFORCED
            ORDER BY Name
        ];
    }

    // Return all the contacts with matching name
    @AuraEnabled(Cacheable=true)
    public static List<Contact> getContactsByName(String strName) {
        String strNameLike = '%' + strName + '%';
        List<Contact> acctList = [
            SELECT Id, Name
            FROM Contact
            WHERE Name LIKE :strNameLike
        ];
        return acctList;
    }

    @AuraEnabled(Cacheable=true)
    public static List<ContactLog__c> getRelatedLogs(id contactId) {
        try {
            return [
                SELECT
                    Role__c,
                    Log__r.Date__c,
                    Log__r.PublicAccessHours__c,
                    Log__r.OtherHours__c,
                    Log__r.Details__c,
                    Log__r.RequestSupportFromTeam__c,
                    Log__r.SupportDetails__c,
                    Log__r.Stress__c,
                    Log__r.Satisfaction__c,
                    Log__r.RequestSupportFromAtlas__c
                FROM ContactLog__c
                WHERE Contact__c = :contactId
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(Cacheable=false)
    public static void createRelatedLog(
        id contactId,
        string roles,
        Log__c log
    ) {
        try {
            insert log;
            System.debug(roles);
            ContactLog__c contactLog = new ContactLog__c(
                Role__c = roles,
                Contact__c = contactId,
                Log__c = log.Id
            );
            insert contactLog;
            System.debug(contactLog);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}