force-app/main/default/objects/AtlasSettings__c/AtlasSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for the Atlas Assistance Dogs app</description>
    <label>Atlas Settings</label>
</CustomObject>

force-app/main/default/objects/AtlasSettings__c/fields/BoardTermEndMonth__c.field-meta.xml
<CustomField>
    <fullName>BoardTermEndMonth__c</fullName>
    <defaultValue>4</defaultValue>
    <description>Month number that board member terms are valid until, where 1 is January and 12 is December.</description>
    <label>Board Term End Month</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BoardTermValidUntil__c.field-meta.xml
<CustomField>
    <fullName>BoardTermValidUntil__c</fullName>
    <description>The date the Board Member Term is valid to</description>
    <label>Board Term Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FirstAidReceived__c.field-meta.xml
<CustomField>
    <fullName>FirstAidReceived__c</fullName>
    <description>The date the most recent version of First Aid Certification was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last First Aid Certificate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FirstAidValidUntil__c.field-meta.xml
<CustomField>
    <fullName>FirstAidValidUntil__c</fullName>
    <description>The date the First Aid Certification is valid until</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>First Aid Certificate Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LastBoardTermStartDate__c.field-meta.xml
<CustomField>
    <fullName>LastBoardTermStartDate__c</fullName>
    <description>Board member&apos;s start date for their most recent term</description>
    <label>Last Board Term Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Positions__c.field-meta.xml
<CustomField>
    <fullName>Positions__c</fullName>
    <description>Positions available</description>
    <label>Positions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Positions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/TrainerCertAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>TrainerCertAgreementReceived__c</fullName>
    <description>The date the most recent version of Trainer Certification Agreement was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Trainer Certification Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TrainerCertValidUntil__c.field-meta.xml
<CustomField>
    <fullName>TrainerCertValidUntil__c</fullName>
    <description>The date the Trainer Certification is valid to</description>
    <label>Trainer Certification Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TrainerInitialCertificationDate__c.field-meta.xml
<CustomField>
    <fullName>TrainerInitialCertificationDate__c</fullName>
    <description>Date that the Trainer was first certified.</description>
    <label>Trainer Initial Certification Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/globalValueSets/Positions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Volunteer</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Board Member</fullName>
    </customValue>
    <customValue>
        <fullName>Trainer</fullName>
    </customValue>
    <customValue>
        <fullName>Client</fullName>
    </customValue>
    <customValue>
        <fullName>Donor</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
        <label>Staff/Contractor</label>
    </customValue>
    <customValue>
        <fullName>Puppy Raiser</fullName>
    </customValue>
    <customValue>
        <fullName>Standalone</fullName>
    </customValue>
    <customValue>
        <fullName>TSiM</fullName>
    </customValue>
    <description>Positions a contact can have</description>
    <masterLabel>Positions</masterLabel>
</GlobalValueSet>

force-app/main/test/contacts/TestContactTrigger.cls
@isTest
public with sharing class TestContactTrigger {
  public TestContactTrigger() {
  }

  private static Contact getContact(Id id) {
    return [
      SELECT
        Email,
        FirstName,
        npe01__HomeEmail__c,
        npe01__AlternateEmail__c,
        Phone,
        HomePhone,
        OtherPhone,
        LastBoardTermStartDate__c,
        BoardTermValidUntil__c
      FROM Contact
      WHERE Id = :id
      LIMIT 1
    ];
  }

  @isTest
  static void insert_LeavesEmailPhone_WhenHomeNotSetAndContactAtEmpty() {
    Contact joe = new Contact(
      Email = 'joe-blow@pump.com',
      FirstName = 'Joe',
      LastName = 'Blow',
      Phone = 'generic-phone'
    );

    // Act
    Test.startTest();
    Database.SaveResult result = Database.insert(joe, false);
    Test.stopTest();

    // Assert
    System.assert(result.isSuccess());
    Contact saved = getContact(result.getId());
    System.assert(result.getErrors().size() == 0);
    System.assertEquals(joe.Email, saved.Email);
    System.assertEquals(joe.Phone, saved.Phone);
    System.assert(string.isBlank(saved.npe01__HomeEmail__c));
    System.assert(string.isBlank(saved.npe01__AlternateEmail__c));
    System.assert(string.isBlank(saved.HomePhone));
    System.assert(string.isBlank(saved.OtherPhone));
  }

  @isTest
  static void update_setsBoardTermEnd_whenStartInJanuary() {
    Contact joe = new Contact(
      Email = 'joe-blow@pump.com',
      FirstName = 'Joe',
      LastName = 'Blow',
      LastBoardTermStartDate__c = null
    );
    insert joe;

    Date start = Date.newInstance(2023, 1, 1);
    joe.LastBoardTermStartDate__c = start;

    // Act
    Test.startTest();
    Database.SaveResult result = Database.update(joe, false);
    Test.stopTest();

    // Assert
    System.assert(result.isSuccess());
    Contact saved = getContact(result.getId());
    System.assert(result.getErrors().size() == 0);
    System.assertEquals(
      Date.newInstance(2026, 4, 30),
      saved.BoardTermValidUntil__c
    );
  }

  @isTest
  static void update_setsBoardTermEnd_whenStartInEndMonth() {
    Contact joe = new Contact(
      Email = 'joe-blow@pump.com',
      FirstName = 'Joe',
      LastName = 'Blow',
      LastBoardTermStartDate__c = null
    );
    insert joe;

    Date start = Date.newInstance(2023, 4, 30);
    joe.LastBoardTermStartDate__c = start;

    // Act
    Test.startTest();
    Database.SaveResult result = Database.update(joe, false);
    Test.stopTest();

    // Assert
    System.assert(result.isSuccess());
    Contact saved = getContact(result.getId());
    System.assert(result.getErrors().size() == 0);
    System.assertEquals(
      Date.newInstance(2026, 4, 30),
      saved.BoardTermValidUntil__c
    );
  }

  @isTest
  static void update_setsBoardTermEnd_whenStartJuly() {
    Contact joe = new Contact(
      Email = 'joe-blow@pump.com',
      FirstName = 'Joe',
      LastName = 'Blow',
      LastBoardTermStartDate__c = null
    );
    insert joe;

    Date start = Date.newInstance(2022, 7, 4);
    joe.LastBoardTermStartDate__c = start;

    // Act
    Test.startTest();
    Database.SaveResult result = Database.update(joe, false);
    Test.stopTest();

    // Assert
    System.assert(result.isSuccess());
    Contact saved = getContact(result.getId());
    System.assert(result.getErrors().size() == 0);
    System.assertEquals(
      Date.newInstance(2026, 4, 30),
      saved.BoardTermValidUntil__c
    );
  }

  @isTest
  static void update_setsBoardTermEnd_whenStartDecember() {
    Contact joe = new Contact(
      Email = 'joe-blow@pump.com',
      FirstName = 'Joe',
      LastName = 'Blow',
      LastBoardTermStartDate__c = null
    );
    insert joe;

    Date start = Date.newInstance(2022, 12, 25);
    joe.LastBoardTermStartDate__c = start;

    // Act
    Test.startTest();
    Database.SaveResult result = Database.update(joe, false);
    Test.stopTest();

    // Assert
    System.assert(result.isSuccess());
    Contact saved = getContact(result.getId());
    System.assert(result.getErrors().size() == 0);
    System.assertEquals(
      Date.newInstance(2026, 4, 30),
      saved.BoardTermValidUntil__c
    );
  }

  @isTest
  static void update_setsBoardTermEnd_whenEndMonth0() {
    AtlasSettings__c settings = AtlasSettings__c.getOrgDefaults();
    settings.BoardTermEndMonth__c = 0;
    upsert settings;

    Contact joe = new Contact(
      Email = 'joe-blow@pump.com',
      FirstName = 'Joe',
      LastName = 'Blow',
      LastBoardTermStartDate__c = null
    );
    insert joe;

    Date start = Date.newInstance(2022, 12, 25);
    joe.LastBoardTermStartDate__c = start;

    // Act
    Test.startTest();
    Database.SaveResult result = Database.update(joe, false);
    Test.stopTest();

    // Assert
    System.assert(result.isSuccess());
    Contact saved = getContact(result.getId());
    System.assert(result.getErrors().size() == 0);
    System.assertEquals(
      Date.newInstance(2025, 12, 31),
      saved.BoardTermValidUntil__c
    );
  }

  @isTest
  static void update_setsBoardTermEnd_whenEndMonth6() {
    AtlasSettings__c settings = AtlasSettings__c.getOrgDefaults();
    settings.BoardTermEndMonth__c = 6;
    upsert settings;

    Contact joe = new Contact(
      Email = 'joe-blow@pump.com',
      FirstName = 'Joe',
      LastName = 'Blow',
      LastBoardTermStartDate__c = null
    );
    insert joe;

    Date start = Date.newInstance(2022, 12, 25);
    joe.LastBoardTermStartDate__c = start;

    // Act
    Test.startTest();
    Database.SaveResult result = Database.update(joe, false);
    Test.stopTest();

    // Assert
    System.assert(result.isSuccess());
    Contact saved = getContact(result.getId());
    System.assert(result.getErrors().size() == 0);
    System.assertEquals(
      Date.newInstance(2026, 6, 30),
      saved.BoardTermValidUntil__c
    );
  }

  @isTest
  static void insert_setsFirstAidValidUntil_whenFirstAidSet() {
    AtlasSettings__c settings = AtlasSettings__c.getOrgDefaults();
    upsert settings;
    Date received = Date.newInstance(2022, 12, 25);

    Contact joe = new Contact(
      Email = 'joe-blow@pump.com',
      FirstName = 'Joe',
      LastName = 'Blow',
      FirstAidReceived__c = received
    );

    // Act
    Test.startTest();
    Database.SaveResult result = Database.insert(joe, true);
    Test.stopTest();

    // Assert
    System.assert(result.isSuccess());
    Contact saved = [
      SELECT id, FirstAidValidUntil__c
      FROM Contact
      WHERE id = :result.getId()
    ];
    System.assert(result.getErrors().size() == 0);
    System.assertEquals(received.addYears(2), saved.FirstAidValidUntil__c);
  }

  @isTest
  static void update_setsFirstAidValidUntil_whenFirstAidSet() {
    AtlasSettings__c settings = AtlasSettings__c.getOrgDefaults();
    upsert settings;
    Date received = Date.newInstance(2022, 12, 25);

    Contact joe = new Contact(
      Email = 'joe-blow@pump.com',
      FirstName = 'Joe',
      LastName = 'Blow',
      FirstAidReceived__c = null,
      FirstAidValidUntil__c = received
    );
    insert joe;

    joe.FirstAidReceived__c = received;

    // Act
    Test.startTest();
    Database.SaveResult result = Database.update(joe, true);
    Test.stopTest();

    // Assert
    System.assert(result.isSuccess());
    Contact saved = [
      SELECT id, FirstAidValidUntil__c
      FROM Contact
      WHERE id = :result.getId()
    ];
    System.assert(result.getErrors().size() == 0);
    System.assertEquals(received.addYears(2), saved.FirstAidValidUntil__c);
  }

  @isTest
  static void update_leavesFirstAidValidUntil_whenValidUntilSet() {
    AtlasSettings__c settings = AtlasSettings__c.getOrgDefaults();
    upsert settings;
    Date received = Date.newInstance(2022, 12, 25);

    Contact joe = new Contact(
      Email = 'joe-blow@pump.com',
      FirstName = 'Joe',
      LastName = 'Blow',
      FirstAidReceived__c = received,
      FirstAidValidUntil__c = received
    );
    insert joe;

    Date expected = received.addYears(3);
    joe.FirstAidValidUntil__c = expected;

    // Act
    Test.startTest();
    Database.SaveResult result = Database.update(joe, true);
    Test.stopTest();

    // Assert
    System.assert(result.isSuccess());
    Contact saved = [
      SELECT id, FirstAidValidUntil__c
      FROM Contact
      WHERE id = :result.getId()
    ];
    System.assert(result.getErrors().size() == 0);
    System.assertEquals(expected, saved.FirstAidValidUntil__c);
  }

  @isTest
  static void update_leavesFirstAidValidUntil_whenReceivedNotSet() {
    AtlasSettings__c settings = AtlasSettings__c.getOrgDefaults();
    upsert settings;
    Date received = Date.newInstance(2022, 12, 25);

    Contact joe = new Contact(
      Email = 'joe-blow@pump.com',
      FirstName = 'Joe',
      LastName = 'Blow',
      FirstAidReceived__c = received
    );
    insert joe;

    joe.FirstAidReceived__c = null;

    // Act
    Test.startTest();
    Database.SaveResult result = Database.update(joe, true);
    Test.stopTest();

    // Assert
    System.assert(result.isSuccess());
    Contact saved = [
      SELECT id, FirstAidValidUntil__c
      FROM Contact
      WHERE id = :result.getId()
    ];
    System.assert(result.getErrors().size() == 0);
    System.assertEquals(null, saved.FirstAidValidUntil__c);
  }

  @isTest
  static void update_setsTrainerCertValidUntil_whenFirstCert() {
    AtlasSettings__c settings = AtlasSettings__c.getOrgDefaults();
    upsert settings;
    Date received = Date.newInstance(2022, 12, 25);

    Contact joe = new Contact(
      Email = 'joe-blow@pump.com',
      FirstName = 'Joe',
      LastName = 'Blow',
      Positions__c = 'Trainer'
    );
    insert joe;

    joe.TrainerCertAgreementReceived__c = received;

    // Act
    Test.startTest();
    Database.SaveResult result = Database.update(joe, true);
    Test.stopTest();

    // Assert
    System.assert(result.isSuccess());
    Contact saved = [
      SELECT id, TrainerInitialCertificationDate__c, TrainerCertValidUntil__c
      FROM Contact
      WHERE id = :result.getId()
    ];
    System.assert(result.getErrors().size() == 0);
    System.assertEquals(received, saved.TrainerInitialCertificationDate__c);
    System.assertEquals(received.addYears(1), saved.TrainerCertValidUntil__c);
  }

  @isTest
  static void update_changesTrainerCertValidUntil_when30daysBefore() {
    AtlasSettings__c settings = AtlasSettings__c.getOrgDefaults();
    upsert settings;
    Date received = Date.newInstance(2022, 12, 25);

    Contact joe = new Contact(
      Email = 'joe-blow@pump.com',
      FirstName = 'Joe',
      LastName = 'Blow',
      Positions__c = 'Trainer',
      TrainerInitialCertificationDate__c = received,
      TrainerCertAgreementReceived__c = received,
      TrainerCertValidUntil__c = received.addYears(1)
    );
    insert joe;

    joe.TrainerCertAgreementReceived__c = received.addYears(1).addDays(-30);

    // Act
    Test.startTest();
    Database.SaveResult result = Database.update(joe, true);
    Test.stopTest();

    // Assert
    System.assert(result.isSuccess());
    Contact saved = [
      SELECT id, TrainerInitialCertificationDate__c, TrainerCertValidUntil__c
      FROM Contact
      WHERE id = :result.getId()
    ];
    System.assert(result.getErrors().size() == 0);
    System.assertEquals(received, saved.TrainerInitialCertificationDate__c);
    System.assertEquals(received.addYears(2), saved.TrainerCertValidUntil__c);
  }
}