force-app/main/default/objects/AtlasSettings__c/AtlasSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for the Atlas Assistance Dogs app</description>
    <label>Atlas Settings</label>
</CustomObject>

force-app/main/default/objects/AtlasSettings__c/fields/OrgWideEmailName__c.field-meta.xml
<CustomField>
    <fullName>OrgWideEmailName__c</fullName>
    <description>Org wide email name to use in automated emails</description>
    <label>Org Wide Email Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/emails/EmailService.cls
public inherited sharing class EmailService {
  public EmailService() {
  }

  public ID getOrgEmailAddressId() {
    AtlasSettings__c settings = AtlasSettings__c.getOrgDefaults();
    String emailName = settings.OrgWideEmailName__c;
    if (emailName == null) {
      settings.OrgWideEmailName__c = 'Atlas Assistance Dogs';
      upsert settings;
    }
    Id addressId = null;
    OrgWideEmailAddress[] addresses = [
      SELECT Id
      FROM OrgWideEmailAddress
      WHERE DisplayName = :emailName
    ];
    if (addresses.size() > 0) {
      addressId = addresses[0].Id;
    }
    return addressId;
  }
  public void sendEmail(List<Messaging.SingleEmailMessage> emails) {
    Messaging.sendEmail(emails);
  }
}