force-app/main/default/objects/AtlasSettings__c/AtlasSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for the Atlas Assistance Dogs app</description>
    <label>Atlas Settings</label>
</CustomObject>

force-app/main/default/objects/Contact/fields/BoardMemberStatus__c.field-meta.xml
<CustomField>
    <fullName>BoardMemberStatus__c</fullName>
    <label>Board Member Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
           </value>
           <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientCertificationValidUntil__c.field-meta.xml
<CustomField>
    <fullName>ClientCertificationValidUntil__c</fullName>
    <description>Date that the client certification is valid until</description>
    <label>Client Certification Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientStatus__c.field-meta.xml
<CustomField>
    <fullName>ClientStatus__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <inlineHelpText>Derived from Team. Do not edit directly.</inlineHelpText>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In ADSiM</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Certified-Hold</fullName>
            </value>
            <value>
                <fullName>Decertified</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Not Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Place/person to contact this person</description>
    <inlineHelpText>Select Guardian to contact this person through their guardian, Home for personal email/phone</inlineHelpText>
    <label>Contact At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
                <default>true</default>
                <label>Home</label>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/FacilitatorCertAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>FacilitatorCertAgreementReceived__c</fullName>
    <description>The date the most recent version of Team Facilitator Certification Agreement was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Facilitator Certification Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FacilitatorStatus__c.field-meta.xml
<CustomField>
    <fullName>FacilitatorStatus__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <label>Facilitator Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Certified-Active</fullName>
            </value>
            <value>
                <fullName>Certified-Hold</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Not Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/GW_Volunteers__Volunteer_Status__c.field-meta.xml
<CustomField>
    <fullName>GW_Volunteers__Volunteer_Status__c</fullName>
    <label>Volunteer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Positions__c.field-meta.xml
<CustomField>
    <fullName>Positions__c</fullName>
    <description>Positions available</description>
    <label>Positions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Positions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/PuppyCertAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>PuppyCertAgreementReceived__c</fullName>
    <description>The date the most recent version of Puppy Raiser Certification Agreement was uploaded</description>
    <label>Last Puppy Raiser Cert Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PuppyRaiserStatus__c.field-meta.xml
<CustomField>
    <fullName>PuppyRaiserStatus__c</fullName>
    <label>Puppy Raiser Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/TrainerCertAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>TrainerCertAgreementReceived__c</fullName>
    <description>The date the most recent version of Trainer Certification Agreement was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Trainer Certification Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TrainerStatus__c.field-meta.xml
<CustomField>
    <fullName>TrainerStatus__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <label>Trainer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Certified-Active</fullName>
            </value>
            <value>
                <fullName>Certified-OnHold</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Not Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Atlas Program</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Months__c.field-meta.xml
<CustomField>
    <fullName>Months__c</fullName>
    <description>Duration in Months</description>
    <label>Months</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Standalone__c.field-meta.xml
<CustomField>
    <fullName>Standalone__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Program isn&apos;t part of a certification program.  Program goes into &quot;Other&quot; category if checked.</description>
    <inlineHelpText>Program isn&apos;t part of a certification program.</inlineHelpText>
    <label>Standalone Program</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/ProgramAssignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Program Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramAssignment__c/fields/AssignedDate__c.field-meta.xml
<CustomField>
    <fullName>AssignedDate__c</fullName>
    <label>Assigned Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assigned Programs</relationshipLabel>
    <relationshipName>AssignedProgram</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Positions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Volunteer</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Board Member</fullName>
    </customValue>
    <customValue>
        <fullName>Trainer</fullName>
    </customValue>
    <customValue>
        <fullName>Client</fullName>
    </customValue>
    <customValue>
        <fullName>Donor</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
        <label>Staff/Contractor</label>
    </customValue>
    <customValue>
        <fullName>Puppy Raiser</fullName>
    </customValue>
    <customValue>
        <fullName>Standalone</fullName>
    </customValue>
    <customValue>
        <fullName>TSiM</fullName>
    </customValue>
    <description>Positions a contact can have</description>
    <masterLabel>Positions</masterLabel>
</GlobalValueSet>

force-app/main/test/TestPositionStatusController.cls
@isTest
public with sharing class TestPositionStatusController {
    @isTest
    public static void getPositionStatusForContact_ReturnsEmptyList_WhenNoPositions() {
        // Arrange
        Contact joe = new Contact(FirstName = 'Joe', LastName = 'Blow');
        insert joe;

        // Act
        List<PositionStatus> statuses = PositionStatusController.getPositionStatusForContact(
            joe.Id
        );

        // Assert
        System.assert(statuses.isEmpty());
    }

    @isTest
    public static void getPositionStatusForContact_ReturnsEmptyList_WhenPositionsBlank() {
        // Arrange
        Contact joe = new Contact(
            FirstName = 'Joe',
            LastName = 'Blow',
            Positions__c = ''
        );
        insert joe;

        // Act
        List<PositionStatus> statuses = PositionStatusController.getPositionStatusForContact(
            joe.Id
        );

        // Assert
        System.assert(statuses.isEmpty());
    }

    @isTest
    public static void getPositionStatusForContact_ReturnsFullList_WhenPositionsFull() {
        // Arrange
        Contact joe = new Contact(
            FirstName = 'Joe',
            LastName = 'Blow',
            Positions__c = 'Client;Volunteer;Trainer;Team Facilitator;Team Facilitator Lead;Puppy Raiser;Board Member',
            GW_Volunteers__Volunteer_Status__c = 'Active',
            FacilitatorStatus__c = 'Certified-Active',
            FacilitatorCertAgreementReceived__c = Date.today().addDays(-250),
            PuppyRaiserStatus__c = 'Inactive',
            PuppyCertAgreementReceived__c = Date.today().addDays(-400),
            BoardMemberStatus__c = 'Onboarding',
            ClientStatus__c = 'In Training',
            ClientCertificationValidUntil__c = Date.today().addDays(300),
            TrainerStatus__c = 'Suspended',
            TrainerCertAgreementReceived__c = Date.today()
        );
        insert joe;
        AtlasSettings__c settings = new AtlasSettings__c();
        upsert settings;
        Program__c program = new Program__c(Name = 'Super Dogs', Standalone__c = true, Months__c = 6);
        insert program;
        ProgramAssignment__c pa = new ProgramAssignment__c(Contact__c = joe.Id, Program__c = program.Id, AssignedDate__c = Date.today());
        insert pa;

        // Act
        List<PositionStatus> statuses = PositionStatusController.getPositionStatusForContact(
            joe.Id
        );

        // Assert
        Integer idx = 0;
        for (string position : PositionStatusController.POSITION_LIST) {
            PositionStatus status = statuses[idx++];
            System.assertEquals(position, status.position);
            //System.assertEquals('Active', statuses[0].status);
        }
        System.assertEquals(PositionStatusController.POSITION_LIST.size(), statuses.size());
    }
}