force-app/main/default/objects/AtlasSettings__c/AtlasSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for the Atlas Assistance Dogs app</description>
    <label>Atlas Settings</label>
</CustomObject>

force-app/main/default/objects/AtlasSettings__c/fields/ShowSiUnits__c.field-meta.xml
<CustomField>
    <fullName>ShowSiUnits__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Show values in SI (System Internationale) units.</description>
    <inlineHelpText>Set to true to display values in SI units.  Values are shown in US units by default.</inlineHelpText>
    <label>Show SI Units</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dog__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <description>Height at shoulders</description>
    <label>Height (in)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/PhysicalExamDue__c.field-meta.xml
<CustomField>
    <fullName>PhysicalExamDue__c</fullName>
    <description>Date the next physical examination is due</description>
    <label>Physical Exam Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/VaccineDueDA2PP__c.field-meta.xml
<CustomField>
    <fullName>VaccineDueDA2PP__c</fullName>
    <description>Date next DA2PP vaccination is due</description>
    <label>DA2PP Vaccine Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/VaccineDueRabies__c.field-meta.xml
<CustomField>
    <fullName>VaccineDueRabies__c</fullName>
    <description>Date next Rabies vaccination is due</description>
    <label>Rabies Vaccine Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <description>Dog&apos;s weight in pounds</description>
    <label>Weight (lb)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DogController.cls
public inherited sharing class DogController {
    @AuraEnabled(cacheable=true)
    public static Dog__c getVaccinations(String recordId) {
        try {
            return [
                SELECT
                    Id,
                    VaccineDueDA2PP__c,
                    VaccineDueRabies__c,
                    PhysicalExamDue__c
                FROM Dog__c
                WHERE Id = :recordId
                LIMIT 1
            ];
        } catch (QueryException exc) {
            AuraHandledException ahe = new AuraHandledException('');
            ahe.setMessage('Dog not found.'); // need to use setMessage for custom message
            throw ahe;
        }
    }

    public class SizeInfo {
        @AuraEnabled
        public Double weight{get; set;}
        @AuraEnabled
        public Double height{get; set;}
        @AuraEnabled
        public Boolean useSiUnits{get; set;}
        public SizeInfo(Dog__c dog, Boolean useSiUnits) {
            this.weight = dog.Weight__c;
            this.height = dog.Height__c;
            this.useSiUnits = useSiUnits;
        }
    }

    @AuraEnabled(cacheable=true)
    public static SizeInfo getSize(Id recordId){
        DogRepository repo = new DogRepository();
        Dog__c dog = repo.getSize(recordId);

        // Get lowest custom settings for this user
        AtlasSettings__c settings = AtlasSettings__c.getInstance();
        if (settings.ShowSiUnits__c == null) {
            settings.ShowSiUnits__c = false; // default to false
            upsert settings;
        }
        return new SizeInfo(dog, settings.ShowSiUnits__c);
    }

    @AuraEnabled
    public static Dog__c setSize(Id recordId, Double height, Double weight){
        DogRepository repo = new DogRepository();
        Dog__c dog = repo.getSize(recordId);
        dog.Height__c = height;
        dog.Weight__c = weight;
        dog = repo.modify(dog);
        return dog;
    }
}