force-app/main/default/objects/AtlasSettings__c/AtlasSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for the Atlas Assistance Dogs app</description>
    <label>Atlas Settings</label>
</CustomObject>

force-app/main/default/objects/AtlasSettings__c/fields/BackgroundCheckRenewalYears__c.field-meta.xml
<CustomField>
    <fullName>BackgroundCheckRenewalYears__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Years between background checks</description>
    <label>Background Check Renewal Years</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BackgroundCheck__c/BackgroundCheck__c.object-meta.xml
<CustomObject>
    <description>Background check record</description>
    <label>Background Check</label>
    <nameField>
        <displayFormat>BC-{0000}</displayFormat>
        <label>Background Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Background Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BackgroundCheck__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contact the background check is for</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Background Checks</relationshipLabel>
    <relationshipName>BackgroundChecks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BackgroundCheck__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Criminal</fullName>
                <default>true</default>
                <label>Criminal</label>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Place/person to contact this person</description>
    <inlineHelpText>Select Guardian to contact this person through their guardian, Home for personal email/phone</inlineHelpText>
    <label>Contact At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
                <default>true</default>
                <label>Home</label>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/VolunteerAccess__c.field-meta.xml
<CustomField>
    <fullName>VolunteerAccess__c</fullName>
    <label>Volunteer Access</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operations- Master Docs - READ ONLY</fullName>
            </value>
            <value>
                <fullName>Operations- Financial</fullName>
            </value>
            <value>
                <fullName>Operations- Client</fullName>
            </value>
            <value>
                <fullName>Operations- Volunteer and Staff</fullName>
            </value>
            <value>
                <fullName>Operations- Trainer</fullName>
            </value>
            <value>
                <fullName>Board - READ ONLY</fullName>
            </value>
            <value>
                <fullName>Board</fullName>
            </value>
            <value>
                <fullName>Sensitive Info- Volunteer and Staff</fullName>
            </value>
            <value>
                <fullName>Sensitive Info- Trainer</fullName>
            </value>
            <value>
                <fullName>Sensitive Info- Board</fullName>
            </value>
            <value>
                <fullName>Active Projects- Academy</fullName>
            </value>
            <value>
                <fullName>Active Projects- ADI</fullName>
            </value>
            <value>
                <fullName>Active Projects- Branding and Marketing</fullName>
            </value>
            <value>
                <fullName>Active Projects- Client Certification</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Community Outreach and Education</fullName>
                <label>Active Projects- Community Outreach and Education</label>
            </value>
            <value>
                <fullName>Active Projects- Dog Availability</fullName>
            </value>
            <value>
                <fullName>Active Projects- Fund Development</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Governance, Compliance and Operations</fullName>
                <label
                >Active Projects- Governance, Compliance and Operations</label>
            </value>
            <value>
                <fullName>Active Projects- Research and Development</fullName>
            </value>
            <value>
                <fullName>Active Projects- Scholarships</fullName>
            </value>
            <value>
                <fullName>Active Projects- State Registration</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Team Facilitator Certification</fullName>
                <label>Active Projects- Team Facilitator Certification</label>
            </value>
            <value>
                <fullName>Active Projects- Technology Infrastructure</fullName>
            </value>
            <value>
                <fullName>Active Projects- Trainer Certification</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Volunteer Recruitment and Retention</fullName>
                <label
                >Active Projects- Volunteer Recruitment and Retention</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contacts.recordType-meta.xml
<RecordType>
    <fullName>Contacts</fullName>
    <active>true</active>
    <label>Contacts</label>
</RecordType>

force-app/main/default/classes/background-checks/BackgroundCheckService.cls
public with sharing class BackgroundCheckService {
  private BackgroundCheckRepository repo;
  private ContactRepository contactRepo;
  private TaskRepository taskRepo;
  public BackgroundCheckService() {
    this.repo = new BackgroundCheckRepository();
    this.contactRepo = new ContactRepository();
    this.taskRepo = new TaskRepository();
  }

  @TestVisible
  private BackgroundCheckService(
    BackgroundCheckRepository bgcrepo,
    ContactRepository contactRepo,
    TaskRepository taskRepo
  ) {
    this.repo = bgcrepo;
    this.contactRepo = contactRepo;
    this.taskRepo = taskRepo;
  }

  public void createReminderTask() {
    AtlasSettings__c settings = AtlasSettings__c.getOrgDefaults();
    // check to see if this setting is missing
    if (settings.BackgroundCheckRenewalYears__c == null) {
      settings.BackgroundCheckRenewalYears__c = 1;
      upsert settings;
    }

    // find the cutoff for which background checks to remind
    Date threshold = Date.today()
      .addYears(-1 * (Integer) settings.BackgroundCheckRenewalYears__c)
      .addMonths(1);

    // Get the group to assign the task to
    Group adminGroup = [
      SELECT Id
      FROM Group
      WHERE Name = 'Background Check Administrator' AND Type = 'Queue'
    ];

    // Make sure we only have one Background check per contact
    Set<Id> contactIds = new Set<Id>();
    Set<Id> creditIds = new Set<Id>();
    Set<Id> criminalIds = new Set<Id>();
    // Check for any contacts that need background checks
    Contact[] contacts = this.contactRepo.getContactsNeedingBackgroundChecks();

    for (Contact person : contacts) {
      contactIds.add(person.Id);
      if (person.VolunteerAccess__c.contains('Credit Check Required')) {
        creditIds.add(person.Id);
      }
      if (person.VolunteerAccess__c.contains('Background Check Required')) {
        criminalIds.add(person.Id);
      }
    }

    BackgroundCheck__c[] checks = repo.getMatchingChecksForContacts(
      contactIds,
      threshold
    );

    // Remove the contacts with recent-enough background checks from the list
    for (BackgroundCheck__c check : checks) {
      if (check.Type__c == 'Criminal') {
        criminalIds.remove(check.Contact__c);
      } else if (check.Type__c == 'Credit') {
        creditIds.remove(check.Contact__c);
      }
    }

    // Create a list of Tasks
    Task[] tasks = new List<Task>();
    // Create tasks to order background checks
    for (Id contactId : criminalIds) {
      tasks.add(
        new Task(
          OwnerId = adminGroup.Id,
          Subject = 'Order background check',
          Status = 'Open',
          Priority = 'Normal',
          WhoId = contactId,
          ActivityDate = Date.today().addMonths(1)
        )
      );
    }
    // Create tasks to order credit checks
    for (Id contactId : creditIds) {
      tasks.add(
        new Task(
          OwnerId = adminGroup.Id,
          Subject = 'Order credit check',
          Status = 'Open',
          Priority = 'Normal',
          WhoId = contactId,
          ActivityDate = Date.today().addMonths(1)
        )
      );
    }

    taskRepo.create(tasks);
  }
}