force-app/main/default/objects/AtlasSettings__c/AtlasSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for the Atlas Assistance Dogs app</description>
    <label>Atlas Settings</label>
</CustomObject>

force-app/main/default/objects/AtlasSettings__c/fields/OrgWideEmailName__c.field-meta.xml
<CustomField>
    <fullName>OrgWideEmailName__c</fullName>
    <description>Org wide email name to use in automated emails</description>
    <label>Org Wide Email Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailTemplate__mdt/EmailTemplate__mdt.object-meta.xml
<CustomObject>
    <description>Email template lookup for automated reminder emails</description>
    <label>Email Template</label>
    <pluralLabel>Email Templates</pluralLabel>
</CustomObject>

force-app/main/default/objects/EmailTemplate__mdt/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <description>Template name to use for this category</description>
    <label>Template Name</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/services/EmailService.cls
public inherited sharing class EmailService {
    public EmailService() {
    }

    public ID getOrgEmailAddressId() {
        AtlasSettings__c settings = AtlasSettings__c.getOrgDefaults();
        String emailName = settings.OrgWideEmailName__c;
        if (emailName == null) {
            settings.OrgWideEmailName__c = 'Atlas Assistance Dogs';
            upsert settings;
        }
        Id addressId = null;
        OrgWideEmailAddress[] addresses = [
            SELECT Id
            FROM OrgWideEmailAddress
            WHERE DisplayName = :emailName
        ];
        if (addresses.size() > 0) {
            addressId = addresses[0].Id;
        }
        return addressId;
    }
    public EmailTemplate getTemplate(String name) {
        EmailTemplate__mdt et = EmailTemplate__mdt.getInstance(name);
        EmailTemplate template = [
            SELECT Id
            FROM EmailTemplate
            WHERE DeveloperName = :et.Template__c
        ];
        return template;
    }
    public void sendEmail(List<Messaging.SingleEmailMessage> emails){
        Messaging.sendEmail(emails);
    }
}