force-app/main/default/objects/Account/fields/Board_Member__c.field-meta.xml
<CustomField>
    <fullName>Board_Member__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Board Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Client</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Main contact email for an organization</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Facilitator__c.field-meta.xml
<CustomField>
    <fullName>Facilitator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Facilitator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>65</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Lead_Facilitator__c.field-meta.xml
<CustomField>
    <fullName>Lead_Facilitator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lead Facilitator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interview Pending</fullName>
            </value>
            <value>
                <fullName>Interview Schedule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trainer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>false</active>
    <description>Client Record Type</description>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Facilitator.recordType-meta.xml
<RecordType>
    <fullName>Facilitator</fullName>
    <active>false</active>
    <description>Facilitator Record Type</description>
    <label>Facilitator</label>
</RecordType>

force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>Records for individuals receiving services from Atlas Assistance Dogs</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Denotes whether a Client is active with Atlas</description>
    <inlineHelpText>Check the box for active, leave unchecked for inacctive</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Lead_Facilitator__c.field-meta.xml
<CustomField>
    <fullName>Lead_Facilitator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This individual serves as the Lead for this client</description>
    <label>Lead (Facilitator)</label>
    <referenceTo>Team_Facilitator__c</referenceTo>
    <relationshipLabel>Clients (Lead (Facilitator))</relationshipLabel>
    <relationshipName>Clients1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This connects the trainer to the client</description>
    <label>Trainer</label>
    <referenceTo>Trainer__c</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>This object contains course records relating to various record types within the contact object</description>
    <label>Course</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Course Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Course_Code__c.field-meta.xml
<CustomField>
    <fullName>Course_Code__c</fullName>
    <label>Course Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <label>Course Name</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Term_SIS__c.field-meta.xml
<CustomField>
    <fullName>Term_SIS__c</fullName>
    <label>Term SIS</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/Course_Master__c.object-meta.xml
<CustomObject>
    <label>Course Master</label>
    <nameField>
        <label>Course Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Master__c/fields/Client_Course__c.field-meta.xml
<CustomField>
    <fullName>Client_Course__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Client Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Common_Course__c.field-meta.xml
<CustomField>
    <fullName>Common_Course__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Common Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Course_Code__c.field-meta.xml
<CustomField>
    <fullName>Course_Code__c</fullName>
    <label>Course Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Course_SIS__c.field-meta.xml
<CustomField>
    <fullName>Course_SIS__c</fullName>
    <label>Course SIS</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Facilitator_Course__c.field-meta.xml
<CustomField>
    <fullName>Facilitator_Course__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Facilitator Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Section_SIS__c.field-meta.xml
<CustomField>
    <fullName>Section_SIS__c</fullName>
    <label>Section SIS</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/Courses_Taken__c.object-meta.xml
<CustomObject>
    <label>Course Assignment</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Courses Taken Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Courses_Taken__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Course Taken</relationshipLabel>
    <relationshipName>Course_Taken</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Formula-AccountName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Assigned_Date__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Date__c</fullName>
    <label>Assigned Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Taken</relationshipLabel>
    <relationshipName>Course_Taken</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Course_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Course_Completion_Date__c</fullName>
    <label>Course Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Course_Description__c.field-meta.xml
<CustomField>
    <fullName>Course_Description__c</fullName>
    <formula>Course_Name__r.Course_SIS_Section_SIS_Course_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course Name</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Taken</relationshipLabel>
    <relationshipName>Course_Taken</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Course_SIS__c.field-meta.xml
<CustomField>
    <fullName>Course_SIS__c</fullName>
    <formula>Course__r.Course_SIS__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Formula Course-SIS</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Expected_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Completion_Date__c</fullName>
    <label>Expected Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Section_SIS__c.field-meta.xml
<CustomField>
    <fullName>Section_SIS__c</fullName>
    <formula>Course__r.Section_SIS__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Formula-Section-SIS</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Replaced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Term_SIS__c.field-meta.xml
<CustomField>
    <fullName>Term_SIS__c</fullName>
    <formula>Course__r.Term_SIS__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Formula Term-SIS</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trainer__c/Trainer__c.object-meta.xml
<CustomObject>
    <label>Trainer</label>
    <nameField>
        <label>Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CourseActionBuilder.cls
public with sharing class CourseActionBuilder{
	static Integer PAGE_SIZE = 10;
	@AuraEnabled(cacheable = true)
	public static pagedResult getAllAccounts(String searchKey, Integer pageNumber){

		String searchId = searchKey.trim();
		String searchCriteria = (String.isBlank(searchId) ? '%' : '%' + searchId + '%');

		Integer pageSize = courseActionBuilder.PAGE_SIZE;
		Integer offset = (pageNumber - 1) * pageSize;

		pagedResult result = new pagedResult();
		result.pageNumber = pageNumber;
		result.pageSize = pageSize;
		result.totalItemCount = Database.countQuery('SELECT count() FROM Account');

		String query = 'SELECT Id, Name From Account Where Name Like :searchCriteria WITH SECURITY_ENFORCED ORDER BY Name LIMIT :pageSize OFFSET :offset';
		List<Account> records = Database.query(query);
		//return records;

		result.records = records;

		return result;
	}

	@AuraEnabled(cacheable = true)
	public static List<Account> getSelectedAccounts(String role){

		return [SELECT Id, Name, (SELECT Id, Name
		                          FROM Course_Taken__r)
		        FROM Account
		        Where Facilitator__c = true AND Id = '001g000002I38BgAAJ'
		        LIMIT 1];
	}

	@AuraEnabled(cacheable = true)
	public static List<Courses_Taken__c> fetchCourse(String courseId){

		return [SELECT Id, Name
		        FROM Courses_Taken__c
		        WHERE Id = :courseId
		        LIMIT 1];
	}

	//AddSelectedCourseToRole
	/*   @AuraEnabled(cacheable=true)
	 public static Integer getAccountsCount(){
	 return [ SELECT Id, Name, First_Name__c, Last_Name__c, Email__c, Board_Member__c, Lead_Facilitator__c, Facilitator__c, Trainer__c, Client__c
	 From Account LIMIt 10];

	 } */
	@AuraEnabled(cacheable = true)
	public static List<Courses_Taken__c> showAssignedCourses(Id account){

		return [SELECT Id, Account_Name__c, Course_Name__c, Course_SIS__c, Section_SIS__c, Course_Description__c, Term_SIS__c, Assigned_Date__c, Expected_Completion_Date__c, Course_Completion_Date__c, Status__c
		        FROM Courses_Taken__c
		        where Account__c = :account];
	}

	@AuraEnabled(cacheable = true)
	public static List<Courses_Taken__c> assignedCoursesForRole(String role){

		List<Courses_Taken__c> lstCourses = new List<Courses_Taken__c>();

		String facilitatorQuery = ' SELECT Id, Account_Name__c, Course_Name__c, Assigned_Date__c, Expected_Completion_Date__c ' + 
								  ' Course_SIS__c, Term_SIS__c, Section_SIS__c ' + 
								  ' FROM Courses_Taken__c ' + 
								  ' WHERE Course__c.Facilitator_Course__c = true ' + 
								  ' AND Common_Course__c = true';


		lstCourses = Database.query(facilitatorQuery);
		return lstCourses;
	}

	@AuraEnabled(cacheable = true)
	public static List<Course_Master__c> getCourses(){

		/*String criteria  = '';

		 if(roles.contains('Facilitator')){
		 criteria = criteria + ' Facilitator_Course__c = true ' ;

		 if(roles.contains('Client')){
		 criteria = criteria + ' AND Client_Course__c = true ' ;
		 }
		 }
		 else if(roles.contains('Client')){
		 criteria = criteria + ' Client_Course__c = true ' ;
		 } */

		/* List<Course_Master__c> result = new List<Course_Master__c>();

		 if(roles.contains('Facilitator') && roles.contains('Client') ){

		 result =  [SELECT Id, Course_Code__c,Course_Name__c FROM Course_Master__c WHERE Active__c = true AND ( Facilitator_Course__c = true OR Client_Course__c = true)];

		 }
		 else  if(roles.contains('Facilitator') && !roles.contains('Client') ){

		 result =  [SELECT Id, Course_Code__c,Course_Name__c FROM Course_Master__c WHERE Active__c = true AND Facilitator_Course__c = true];

		 }
		 else  if(!roles.contains('Facilitator') && roles.contains('Client') ){

		 result = [SELECT Id, Course_Code__c,Course_Name__c FROM Course_Master__c WHERE Active__c = true AND Client_Course__c = true];

		 }

		 return result;


		 String query = 'SELECT Id, Course_Code__c,Course_Name__c FROM Course_Master__c WHERE Active__c = true AND ' + criteria;

		 return Database.query(query); */


		return [SELECT Id, Course_Code__c, Course_Name__c
		        FROM Course_Master__c
		        WHERE Active__c = true];
	}

	/* return [ SELECT
	 Id, Name, Course_Code__c, Course_Name__c,Active__c,
	 Common_Course__c, Client_Course__c,
	 Facilitator_Course__c, Trainerr_Course__c
	 FROM Course_Master__c Where ]; */
}