force-app/main/default/objects/Account/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Client</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Facilitator__c.field-meta.xml
<CustomField>
    <fullName>Facilitator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Facilitator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trainer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>false</active>
    <description>Client Record Type</description>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Facilitator.recordType-meta.xml
<RecordType>
    <fullName>Facilitator</fullName>
    <active>false</active>
    <description>Facilitator Record Type</description>
    <label>Facilitator</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Trainer.recordType-meta.xml
<RecordType>
    <fullName>Trainer</fullName>
    <active>false</active>
    <description>Trainer Record Type</description>
    <label>Trainer</label>
</RecordType>

force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>Records for individuals receiving services from Atlas Assistance Dogs</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Denotes whether a Client is active with Atlas</description>
    <inlineHelpText>Check the box for active, leave unchecked for inacctive</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This connects the trainer to the client</description>
    <label>Trainer</label>
    <referenceTo>Trainer__c</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>This object contains course records relating to various record types within the contact object</description>
    <label>Course</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Course Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Course_Code__c.field-meta.xml
<CustomField>
    <fullName>Course_Code__c</fullName>
    <label>Course Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <label>Course Name</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/Course_Master__c.object-meta.xml
<CustomObject>
    <label>Course Master</label>
    <nameField>
        <label>Course Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Master__c/fields/Client_Course__c.field-meta.xml
<CustomField>
    <fullName>Client_Course__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Client Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Course_Code__c.field-meta.xml
<CustomField>
    <fullName>Course_Code__c</fullName>
    <label>Course Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Facilitator_Course__c.field-meta.xml
<CustomField>
    <fullName>Facilitator_Course__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Facilitator Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Trainer_Course__c.field-meta.xml
<CustomField>
    <fullName>Trainer_Course__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trainer Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/Courses_Taken__c.object-meta.xml
<CustomObject>
    <label>Course Assignment</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Courses Taken Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Courses_Taken__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Course Taken</relationshipLabel>
    <relationshipName>Course_Taken</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Assigned_Date__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Date__c</fullName>
    <label>Assigned Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Taken</relationshipLabel>
    <relationshipName>Course_Taken</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course Name</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Taken</relationshipLabel>
    <relationshipName>Course_Taken</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trainer__c/Trainer__c.object-meta.xml
<CustomObject>
    <label>Trainer</label>
    <nameField>
        <label>Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AddCourses.cls
public with sharing class AddCourses{
	@AuraEnabled
	public static void addSelectedCourses(List<String> roles, List<Id> selectedCourses){

		String criteria;
		List<Course_Master__c> lst = new List<Course_Master__c>();

		if (!roles.contains('Client') && !roles.contains('Trainer') && roles.contains('Facilitator')){


			criteria = ' Facilitator__c = true';

			//lst = [SELECT Id, Name, Course_Code__c, Course_Name__c From Course_Master__c Where Facilitator_Course__c = true AND Active__c = true LIMIT 1 ];
		}

		if (!roles.contains('Client') && roles.contains('Trainer') && !roles.contains('Facilitator')){

			criteria = ' Trainer__c = true';


			//lst = [SELECT Id, Name, Course_Code__c, Course_Name__c From Course_Master__c Where Trainer_Course__c = true AND Active__c = true  ];
		}

		if (roles.contains('Client') && !roles.contains('Trainer') && !roles.contains('Facilitator')){

			criteria = ' Client__c = true ';


			//lst = [SELECT Id, Name, Course_Code__c, Course_Name__c From Course_Master__c Where Client_Course__c = true AND Active__c = true  ];
		}

		if (roles.contains('Facilitator') && roles.contains('Client') && !roles.contains('Trainer')){

			criteria = ' Client__c = true AND Facilitator__c = true ';

		}

		if (roles.contains('Facilitator') && roles.contains('Trainer') && !roles.contains('Client')){

			criteria = ' Trainer__c = true AND Facilitator__c = true ';

		}

		if (roles.contains('Client') && roles.contains('Trainer') && !roles.contains('Facilitator')){

			criteria = ' Trainer__c = true AND Client__c = true ';

		}

		if (roles.contains('Client') && roles.contains('Trainer') && roles.contains('Facilitator')){

			criteria = ' Trainer__c = true AND Client__c = true AND Facilitator__c = true ';

		}


		// List<Account> accountList = [ SELECT Id FROM Account WHERE Client__c = true AND Facilitator__c = true ANd Id = '001g000002JR2BgAAL' LIMIT 1];

		String query = 'SELECT Id FROM Account WHERE ' + criteria;

		List<Account> accountList = Database.query(query);

		List<Course_Master__c> assignedCoursesList = [SELECT Id
		                                              FROM Course_Master__c
		                                              WHERE ID IN :selectedCourses];

		List<Courses_Taken__c> ListToUpdate = new List<Courses_Taken__c>();

		for (Account acc : accountList){

			for (Course_Master__c course : assignedCoursesList){

				Courses_Taken__c c = new Courses_Taken__c();
				c.Course__c = course.Id;
				c.Account__c = acc.Id;
				c.Assigned_Date__c = system.today();

				ListToUpdate.add(c);
			}

		}
		insert ListToUpdate;
		return;
	}
}