force-app/main/default/objects/Account/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>First_Name__c &amp; &quot;, &quot; &amp; Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interview Pending</fullName>
            </value>
            <value>
                <fullName>Interview Schedule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/Courses_Taken__c.object-meta.xml
<CustomObject>
    <label>Course Assignment</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Courses Taken Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Courses_Taken__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Formula-AccountName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Assigned_Date__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Date__c</fullName>
    <label>Assigned Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Course_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Course_Completion_Date__c</fullName>
    <label>Course Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Course_Description__c.field-meta.xml
<CustomField>
    <fullName>Course_Description__c</fullName>
    <formula>Course_Name__r.Course_SIS_Section_SIS_Course_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Expected_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Completion_Date__c</fullName>
    <label>Expected Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Courses_Taken__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Replaced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CourseAssignmentInline.cls
public with sharing class CourseAssignmentInline {
    @AuraEnabled(cacheable=true)
    public static List<Courses_Taken__c> getAssignedCourse(String accountID) {
                return [SELECT Id, Name,
        Course_Description__c, Assigned_Date__c,
        Expected_Completion_Date__c,
     Course_Completion_Date__c, Status__c
     FROM Courses_Taken__c where Account_Name__c = :accountID];
    }

      @AuraEnabled(Cacheable=true)
    public static List <Account> getAcct(String strName) {
        String strNameLike = '%'+strName+'%';
        List<Account> acctList = [SELECT Id,Full_Name__c
                                   FROM Account
                                   Where Full_Name__c like :strNameLike];
        return acctList; }

}