force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interview Pending</fullName>
            </value>
            <value>
                <fullName>Interview Schedule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Facilitator.recordType-meta.xml
<RecordType>
    <fullName>Facilitator</fullName>
    <active>false</active>
    <description>Facilitator Record Type</description>
    <label>Facilitator</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Trainer.recordType-meta.xml
<RecordType>
    <fullName>Trainer</fullName>
    <active>false</active>
    <description>Trainer Record Type</description>
    <label>Trainer</label>
</RecordType>

force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <description>Track progress toward a certification or renewal.  CEUs are be associated with certifications</description>
    <label>Certification</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Trainer or Facilitator</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Certifications</relationshipLabel>
    <relationshipName>Certifications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Certification status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Facilitator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEU__c/CEU__c.object-meta.xml
<CustomObject>
    <label>CEU</label>
    <nameField>
        <displayFormat>CEU-{0000}</displayFormat>
        <label>CEU Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CEUs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CEU__c/fields/Authority__c.field-meta.xml
<CustomField>
    <fullName>Authority__c</fullName>
    <label>CUE Authority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Atlas</fullName>
                <default>true</default>
                <label>Atlas</label>
            </value>
            <value>
                <fullName>KPA</fullName>
            </value>
            <value>
                <fullName>CCPDT</fullName>
            </value>
            <value>
                <fullName>IAABC</fullName>
            </value>
            <value>
                <fullName>CBCC</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEU__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CEUs</relationshipLabel>
    <relationshipName>CEUs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CEU__c/fields/DateCompleted__c.field-meta.xml
<CustomField>
    <fullName>DateCompleted__c</fullName>
    <label>Date Completed</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CEU__c/fields/DateSubmitted__c.field-meta.xml
<CustomField>
    <fullName>DateSubmitted__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date Submitted</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CEU__c/fields/ProgramDate__c.field-meta.xml
<CustomField>
    <fullName>ProgramDate__c</fullName>
    <label>Program Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CEU__c/fields/ProgramHours__c.field-meta.xml
<CustomField>
    <fullName>ProgramHours__c</fullName>
    <label>Program Hours</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CEU__c/fields/ProgramTitle__c.field-meta.xml
<CustomField>
    <fullName>ProgramTitle__c</fullName>
    <label>Program Title</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEU__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Requested CEUs</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CEU__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attendee</fullName>
            </value>
            <value>
                <fullName>Presenter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEU__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Place/person to contact this person</description>
    <inlineHelpText>Select Guardian to contact this person through their guardian, Home for personal email/phone</inlineHelpText>
    <label>Contact At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
                <default>true</default>
                <label>Home</label>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contacts.recordType-meta.xml
<RecordType>
    <fullName>Contacts</fullName>
    <active>true</active>
    <label>Contacts</label>
</RecordType>

force-app/main/test/certifications/TestCertificationRepository.cls
/**
 * This class contains unit tests for validating the behavior of CertificationRepository
 */
@isTest
private class TestCertificationRepository {
  private static CertificationRepository repo = new CertificationRepository();

  @isTest
  static void getForContact_returnsEmpty_whenNullId() {
    List<Certification__c> certs = repo.getForContact(null);
    System.assert(certs.isEmpty(), 'Should be empty');
  }

  @isTest
  static void getForContact_returnsEmpty_whenNotContactId() {
    List<Certification__c> certs = repo.getForContact(
      MockProvider.createId(Account.class)
    );
    System.assert(certs.isEmpty(), 'Should be empty');
  }

  @IsTest
  static void getForContact_returnsEmpty_whenNoCertifications() {
    Contact con = new Contact(FirstName = 'John', LastName = 'Smith');
    insert con;
    List<Certification__c> certs = repo.getForContact(
      MockProvider.createId(Account.class)
    );
    System.assert(certs.isEmpty(), 'Should be empty');
  }

  // Create certification for 2 contacts of both Trainer and Facilitator
  // types and going back 3 years
  static private void createCertifications(Contact con1, Contact con2) {
    Certification__c[] certs = new List<Certification__c>();
    for (Integer i = 3; i >= 0; i--) {
      for (Certification__c cert : certs) {
        cert.Status__c = 'Complete';
      }
      update certs;

      certs.clear();
      String status = 'Active';
      certs.add(
        new Certification__c(
          Status__c = status,
          Contact__c = con1.Id,
          End__c = Date.today().addYears(-i),
          Start__c = Date.today().addYears(-i + 1),
          Type__c = 'Trainer'
        )
      );
      certs.add(
        new Certification__c(
          Status__c = status,
          Contact__c = con1.Id,
          End__c = Date.today().addYears(-i),
          Start__c = Date.today().addYears(-i + 1),
          Type__c = 'Facilitator'
        )
      );
      certs.add(
        new Certification__c(
          Status__c = status,
          Contact__c = con2.Id,
          End__c = Date.today().addYears(-i),
          Start__c = Date.today().addYears(-i + 1),
          Type__c = 'Trainer'
        )
      );
      certs.add(
        new Certification__c(
          Status__c = status,
          Contact__c = con2.Id,
          End__c = Date.today().addYears(-i),
          Start__c = Date.today().addYears(-i + 1),
          Type__c = 'Facilitator'
        )
      );
      insert certs;

      Certification__c cert = certs[0];
      CEU__c[] ceus = new List<CEU__c>();
      // Create CEUS for these certs
      for (Integer j = 0; j < 5; j++) {
        Date day = cert.Start__c.addMonths(j + 1);
        ceus.add(
          new Ceu__c(
            Authority__c = 'Atlas',
            Comments__c = 'Comments1',
            DateCompleted__c = day,
            DateSubmitted__c = day,
            ProgramDate__c = day,
            ProgramHours__c = 2,
            ProgramTitle__c = 'A Day in the Life of a Dog',
            Quantity__c = 2,
            Role__c = 'Attendee',
            Status__c = 'Approved',
            Contact__c = con2.Id
          )
        );
        ceus.add(
          new Ceu__c(
            Authority__c = 'Atlas',
            Comments__c = 'Comments1',
            DateCompleted__c = day,
            DateSubmitted__c = day,
            ProgramDate__c = day,
            ProgramHours__c = 2,
            ProgramTitle__c = 'A Day in the Life of a Dog',
            Quantity__c = 2,
            Role__c = 'Attendee',
            Status__c = 'Approved',
            Contact__c = con1.Id
          )
        );
      }
      insert ceus;
    }
  }

  @IsTest
  static void getForContact_returnsCertifications() {
    Contact con1 = new Contact(FirstName = 'John', LastName = 'Smith');
    Contact con2 = new Contact(FirstName = 'Sarah', LastName = 'Smith');
    insert new List<Contact>{ con1, con2 };
    createCertifications(con1, con2);
    // Act
    List<Certification__c> actual = repo.getForContact(con1.Id);
    // Assert
    System.Assert.areEqual(6, actual.size(), 'Should have 6');
  }
}