force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Atlas Program</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Months__c.field-meta.xml
<CustomField>
    <fullName>Months__c</fullName>
    <description>Duration in Months</description>
    <label>Months</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProgramDuration__mdt/ProgramDuration__mdt.object-meta.xml
<CustomObject>
    <description>Expected duration for a program</description>
    <label>Program Duration</label>
    <pluralLabel>Program Durations</pluralLabel>
</CustomObject>

force-app/main/default/objects/ProgramDuration__mdt/fields/Months__c.field-meta.xml
<CustomField>
    <fullName>Months__c</fullName>
    <description>Duration in months</description>
    <label>Months</label>
    <precision>6</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProgramDuration__mdt/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Atlas training program</description>
    <label>Program</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sweet Snoopers Trainer</fullName>
                <default>true</default>
                <label>Sweet Snoopers Trainer</label>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Teams Set in Motion Client</fullName>
            </value>
            <value>
                <fullName>Team Facilitator</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Settings.cls
public with sharing class Settings {
    @TestVisible
    public static Map<String, Decimal> programDurations {
        get {
            if (programDurations == null) {
                ProgramDuration__mdt[] durations = [
                    SELECT Months__c, Program__c
                    FROM ProgramDuration__mdt
                ];
                programDurations = new Map<String, Decimal>();
                for (ProgramDuration__mdt duration : durations) {
                    programDurations.put(
                        duration.Program__c,
                        duration.Months__c
                    );
                }
            }

            return programDurations;
        }
        private set {
            programDurations = value;
        }
    }
}