force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Atlas Program</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Reminder__c.field-meta.xml
<CustomField>
    <fullName>Reminder__c</fullName>
    <description>Remind the contact x days before expected completion</description>
    <label>Reminder</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/ProgramAssignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Program Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramAssignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assigned Programs</relationshipLabel>
    <relationshipName>AssignedProgram</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/ExpectedCompletion__c.field-meta.xml
<CustomField>
    <fullName>ExpectedCompletion__c</fullName>
    <description>Expected completion date</description>
    <label>Expected Completion</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/programs/Reminders.cls
global class Reminders implements Schedulable {
  private final String groupName;

  // default constructor
  public Reminders() {
    groupName = 'Program Administrator';
  }

  // used for test
  public Reminders(String name) {
    groupName = name;
  }

  global void execute(SchedulableContext SC) {
    // Find out which assignments may need reminder tasks.
    // Note we cannot join with Tasks since that is not supported.
    // NOTE: We need to use literals when filtering dates, so break down by weeks and hit the
    // ones we expect to see most
    List<ProgramAssignment__c> assignments = [
      SELECT
        id,
        Contact__c,
        ExpectedCompletion__c,
        Program__r.Name,
        Program__r.Reminder__c
      FROM ProgramAssignment__c
      WHERE
        Status__c = 'In progress'
        AND Program__r.Reminder__c != 0
        AND ((Program__r.Reminder__c >= 30
        AND ExpectedCompletion__c <= NEXT_N_DAYS:30)
        OR (Program__r.Reminder__c >= 21
        AND ExpectedCompletion__c <= NEXT_N_DAYS:21)
        OR (Program__r.Reminder__c >= 14
        AND ExpectedCompletion__c <= NEXT_N_DAYS:14)
        OR (Program__r.Reminder__c >= 7
        AND ExpectedCompletion__c <= NEXT_N_DAYS:7)
        OR ExpectedCompletion__c = TODAY)
    ];

    Group adminGroup = [
      SELECT id
      FROM Group
      WHERE Name = :groupName
      LIMIT 1
    ];

    // Create a reminder task if one wasn't already created
    for (ProgramAssignment__c assignment : assignments) {
      if (
        Date.today().addDays((integer) assignment.Program__r.Reminder__c) <
        assignment.ExpectedCompletion__c
      ) {
        continue; // don't need to remind yet
      }
      List<Task> createdTasks = [
        SELECT id
        FROM TASK
        WHERE WhatId = :assignment.id
      ];
      if (createdTasks.size() == 0) {
        // Create a reminder task
        Task newTask = new Task(
          OwnerId = adminGroup.id,
          Description = 'Check on Program progress',
          Priority = 'Normal',
          Type = 'Call',
          Subject = 'Other',
          WhatId = assignment.id,
          WhoId = assignment.Contact__c,
          IsReminderSet = true,
          ReminderDateTime = System.now()
        );
        insert newTask;
      }
    }
  }
}