force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Atlas Program</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramAssignment__c/ProgramAssignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Program Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramAssignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assigned Programs</relationshipLabel>
    <relationshipName>AssignedProgram</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/ExpectedCompletion__c.field-meta.xml
<CustomField>
    <fullName>ExpectedCompletion__c</fullName>
    <description>Expected completion date</description>
    <label>Expected Completion</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Reminders.cls
global class Reminders implements Schedulable {
    public Reminders() {
    }

    global void execute(SchedulableContext SC) {
        Date month = Date.today().addMonths(1);
        Date week = Date.today().addDays(7);
        // Find out which assignments may need reminder tasks.
        // Note we cannot join with Tasks since that is not supported.
        List<ProgramAssignment__c> assignments = [
            SELECT id, Contact__c, ExpectedCompletion__c
            FROM ProgramAssignment__c
            WHERE
                Status__c = 'In progress'
                AND ((Program__c = 'Volunteer'
                AND ExpectedCompletion__c <= :week)
                OR (Program__c != 'Volunteer'
                AND ExpectedCompletion__c <= :month))
        ];

        Group adminGroup = [
            SELECT id
            FROM Group
            WHERE Name = 'Program Administrator'
            LIMIT 1
        ];
        // Create a reminder task if one hasn't been already created
        for (ProgramAssignment__c assignment : assignments) {
            List<Task> createdTasks = [
                SELECT id
                FROM TASK
                WHERE WhatId = :assignment.id
            ];
            if (createdTasks.size() == 0) {
                // Create a reminder task
                Task newTask = new Task(
                    OwnerId = adminGroup.id,
                    Description = 'Check on Program progress',
                    Priority = 'Normal',
                    Type = 'Call',
                    Subject = 'Other',
                    WhatId = assignment.id,
                    WhoId = assignment.Contact__c,
                    IsReminderSet = true,
                    ReminderDateTime = System.now()
                );
                insert newTask;
            }
        }
    }
}