force-app/main/default/objects/ContinuingEducationUnit__c/ContinuingEducationUnit__c.object-meta.xml
<CustomObject>
    <description>Continuing Education Units</description>
    <label>CEU</label>
    <nameField>
        <label>CEU Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEUs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ContinuingEducationUnit__c/fields/Authority__c.field-meta.xml
<CustomField>
    <fullName>Authority__c</fullName>
    <label>CUE Authority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Atlas</fullName>
                <default>true</default>
                <label>Atlas</label>
            </value>
            <value>
                <fullName>KPA</fullName>
            </value>
            <value>
                <fullName>CCPDT</fullName>
            </value>
            <value>
                <fullName>IAABC</fullName>
            </value>
            <value>
                <fullName>CBCC</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContinuingEducationUnit__c/fields/AuthorityOther__c.field-meta.xml
<CustomField>
    <fullName>AuthorityOther__c</fullName>
    <label>CUE Authority (Other)</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContinuingEducationUnit__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/ContinuingEducationUnit__c/fields/DateCompleted__c.field-meta.xml
<CustomField>
    <fullName>DateCompleted__c</fullName>
    <label>Date Completed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ContinuingEducationUnit__c/fields/DateSubmitted__c.field-meta.xml
<CustomField>
    <fullName>DateSubmitted__c</fullName>
    <label>Date Submitted</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ContinuingEducationUnit__c/fields/ProgramDate__c.field-meta.xml
<CustomField>
    <fullName>ProgramDate__c</fullName>
    <label>Program Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ContinuingEducationUnit__c/fields/ProgramHours__c.field-meta.xml
<CustomField>
    <fullName>ProgramHours__c</fullName>
    <label>Program Hours</label>
    <precision>5</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContinuingEducationUnit__c/fields/ProgramTitle__c.field-meta.xml
<CustomField>
    <fullName>ProgramTitle__c</fullName>
    <label>Program Title</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContinuingEducationUnit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContinuingEducationUnit__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Trainer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CEUs</relationshipLabel>
    <relationshipName>CEUs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trainer__c/Trainer__c.object-meta.xml
<CustomObject>
    <label>Trainer</label>
    <nameField>
        <label>Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/continuing-education-units/ContinuingEducationUnitController.cls
public with sharing class ContinuingEducationUnitController {
  // This method is used by the related list component
  @AuraEnabled(Cacheable=true)
  public static RelatedObjects getRelatedCeus(Id contactId, Integer max) {
    if (max == null) {
      max = 6;
    }
    try {
      RelatedObjects related = new RelatedObjects();
      List<ContinuingEducationUnit__c> ceus = [
        SELECT
          Authority__c,
          AuthorityOther__c,
          Comments__c,
          DateCompleted__c,
          DateSubmitted__c,
          Name,
          ProgramDate__c,
          ProgramHours__c,
          ProgramTitle__c,
          Quantity__c,
          Role__c,
          Status__c,
          Trainer__c
        FROM ContinuingEducationUnit__c
        WHERE Trainer__c = :contactId
        LIMIT :max
      ];
      for (ContinuingEducationUnit__c ceu : ceus) {
        related.items.add(ceu);
      }
      related.total = [
        SELECT COUNT()
        FROM ContinuingEducationUnit__c
        WHERE Trainer__c = :contactId
      ];
      return related;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}