force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dog__c/fields/VacExamsReceived__c.field-meta.xml
<CustomField>
    <fullName>VacExamsReceived__c</fullName>
    <description
    >The date the most recent version of Vaccinations and Exams was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last  Vaccinations and Exams</label>
    <type>Date</type>
</CustomField>

force-app/main/test/file-dates/TestFileServiceDogFields.cls
@isTest
public with sharing class TestFileServiceDogFields {


    @isTest
    public static void updateDate_DogVacExams_SetsDateWhenNull() {
        Dog__c record = new Dog__c(Name = 'Fido');
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Dog', 'VacExams', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT VacExamsReceived__c
            FROM Dog__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.VacExamsReceived__c,
            'VacExamsReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_DogVacExams_SetsDateWhenNewer() {
        Dog__c record = new Dog__c(Name = 'Fido', VacExamsReceived__c = Date.today().addDays(-1));
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Dog', 'VacExams', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT VacExamsReceived__c
            FROM Dog__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.VacExamsReceived__c,
            'VacExamsReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_DogVacExams_LeavesDateWhenOlder() {
        Dog__c record = new Dog__c(Name = 'Fido', VacExamsReceived__c = Date.today());
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Dog', 'VacExams', Date.today().addDays(-1), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT VacExamsReceived__c
            FROM Dog__c
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.VacExamsReceived__c,
            'VacExamsReceived__c set to an older date'
        );
    }
}