force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dog__c/fields/PhysicalExamDue__c.field-meta.xml
<CustomField>
    <fullName>PhysicalExamDue__c</fullName>
    <description>Date the next physical examination is due</description>
    <label>Physical Exam Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/VaccineDueDA2PP__c.field-meta.xml
<CustomField>
    <fullName>VaccineDueDA2PP__c</fullName>
    <description>Date next DA2PP vaccination is due</description>
    <label>DA2PP Vaccine Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/VaccineDueRabies__c.field-meta.xml
<CustomField>
    <fullName>VaccineDueRabies__c</fullName>
    <description>Date next Rabies vaccination is due</description>
    <label>Rabies Vaccine Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/dogs/DogController.cls
public inherited sharing class DogController {
  @AuraEnabled(cacheable=true)
  public static Dog__c getVaccinations(String recordId) {
    try {
      return [
        SELECT Id, VaccineDueDA2PP__c, VaccineDueRabies__c, PhysicalExamDue__c
        FROM Dog__c
        WHERE Id = :recordId
        LIMIT 1
      ];
    } catch (QueryException exc) {
      AuraHandledException ahe = new AuraHandledException('');
      ahe.setMessage('Dog not found.'); // need to use setMessage for custom message
      throw ahe;
    }
  }
}