force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dog__c/fields/Most_Recent_Hepatitis_Vaccine__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Hepatitis_Vaccine__c</fullName>
    <description>Hepatitis/Adenovirus vaccination expiration date</description>
    <inlineHelpText>Latest  Hepatitis/Adenovirus vaccination date</inlineHelpText>
    <label>Hepatitis Vaccine Expiration date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/Most_Recent_Parainfluenza_Vaccine__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Parainfluenza_Vaccine__c</fullName>
    <description>Most recent Parainfluenza Vaccine</description>
    <inlineHelpText>Most recent Parainfluenza vaccine Date</inlineHelpText>
    <label>Most Recent Parainfluenza Vaccine</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/Most_Recent_Parvovirus_Vaccine__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Parvovirus_Vaccine__c</fullName>
    <description>Most recent Parvovirus vaccine date</description>
    <inlineHelpText>Most recent Parvovirus Vaccine date</inlineHelpText>
    <label>Most Recent Parvovirus Vaccine</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/Most_Recent_Physical_Exam__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Physical_Exam__c</fullName>
    <description>Most recent Physical exam</description>
    <inlineHelpText>Most recend Physical exam</inlineHelpText>
    <label>Most Recend Physical Exam</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/Most_Recent_Rabies_Vaccine__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Rabies_Vaccine__c</fullName>
    <description>Rabies Vaccination Expiration Date</description>
    <inlineHelpText>Rabies Vaccination Expiration Date</inlineHelpText>
    <label>Rabies Vaccine Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/DogHandler.cls
public with sharing class DogHandler{
	@AuraEnabled(cacheable = true)
	public static Dog__c getVaccinatios(String recordId){

		Dog__c dog = new Dog__c();

		dog = [SELECT Id, Most_Recent_Hepatitis_Vaccine__c, Most_Recent_Parainfluenza_Vaccine__c, Most_Recent_Parvovirus_Vaccine__c, Most_Recent_Rabies_Vaccine__c, Most_Recent_Physical_Exam__c
		       FROM Dog__c
		       WHERE Id = :recordId
		       LIMIT 1];

		if (dog != null){
			return dog;
		} else{
			return null;
		}
	}
}