force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dog__c/fields/VaccineDueDA2PP__c.field-meta.xml
<CustomField>
    <fullName>VaccineDueDA2PP__c</fullName>
    <description>Date next DA2PP vaccination is due</description>
    <label>DA2PP Vaccine Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/VaccineDueDistemper__c.field-meta.xml
<CustomField>
    <fullName>VaccineDueDistemper__c</fullName>
    <description>Date next Distemper vaccination is due</description>
    <label>Distemper Vaccine Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/VaccineDueHepatitis__c.field-meta.xml
<CustomField>
    <fullName>VaccineDueHepatitis__c</fullName>
    <description>Date next Hepatitis/Adenovirus vaccination is due</description>
    <label>Hepatitis/Adenovirus Vaccination Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/VaccineDueParainfluenza__c.field-meta.xml
<CustomField>
    <fullName>VaccineDueParainfluenza__c</fullName>
    <description>Date next Parainfluenza vaccine is due</description>
    <label>Parainfluenza Vaccine Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/VaccineDueParvovirus__c.field-meta.xml
<CustomField>
    <fullName>VaccineDueParvovirus__c</fullName>
    <description>Date next Parvovirus vaccination is due</description>
    <label>Parvovirus Vaccine Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PostInstall.cls
global class PostInstall implements InstallHandler {
    global void onInstall(InstallContext context) {
        if (context == null) {
            return;
        }
        if (context.previousVersion() == null) {
            return;
        }
        if (context.previousVersion().compareTo(new Version(1, 3)) <= 0) {
            // combine dog vaccine fields
            List<Dog__c> dogs = [
                SELECT
                    Name,
                    VaccineDueDA2PP__c,
                    VaccineDueDistemper__c,
                    VaccineDueHepatitis__c,
                    VaccineDueParainfluenza__c,
                    VaccineDueParvovirus__c
                FROM Dog__c
            ];
            for (Dog__c dog : dogs) {
                system.debug(dog);
                Date latest = later(
                    dog.VaccineDueDistemper__c,
                    dog.VaccineDueHepatitis__c
                );
                latest = later(latest, dog.VaccineDueParainfluenza__c);
                latest = later(latest, dog.VaccineDueParvovirus__c);
                dog.VaccineDueDA2PP__c = latest;
            }
            update dogs;
        }
    }

    private Date later(Date latest, Date vaccine) {
        if (latest == null) {
            return vaccine;
        }
        if (vaccine > latest) {
            return vaccine;
        }
        return latest;
    }
}