force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DogRelationship__c/DogRelationship__c.object-meta.xml
<CustomObject>
    <description>Connection between a dog and a contact</description>
    <label>Dog Relationship</label>
    <nameField>
        <displayFormat>DR-{00000}</displayFormat>
        <label>Dog Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dogs Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DogRelationship__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Dogs</relationshipLabel>
    <relationshipName>DogsContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DogRelationship__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A dog for this contact</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>Humans</relationshipLabel>
    <relationshipName>DogsContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DogRelationship__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
    >Team the dog and human are on.  Only valid if the relationship is dog-client or dog-trainer.</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Dogs Relationships</relationshipLabel>
    <relationshipName>Dogs_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Records the Facilitator, Lead, and Client relationship</description>
    <label>Team</label>
    <nameField>
        <displayFormat>Team-{00000}</displayFormat>
        <label>Team Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dog on the team</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Facilitator__c.field-meta.xml
<CustomField>
    <fullName>Facilitator__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Facilitator</description>
    <label>Facilitator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams (Facilitator)</relationshipLabel>
    <relationshipName>Teams2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Handler in the team, if not the client</description>
    <label>Handler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/NextPatDue__c.field-meta.xml
<CustomField>
    <fullName>NextPatDue__c</fullName>
    <description>Date the next Public Access Test is due</description>
    <label>Next PAT Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/PatCount__c.field-meta.xml
<CustomField>
    <fullName>PatCount__c</fullName>
    <description
    >Number of Public Access Tests the Client-Dog team has taken</description>
    <label>PAT Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/PrimaryCertification__c.field-meta.xml
<CustomField>
    <fullName>PrimaryCertification__c</fullName>
    <label>Primary Certification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Certifications</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team__c/fields/SecondaryCertification__c.field-meta.xml
<CustomField>
    <fullName>SecondaryCertification__c</fullName>
    <label>Secondary Certification</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Certifications</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Trainer in the team</description>
    <label>Trainer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trainer__c/Trainer__c.object-meta.xml
<CustomObject>
    <label>Trainer</label>
    <nameField>
        <label>Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trainer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field connects the trainer object to his/her contact information</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trainers</relationshipLabel>
    <relationshipName>Trainers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Certifications.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Atlas</fullName>
        <default>true</default>
        <label>Atlas</label>
    </customValue>
    <customValue>
        <fullName>KPA</fullName>
    </customValue>
    <customValue>
        <fullName>CCPDT</fullName>
    </customValue>
    <customValue>
        <fullName>IAABC</fullName>
    </customValue>
    <customValue>
        <fullName>CBCC</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <description>Client Dog Team Certifications</description>
    <masterLabel>Certifications</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TeamController.cls
public with sharing class TeamController {
    @AuraEnabled(Cacheable=true)
    public static List<Team__c> getRelatedTeams(id recordId) {
        try {
            List<Team__c> teams = [
                SELECT
                    Facilitator__c,
                    Handler__c,
                    NextPatDue__c,
                    PatCount__c,
                    PrimaryCertification__c,
                    SecondaryCertification__c,
                    Trainer__c
                FROM Team__c
                WHERE
                    Facilitator__c = :recordId
                    OR Handler__c = :recordId
                    OR Trainer__c = :recordId
            ];
            List<DogRelationship__c> relationships = [
                SELECT Team__c
                FROM DogRelationship__c
                WHERE
                    (Contact__c = :recordId
                    OR Dog__c = :recordId)
                    AND Team__c != NULL
            ];

            List<ID> relatedTeams = new List<ID>();

            for (DogRelationship__c relationship : relationships) {
                relatedTeams.add(relationship.Team__c);
            }

            teams.addall(
                [
                    SELECT
                        Facilitator__c,
                        Handler__c,
                        NextPatDue__c,
                        PatCount__c,
                        PrimaryCertification__c,
                        SecondaryCertification__c,
                        Trainer__c
                    FROM Team__c
                    WHERE Id IN :relatedTeams
                ]
            );

            return teams;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}