force-app/main/default/objects/Contact/fields/AbilityStatus__c.field-meta.xml
<CustomField>
    <fullName>AbilityStatus__c</fullName>
    <label>Ability Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blind/Low vision</fullName>
            </value>
            <value>
                <fullName>Deaf/Hard of hearing</fullName>
            </value>
            <value>
                <fullName
                >Learning disability/cognitive processing disability</fullName>
                <label
                >Learning disability/cognitive processing disability</label>
            </value>
            <value>
                <fullName>Chronic medical illness</fullName>
            </value>
            <value>
                <fullName>Mental health condition</fullName>
            </value>
            <value>
                <fullName>Mobility/ambulatory difficulty</fullName>
            </value>
            <value>
                <fullName>Sensory processing disorder</fullName>
            </value>
            <value>
                <fullName>Intellectual disability</fullName>
            </value>
            <value>
                <fullName>None/do not identify with a disability</fullName>
            </value>
            <value>
                <fullName>Prefer to self-describe</fullName>
            </value>
            <value>
                <fullName>Prefer not to answer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Place/person to contact this person</description>
    <inlineHelpText>Select Guardian to contact this person through their guardian, Home for personal email/phone</inlineHelpText>
    <label>Contact At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
                <default>true</default>
                <label>Home</label>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>This field is configured in NPSP Settings &gt; Relationships &gt; Relationships as the Gender field. Do not delete this field unless you remove the reference or select another Gender field there.</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/PreferredName__c.field-meta.xml
<CustomField>
    <fullName>PreferredName__c</fullName>
    <description>Contact Preferred Name</description>
    <inlineHelpText>This defaults to the contact&apos;s first name, and will be filled in as such if left empty.</inlineHelpText>
    <label>Preferred Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Pronoun__c.field-meta.xml
<CustomField>
    <fullName>Pronoun__c</fullName>
    <label>Pronoun</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Pronouns</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/PronounOther__c.field-meta.xml
<CustomField>
    <fullName>PronounOther__c</fullName>
    <label>Specified Pronoun</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SpecifiedAbilityStatus__c.field-meta.xml
<CustomField>
    <fullName>SpecifiedAbilityStatus__c</fullName>
    <label>Specified Ability Status</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contacts.recordType-meta.xml
<RecordType>
    <fullName>Contacts</fullName>
    <active>true</active>
    <label>Contacts</label>
</RecordType>

force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dog__c/fields/AgeYears__c.field-meta.xml
<CustomField>
    <fullName>AgeYears__c</fullName>
    <description>Current Age of Dog</description>
    <formula>(Today() -  Birthdate__c) / 365</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age (Years)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/Breed__c.field-meta.xml
<CustomField>
    <fullName>Breed__c</fullName>
    <description>Describes the dog&apos;s breed</description>
    <label>Breed</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program the dog is in training for/certified for</description>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assistance Dogs Set In Motion</fullName>
            </value>
            <value>
                <fullName>Team Certification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Derived from Team.  Do not edit directly.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In ADSiM</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Certified-Active</fullName>
            </value>
            <value>
                <fullName>Certified-OnHold</fullName>
            </value>
            <value>
                <fullName>Decertified</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DogRelationship__c/DogRelationship__c.object-meta.xml
<CustomObject>
    <description>Connection between a dog and a contact</description>
    <label>Dog Relationship</label>
    <nameField>
        <displayFormat>DR-{00000}</displayFormat>
        <label>Dog Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dogs Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DogRelationship__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Dogs</relationshipLabel>
    <relationshipName>DogsContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DogRelationship__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A dog for this contact</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>Humans</relationshipLabel>
    <relationshipName>DogsContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DogRelationship__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Relationship types between a dog and contact</description>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Veterinarian</fullName>
            </value>
            <value>
                <fullName>Handler</fullName>
            </value>
            <value>
                <fullName>Facilitator</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Atlas Program</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Standalone__c.field-meta.xml
<CustomField>
    <fullName>Standalone__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Program isn&apos;t part of a certification program.  Program goes into &quot;Other&quot; category if checked.</description>
    <inlineHelpText>Program isn&apos;t part of a certification program.</inlineHelpText>
    <label>Standalone Program</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/ProgramAssignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Program Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramAssignment__c/fields/AssignedDate__c.field-meta.xml
<CustomField>
    <fullName>AssignedDate__c</fullName>
    <label>Assigned Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/CompletionDate__c.field-meta.xml
<CustomField>
    <fullName>CompletionDate__c</fullName>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assigned Programs</relationshipLabel>
    <relationshipName>AssignedProgram</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/ExpectedCompletion__c.field-meta.xml
<CustomField>
    <fullName>ExpectedCompletion__c</fullName>
    <description>Expected completion date</description>
    <label>Expected Completion</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Pronouns.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>They/Them</fullName>
    </customValue>
    <customValue>
        <fullName>He/Him</fullName>
    </customValue>
    <customValue>
        <fullName>She/Her</fullName>
    </customValue>
    <customValue>
        <fullName>Prefer to self-describe</fullName>
    </customValue>
    <customValue>
        <fullName>Prefer not to answer</fullName>
    </customValue>
    <description>Pronouns for a contact</description>
    <masterLabel>Pronouns</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/programs/ProgramAssignmentController.cls
/* Methods for finding and updating contacts */
public inherited sharing class ProgramAssignmentController {
  @AuraEnabled(Cacheable=true)
  public static List<ProgramAssignment__c> getProgramAssignments(Id contactId) {
    try {
      return [
        SELECT
          AssignedDate__c,
          CompletionDate__c,
          ExpectedCompletion__c,
          Program__c,
          Program__r.Name,
          Program__r.Standalone__c,
          Status__c
        FROM ProgramAssignment__c
        WHERE Contact__c = :contactId
      ];
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled(Cacheable=true)
  public static RelatedObjects getReport(string name) {
    List<ProgramAssignment__c> pas = [
      SELECT
        Program__r.Name,
        Contact__c,
        Status__c,
        AssignedDate__c,
        Contact__r.Name,
        Contact__r.MailingAddress,
        Contact__r.AbilityStatus__c,
        Contact__r.SpecifiedAbilityStatus__c,
        Contact__r.FirstName,
        Contact__r.LastName,
        Contact__r.PreferredName__c,
        Contact__r.Pronoun__c,
        Contact__r.PronounOther__c,
        Contact__r.Email
      FROM ProgramAssignment__c
      WHERE Program__r.Name = :name AND Status__c IN ('In Progress', 'Pending')
      ORDER BY AssignedDate__c
    ];

    RelatedObjects related = new RelatedObjects();
    related.total = pas.size();

    for (ProgramAssignment__c pa : pas) {
      ProgramReportRow row = new ProgramReportRow();
      row.pa = pa;
      row.contact = pa.Contact__r;
      try {
        DogRelationShip__c relatedDog = [
          SELECT
            Dog__c,
            Dog__r.Name,
            Dog__r.AgeYears__c,
            Dog__r.Breed__c,
            Dog__r.Gender__c
          FROM DogRelationShip__c
          WHERE
            Contact__c = :pa.Contact__c
            AND Type__c INCLUDES ('Owner', 'Client', 'Handler')
          LIMIT 1
        ];
        row.dog = relatedDog.Dog__r;
      } catch (Exception exc) {
      }
      related.items.add(row);
    }
    return related;
  }
  /*
    public static void sendReportEmail(RelatedObjects report, string email) {
        String generatedCSVFile = '';
        String fileRow = '';

        for (company__c company : extractcompanyMemList) {
            fileRow = '';
            fileRow = fileRow + ',' + company.Id;
            fileRow = fileRow + ',' + company.Name;
            fileRow = fileRow.replaceFirst(',', '');
            generatedCSVFile = generatedCSVFile + fileRow + '\n';
        }

        Messaging.EmailFileAttachment csvAttachment = new Messaging.EmailFileAttachment();
        Blob csvBlob = blob.valueOf(generatedCSVFile);
        String csvName = 'report.csv';
        csvAttachment.setFileName(csvName);
        csvAttachment.setBody(csvBlob);
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        String[] toAddresses = new List<String>{ 'Your Email Id' };
        String subject = 'Report';
        email.setSubject(subject);
        email.setToAddresses(toAddresses);
        email.setPlainTextBody('Report');
        email.setFileAttachments(
            new List<Messaging.EmailFileAttachment>{ csvAttachment }
        );
        Messaging.SendEmailResult[] r = Messaging.sendEmail(
            new List<Messaging.SingleEmailMessage>{ email }
        );
    }*/
}