force-app/main/default/objects/Contact/fields/ADSiMApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>ADSiMApplicationReceived__c</fullName>
    <description
    >The date the most recent version of Assistance Dogs Set in Motion Application was uploaded</description>
    <label>Last ADSiM Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ADSiMPreApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>ADSiMPreApplicationReceived__c</fullName>
    <description>The date the most recent version of Assistance Dogs Set in Motion Pre Application was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last ADSiM Pre Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ADSiMProgAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>ADSiMProgAgreementReceived__c</fullName>
    <description
    >The date the most recent version of Assistance Dogs Set in Motion Program Agreement was uploaded</description>
    <label>Last ADSiM Program Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BoardAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>BoardAgreementReceived__c</fullName>
    <description
    >The date the most recent version of Board Agreement was uploaded</description>
    <label>Last Board Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BoardApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>BoardApplicationReceived__c</fullName>
    <description
    >The date the most recent version of Board Application was uploaded</description>
    <label>Last Board Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BoardCoIReceived__c.field-meta.xml
<CustomField>
    <fullName>BoardCoIReceived__c</fullName>
    <description
    >The date the most recent version of Board Conflict of Interest was uploaded</description>
    <label>Last Board Conflict of Interest</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BoardResumeReceived__c.field-meta.xml
<CustomField>
    <fullName>BoardResumeReceived__c</fullName>
    <description>The date the most recent version of Board Resume was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Board Resume</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BoardToNReceived__c.field-meta.xml
<CustomField>
    <fullName>BoardToNReceived__c</fullName>
    <description
    >The date the most recent version of Board Transmission of Notices was uploaded</description>
    <label>Last Board Transmission of Notices</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientApplicationReceived__c</fullName>
    <description
    >The date the most recent version of Client Application was uploaded</description>
    <label>Last Client Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientLOMIReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientLOMIReceived__c</fullName>
    <description
    >The date the most recent version of Client LOMI was uploaded</description>
    <label>Last Client LOMI</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientPreApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientPreApplicationReceived__c</fullName>
    <description
    >The date the most recent version of Client Pre Application was uploaded</description>
    <label>Last Client Pre Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientProgAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientProgAgreementReceived__c</fullName>
    <description
    >The date the most recent version of Client Program Agreement was uploaded</description>
    <label>Last Client Program Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientSurveyReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientSurveyReceived__c</fullName>
    <description
    >The date the most recent version of Client Certification Survey was uploaded</description>
    <label>Last Client Certification Survey</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientVAPWReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientVAPWReceived__c</fullName>
    <description
    >The date the most recent version of Client Veteran Paperwork was uploaded</description>
    <label>Last Client Veteran Paperwork</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FacilitatorApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>FacilitatorApplicationReceived__c</fullName>
    <description
    >The date the most recent version of Team Facilitator Application was uploaded</description>
    <label>Last Facilitator Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/StaffAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>StaffAgreementReceived__c</fullName>
    <description
    >The date the most recent version of Staff Agreement was uploaded</description>
    <label>Last Staff Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/StaffApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>StaffApplicationReceived__c</fullName>
    <description>The date the most recent version of Staff Application was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/StaffResumeReceived__c.field-meta.xml
<CustomField>
    <fullName>StaffResumeReceived__c</fullName>
    <description>The date the most recent version of Staff Resume was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Staff Resume</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TrainerApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>TrainerApplicationReceived__c</fullName>
    <description>The date the most recent version of Trainer Application was uploaded</description>
    <label>Last Trainer Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TSiMApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>TSiMApplicationReceived__c</fullName>
    <description>The date the most recent version of a Standalone Program Application was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last TSiM Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TSiMPreApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>TSiMPreApplicationReceived__c</fullName>
    <description
    >The date the most recent version of Teams Set in Motion Pre Application was uploaded</description>
    <label>Last TSiM Pre Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TSiMProgAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>TSiMProgAgreementReceived__c</fullName>
    <description
    >The date the most recent version of Teams Set in Motion Program Agreement was uploaded</description>
    <label>Last TSiM Program Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/VolunteerAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>VolunteerAgreementReceived__c</fullName>
    <description>The date the most recent version of Volunteer Agreement was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Volunteer Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/VolunteerApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>VolunteerApplicationReceived__c</fullName>
    <description>The date the most recent version of Volunteer Application was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Volunteer Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/VolunteerResumeReceived__c.field-meta.xml
<CustomField>
    <fullName>VolunteerResumeReceived__c</fullName>
    <description
    >The date the most recent version of Volunteer Resume was uploaded</description>
    <label>Last Volunteer Resume</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/ContentVersion/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Board</fullName>
            </value>
            <value>
                <fullName>Na</fullName>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Client</fullName>
                <label>Team Client</label>
            </value>
            <value>
                <fullName>TeamDog</fullName>
                <label>Team Dog</label>
            </value>
            <value>
                <fullName>TeamDog</fullName>
                <label>Team Dog</label>
            </value>
            <value>
                <fullName>Standalone</fullName>
                <label>Standalone Programs</label>
            </value>
            <value>
                <fullName>ADSiM</fullName>
                <label>Assistance Dogs Set in Motion</label>
            </value>
            <value>
                <fullName>Facilitator</fullName>
                <label>Team Facilitator</label>
            </value>
            <value>
                <fullName>Puppy</fullName>
                <label>Puppy Raiser</label>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
                <label>Staff/Contractor</label>
            </value>
            <value>
                <fullName>Dog</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PreApplication</fullName>
                <label>Pre Application</label>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>ContactForm</fullName>
                <label>Contact Form</label>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>CoI</fullName>
                <label>Conflict of Interest</label>
            </value>
            <value>
                <fullName>ToN</fullName>
                <label>Transmission of Notices</label>
            </value>
            <value>
                <fullName>LOMI</fullName>
                <label>Medical Provider Form</label>
            </value>
            <value>
                <fullName>Media</fullName>
                <label>Media Release</label>
            </value>
            <value>
                <fullName>VAPW</fullName>
                <label>Veteran Paperwork</label>
            </value>
            <value>
                <fullName>Survey</fullName>
                <label>Certification Survey</label>
            </value>
            <value>
                <fullName>Reference</fullName>
                <label>Reference Letter</label>
            </value>
            <value>
                <fullName>ClientReference</fullName>
                <label>Client Reference Letter</label>
            </value>
            <value>
                <fullName>ProfReference</fullName>
                <label>Professional Reference Letter</label>
            </value>
            <value>
                <fullName>ProgAgreement</fullName>
                <label>Program Agreement</label>
            </value>
            <value>
                <fullName>CertAgreement</fullName>
                <label>Certification Agreement</label>
            </value>
            <value>
                <fullName>Practicum</fullName>
            </value>
            <value>
                <fullName>InfrNotice</fullName>
                <label>Infraction Notice</label>
            </value>
            <value>
                <fullName>HealthForm</fullName>
                <label>Vet Health Form</label>
            </value>
            <value>
                <fullName>Notes</fullName>
                <label>Interview Notes</label>
            </value>
            <value>
                <fullName>Xray</fullName>
                <label>Vet Xray Report</label>
            </value>
            <value>
                <fullName>VacExams</fullName>
                <label>Vaccinations and Exams</label>
            </value>
            <value>
                <fullName>Resume</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
                <label>Offer Letter</label>
            </value>
            <value>
                <fullName>W4</fullName>
            </value>
            <value>
                <fullName>I9</fullName>
            </value>
            <value>
                <fullName>W9</fullName>
                <label>Contractor W9</label>
            </value>
            <value>
                <fullName>ApplicationVideo</fullName>
                <label>Application Video</label>
            </value>
            <value>
                <fullName>CGCForm</fullName>
                <label>CGC Form</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FileService.cls
public with sharing class FileService {
    // Update the last received date for the contact for the document category and type
    public static void updateContactDate(Contact contact, ContentVersion cv) {
        if (cv.Category__c == 'Volunteer' && cv.Type__c == 'Application') {
            contact.VolunteerApplicationReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'Board' && cv.Type__c == 'Application') {
            contact.BoardApplicationReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'Client' && cv.Type__c == 'Application') {
            contact.ClientApplicationReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'TSiM' && cv.Type__c == 'Application') {
            contact.TSiMApplicationReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'ADSiM' && cv.Type__c == 'Application') {
            contact.ADSiMApplicationReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'Facilitator' && cv.Type__c == 'Application') {
            contact.FacilitatorApplicationReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'Trainer' && cv.Type__c == 'Application') {
            contact.TrainerApplicationReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'Staff' && cv.Type__c == 'Application') {
            contact.StaffApplicationReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'Volunteer' && cv.Type__c == 'Agreement') {
            contact.VolunteerAgreementReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'Board' && cv.Type__c == 'Agreement') {
            contact.BoardAgreementReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'Staff' && cv.Type__c == 'Agreement') {
            contact.StaffAgreementReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'Volunteer' && cv.Type__c == 'Resume') {
            contact.VolunteerResumeReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'Board' && cv.Type__c == 'Resume') {
            contact.BoardResumeReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'Staff' && cv.Type__c == 'Resume') {
            contact.StaffResumeReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'Board' && cv.Type__c == 'Conflict of Interest') {
            contact.BoardCoIReceived__c = cv.LastModifiedDate.date();
        }

        if (
            cv.Category__c == 'Board' &&
            cv.Type__c == 'Transmission of Notices'
        ) {
            contact.BoardToNReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'Client' && cv.Type__c == 'Pre Application') {
            contact.ClientPreApplicationReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'TSiM' && cv.Type__c == 'Pre Application') {
            contact.TSiMPreApplicationReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'ADSiM' && cv.Type__c == 'Pre Application') {
            contact.ADSiMPreApplicationReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'Client' && cv.Type__c == 'LOMI') {
            contact.ClientLOMIReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'Client' && cv.Type__c == 'Veteran Paperwork') {
            contact.ClientVAPWReceived__c = cv.LastModifiedDate.date();
        }

        if (
            cv.Category__c == 'Client' &&
            cv.Type__c == 'Certification Survey'
        ) {
            contact.ClientSurveyReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'Client' && cv.Type__c == 'Program Agreement') {
            contact.ClientProgAgreementReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'TSiM' && cv.Type__c == 'Program Agreement') {
            contact.TSiMProgAgreementReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'ADSiM' && cv.Type__c == 'Program Agreement') {
            contact.ADSiMProgAgreementReceived__c = cv.LastModifiedDate.date();
        }

        if (
            cv.Category__c == 'Facilitator' &&
            cv.Type__c == 'Program Agreement'
        ) {
            contact.FacilitatorProgAgreementReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'Trainer' && cv.Type__c == 'Program Agreement') {
            contact.TrainerProgAgreementReceived__c = cv.LastModifiedDate.date();
        }

        if (
            cv.Category__c == 'Client' &&
            cv.Type__c == 'Certification Agreement'
        ) {
            contact.ClientCertAgreementReceived__c = cv.LastModifiedDate.date();
        }

        if (
            cv.Category__c == 'Facilitator' &&
            cv.Type__c == 'Certification Agreement'
        ) {
            contact.FacilitatorCertAgreementReceived__c = cv.LastModifiedDate.date();
        }

        if (
            cv.Category__c == 'Trainer' &&
            cv.Type__c == 'Certification Agreement'
        ) {
            contact.TrainerCertAgreementReceived__c = cv.LastModifiedDate.date();
        }

        if (
            cv.Category__c == 'Facilitator' &&
            cv.Type__c == 'Reference Letter'
        ) {
            contact.FacilitatorReferenceReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'Trainer' && cv.Type__c == 'Reference Letter') {
            contact.TrainerReferenceReceived__c = cv.LastModifiedDate.date();
        }

        if (
            cv.Category__c == 'Facilitator' &&
            cv.Type__c == 'Professional Growth Plan'
        ) {
            contact.FacilitatorProfGrowthPlanReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'Facilitator' && cv.Type__c == 'Practicum') {
            contact.FacilitatorPracticumReceived__c = cv.LastModifiedDate.date();
        }

        if (
            cv.Category__c == 'Facilitator' &&
            cv.Type__c == 'Infraction Notice'
        ) {
            contact.FacilitatorInfrNoticeReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'Trainer' && cv.Type__c == 'Infraction Notice') {
            contact.TrainerInfrNoticeReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'Staff' && cv.Type__c == 'Offer Letter') {
            contact.StaffOfferReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'Staff' && cv.Type__c == 'W4') {
            contact.StaffW4Received__c = cv.LastModifiedDate.date();
        }

        if (cv.Category__c == 'Staff' && cv.Type__c == 'I9') {
            contact.StaffI9Received__c = cv.LastModifiedDate.date();
        }
        update contact;
    }

    // Update the last received date for the contact for the document type
    public static void updateDogDate(Dog__c dog, ContentVersion cv) {
        if (cv.Type__c == 'Vet Health Form') {
            dog.HealthFormReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Type__c == 'Vet Xray Report') {
            dog.XrayReceived__c = cv.LastModifiedDate.date();
        }

        if (cv.Type__c == 'Vaccinations and Exams') {
            dog.VacExamsReceived__c = cv.LastModifiedDate.date();
        }
        update dog;
    }
}