force-app/main/default/objects/Contact/fields/BoardMemberStatus__c.field-meta.xml
<CustomField>
    <fullName>BoardMemberStatus__c</fullName>
    <label>Board Member Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
           </value>
           <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientCertificationValidUntil__c.field-meta.xml
<CustomField>
    <fullName>ClientCertificationValidUntil__c</fullName>
    <description>Date that the client certification is valid until</description>
    <label>Client Certification Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientDog__c.field-meta.xml
<CustomField>
    <fullName>ClientDog__c</fullName>
    <description>Name of the Client&apos;s dog</description>
    <label>Client Dog</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientFacilitatorAvailability__c.field-meta.xml
<CustomField>
    <fullName>ClientFacilitatorAvailability__c</fullName>
    <description>Facilitator availability for the client</description>
    <label>Facilitator Availability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
            <value>
                <fullName>Waitlist</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientInitialCertificationDate__c.field-meta.xml
<CustomField>
    <fullName>ClientInitialCertificationDate__c</fullName>
    <description>Date that the client was first certified.</description>
    <inlineHelpText>Derived from Team Initial Certification Date. Do not edit directly.</inlineHelpText>
    <label>Client Initial Certification Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientStatus__c.field-meta.xml
<CustomField>
    <fullName>ClientStatus__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <inlineHelpText>Derived from Team. Do not edit directly.</inlineHelpText>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In ADSiM</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Certified-Hold</fullName>
            </value>
            <value>
                <fullName>Decertified</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Not Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/FacilitatorCertAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>FacilitatorCertAgreementReceived__c</fullName>
    <description>The date the most recent version of Team Facilitator Certification Agreement was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Facilitator Certification Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FacilitatorStatus__c.field-meta.xml
<CustomField>
    <fullName>FacilitatorStatus__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <label>Facilitator Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Certified-Active</fullName>
            </value>
            <value>
                <fullName>Certified-Hold</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Not Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/GW_Volunteers__Volunteer_Status__c.field-meta.xml
<CustomField>
    <fullName>GW_Volunteers__Volunteer_Status__c</fullName>
    <label>Volunteer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LeadFacilitatorStatus__c.field-meta.xml
<CustomField>
    <fullName>LeadFacilitatorStatus__c</fullName>
    <label>Lead Facilitator Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Positions__c.field-meta.xml
<CustomField>
    <fullName>Positions__c</fullName>
    <description>Positions available</description>
    <label>Positions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Positions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/PuppyCertAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>PuppyCertAgreementReceived__c</fullName>
    <description>The date the most recent version of Puppy Raiser Certification Agreement was uploaded</description>
    <label>Last Puppy Raiser Cert Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PuppyRaiserStatus__c.field-meta.xml
<CustomField>
    <fullName>PuppyRaiserStatus__c</fullName>
    <label>Puppy Raiser Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/StaffStatus__c.field-meta.xml
<CustomField>
    <fullName>StaffStatus__c</fullName>
    <label>Staff Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/StandaloneStatus__c.field-meta.xml
<CustomField>
    <fullName>StandaloneStatus__c</fullName>
    <description>Status in enrolled standalone program</description>
    <label>Standalone Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/TrainerCertAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>TrainerCertAgreementReceived__c</fullName>
    <description>The date the most recent version of Trainer Certification Agreement was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Trainer Certification Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TrainerStatus__c.field-meta.xml
<CustomField>
    <fullName>TrainerStatus__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <label>Trainer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Certified-Active</fullName>
            </value>
            <value>
                <fullName>Certified-OnHold</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Not Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/TSiMStatus__c.field-meta.xml
<CustomField>
    <fullName>TSiMStatus__c</fullName>
    <description>Status in enrolled standalone program</description>
    <label>TSiM Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Not Accepted</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contacts.recordType-meta.xml
<RecordType>
    <fullName>Contacts</fullName>
    <active>true</active>
    <label>Contacts</label>
</RecordType>

force-app/main/default/globalValueSets/Positions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Volunteer</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Board Member</fullName>
    </customValue>
    <customValue>
        <fullName>Trainer</fullName>
    </customValue>
    <customValue>
        <fullName>Client</fullName>
    </customValue>
    <customValue>
        <fullName>Donor</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
        <label>Staff/Contractor</label>
    </customValue>
    <customValue>
        <fullName>Puppy Raiser</fullName>
    </customValue>
    <customValue>
        <fullName>Standalone</fullName>
    </customValue>
    <customValue>
        <fullName>TSiM</fullName>
    </customValue>
    <description>Positions a contact can have</description>
    <masterLabel>Positions</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/contacts/ContactRepository.cls
public inherited sharing class ContactRepository {
  public ContactRepository() {
  }
  public Contact getPositionStatusForContact(Id contactId) {
    return [
      SELECT
        Positions__c,
        BoardMemberStatus__c,
        ClientCertificationValidUntil__c,
        ClientStatus__c,
        FacilitatorCertAgreementReceived__c,
        FacilitatorStatus__c,
        LeadFacilitatorStatus__c,
        PuppyRaiserStatus__c,
        PuppyCertAgreementReceived__c,
        StaffStatus__c,
        StandaloneStatus__c,
        TSiMStatus__c,
        TrainerCertAgreementReceived__c,
        TrainerStatus__c,
        GW_Volunteers__Volunteer_Status__c
      FROM Contact
      WHERE Id = :contactId
    ];
  }

  public Set<Id> getActiveFacilitators() {
    List<Contact> active = [
      SELECT Id
      FROM Contact
      WHERE
        Positions__c INCLUDES ('Team Facilitator')
        AND FacilitatorStatus__c = 'Certified-Active'
    ];

    Set<Id> facilitators = new Set<Id>();
    for (Contact facilitator : active) {
      facilitators.add(facilitator.Id);
    }
    return facilitators;
  }

  public Contact getClientStatus(Id contactId) {
    List<Contact> clients = [
      SELECT
        ClientStatus__c,
        ClientDog__c,
        ClientCertificationValidUntil__c,
        ClientFacilitatorAvailability__c,
        ClientInitialCertificationDate__c
      FROM Contact
      WHERE Id = :contactId
    ];
    if (!clients.isEmpty()) {
      return clients[0];
    }
    return null;
  }

  public Contact modify(Contact cntct) {
    upsert cntct;
    return cntct;
  }

  public Contact[] getContactsNeedingBackgroundChecks() {
    // Check for any contacts that need background checks
    return [
      SELECT Id, Name, VolunteerAccess__c
      FROM Contact
      WHERE
        VolunteerAccess__c INCLUDES (
          'Credit Check Required',
          'Background Check Required'
        )
    ];
  }
}