force-app/main/default/objects/Contact/fields/BoardMemberStatus__c.field-meta.xml
<CustomField>
    <fullName>BoardMemberStatus__c</fullName>
    <label>Board Member Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
           </value>
           <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientCertificationValidUntil__c.field-meta.xml
<CustomField>
    <fullName>ClientCertificationValidUntil__c</fullName>
    <description>Date that the client certification is valid until</description>
    <label>Client Certification Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientStatus__c.field-meta.xml
<CustomField>
    <fullName>ClientStatus__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <inlineHelpText>Derived from Team. Do not edit directly.</inlineHelpText>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In ADSiM</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Certified-Hold</fullName>
            </value>
            <value>
                <fullName>Decertified</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Not Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/FacilitatorCertAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>FacilitatorCertAgreementReceived__c</fullName>
    <description>The date the most recent version of Team Facilitator Certification Agreement was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Facilitator Certification Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FacilitatorStatus__c.field-meta.xml
<CustomField>
    <fullName>FacilitatorStatus__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <label>Facilitator Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Certified-Active</fullName>
            </value>
            <value>
                <fullName>Certified-Hold</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Not Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/GW_Volunteers__Volunteer_Status__c.field-meta.xml
<CustomField>
    <fullName>GW_Volunteers__Volunteer_Status__c</fullName>
    <label>Volunteer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LeadFacilitatorStatus__c.field-meta.xml
<CustomField>
    <fullName>LeadFacilitatorStatus__c</fullName>
    <label>Lead Facilitator Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Positions__c.field-meta.xml
<CustomField>
    <fullName>Positions__c</fullName>
    <description>Positions available</description>
    <label>Positions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Positions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/PuppyCertAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>PuppyCertAgreementReceived__c</fullName>
    <description>The date the most recent version of Puppy Raiser Certification Agreement was uploaded</description>
    <label>Last Puppy Raiser Cert Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PuppyRaiserStatus__c.field-meta.xml
<CustomField>
    <fullName>PuppyRaiserStatus__c</fullName>
    <label>Puppy Raiser Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/StaffStatus__c.field-meta.xml
<CustomField>
    <fullName>StaffStatus__c</fullName>
    <label>Staff Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/StandaloneStatus__c.field-meta.xml
<CustomField>
    <fullName>StandaloneStatus__c</fullName>
    <description>Status in enrolled standalone program</description>
    <label>Standalone Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/TrainerCertAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>TrainerCertAgreementReceived__c</fullName>
    <description>The date the most recent version of Trainer Certification Agreement was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Trainer Certification Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TrainerStatus__c.field-meta.xml
<CustomField>
    <fullName>TrainerStatus__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <label>Trainer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Certified-Active</fullName>
            </value>
            <value>
                <fullName>Certified-OnHold</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Not Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/VolunteerAccess__c.field-meta.xml
<CustomField>
    <fullName>VolunteerAccess__c</fullName>
    <label>Volunteer Access</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operations- Master Docs - READ ONLY</fullName>
            </value>
            <value>
                <fullName>Operations- Financial</fullName>
            </value>
            <value>
                <fullName>Operations- Client</fullName>
            </value>
            <value>
                <fullName>Operations- Volunteer and Staff</fullName>
            </value>
            <value>
                <fullName>Operations- Trainer</fullName>
            </value>
            <value>
                <fullName>Board - READ ONLY</fullName>
            </value>
            <value>
                <fullName>Board</fullName>
            </value>
            <value>
                <fullName>Sensitive Info- Volunteer and Staff</fullName>
            </value>
            <value>
                <fullName>Sensitive Info- Trainer</fullName>
            </value>
            <value>
                <fullName>Sensitive Info- Board</fullName>
            </value>
            <value>
                <fullName>Active Projects- Academy</fullName>
            </value>
            <value>
                <fullName>Active Projects- ADI</fullName>
            </value>
            <value>
                <fullName>Active Projects- Branding and Marketing</fullName>
            </value>
            <value>
                <fullName>Active Projects- Client Certification</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Community Outreach and Education</fullName>
                <label>Active Projects- Community Outreach and Education</label>
            </value>
            <value>
                <fullName>Active Projects- Dog Availability</fullName>
            </value>
            <value>
                <fullName>Active Projects- Fund Development</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Governance, Compliance and Operations</fullName>
                <label
                >Active Projects- Governance, Compliance and Operations</label>
            </value>
            <value>
                <fullName>Active Projects- Research and Development</fullName>
            </value>
            <value>
                <fullName>Active Projects- Scholarships</fullName>
            </value>
            <value>
                <fullName>Active Projects- State Registration</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Team Facilitator Certification</fullName>
                <label>Active Projects- Team Facilitator Certification</label>
            </value>
            <value>
                <fullName>Active Projects- Technology Infrastructure</fullName>
            </value>
            <value>
                <fullName>Active Projects- Trainer Certification</fullName>
            </value>
            <value>
                <fullName
                >Active Projects- Volunteer Recruitment and Retention</fullName>
                <label
                >Active Projects- Volunteer Recruitment and Retention</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/globalValueSets/Positions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Volunteer</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Board Member</fullName>
    </customValue>
    <customValue>
        <fullName>Trainer</fullName>
    </customValue>
    <customValue>
        <fullName>Client</fullName>
    </customValue>
    <customValue>
        <fullName>Donor</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
        <label>Staff/Contractor</label>
    </customValue>
    <customValue>
        <fullName>Puppy Raiser</fullName>
    </customValue>
    <customValue>
        <fullName>Standalone</fullName>
    </customValue>
    <customValue>
        <fullName>TSiM</fullName>
    </customValue>
    <description>Positions a contact can have</description>
    <masterLabel>Positions</masterLabel>
</GlobalValueSet>

force-app/main/test/contacts/TestContactRepository.cls
@isTest
private class TestContactRepository {
  @isTest
  static void getContactsNeedingBackgroundChecks_returnsEmpty_whenNoContacts() {
    ContactRepository repo = new ContactRepository();
    Contact[] result = repo.getContactsNeedingBackgroundChecks();
    System.assert(result.isEmpty());
  }
  @isTest
  static void getContactsNeedingBackgroundChecks_returnsEmpty_whenNoContactsWithVolunteerAccess() {
    Contact bluey = new Contact(
      FirstName = 'Bluey',
      LastName = 'Heeler',
      Email = 'bluey@test.com'
    );
    insert bluey;
    ContactRepository repo = new ContactRepository();
    Contact[] result = repo.getContactsNeedingBackgroundChecks();
    System.assert(result.isEmpty());
  }
  @isTest
  static void getContactsNeedingBackgroundChecks_returnsEmpty_whenNoContactsWithCheckRequired() {
    Contact bluey = new Contact(
      FirstName = 'Bluey',
      LastName = 'Heeler',
      Email = 'bluey@test.com',
      VolunteerAccess__c = 'Active Projects- Academy'
    );
    insert bluey;
    ContactRepository repo = new ContactRepository();
    Contact[] result = repo.getContactsNeedingBackgroundChecks();
    System.assert(result.isEmpty());
  }
  @isTest
  static void getContactsNeedingBackgroundChecks_returnsEmpty_whenContactNeedsCriminal() {
    Contact bluey = new Contact(
      FirstName = 'Bluey',
      LastName = 'Heeler',
      Email = 'bluey@test.com',
      VolunteerAccess__c = 'Background Check Required'
    );
    insert bluey;
    ContactRepository repo = new ContactRepository();
    Contact[] result = repo.getContactsNeedingBackgroundChecks();
    Contact puppy = result[0];
    System.assertEquals(bluey.Id, puppy.Id);
    System.assertEquals(bluey.VolunteerAccess__c, puppy.VolunteerAccess__c);
  }
  @isTest
  static void getContactsNeedingBackgroundChecks_returnsEmpty_whenContactNeedsCredit() {
    Contact bluey = new Contact(
      FirstName = 'Bluey',
      LastName = 'Heeler',
      Email = 'bluey@test.com',
      VolunteerAccess__c = 'Credit Check Required'
    );
    insert bluey;
    ContactRepository repo = new ContactRepository();
    Contact[] result = repo.getContactsNeedingBackgroundChecks();
    Contact puppy = result[0];
    System.assertEquals(bluey.Id, puppy.Id);
    System.assertEquals(bluey.VolunteerAccess__c, puppy.VolunteerAccess__c);
  }
  @isTest
  static void getContactsNeedingBackgroundChecks_returnsEmpty_whenContactNeedsBoth() {
    Contact bluey = new Contact(
      FirstName = 'Bluey',
      LastName = 'Heeler',
      Email = 'bluey@test.com',
      VolunteerAccess__c = 'Background Check Required;Credit Check Required'
    );
    insert bluey;
    ContactRepository repo = new ContactRepository();
    Contact[] result = repo.getContactsNeedingBackgroundChecks();
    Contact puppy = result[0];
    System.assertEquals(bluey.Id, puppy.Id);
    System.assert(
      bluey.VolunteerAccess__c.contains('Background Check Required')
    );
    System.assert(bluey.VolunteerAccess__c.contains('Credit Check Required'));
  }
  @isTest
  static void getActiveFacilitators_returnsEmptyList_whenNoContacts() {
    ContactRepository repo = new ContactRepository();
    Set<Id> facilitators = repo.getActiveFacilitators();

    System.assertEquals(new Set<Id>(), facilitators);
  }
  @isTest
  static void getActiveFacilitators_returnsEmptyList_whenNoFacilitators() {
    Contact client = new Contact(
      FirstName = 'Billy',
      LastName = 'Kid',
      Positions__c = 'Client'
    );
    insert client;

    ContactRepository repo = new ContactRepository();
    Set<Id> facilitators = repo.getActiveFacilitators();

    System.assertEquals(new Set<Id>(), facilitators);
  }
  @isTest
  static void getActiveFacilitators_returnsEmptyList_whenFacilitatorNotActive() {
    Contact[] facs = new List<Contact>{
      new Contact(
        FirstName = 'Jack',
        LastName = 'ONeil',
        Positions__c = 'Team Facilitator',
        FacilitatorStatus__c = 'Inactive'
      ),
      new Contact(
        FirstName = 'Sam',
        LastName = 'Carter',
        Positions__c = 'Team Facilitator',
        FacilitatorStatus__c = 'Initial Inquiry'
      ),
      new Contact(
        FirstName = 'Daniel',
        LastName = 'Jackson',
        Positions__c = 'Team Facilitator',
        FacilitatorStatus__c = 'In Training'
      ),
      new Contact(
        FirstName = 'Tealc',
        LastName = 'Na',
        Positions__c = 'Team Facilitator',
        FacilitatorStatus__c = 'None'
      ),
      new Contact(
        FirstName = 'Cameron',
        LastName = 'Mitchell',
        Positions__c = 'Team Facilitator',
        FacilitatorStatus__c = 'Onboarding'
      ),
      new Contact(
        FirstName = 'Janet',
        LastName = 'Carter',
        Positions__c = 'Team Facilitator',
        FacilitatorStatus__c = 'Suspended'
      ),
      new Contact(
        FirstName = 'Vala',
        LastName = 'Maldoran',
        Positions__c = 'Team Facilitator',
        FacilitatorStatus__c = 'Discontinued'
      )
    };
    insert facs;

    ContactRepository repo = new ContactRepository();
    Set<Id> facilitators = repo.getActiveFacilitators();

    System.assertEquals(new Set<Id>(), facilitators);
  }
  @isTest
  static void getActiveFacilitators_returnsOnlyActive_whenOtherNotActive() {
    Contact[] facs = new List<Contact>{
      new Contact(
        FirstName = 'Jack',
        LastName = 'ONeil',
        Positions__c = 'Team Facilitator',
        FacilitatorStatus__c = 'Inactive'
      ),
      new Contact(
        FirstName = 'Sam',
        LastName = 'Carter',
        Positions__c = 'Team Facilitator',
        FacilitatorStatus__c = 'Initial Inquiry'
      ),
      new Contact(
        FirstName = 'Daniel',
        LastName = 'Jackson',
        Positions__c = 'Team Facilitator',
        FacilitatorStatus__c = 'In Training'
      ),
      new Contact(
        FirstName = 'Tealc',
        LastName = 'Na',
        Positions__c = 'Team Facilitator',
        FacilitatorStatus__c = 'Certified-Active'
      ),
      new Contact(
        FirstName = 'Cameron',
        LastName = 'Mitchell',
        Positions__c = 'Team Facilitator',
        FacilitatorStatus__c = 'Onboarding'
      ),
      new Contact(
        FirstName = 'Janet',
        LastName = 'Carter',
        Positions__c = 'Team Facilitator',
        FacilitatorStatus__c = 'Suspended'
      ),
      new Contact(
        FirstName = 'Vala',
        LastName = 'Maldoran',
        Positions__c = 'Team Facilitator',
        FacilitatorStatus__c = 'Discontinued'
      )
    };
    insert facs;

    ContactRepository repo = new ContactRepository();
    Set<Id> facilitators = repo.getActiveFacilitators();

    System.assertEquals(new Set<Id>{ facs[3].id }, facilitators);
  }
  @isTest
  static void getActiveFacilitators_returnsAllActive_whenOtherPositions() {
    Contact[] facs = new List<Contact>{
      new Contact(
        FirstName = 'Jack',
        LastName = 'ONeil',
        Positions__c = 'Team Facilitator;Volunteer',
        FacilitatorStatus__c = 'Inactive'
      ),
      new Contact(
        FirstName = 'Sam',
        LastName = 'Carter',
        Positions__c = 'Team Facilitator;Client',
        FacilitatorStatus__c = 'Initial Inquiry'
      ),
      new Contact(
        FirstName = 'Daniel',
        LastName = 'Jackson',
        Positions__c = 'Team Facilitator;Board Member',
        FacilitatorStatus__c = 'In Training'
      ),
      new Contact(
        FirstName = 'Tealc',
        LastName = 'Na',
        Positions__c = 'Team Facilitator;Trainer',
        FacilitatorStatus__c = 'Certified-Active'
      ),
      new Contact(
        FirstName = 'Cameron',
        LastName = 'Mitchell',
        Positions__c = 'Team Facilitator;Team Facilitator Lead',
        FacilitatorStatus__c = 'Onboarding'
      ),
      new Contact(
        FirstName = 'Janet',
        LastName = 'Carter',
        Positions__c = 'Team Facilitator;Client;Board Member;Volunteer',
        FacilitatorStatus__c = 'Certified-Active'
      ),
      new Contact(
        FirstName = 'Vala',
        LastName = 'Maldoran',
        Positions__c = 'Client',
        FacilitatorStatus__c = 'Discontinued'
      )
    };
    insert facs;

    ContactRepository repo = new ContactRepository();
    Set<Id> facilitators = repo.getActiveFacilitators();

    System.assertEquals(new Set<Id>{ facs[3].id, facs[5].id }, facilitators);
  }

  @isTest
  public static void getPositionStatusForContact_returnsAllStatuses() {
    Contact vala = new Contact(
      FirstName = 'Vala',
      LastName = 'Maldoran',
      Positions__c = 'Team Facilitator;Client;Board Member;Volunteer;Trainer;Staff',
      BoardMemberStatus__c = 'Initial Inquiry',
      ClientCertificationValidUntil__c = Date.today().addMonths(3),
      ClientStatus__c = 'In ADSiM',
      FacilitatorCertAgreementReceived__c = Date.today().addMonths(-3),
      FacilitatorStatus__c = 'Discontinued',
      GW_Volunteers__Volunteer_Status__c = 'Active',
      LeadFacilitatorStatus__c = 'Active',
      PuppyCertAgreementReceived__c = Date.today().addYears(-1),
      PuppyRaiserStatus__c = 'Onboarding',
      StaffStatus__c = 'Employee',
      StandaloneStatus__c = 'In Training',
      TrainerCertAgreementReceived__c = Date.today().addMonths(-1),
      TrainerStatus__c = 'Certified-Active'
    );
    insert vala;

    ContactRepository repo = new ContactRepository();
    Contact actual = repo.getPositionStatusForContact(vala.Id);

    // Assert
    System.assertEquals(vala.Id, actual.Id);
    System.assertEquals(
      new Set<String>(vala.Positions__c.split(';')),
      new Set<String>(actual.Positions__c.split(';'))
    );
    System.assertEquals(vala.BoardMemberStatus__c, actual.BoardMemberStatus__c);
    System.assertEquals(
      vala.ClientCertificationValidUntil__c,
      actual.ClientCertificationValidUntil__c
    );
    System.assertEquals(vala.ClientStatus__c, actual.ClientStatus__c);
    System.assertEquals(
      vala.FacilitatorCertAgreementReceived__c,
      actual.FacilitatorCertAgreementReceived__c
    );
    System.assertEquals(vala.FacilitatorStatus__c, actual.FacilitatorStatus__c);
    System.assertEquals(
      vala.GW_Volunteers__Volunteer_Status__c,
      actual.GW_Volunteers__Volunteer_Status__c
    );
    System.assertEquals(
      vala.LeadFacilitatorStatus__c,
      actual.LeadFacilitatorStatus__c
    );
    System.assertEquals(
      vala.PuppyCertAgreementReceived__c,
      actual.PuppyCertAgreementReceived__c
    );
    System.assertEquals(vala.PuppyRaiserStatus__c, actual.PuppyRaiserStatus__c);
    System.assertEquals(vala.StaffStatus__c, actual.StaffStatus__c);
    System.assertEquals(vala.StaffStatus__c, actual.StaffStatus__c);
    System.assertEquals(
      vala.TrainerCertAgreementReceived__c,
      actual.TrainerCertAgreementReceived__c
    );
    System.assertEquals(vala.TrainerStatus__c, actual.TrainerStatus__c);
  }
}