force-app/main/default/objects/Contact/fields/BoardAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>BoardAgreementReceived__c</fullName>
    <description
    >The date the most recent version of Board Agreement was uploaded</description>
    <label>Last Board Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BoardApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>BoardApplicationReceived__c</fullName>
    <description
    >The date the most recent version of Board Application was uploaded</description>
    <label>Last Board Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BoardCoIReceived__c.field-meta.xml
<CustomField>
    <fullName>BoardCoIReceived__c</fullName>
    <description
    >The date the most recent version of Board Conflict of Interest was uploaded</description>
    <label>Last Board Conflict of Interest</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BoardResumeReceived__c.field-meta.xml
<CustomField>
    <fullName>BoardResumeReceived__c</fullName>
    <description>The date the most recent version of Board Resume was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Board Resume</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BoardToNReceived__c.field-meta.xml
<CustomField>
    <fullName>BoardToNReceived__c</fullName>
    <description
    >The date the most recent version of Board Transmission of Notices was uploaded</description>
    <label>Last Board Transmission of Notices</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/ContentVersion/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Board</fullName>
            </value>
            <value>
                <fullName>Na</fullName>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Client</fullName>
                <label>Team Client</label>
            </value>
            <value>
                <fullName>TeamDog</fullName>
                <label>Team Dog</label>
            </value>
            <value>
                <fullName>TeamDog</fullName>
                <label>Team Dog</label>
            </value>
            <value>
                <fullName>Standalone</fullName>
                <label>Standalone Programs</label>
            </value>
            <value>
                <fullName>ADSiM</fullName>
                <label>Assistance Dogs Set in Motion</label>
            </value>
            <value>
                <fullName>Facilitator</fullName>
                <label>Team Facilitator</label>
            </value>
            <value>
                <fullName>Puppy</fullName>
                <label>Puppy Raiser</label>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
                <label>Staff/Contractor</label>
            </value>
            <value>
                <fullName>Dog</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PreApplication</fullName>
                <label>Pre Application</label>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>ContactForm</fullName>
                <label>Contact Form</label>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>CoI</fullName>
                <label>Conflict of Interest</label>
            </value>
            <value>
                <fullName>ToN</fullName>
                <label>Transmission of Notices</label>
            </value>
            <value>
                <fullName>LOMI</fullName>
                <label>Medical Provider Form</label>
            </value>
            <value>
                <fullName>Media</fullName>
                <label>Media Release</label>
            </value>
            <value>
                <fullName>VAPW</fullName>
                <label>Veteran Paperwork</label>
            </value>
            <value>
                <fullName>Survey</fullName>
                <label>Certification Survey</label>
            </value>
            <value>
                <fullName>Reference</fullName>
                <label>Reference Letter</label>
            </value>
            <value>
                <fullName>ClientReference</fullName>
                <label>Client Reference Letter</label>
            </value>
            <value>
                <fullName>ProfReference</fullName>
                <label>Professional Reference Letter</label>
            </value>
            <value>
                <fullName>ProgAgreement</fullName>
                <label>Program Agreement</label>
            </value>
            <value>
                <fullName>CertAgreement</fullName>
                <label>Certification Agreement</label>
            </value>
            <value>
                <fullName>Practicum</fullName>
            </value>
            <value>
                <fullName>InfrNotice</fullName>
                <label>Infraction Notice</label>
            </value>
            <value>
                <fullName>HealthForm</fullName>
                <label>Vet Health Form</label>
            </value>
            <value>
                <fullName>Notes</fullName>
                <label>Interview Notes</label>
            </value>
            <value>
                <fullName>Xray</fullName>
                <label>Vet Xray Report</label>
            </value>
            <value>
                <fullName>VacExams</fullName>
                <label>Vaccinations and Exams</label>
            </value>
            <value>
                <fullName>Resume</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
                <label>Offer Letter</label>
            </value>
            <value>
                <fullName>W4</fullName>
            </value>
            <value>
                <fullName>I9</fullName>
            </value>
            <value>
                <fullName>W9</fullName>
                <label>Contractor W9</label>
            </value>
            <value>
                <fullName>ApplicationVideo</fullName>
                <label>Application Video</label>
            </value>
            <value>
                <fullName>CGCForm</fullName>
                <label>CGC Form</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/test/files/TestClearDateServiceBoardFields.cls
@isTest
public with sharing class TestClearDateServiceBoardFields {
  @isTest
  public static void clearDate_BoardAgreement_SetsDateToNull() {
    ContentVersion cv = new ContentVersion(
      Category__c = 'Board',
      Type__c = 'Agreement'
    );
    Contact record = new Contact(
      FirstName = 'Test',
      LastName = 'Contact',
      Email = 'abc@abc.com'
    );
    insert record;
    ClearDateService.clear(cv, record.Id);

    record = [
      SELECT BoardAgreementReceived__c
      FROM Contact
      WHERE Id = :record.Id
      LIMIT 1
    ];
    system.assertEquals(
      null,
      record.BoardAgreementReceived__c,
      'BoardAgreementReceived__c not cleared'
    );
  }

  @isTest
  public static void clearDate_BoardApplication_SetsDateToNull() {
    ContentVersion cv = new ContentVersion(
      Category__c = 'Board',
      Type__c = 'Application'
    );
    Contact record = new Contact(
      FirstName = 'Test',
      LastName = 'Contact',
      Email = 'abc@abc.com'
    );
    insert record;
    ClearDateService.clear(cv, record.Id);

    record = [
      SELECT BoardApplicationReceived__c
      FROM Contact
      WHERE Id = :record.Id
      LIMIT 1
    ];
    system.assertEquals(
      null,
      record.BoardApplicationReceived__c,
      'BoardApplicationReceived__c not cleared'
    );
  }

  @isTest
  public static void clearDate_BoardCoI_SetsDateToNull() {
    ContentVersion cv = new ContentVersion(
      Category__c = 'Board',
      Type__c = 'CoI'
    );
    Contact record = new Contact(
      FirstName = 'Test',
      LastName = 'Contact',
      Email = 'abc@abc.com'
    );
    insert record;
    ClearDateService.clear(cv, record.Id);

    record = [
      SELECT BoardCoIReceived__c
      FROM Contact
      WHERE Id = :record.Id
      LIMIT 1
    ];
    system.assertEquals(
      null,
      record.BoardCoIReceived__c,
      'BoardCoIReceived__c not cleared'
    );
  }

  @isTest
  public static void clearDate_BoardResume_SetsDateToNull() {
    ContentVersion cv = new ContentVersion(
      Category__c = 'Board',
      Type__c = 'Resume'
    );
    Contact record = new Contact(
      FirstName = 'Test',
      LastName = 'Contact',
      Email = 'abc@abc.com'
    );
    insert record;
    ClearDateService.clear(cv, record.Id);

    record = [
      SELECT BoardResumeReceived__c
      FROM Contact
      WHERE Id = :record.Id
      LIMIT 1
    ];
    system.assertEquals(
      null,
      record.BoardResumeReceived__c,
      'BoardResumeReceived__c not cleared'
    );
  }

  @isTest
  public static void clearDate_BoardToN_SetsDateToNull() {
    ContentVersion cv = new ContentVersion(
      Category__c = 'Board',
      Type__c = 'ToN'
    );
    Contact record = new Contact(
      FirstName = 'Test',
      LastName = 'Contact',
      Email = 'abc@abc.com'
    );
    insert record;
    ClearDateService.clear(cv, record.Id);

    record = [
      SELECT BoardToNReceived__c
      FROM Contact
      WHERE Id = :record.Id
      LIMIT 1
    ];
    system.assertEquals(
      null,
      record.BoardToNReceived__c,
      'BoardToNReceived__c not cleared'
    );
  }
}