force-app/main/default/objects/Contact/fields/ClientCertificationValidUntil__c.field-meta.xml
<CustomField>
    <fullName>ClientCertificationValidUntil__c</fullName>
    <description>Date that the client certification is valid until</description>
    <label>Client Certification Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientDog__c.field-meta.xml
<CustomField>
    <fullName>ClientDog__c</fullName>
    <description>Name of the Client&apos;s dog</description>
    <label>Client Dog</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientFacilitatorAvailability__c.field-meta.xml
<CustomField>
    <fullName>ClientFacilitatorAvailability__c</fullName>
    <description>Facilitator availability for the client</description>
    <label>Facilitator Availability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
            <value>
                <fullName>Waitlist</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientInitialCertificationDate__c.field-meta.xml
<CustomField>
    <fullName>ClientInitialCertificationDate__c</fullName>
    <description>Date that the client was first certified.</description>
    <inlineHelpText>Derived from Team Initial Certification Date. Do not edit directly.</inlineHelpText>
    <label>Client Initial Certification Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientStatus__c.field-meta.xml
<CustomField>
    <fullName>ClientStatus__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <inlineHelpText>Derived from Team. Do not edit directly.</inlineHelpText>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In ADSiM</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Certified-Hold</fullName>
            </value>
            <value>
                <fullName>Decertified</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Not Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/repositories/ContactRepository.cls
public with sharing class ContactRepository {

    public Contact getClientStatus(Id contactId) {
        List<Contact> clients = [
            SELECT
                ClientStatus__c,
                ClientDog__c,
                ClientCertificationValidUntil__c,
                ClientFacilitatorAvailability__c,
                ClientInitialCertificationDate__c
            FROM Contact
            WHERE Id = :contactId
        ];
        if (!clients.isEmpty()) {
            return clients[0];
        }
        return null;
    }

    public Contact modify(Contact cntct) {
        upsert cntct;
        return cntct;
    }
}