force-app/main/default/objects/Contact/fields/ClientApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientApplicationReceived__c</fullName>
    <description
    >The date the most recent version of Client Application was uploaded</description>
    <label>Last Client Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientCertAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientCertAgreementReceived__c</fullName>
    <description
    >The date the most recent version of Client Certification Agreement was uploaded</description>
    <label>Last Client Certification Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientLOMIReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientLOMIReceived__c</fullName>
    <description
    >The date the most recent version of Client LOMI was uploaded</description>
    <label>Last Client LOMI</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientPreApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientPreApplicationReceived__c</fullName>
    <description
    >The date the most recent version of Client Pre Application was uploaded</description>
    <label>Last Client Pre Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientProgAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientProgAgreementReceived__c</fullName>
    <description
    >The date the most recent version of Client Program Agreement was uploaded</description>
    <label>Last Client Program Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientSurveyReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientSurveyReceived__c</fullName>
    <description
    >The date the most recent version of Client Certification Survey was uploaded</description>
    <label>Last Client Certification Survey</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ClientVAPWReceived__c.field-meta.xml
<CustomField>
    <fullName>ClientVAPWReceived__c</fullName>
    <description
    >The date the most recent version of Client Veteran Paperwork was uploaded</description>
    <label>Last Client Veteran Paperwork</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ContactFormReceived__c.field-meta.xml
<CustomField>
    <fullName>ContactFormReceived__c</fullName>
    <description>The date the most recent version of Contact Form was uploaded</description>
    <inlineHelpText>Set programmatically when online contact form is completed.</inlineHelpText>
    <label>Last Contact Form</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/ContentVersion/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Board</fullName>
            </value>
            <value>
                <fullName>Na</fullName>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Client</fullName>
                <label>Team Client</label>
            </value>
            <value>
                <fullName>TeamDog</fullName>
                <label>Team Dog</label>
            </value>
            <value>
                <fullName>TeamDog</fullName>
                <label>Team Dog</label>
            </value>
            <value>
                <fullName>Standalone</fullName>
                <label>Standalone Programs</label>
            </value>
            <value>
                <fullName>ADSiM</fullName>
                <label>Assistance Dogs Set in Motion</label>
            </value>
            <value>
                <fullName>Facilitator</fullName>
                <label>Team Facilitator</label>
            </value>
            <value>
                <fullName>Puppy</fullName>
                <label>Puppy Raiser</label>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
                <label>Staff/Contractor</label>
            </value>
            <value>
                <fullName>Dog</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PreApplication</fullName>
                <label>Pre Application</label>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>ContactForm</fullName>
                <label>Contact Form</label>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>CoI</fullName>
                <label>Conflict of Interest</label>
            </value>
            <value>
                <fullName>ToN</fullName>
                <label>Transmission of Notices</label>
            </value>
            <value>
                <fullName>LOMI</fullName>
                <label>Medical Provider Form</label>
            </value>
            <value>
                <fullName>Media</fullName>
                <label>Media Release</label>
            </value>
            <value>
                <fullName>VAPW</fullName>
                <label>Veteran Paperwork</label>
            </value>
            <value>
                <fullName>Survey</fullName>
                <label>Certification Survey</label>
            </value>
            <value>
                <fullName>Reference</fullName>
                <label>Reference Letter</label>
            </value>
            <value>
                <fullName>ClientReference</fullName>
                <label>Client Reference Letter</label>
            </value>
            <value>
                <fullName>ProfReference</fullName>
                <label>Professional Reference Letter</label>
            </value>
            <value>
                <fullName>ProgAgreement</fullName>
                <label>Program Agreement</label>
            </value>
            <value>
                <fullName>CertAgreement</fullName>
                <label>Certification Agreement</label>
            </value>
            <value>
                <fullName>Practicum</fullName>
            </value>
            <value>
                <fullName>InfrNotice</fullName>
                <label>Infraction Notice</label>
            </value>
            <value>
                <fullName>HealthForm</fullName>
                <label>Vet Health Form</label>
            </value>
            <value>
                <fullName>Notes</fullName>
                <label>Interview Notes</label>
            </value>
            <value>
                <fullName>Xray</fullName>
                <label>Vet Xray Report</label>
            </value>
            <value>
                <fullName>VacExams</fullName>
                <label>Vaccinations and Exams</label>
            </value>
            <value>
                <fullName>Resume</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
                <label>Offer Letter</label>
            </value>
            <value>
                <fullName>W4</fullName>
            </value>
            <value>
                <fullName>I9</fullName>
            </value>
            <value>
                <fullName>W9</fullName>
                <label>Contractor W9</label>
            </value>
            <value>
                <fullName>ApplicationVideo</fullName>
                <label>Application Video</label>
            </value>
            <value>
                <fullName>CGCForm</fullName>
                <label>CGC Form</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/test/TestClearDateServiceClientFields.cls
@isTest
public with sharing class TestClearDateServiceClientFields {

    @isTest
    public static void clearDate_ClientApplication_SetsDateToNull() {
        ContentVersion cv = new ContentVersion(Category__c = 'Client', Type__c = 'Application');
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert record;
        ClearDateService.clear(cv, record.Id);

        record = [
            SELECT ClientApplicationReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            null,
            record.ClientApplicationReceived__c,
            'ClientApplicationReceived__c not cleared'
        );
    }

    @isTest
    public static void clearDate_ClientCertAgreement_SetsDateToNull() {
        ContentVersion cv = new ContentVersion(Category__c = 'Client', Type__c = 'CertAgreement');
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert record;
        ClearDateService.clear(cv, record.Id);

        record = [
            SELECT ClientCertAgreementReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            null,
            record.ClientCertAgreementReceived__c,
            'ClientCertAgreementReceived__c not cleared'
        );
    }

    @isTest
    public static void clearDate_ClientContactForm_SetsDateToNull() {
        ContentVersion cv = new ContentVersion(Category__c = 'Client', Type__c = 'ContactForm');
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert record;
        ClearDateService.clear(cv, record.Id);

        record = [
            SELECT ContactFormReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            null,
            record.ContactFormReceived__c,
            'ContactFormReceived__c not cleared'
        );
    }

    @isTest
    public static void clearDate_ClientLOMI_SetsDateToNull() {
        ContentVersion cv = new ContentVersion(Category__c = 'Client', Type__c = 'LOMI');
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert record;
        ClearDateService.clear(cv, record.Id);

        record = [
            SELECT ClientLOMIReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            null,
            record.ClientLOMIReceived__c,
            'ClientLOMIReceived__c not cleared'
        );
    }

    @isTest
    public static void clearDate_ClientPreApplication_SetsDateToNull() {
        ContentVersion cv = new ContentVersion(Category__c = 'Client', Type__c = 'PreApplication');
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert record;
        ClearDateService.clear(cv, record.Id);

        record = [
            SELECT ClientPreApplicationReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            null,
            record.ClientPreApplicationReceived__c,
            'ClientPreApplicationReceived__c not cleared'
        );
    }

    @isTest
    public static void clearDate_ClientProgAgreement_SetsDateToNull() {
        ContentVersion cv = new ContentVersion(Category__c = 'Client', Type__c = 'ProgAgreement');
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert record;
        ClearDateService.clear(cv, record.Id);

        record = [
            SELECT ClientProgAgreementReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            null,
            record.ClientProgAgreementReceived__c,
            'ClientProgAgreementReceived__c not cleared'
        );
    }

    @isTest
    public static void clearDate_ClientSurvey_SetsDateToNull() {
        ContentVersion cv = new ContentVersion(Category__c = 'Client', Type__c = 'Survey');
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert record;
        ClearDateService.clear(cv, record.Id);

        record = [
            SELECT ClientSurveyReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            null,
            record.ClientSurveyReceived__c,
            'ClientSurveyReceived__c not cleared'
        );
    }

    @isTest
    public static void clearDate_ClientVAPW_SetsDateToNull() {
        ContentVersion cv = new ContentVersion(Category__c = 'Client', Type__c = 'VAPW');
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert record;
        ClearDateService.clear(cv, record.Id);

        record = [
            SELECT ClientVAPWReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            null,
            record.ClientVAPWReceived__c,
            'ClientVAPWReceived__c not cleared'
        );
    }
}