force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Place/person to contact this person</description>
    <inlineHelpText>Select Guardian to contact this person through their guardian, Home for personal email/phone</inlineHelpText>
    <label>Contact At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
                <default>true</default>
                <label>Home</label>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Atlas Program</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramAssignment__c/ProgramAssignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Program Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramAssignment__c/fields/AssignedDate__c.field-meta.xml
<CustomField>
    <fullName>AssignedDate__c</fullName>
    <label>Assigned Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assigned Programs</relationshipLabel>
    <relationshipName>AssignedProgram</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/ExpectedCompletion__c.field-meta.xml
<CustomField>
    <fullName>ExpectedCompletion__c</fullName>
    <description>Expected completion date</description>
    <label>Expected Completion</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/test/TestReminders.cls
@isTest
public with sharing class TestReminders {
    // Dummy CRON expression: midnight on March 15.
    // Because this is a test, job executes
    // immediately after Test.stopTest().
    public static String CRON_EXP = '0 0 0 15 3 ? 2022';
    private static Group adminGroup;
    private static Contact joe;

    static void createRecords() {
        //adminGroup = new Group(Name = 'Program Administrator', Type = 'Queue');
        //insert adminGroup;
        adminGroup = [
            SELECT id
            FROM Group
            WHERE Name = 'Program Administrator'
            LIMIT 1
        ];

        joe = new Contact(FirstName = 'Joe', LastName = 'Blow');
        insert joe;

        QueueSobject mappingObject = new QueueSobject(
            QueueId = adminGroup.Id,
            SobjectType = 'Task'
        );
        System.runAs(new User(Id = UserInfo.getUserId())) {
            insert mappingObject;
        }
    }

    static testMethod void testScheduledJob() {
        createRecords();

        ProgramAssignment__c assignment = new ProgramAssignment__c(
            AssignedDate__c = Date.today().addDays(-8),
            ExpectedCompletion__c = Date.today().addDays(7),
            Program__c = 'Volunteer',
            Status__c = 'In progress',
            Contact__c = joe.Id
        );
        insert assignment;
        // Get the ID of the assignment we just inserted
        /*Map<Id, ProgramAssignment__c> opptyMap = new Map<Id, ProgramAssignment__c>(opptys);
         List<Id> opptyIds = new List<Id>(opptyMap.keySet());*/
        Test.startTest();
        // Schedule the test job
        String jobId = System.schedule(
            'ScheduledApexTest',
            CRON_EXP,
            new Reminders()
        );
        // Verify the scheduled job has not run yet.
        List<Task> tasks = [SELECT Id FROM Task WHERE WhatId = :assignment.Id];
        System.assertEquals(0, tasks.size(), 'Tasks exist before job has run');
        // Stopping the test will run the job synchronously
        Test.stopTest();
        // Now that the scheduled job has executed,
        // check that our tasks were created
        tasks = [
            SELECT
                Id,
                WhoId,
                OwnerId,
                Description,
                Priority,
                Type,
                Subject,
                IsReminderSet,
                ReminderDateTime
            FROM Task
            WHERE WhatId = :assignment.Id
        ];
        System.assertEquals(1, tasks.size(), 'Task was not created');
        Task remind = tasks[0];
        System.assertEquals(joe.Id, remind.WhoId);
        System.assertEquals(adminGroup.Id, remind.OwnerId);
        System.assertEquals('Check on Program progress', remind.Description);
        System.assertEquals('Normal', remind.Priority);
        System.assertEquals('Call', remind.Type);
        System.assertEquals('Other', remind.Subject);
        System.assert(remind.IsReminderSet);
        System.assertEquals(Date.today(), remind.ReminderDateTime.date());
    }
}