force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Place/person to contact this person</description>
    <inlineHelpText>Select Guardian to contact this person through their guardian, Home for personal email/phone</inlineHelpText>
    <label>Contact At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
                <default>true</default>
                <label>Home</label>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Positions__c.field-meta.xml
<CustomField>
    <fullName>Positions__c</fullName>
    <description>Positions available</description>
    <label>Positions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Positions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/npe4__Relationship__c/fields/npe4__Status__c.field-meta.xml
<CustomField>
    <fullName>npe4__Status__c</fullName>
    <description>Status of the Relationship.</description>
    <inlineHelpText>Status of the Relationship.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
                <default>true</default>
                <label>Current</label>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe4__Relationship__c/fields/npe4__Type__c.field-meta.xml
<CustomField>
    <fullName>npe4__Type__c</fullName>
    <description
  >Field that describes how the Related Contact is connected to the Contact.</description>
    <inlineHelpText
  >Field that describes how the Related Contact is connected to the Contact.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Friend</fullName>
            </value>
            <value>
                <fullName>Family</fullName>
            </value>
            <value>
                <fullName>Coworker</fullName>
            </value>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Son</fullName>
            </value>
            <value>
                <fullName>Daughter</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Aunt</fullName>
            </value>
            <value>
                <fullName>Uncle</fullName>
            </value>
            <value>
                <fullName>Husband</fullName>
            </value>
            <value>
                <fullName>Wife</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Cousin</fullName>
            </value>
            <value>
                <fullName>Grandmother</fullName>
            </value>
            <value>
                <fullName>Grandfather</fullName>
            </value>
            <value>
                <fullName>Grandparent</fullName>
            </value>
            <value>
                <fullName>Grandson</fullName>
            </value>
            <value>
                <fullName>Granddaughter</fullName>
            </value>
            <value>
                <fullName>Grandchild</fullName>
            </value>
            <value>
                <fullName>Employer</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Facilitator</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Team Faciliator</fullName>
            </value>
            <value>
                <fullName>Team Facilitator Lead</fullName>
            </value>
            <value>
                <fullName>Volunteer Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Positions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Volunteer</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Board Member</fullName>
    </customValue>
    <customValue>
        <fullName>Trainer</fullName>
    </customValue>
    <customValue>
        <fullName>Client</fullName>
    </customValue>
    <customValue>
        <fullName>Donor</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
        <label>Staff/Contractor</label>
    </customValue>
    <customValue>
        <fullName>Puppy Raiser</fullName>
    </customValue>
    <customValue>
        <fullName>Standalone</fullName>
    </customValue>
    <customValue>
        <fullName>TSiM</fullName>
    </customValue>
    <description>Positions a contact can have</description>
    <masterLabel>Positions</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/relationships/RelationshipRepository.cls
public class RelationshipRepository {
  public List<npe4__Relationship__c> getForPair(
    Id contactId,
    Id relatedId,
    String type
  ) {
    return [
      SELECT
        Id,
        npe4__Contact__c,
        npe4__Type__c,
        npe4__Status__c,
        npe4__RelatedContact__c
      FROM npe4__Relationship__c
      WHERE
        npe4__Contact__c = :contactId
        AND npe4__RelatedContact__c = :relatedId
        AND npe4__Type__c = :type
    ];
  }

  public List<npe4__Relationship__c> getCurrentRelated(
    Id contactId,
    String type
  ) {
    return [
      SELECT
        Id,
        npe4__RelatedContact__c,
        npe4__RelatedContact__r.Email,
        npe4__RelatedContact__r.Phone,
        npe4__Type__c
      FROM npe4__Relationship__c
      WHERE
        npe4__Type__c = :type
        AND npe4__Contact__c = :contactId
        AND npe4__Status__c = 'Current'
    ];
  }

  public List<npe4__Relationship__c> getCurrentRelated(Id contactId) {
    return [
      SELECT
        Id,
        npe4__Contact__c,
        npe4__Contact__r.Contact__c,
        npe4__Contact__r.Email,
        npe4__Contact__r.Phone,
        npe4__RelatedContact__c,
        npe4__RelatedContact__r.Email,
        npe4__RelatedContact__r.Phone,
        npe4__Type__c
      FROM npe4__Relationship__c
      WHERE npe4__RelatedContact__c = :contactId AND npe4__Status__c = 'Current'
    ];
  }

  public npe4__Relationship__c[] getSharingPositions(Id contactId) {
    // Find who the contact is related to as an emergency contact
    return [
      SELECT Id, npe4__Contact__r.Positions__c
      FROM npe4__Relationship__c
      WHERE
        (npe4__Type__c LIKE '%Emergency Contact'
        OR npe4__Type__c = 'Guardian')
        AND npe4__Status__c = 'Current'
        AND npe4__RelatedContact__c = :contactId
    ];
  }

  public List<npe4__Relationship__c> getCurrentRelated(
    Set<Id> contactIds,
    String type
  ) {
    return [
      SELECT Id, npe4__Contact__c, npe4__RelatedContact__c
      FROM npe4__Relationship__c
      WHERE
        npe4__Contact__c IN :contactIds
        AND npe4__Status__c = 'Current'
        AND npe4__Type__c = :type
    ];
  }
  public npe4__Relationship__c create(npe4__Relationship__c relationship) {
    upsert relationship;
    return relationship;
  }
  public npe4__Relationship__c modify(npe4__Relationship__c relationship) {
    update relationship;
    return relationship;
  }
}