force-app/main/default/objects/Contact/fields/ContactFormReceived__c.field-meta.xml
<CustomField>
    <fullName>ContactFormReceived__c</fullName>
    <description>The date the most recent version of Contact Form was uploaded</description>
    <inlineHelpText>Set programmatically when online contact form is completed.</inlineHelpText>
    <label>Last Contact Form</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FirstAidReceived__c.field-meta.xml
<CustomField>
    <fullName>FirstAidReceived__c</fullName>
    <description>The date the most recent version of First Aid Certification was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last First Aid Certificate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MediaReceived__c.field-meta.xml
<CustomField>
    <fullName>MediaReceived__c</fullName>
    <description>The date the most recent version of Media Agreement was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Media Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ParticipationAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>ParticipationAgreementReceived__c</fullName>
    <description>The date the most recent version of Participant Agreement was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Participation Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/test/files/TestFileServiceNaFields.cls
@isTest
public with sharing class TestFileServiceNaFields {


    @isTest
    public static void updateDate_NaContactForm_SetsDateWhenNull() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Na', 'ContactForm', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ContactFormReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ContactFormReceived__c,
            'ContactFormReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_NaContactForm_SetsDateWhenNewer() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', ContactFormReceived__c = Date.today().addDays(-1));
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Na', 'ContactForm', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ContactFormReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ContactFormReceived__c,
            'ContactFormReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_NaContactForm_LeavesDateWhenOlder() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', ContactFormReceived__c = Date.today());
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Na', 'ContactForm', Date.today().addDays(-1), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ContactFormReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ContactFormReceived__c,
            'ContactFormReceived__c set to an older date'
        );
    }

    @isTest
    public static void updateDate_NaFirstAid_SetsDateWhenNull() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Na', 'FirstAid', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT FirstAidReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.FirstAidReceived__c,
            'FirstAidReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_NaFirstAid_SetsDateWhenNewer() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', FirstAidReceived__c = Date.today().addDays(-1));
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Na', 'FirstAid', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT FirstAidReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.FirstAidReceived__c,
            'FirstAidReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_NaFirstAid_LeavesDateWhenOlder() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', FirstAidReceived__c = Date.today());
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Na', 'FirstAid', Date.today().addDays(-1), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT FirstAidReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.FirstAidReceived__c,
            'FirstAidReceived__c set to an older date'
        );
    }

    @isTest
    public static void updateDate_NaMedia_SetsDateWhenNull() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Na', 'Media', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT MediaReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.MediaReceived__c,
            'MediaReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_NaMedia_SetsDateWhenNewer() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', MediaReceived__c = Date.today().addDays(-1));
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Na', 'Media', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT MediaReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.MediaReceived__c,
            'MediaReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_NaMedia_LeavesDateWhenOlder() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', MediaReceived__c = Date.today());
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Na', 'Media', Date.today().addDays(-1), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT MediaReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.MediaReceived__c,
            'MediaReceived__c set to an older date'
        );
    }

    @isTest
    public static void updateDate_NaParticipationAgreement_SetsDateWhenNull() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Na', 'ParticipationAgreement', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ParticipationAgreementReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ParticipationAgreementReceived__c,
            'ParticipationAgreementReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_NaParticipationAgreement_SetsDateWhenNewer() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', ParticipationAgreementReceived__c = Date.today().addDays(-1));
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Na', 'ParticipationAgreement', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ParticipationAgreementReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ParticipationAgreementReceived__c,
            'ParticipationAgreementReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_NaParticipationAgreement_LeavesDateWhenOlder() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', ParticipationAgreementReceived__c = Date.today());
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Na', 'ParticipationAgreement', Date.today().addDays(-1), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ParticipationAgreementReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ParticipationAgreementReceived__c,
            'ParticipationAgreementReceived__c set to an older date'
        );
    }
}