force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Place/person to contact this person</description>
    <inlineHelpText>Select Guardian to contact this person through their guardian, Home for personal email/phone</inlineHelpText>
    <label>Contact At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
                <default>true</default>
                <label>Home</label>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Atlas Program</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramAssignment__c/ProgramAssignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Program Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramAssignment__c/fields/AssignedDate__c.field-meta.xml
<CustomField>
    <fullName>AssignedDate__c</fullName>
    <label>Assigned Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/CompletionDate__c.field-meta.xml
<CustomField>
    <fullName>CompletionDate__c</fullName>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assigned Programs</relationshipLabel>
    <relationshipName>AssignedProgram</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/ExpectedCompletion__c.field-meta.xml
<CustomField>
    <fullName>ExpectedCompletion__c</fullName>
    <description>Expected completion date</description>
    <label>Expected Completion</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramAssignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/test/TestProgramAssignmentTrigger.cls
@isTest
public with sharing class TestProgramAssignmentTrigger {
    @testSetup
    static void setup() {
        Contact joe = new Contact(FirstName = 'Joe', LastName = 'Blow');
        insert joe;
    }

    static void setProgramDurations() {
        // Set some durations, all different to make testing more clear
        Settings.programDurations = new Map<String, Decimal>{
            'Volunteer' => 0.5,
            'Client' => 3,
            'Team Facilitator' => 4,
            'Teams Set in Motion Client' => 5,
            'Trainer' => 6
        };
        System.debug('Set programDurations');
    }

    static ProgramAssignment__c getProgramAssignment(Id ProgramAssignmentId) {
        ProgramAssignment__c saved = [
            SELECT
                AssignedDate__c,
                CompletionDate__c,
                Contact__c,
                ExpectedCompletion__c,
                Program__c,
                Status__c
            FROM ProgramAssignment__c
            WHERE id = :ProgramAssignmentId
            LIMIT 1
        ];
        return saved;
    }

    @isTest
    static void insert_setsAssignedToday_WhenAssignedNotSet() {
        // Set some durations, all different to make testing more clear
        setProgramDurations();
        Contact joe = [SELECT Id FROM Contact WHERE FirstName = 'Joe' LIMIT 1];
        ProgramAssignment__c ProgramAssignment = new ProgramAssignment__c(
            Program__c = 'Volunteer',
            Contact__c = joe.id,
            AssignedDate__c = Date.today()
        );

        // Act
        Test.startTest();
        Database.SaveResult result = Database.insert(ProgramAssignment, false);
        Test.stopTest();

        // Assert
        System.assert(result.isSuccess());
        ProgramAssignment__c saved = getProgramAssignment(result.getId());
        System.assert(result.getErrors().size() == 0);
        System.assertEquals(Date.today(), saved.AssignedDate__c);
    }

    static void testInsertSetsExpected(String program) {
        // Arrange
        setProgramDurations();
        Contact joe = [SELECT Id FROM Contact WHERE FirstName = 'Joe' LIMIT 1];
        // Create a ProgramAssignment__c with Volunteer program
        Date assigned = Date.newInstance(2021, 1, 10);
        ProgramAssignment__c assignment = new ProgramAssignment__c(
            AssignedDate__c = assigned,
            Program__c = program,
            Contact__c = joe.Id
        );

        Decimal duration = Settings.programDurations.get(program);

        // Act
        Test.startTest();
        Database.SaveResult result = Database.insert(assignment, false);
        Test.stopTest();

        // Assert
        System.assert(result.isSuccess());
        ProgramAssignment__c saved = getProgramAssignment(result.getId());
        Date expected = assigned.addDays((Integer) (duration * 30));
        System.assert(result.getErrors().size() == 0);
        System.assertEquals(expected, saved.ExpectedCompletion__c);
        System.assertEquals(assigned, saved.AssignedDate__c);
    }

    @isTest
    static void insertVolunteerProgramAssignment_SetsExpected() {
        testInsertSetsExpected('Volunteer');
    }

    @isTest
    static void insert_DoesNotChangeExpected_WhenExpectedSet() {
        // Arrange
        setProgramDurations();
        Contact joe = [SELECT Id FROM Contact WHERE FirstName = 'Joe' LIMIT 1];
        // Create a ProgramAssignment__c with Volunteer program
        Date assigned = Date.newInstance(2021, 1, 10);
        Date expected = assigned.addMonths(1);
        ProgramAssignment__c assignment = new ProgramAssignment__c(
            AssignedDate__c = assigned,
            ExpectedCompletion__c = expected,
            Program__c = 'Volunteer',
            Contact__c = joe.Id
        );

        // Act
        Test.startTest();
        Database.SaveResult result = Database.insert(assignment, false);
        Test.stopTest();

        // Assert
        System.assert(result.isSuccess());
        ProgramAssignment__c saved = getProgramAssignment(result.getId());
        System.assert(result.getErrors().size() == 0);
        System.assertEquals(expected, saved.ExpectedCompletion__c);
    }

    @isTest
    static void updateWithNoDateChangesLeavesThem() {
        setProgramDurations();
        Contact joe = [SELECT Id FROM Contact WHERE FirstName = 'Joe' LIMIT 1];
        Date assigned = Date.newInstance(2020, 1, 10);
        ProgramAssignment__c programAssignment = new ProgramAssignment__c(
            AssignedDate__c = assigned,
            ExpectedCompletion__c = Date.today(),
            Contact__c = joe.Id
        );
        insert programAssignment;

        programAssignment = getProgramAssignment(ProgramAssignment.Id);

        // Act
        Test.startTest();
        Database.SaveResult result = Database.update(programAssignment, false);
        Test.stopTest();

        // Assert
        System.assert(result.isSuccess());
        ProgramAssignment__c saved = getProgramAssignment(programAssignment.Id);
        System.assert(result.getErrors().size() == 0);
        System.assertEquals(assigned, saved.AssignedDate__c);
        System.assertEquals(Date.today(), saved.ExpectedCompletion__c);
    }
}