force-app/main/default/objects/Contact/fields/ContactFormReceived__c.field-meta.xml
<CustomField>
    <fullName>ContactFormReceived__c</fullName>
    <description>The date the most recent version of Contact Form was uploaded</description>
    <inlineHelpText>Set programmatically when online contact form is completed.</inlineHelpText>
    <label>Last Contact Form</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FacilitatorApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>FacilitatorApplicationReceived__c</fullName>
    <description
    >The date the most recent version of Team Facilitator Application was uploaded</description>
    <label>Last Facilitator Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FacilitatorCertAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>FacilitatorCertAgreementReceived__c</fullName>
    <description>The date the most recent version of Team Facilitator Certification Agreement was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Facilitator Certification Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FacilitatorInfrNoticeReceived__c.field-meta.xml
<CustomField>
    <fullName>FacilitatorInfrNoticeReceived__c</fullName>
    <description
    >The date the most recent version of Team Facilitator Infraction Notice was uploaded</description>
    <label>Last Facilitator Infraction Notice</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FacilitatorPracticumReceived__c.field-meta.xml
<CustomField>
    <fullName>FacilitatorPracticumReceived__c</fullName>
    <description
    >The date the most recent version of Team Facilitator Practicum was uploaded</description>
    <label>Last Facilitator Practicum</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FacilitatorProfGrowthPlanReceived__c.field-meta.xml
<CustomField>
    <fullName>FacilitatorProfGrowthPlanReceived__c</fullName>
    <description>The date the most recent version of Team Facilitator Professional Growth Plan was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Facilitator Prof Growth Plan</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FacilitatorProgAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>FacilitatorProgAgreementReceived__c</fullName>
    <description>The date the most recent version of Team Facilitator Program Agreement was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last Facilitator Program Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FacilitatorReferenceReceived__c.field-meta.xml
<CustomField>
    <fullName>FacilitatorReferenceReceived__c</fullName>
    <description
    >The date the most recent version of Team Facilitator Reference Letter was uploaded</description>
    <label>Last Facilitator Reference Letter</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/test/TestFileServiceFacilitatorFields.cls
@isTest
public with sharing class TestFileServiceFacilitatorFields {


    @isTest
    public static void updateDate_FacilitatorApplication_SetsDateWhenNull() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Facilitator', 'Application', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT FacilitatorApplicationReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.FacilitatorApplicationReceived__c,
            'FacilitatorApplicationReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_FacilitatorApplication_SetsDateWhenNewer() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', FacilitatorApplicationReceived__c = Date.today().addDays(-1));
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Facilitator', 'Application', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT FacilitatorApplicationReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.FacilitatorApplicationReceived__c,
            'FacilitatorApplicationReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_FacilitatorApplication_LeavesDateWhenOlder() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', FacilitatorApplicationReceived__c = Date.today());
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Facilitator', 'Application', Date.today().addDays(-1), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT FacilitatorApplicationReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.FacilitatorApplicationReceived__c,
            'FacilitatorApplicationReceived__c set to an older date'
        );
    }

    @isTest
    public static void updateDate_FacilitatorCertAgreement_SetsDateWhenNull() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Facilitator', 'CertAgreement', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT FacilitatorCertAgreementReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.FacilitatorCertAgreementReceived__c,
            'FacilitatorCertAgreementReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_FacilitatorCertAgreement_SetsDateWhenNewer() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', FacilitatorCertAgreementReceived__c = Date.today().addDays(-1));
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Facilitator', 'CertAgreement', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT FacilitatorCertAgreementReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.FacilitatorCertAgreementReceived__c,
            'FacilitatorCertAgreementReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_FacilitatorCertAgreement_LeavesDateWhenOlder() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', FacilitatorCertAgreementReceived__c = Date.today());
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Facilitator', 'CertAgreement', Date.today().addDays(-1), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT FacilitatorCertAgreementReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.FacilitatorCertAgreementReceived__c,
            'FacilitatorCertAgreementReceived__c set to an older date'
        );
    }

    @isTest
    public static void updateDate_FacilitatorContactForm_SetsDateWhenNull() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Facilitator', 'ContactForm', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ContactFormReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ContactFormReceived__c,
            'ContactFormReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_FacilitatorContactForm_SetsDateWhenNewer() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', ContactFormReceived__c = Date.today().addDays(-1));
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Facilitator', 'ContactForm', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ContactFormReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ContactFormReceived__c,
            'ContactFormReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_FacilitatorContactForm_LeavesDateWhenOlder() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', ContactFormReceived__c = Date.today());
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Facilitator', 'ContactForm', Date.today().addDays(-1), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT ContactFormReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.ContactFormReceived__c,
            'ContactFormReceived__c set to an older date'
        );
    }

    @isTest
    public static void updateDate_FacilitatorInfrNotice_SetsDateWhenNull() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Facilitator', 'InfrNotice', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT FacilitatorInfrNoticeReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.FacilitatorInfrNoticeReceived__c,
            'FacilitatorInfrNoticeReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_FacilitatorInfrNotice_SetsDateWhenNewer() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', FacilitatorInfrNoticeReceived__c = Date.today().addDays(-1));
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Facilitator', 'InfrNotice', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT FacilitatorInfrNoticeReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.FacilitatorInfrNoticeReceived__c,
            'FacilitatorInfrNoticeReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_FacilitatorInfrNotice_LeavesDateWhenOlder() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', FacilitatorInfrNoticeReceived__c = Date.today());
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Facilitator', 'InfrNotice', Date.today().addDays(-1), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT FacilitatorInfrNoticeReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.FacilitatorInfrNoticeReceived__c,
            'FacilitatorInfrNoticeReceived__c set to an older date'
        );
    }

    @isTest
    public static void updateDate_FacilitatorPracticum_SetsDateWhenNull() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Facilitator', 'Practicum', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT FacilitatorPracticumReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.FacilitatorPracticumReceived__c,
            'FacilitatorPracticumReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_FacilitatorPracticum_SetsDateWhenNewer() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', FacilitatorPracticumReceived__c = Date.today().addDays(-1));
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Facilitator', 'Practicum', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT FacilitatorPracticumReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.FacilitatorPracticumReceived__c,
            'FacilitatorPracticumReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_FacilitatorPracticum_LeavesDateWhenOlder() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', FacilitatorPracticumReceived__c = Date.today());
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Facilitator', 'Practicum', Date.today().addDays(-1), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT FacilitatorPracticumReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.FacilitatorPracticumReceived__c,
            'FacilitatorPracticumReceived__c set to an older date'
        );
    }

    @isTest
    public static void updateDate_FacilitatorProfGrowthPlan_SetsDateWhenNull() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Facilitator', 'ProfGrowthPlan', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT FacilitatorProfGrowthPlanReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.FacilitatorProfGrowthPlanReceived__c,
            'FacilitatorProfGrowthPlanReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_FacilitatorProfGrowthPlan_SetsDateWhenNewer() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', FacilitatorProfGrowthPlanReceived__c = Date.today().addDays(-1));
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Facilitator', 'ProfGrowthPlan', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT FacilitatorProfGrowthPlanReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.FacilitatorProfGrowthPlanReceived__c,
            'FacilitatorProfGrowthPlanReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_FacilitatorProfGrowthPlan_LeavesDateWhenOlder() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', FacilitatorProfGrowthPlanReceived__c = Date.today());
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Facilitator', 'ProfGrowthPlan', Date.today().addDays(-1), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT FacilitatorProfGrowthPlanReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.FacilitatorProfGrowthPlanReceived__c,
            'FacilitatorProfGrowthPlanReceived__c set to an older date'
        );
    }

    @isTest
    public static void updateDate_FacilitatorProgAgreement_SetsDateWhenNull() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Facilitator', 'ProgAgreement', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT FacilitatorProgAgreementReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.FacilitatorProgAgreementReceived__c,
            'FacilitatorProgAgreementReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_FacilitatorProgAgreement_SetsDateWhenNewer() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', FacilitatorProgAgreementReceived__c = Date.today().addDays(-1));
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Facilitator', 'ProgAgreement', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT FacilitatorProgAgreementReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.FacilitatorProgAgreementReceived__c,
            'FacilitatorProgAgreementReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_FacilitatorProgAgreement_LeavesDateWhenOlder() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', FacilitatorProgAgreementReceived__c = Date.today());
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Facilitator', 'ProgAgreement', Date.today().addDays(-1), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT FacilitatorProgAgreementReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.FacilitatorProgAgreementReceived__c,
            'FacilitatorProgAgreementReceived__c set to an older date'
        );
    }

    @isTest
    public static void updateDate_FacilitatorReference_SetsDateWhenNull() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Facilitator', 'Reference', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT FacilitatorReferenceReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.FacilitatorReferenceReceived__c,
            'FacilitatorReferenceReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_FacilitatorReference_SetsDateWhenNewer() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', FacilitatorReferenceReceived__c = Date.today().addDays(-1));
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Facilitator', 'Reference', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT FacilitatorReferenceReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.FacilitatorReferenceReceived__c,
            'FacilitatorReferenceReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_FacilitatorReference_LeavesDateWhenOlder() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', FacilitatorReferenceReceived__c = Date.today());
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('Facilitator', 'Reference', Date.today().addDays(-1), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT FacilitatorReferenceReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.FacilitatorReferenceReceived__c,
            'FacilitatorReferenceReceived__c set to an older date'
        );
    }
}