force-app/main/default/objects/Contact/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Handler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contacts.recordType-meta.xml
<RecordType>
    <fullName>Contacts</fullName>
    <active>true</active>
    <label>Contacts</label>
</RecordType>

force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Derived from Team.  Do not edit directly.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In ADSiM</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>Certified-Active</fullName>
            </value>
            <value>
                <fullName>Certified-OnHold</fullName>
            </value>
            <value>
                <fullName>Decertified</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/PublicAccessTest__c.object-meta.xml
<CustomObject>
    <description>Tests that the Dog/Client team can perform in public.</description>
    <label>PAT</label>
    <nameField>
        <displayFormat>PAT-{0000}</displayFormat>
        <label>Public Access Test Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PATs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PublicAccessTest__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person assessing the team</description>
    <label>Assessor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Public_Access_Tests_Assessor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/AssessorComments__c.field-meta.xml
<CustomField>
    <fullName>AssessorComments__c</fullName>
    <description>Comments from the person assessing the team</description>
    <label>Assessor Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client being assessed in the PAT</description>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PATs (Client)</relationshipLabel>
    <relationshipName>Public_Access_Tests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/DateCompleted__c.field-meta.xml
<CustomField>
    <fullName>DateCompleted__c</fullName>
    <description>Date the test was completed</description>
    <label>Date Completed</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Dog in the PAT team</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>PATs</relationshipLabel>
    <relationshipName>Public_Access_Tests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Handler in the team, if not the client</description>
    <label>Handler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Public_Access_Tests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Relative location of the test</description>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/ReviewComments__c.field-meta.xml
<CustomField>
    <fullName>ReviewComments__c</fullName>
    <description>Comments made by the client</description>
    <label>Review Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the PAT</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Provisionally Passed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PublicAccessTest__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Team the test is for</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>PATs</relationshipLabel>
    <relationshipName>PATs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Records the Facilitator, Lead, and Client relationship</description>
    <label>Team</label>
    <nameField>
        <displayFormat>Team-{00000}</displayFormat>
        <label>Team Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client</description>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams (Client)</relationshipLabel>
    <relationshipName>Teams1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Dog__c.field-meta.xml
<CustomField>
    <fullName>Dog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dog on the team</description>
    <label>Dog</label>
    <referenceTo>Dog__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Handler in the team, if not the client</description>
    <label>Handler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/PatCount__c.field-meta.xml
<CustomField>
    <fullName>PatCount__c</fullName>
    <description
    >Number of Public Access Tests the Client-Dog team has taken</description>
    <label>PAT Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/PatValidUntil__c.field-meta.xml
<CustomField>
    <fullName>PatValidUntil__c</fullName>
    <description>Date the Public Access Test expires</description>
    <inlineHelpText>Derived from most recent passed PAT. Do not edit directly.</inlineHelpText>
    <label>PAT Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/PrimaryCertification__c.field-meta.xml
<CustomField>
    <fullName>PrimaryCertification__c</fullName>
    <label>Primary Certification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Certifications</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team__c/fields/SecondaryCertification__c.field-meta.xml
<CustomField>
    <fullName>SecondaryCertification__c</fullName>
    <label>Secondary Certification</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Certifications</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>This status defines the status for the Team, Dog, and Client.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inquiry</fullName>
            </value>
            <value>
                <fullName>In ADSiM</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>In Training</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Certified-Hold</fullName>
            </value>
            <value>
                <fullName>Decertified</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Certifications.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Atlas</fullName>
        <default>true</default>
        <label>Atlas</label>
    </customValue>
    <customValue>
        <fullName>KPA</fullName>
    </customValue>
    <customValue>
        <fullName>CCPDT</fullName>
    </customValue>
    <customValue>
        <fullName>IAABC</fullName>
    </customValue>
    <customValue>
        <fullName>CBCC</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <description>Client Dog Team Certifications</description>
    <masterLabel>Certifications</masterLabel>
</GlobalValueSet>

force-app/main/test/TestPublicAccessTestController.cls
@isTest
public class TestPublicAccessTestController {
    private static Contact jack;
    private static Contact jill;
    private static Dog__c fido;
    private static Dog__c rover;
    private static Team__c team;
    private static void insertContacts() {
        List<Contact> contacts = new List<Contact>();
        contacts.add(
            new Contact(
                FirstName = 'Jack',
                LastName = 'Contact',
                Email = 'jack@test.com'
            )
        );
        contacts.add(
            new Contact(
                FirstName = 'Jill',
                LastName = 'Contact',
                Email = 'jill@test.com'
            )
        );
        insert contacts;

        jack = contacts[0];
        jill = contacts[1];

        fido = new Dog__c(Name = 'Fido');
        rover = new Dog__c(Name = 'Rover');
        insert new List<Dog__c>{ fido, rover };

        team = new Team__c(
            Client__c = jack.Id,
            Dog__c = fido.Id,
            Handler__c = jill.Id,
            PatCount__c = 2,
            PatValidUntil__c = Date.today().addYears(1),
            PrimaryCertification__c = 'Allergen Alert',
            SecondaryCertification__c = 'Autism'
        );
        insert team;
    }

    @isTest
    public static void getRelatedPats_ReturnsEmpty_WhenNoId() {
        Test.startTest();
        RelatedObjects result = PublicAccessTestController.getRelatedPats(
            null, 5
        );
        Test.stopTest();

        System.assert(result.items.isEmpty());
        System.assertEquals(0, result.total);
    }

    @isTest
    public static void getRelatedPats_ReturnsEmpty_WhenNoPats() {
        insertContacts();

        Test.startTest();
        RelatedObjects result = PublicAccessTestController.getRelatedPats(
            jill.Id, 5
        );
        Test.stopTest();

        System.assert(result.items.isEmpty());
        System.assertEquals(0, result.total);
    }

    @isTest
    public static void getRelatedPats_ReturnsEmpty_WhenNoPatsForTheContact() {
        insertContacts();
        List<PublicAccessTest__c> pats = new List<PublicAccessTest__c>();
        pats.add(
            new PublicAccessTest__c(
                Assessor__c = jill.Id,
                AssessorComments__c = 'AssessorComments__c',
                DateCompleted__c = Date.today().addDays(-2),
                Location__c = 'In Person',
                ReviewComments__c = 'ReviewComments__c',
                Status__c = 'Passed',
                Team__c = team.Id,
                Type__c = 'Recertification'
            )
        );

        pats.add(
            new PublicAccessTest__c(
                AssessorComments__c = 'AssessorComments__c',
                DateCompleted__c = Date.today().addDays(-2),
                Location__c = 'In Person',
                ReviewComments__c = 'ReviewComments__c',
                Status__c = 'Passed',
                Team__c = team.Id,
                Type__c = 'Recertification'
            )
        );

        pats.add(
            new PublicAccessTest__c(
                AssessorComments__c = 'AssessorComments__c',
                DateCompleted__c = Date.today().addDays(-2),
                Location__c = 'In Person',
                ReviewComments__c = 'ReviewComments__c',
                Status__c = 'Passed',
                Team__c = team.Id,
                Type__c = 'Recertification'
            )
        );
        insert pats;

        Test.startTest();
        RelatedObjects result = PublicAccessTestController.getRelatedPats(
            jack.Id, 5
        );
        Test.stopTest();

        System.assert(result.items.isEmpty());
        System.assertEquals(0, result.total);
    }

    @isTest
    public static void getRelatedPats_ReturnsAllPatsForTheTeam() {
        insertContacts();
        List<PublicAccessTest__c> pats = new List<PublicAccessTest__c>();
        pats.add(
            new PublicAccessTest__c(
                Assessor__c = jill.Id,
                AssessorComments__c = 'AssessorComments 1',
                DateCompleted__c = Date.today(),
                Location__c = 'In Person',
                ReviewComments__c = 'ReviewComments 1',
                Status__c = 'Passed',
                Team__c = team.Id,
                Type__c = 'Initial'
            )
        );

        pats.add(
            new PublicAccessTest__c(
                AssessorComments__c = 'AssessorComments 2',
                DateCompleted__c = Date.today().addDays(-1),
                Location__c = 'Virtual',
                ReviewComments__c = 'ReviewComments 2',
                Status__c = 'Failed',
                Team__c = team.Id,
                Type__c = 'Recertification'
            )
        );

        pats.add(
            new PublicAccessTest__c(
                AssessorComments__c = 'AssessorComments 3',
                DateCompleted__c = Date.today().addDays(-2),
                Location__c = 'In Person',
                ReviewComments__c = 'ReviewComments 3',
                Status__c = 'Provisionally Passed',
                Team__c = team.Id,
                Type__c = 'Retest'
            )
        );
        insert pats;

        Test.startTest();
        RelatedObjects result = PublicAccessTestController.getRelatedPats(
            team.Id, 5
        );
        Test.stopTest();

        System.assertEquals(3, result.items.size());
        System.assertEquals(3, result.total);
        for (Integer idx = 0; idx < pats.size(); idx++) {
            PublicAccessTest__c actual = (PublicAccessTest__c)result.items[idx];
            PublicAccessTest__c expected = pats[idx];
            System.assertEquals(expected.Id, actual.Id);
            System.assertEquals(expected.Assessor__c, actual.Assessor__c);
            System.assertEquals(
                expected.AssessorComments__c,
                actual.AssessorComments__c
            );
            System.assertEquals(
                expected.DateCompleted__c,
                actual.DateCompleted__c
            );
            System.assertEquals(expected.Location__c, actual.Location__c);
            System.assertEquals(
                expected.ReviewComments__c,
                actual.ReviewComments__c
            );
            System.assertEquals(expected.Status__c, actual.Status__c);
            System.assertEquals(expected.Team__c, actual.Team__c);
            System.assertEquals(expected.Type__c, actual.Type__c);
        }
    }

    @isTest
    public static void createPat_ReturnsException() {
        insertContacts();

        PublicAccessTest__c pat = new PublicAccessTest__c(
            Assessor__c = fido.Id,
            AssessorComments__c = 'AssessorComments',
            DateCompleted__c = Date.today().addDays(-2),
            Location__c = 'In Person',
            ReviewComments__c = 'ReviewComments',
            Status__c = 'Provisionally Passed',
            Team__c = team.Id,
            Type__c = 'Retest'
        );
        Boolean thrown = false;

        Test.startTest();
        try {
            PublicAccessTestController.createPat(pat, null);
        } catch (AuraHandledException e) {
            thrown = true;
        }
        Test.stopTest();

        System.assert(thrown);
    }

    @isTest
    public static void createPat_InsertsPat() {
        insertContacts();

        PublicAccessTest__c expected = new PublicAccessTest__c(
            Assessor__c = jack.Id,
            AssessorComments__c = 'AssessorComments',
            DateCompleted__c = Date.today().addDays(-2),
            Location__c = 'In Person',
            ReviewComments__c = 'ReviewComments',
            Status__c = 'Provisionally Passed',
            Team__c = team.Id,
            Type__c = 'Retest'
        );

        Test.startTest();
        PublicAccessTestController.createPat(expected, null);
        Test.stopTest();

        PublicAccessTest__c actual = [
            SELECT
                Assessor__c,
                AssessorComments__c,
                DateCompleted__c,
                Location__c,
                ReviewComments__c,
                Status__c,
                Team__c,
                Type__c
            FROM PublicAccessTest__c
            LIMIT 1
        ];

        System.assertEquals(expected.Assessor__c, actual.Assessor__c);
        System.assertEquals(
            expected.AssessorComments__c,
            actual.AssessorComments__c
        );
        System.assertEquals(expected.DateCompleted__c, actual.DateCompleted__c);
        System.assertEquals(expected.Location__c, actual.Location__c);
        System.assertEquals(
            expected.ReviewComments__c,
            actual.ReviewComments__c
        );
        System.assertEquals(expected.Status__c, actual.Status__c);
        System.assertEquals(expected.Team__c, actual.Team__c);
        System.assertEquals(expected.Type__c, actual.Type__c);
    }

    @isTest
    public static void createPat_InsertsPatAndRelatesFile() {
        insertContacts();

        PublicAccessTest__c expected = new PublicAccessTest__c(
            Assessor__c = jack.Id,
            AssessorComments__c = 'AssessorComments',
            DateCompleted__c = Date.today().addDays(-2),
            Location__c = 'In Person',
            ReviewComments__c = 'ReviewComments',
            Status__c = 'Provisionally Passed',
            Team__c = team.Id,
            Type__c = 'Retest'
        );

        ContentVersion document = new ContentVersion(
            Title = 'TestDocument',
            PathOnClient = 'TestDocument.jpg',
            Origin = 'H',
            VersionData = Blob.valueOf('Document Body')
        );
        insert document;

        Id contentDocumentId = [
            SELECT ContentDocumentId
            FROM ContentVersion
            WHERE Id = :document.Id
        ]
        .ContentDocumentId;

        Test.startTest();
        PublicAccessTestController.createPat(
            expected,
            new List<Id>{ contentDocumentId }
        );
        Test.stopTest();

        PublicAccessTest__c actual = [
            SELECT
                Assessor__c,
                AssessorComments__c,
                DateCompleted__c,
                Location__c,
                ReviewComments__c,
                Status__c,
                Team__c,
                Type__c
            FROM PublicAccessTest__c
            LIMIT 1
        ];

        RelatedObjects related = FileController.getRelatedFiles(
            actual.Id, 5
        );
        System.assertEquals(
            contentDocumentId,
            ((ContentVersion)related.items[0]).ContentDocumentId
        );
    }

    @isTest
    public static void updatePat_ThrowsException_WhenNoPat() {
        Boolean thrown = false;

        Test.startTest();
        try {
            BackgroundCheckController.updateBackgroundCheck(null);
        } catch (AuraHandledException e) {
            thrown = true;
        }
        Test.stopTest();

        System.assert(thrown);
    }

    @isTest
    public static void updatePat_ThrowsException_WhenNotInserted() {
        insertContacts();
        PublicAccessTest__c pat = new PublicAccessTest__c(
            Assessor__c = jack.Id,
            AssessorComments__c = 'AssessorComments',
            DateCompleted__c = Date.today().addDays(-2),
            Location__c = 'In Person',
            ReviewComments__c = 'ReviewComments',
            Status__c = 'Provisionally Passed',
            Team__c = team.Id,
            Type__c = 'Retest'
        );
        Boolean thrown = false;

        Test.startTest();
        try {
            PublicAccessTestController.updatePat(pat);
        } catch (AuraHandledException e) {
            thrown = true;
        }
        Test.stopTest();

        System.assert(thrown);
    }

    @isTest
    public static void updatePat_UpdatesPat() {
        insertContacts();
        PublicAccessTest__c pat = new PublicAccessTest__c(
            Assessor__c = jack.Id,
            AssessorComments__c = 'AssessorComments',
            DateCompleted__c = Date.today().addDays(-2),
            Location__c = 'Virtual',
            ReviewComments__c = 'ReviewComments',
            Status__c = 'Provisionally Passed',
            Team__c = team.Id,
            Type__c = 'Retest'
        );
        insert pat;

        pat.Assessor__c = jill.Id;
        pat.AssessorComments__c = 'Different comments';
        pat.DateCompleted__c = Date.today();
        pat.ReviewComments__c = 'Different review comments';
        pat.Status__c = 'Failed';
        pat.Type__c = 'Initial';

        Test.startTest();
        PublicAccessTestController.updatePat(pat);
        Test.stopTest();

        PublicAccessTest__c actual = [
            SELECT
                Assessor__c,
                AssessorComments__c,
                DateCompleted__c,
                Location__c,
                ReviewComments__c,
                Status__c,
                Team__c,
                Type__c
            FROM PublicAccessTest__c
            LIMIT 1
        ];
        System.assertEquals(pat.Assessor__c, actual.Assessor__c);
        System.assertEquals(
            pat.AssessorComments__c,
            actual.AssessorComments__c
        );
        System.assertEquals(pat.DateCompleted__c, actual.DateCompleted__c);
        System.assertEquals(pat.Location__c, actual.Location__c);
        System.assertEquals(pat.ReviewComments__c, actual.ReviewComments__c);
        System.assertEquals(pat.Status__c, actual.Status__c);
        System.assertEquals(pat.Team__c, actual.Team__c);
        System.assertEquals(pat.Type__c, actual.Type__c);
    }

    @isTest
    public static void deletePat_ThrowsException_WhenNoRecordId() {
        Boolean thrown = true;

        Test.startTest();
        try {
            PublicAccessTestController.deletePat(null);
        } catch (AuraHandledException e) {
            thrown = true;
        }

        System.assert(thrown);
    }

    @isTest
    public static void deletePat_ThrowsException_WhenBadRecordId() {
        insertContacts();
        Boolean thrown = true;

        Test.startTest();
        try {
            PublicAccessTestController.deletePat(jill.Id);
        } catch (AuraHandledException e) {
            thrown = true;
        }

        System.assert(thrown);
    }

    @isTest
    public static void deletePat_DeletesPat() {
        insertContacts();
        PublicAccessTest__c pat = new PublicAccessTest__c(
            Assessor__c = jack.Id,
            AssessorComments__c = 'AssessorComments',
            DateCompleted__c = Date.today().addDays(-2),
            Location__c = 'In Person',
            ReviewComments__c = 'ReviewComments',
            Status__c = 'Provisionally Passed',
            Team__c = team.Id,
            Type__c = 'Retest'
        );
        insert pat;

        Test.startTest();
        PublicAccessTestController.deletePat(pat.Id);
        Test.stopTest();

        List<PublicAccessTest__c> actual = [SELECT Id FROM PublicAccessTest__c];
        System.assert(actual.isEmpty());
    }
}