force-app/main/default/objects/Contact/fields/Positions__c.field-meta.xml
<CustomField>
    <fullName>Positions__c</fullName>
    <description>Positions available</description>
    <label>Positions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Positions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ShareBoard__c.field-meta.xml
<CustomField>
    <fullName>ShareBoard__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Share this contact with users in the Board group</description>
    <label>Share With Board</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SharePuppyRaiser__c.field-meta.xml
<CustomField>
    <fullName>SharePuppyRaiser__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Share this contact with users in the Puppy Raiser group</description>
    <label>Share With Puppy Raiser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ShareStaff__c.field-meta.xml
<CustomField>
    <fullName>ShareStaff__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Share this contact with users in the Staff group</description>
    <label>Share With Staff</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ShareStandalonePrograms__c.field-meta.xml
<CustomField>
    <fullName>ShareStandalonePrograms__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Share this contact with users in the Standalone Programs group</description>
    <label>Share With Standalone Programs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ShareTeam__c.field-meta.xml
<CustomField>
    <fullName>ShareTeam__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Share this contact with users in the Team group</description>
    <label>Share With Team</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ShareTrainer__c.field-meta.xml
<CustomField>
    <fullName>ShareTrainer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Share this contact with users in the Trainer group</description>
    <label>Share With Trainer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ShareVolunteer__c.field-meta.xml
<CustomField>
    <fullName>ShareVolunteer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Share this contact with users in the Volunteer group</description>
    <label>Share With Volunteer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/ContentVersion/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Board</fullName>
            </value>
            <value>
                <fullName>Na</fullName>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Client</fullName>
                <label>Team Client</label>
            </value>
            <value>
                <fullName>TeamDog</fullName>
                <label>Team Dog</label>
            </value>
            <value>
                <fullName>TeamDog</fullName>
                <label>Team Dog</label>
            </value>
            <value>
                <fullName>Standalone</fullName>
                <label>Standalone Programs</label>
            </value>
            <value>
                <fullName>ADSiM</fullName>
                <label>Assistance Dogs Set in Motion</label>
            </value>
            <value>
                <fullName>Facilitator</fullName>
                <label>Team Facilitator</label>
            </value>
            <value>
                <fullName>Puppy</fullName>
                <label>Puppy Raiser</label>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
                <label>Staff/Contractor</label>
            </value>
            <value>
                <fullName>Dog</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Document Date</description>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Positions__c.field-meta.xml
<CustomField>
    <fullName>Positions__c</fullName>
    <description>Positions the Course is Applicable to</description>
    <label>Positions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Positions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PreApplication</fullName>
                <label>Pre Application</label>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>ContactForm</fullName>
                <label>Contact Form</label>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>CoI</fullName>
                <label>Conflict of Interest</label>
            </value>
            <value>
                <fullName>ToN</fullName>
                <label>Transmission of Notices</label>
            </value>
            <value>
                <fullName>LOMI</fullName>
                <label>Medical Provider Form</label>
            </value>
            <value>
                <fullName>Media</fullName>
                <label>Media Release</label>
            </value>
            <value>
                <fullName>VAPW</fullName>
                <label>Veteran Paperwork</label>
            </value>
            <value>
                <fullName>Survey</fullName>
                <label>Certification Survey</label>
            </value>
            <value>
                <fullName>Reference</fullName>
                <label>Reference Letter</label>
            </value>
            <value>
                <fullName>ClientReference</fullName>
                <label>Client Reference Letter</label>
            </value>
            <value>
                <fullName>ProfReference</fullName>
                <label>Professional Reference Letter</label>
            </value>
            <value>
                <fullName>ProgAgreement</fullName>
                <label>Program Agreement</label>
            </value>
            <value>
                <fullName>CertAgreement</fullName>
                <label>Certification Agreement</label>
            </value>
            <value>
                <fullName>Practicum</fullName>
            </value>
            <value>
                <fullName>InfrNotice</fullName>
                <label>Infraction Notice</label>
            </value>
            <value>
                <fullName>HealthForm</fullName>
                <label>Vet Health Form</label>
            </value>
            <value>
                <fullName>Notes</fullName>
                <label>Interview Notes</label>
            </value>
            <value>
                <fullName>Xray</fullName>
                <label>Vet Xray Report</label>
            </value>
            <value>
                <fullName>VacExams</fullName>
                <label>Vaccinations and Exams</label>
            </value>
            <value>
                <fullName>Resume</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
                <label>Offer Letter</label>
            </value>
            <value>
                <fullName>W4</fullName>
            </value>
            <value>
                <fullName>I9</fullName>
            </value>
            <value>
                <fullName>W9</fullName>
                <label>Contractor W9</label>
            </value>
            <value>
                <fullName>ApplicationVideo</fullName>
                <label>Application Video</label>
            </value>
            <value>
                <fullName>CGCForm</fullName>
                <label>CGC Form</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Positions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Volunteer</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Board Member</fullName>
    </customValue>
    <customValue>
        <fullName>Trainer</fullName>
    </customValue>
    <customValue>
        <fullName>Client</fullName>
    </customValue>
    <customValue>
        <fullName>Donor</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
        <label>Staff/Contractor</label>
    </customValue>
    <customValue>
        <fullName>Puppy Raiser</fullName>
    </customValue>
    <customValue>
        <fullName>Standalone</fullName>
    </customValue>
    <customValue>
        <fullName>TSiM</fullName>
    </customValue>
    <description>Positions a contact can have</description>
    <masterLabel>Positions</masterLabel>
</GlobalValueSet>

force-app/main/test/files/TestFileControllerRestrictions.cls
/**
 * This class contains unit tests for validating the behavior of FileController
 */
@isTest
private class TestFileControllerRestrictions {
  public static List<ContentVersion> insertRecords() {
    // get a map of the category and type labels
    Map<String, List<String>> allCategories = TestUtilities.getCategoryTypeDependencies();
    List<ContentVersion> documents = new List<ContentVersion>();
    Integer count = 1;
    for (String category : allCategories.keySet()) {
      List<String> types = allCategories.get(category);
      for (String docType : types) {
        List<Object> parameters = new List<Object>{ count };
        documents.add(new ContentVersion(
          Title = String.format('TestDocument{0}', parameters), 
          PathOnClient = String.format('TestDocument{0}.jpg', parameters), 
          Origin = 'H', 
          VersionData = Blob.valueOf('Document Body'), 
          Category__c = category, 
          Type__c = docType, 
          Date__c = Date.today().addDays(-count)
        ));
        count = count + 1;
      }
    }

    insert documents;

    // We need to do the query here to get the ContentDocumentId's
    documents = [SELECT Id, 
                        ContentDocumentId, 
                        Title, 
                        PathOnClient, 
                        Origin, 
                        VersionData, 
                        Category__c, 
                        Type__c, 
                        Date__c
                 FROM ContentVersion];
    return documents;
  }

  // This method is used to setup the getRelatedFilesWith... tests.  The file records have all category/type combinations
  private static RelatedObjects getRelatedFilesWithGroups(string[] groups) {
    TestUtilities.insertCategoryRules();

    List<ContentVersion> documents = insertRecords();

    // Get the ids of all these documents
    List<Id> ids = new List<Id>();
    for (ContentVersion cv : documents) {
      ids.add(cv.ContentDocumentId);
    }
    Contact ronan = new Contact(
      FirstName = 'Ronan', 
      LastName = 'Dax', 
      email = 'ronan@test.com', 
      Positions__c = 'Board Member;Client;Puppy Raiser;Standalone;Staff;Team Facilitator;Team Facilitator Lead;Trainer;Volunteer', 
      ShareBoard__c = true, 
      SharePuppyRaiser__c = true, 
      ShareStaff__c = true, 
      ShareStandalonePrograms__c = true, 
      ShareTeam__c = true, 
      ShareTrainer__c = true, 
      ShareVolunteer__c = true
    );
    insert ronan;
    FileController.relateFiles(ids, ronan.Id);

    User testUser = TestUtilities.createUser('System Administrator');
    TestUtilities.addUserToGroups(testUser, groups);
    RelatedObjects related = new RelatedObjects();
    Test.startTest();
    System.runAs(new User(
      Id = testUser.Id
    )) {
      related = FileController.getRelatedFiles(ronan.Id, 6);
    }
    Test.stopTest();

    return related;
  }

  @isTest
  public static void getRelatedFiles_ReturnsRelatedRecords_ForBoardVolunteerTrainer() {
    RelatedObjects related = getRelatedFilesWithGroups(new List<string>{ 'Board', 'Volunteer', 'Trainer' });
    System.assert(related.items.size() <= 6);
    System.assertEquals(18, related.total, 'should have 18 total');
  }

  @isTest
  public static void getRelatedFiles_ReturnsRelatedRecords_ForBoard() {
    RelatedObjects related = getRelatedFilesWithGroups(new List<string>{ 'Board' });

    System.assertEquals(6, related.items.size());
    System.assertEquals(9, related.total, 'should have 9 files');
    System.assertEquals('Board', ((FileInfo)related.items[0]).category);
  }

  @isTest
  public static void getRelatedFiles_ReturnsRelatedRecords_ForVolunteer() {
    RelatedObjects related = getRelatedFilesWithGroups(new List<string>{ 'Volunteer' });

    System.assertEquals(6, related.items.size(), 'should have 6 files returned');
    System.assertEquals(7, related.total, 'should have 7 total');
    Set<String> cats = new Set<String>{ 'N/A', 'Volunteer' };
    for (Object obj : related.items) {
      FileInfo info = (FileInfo)obj;
      System.assert(cats.contains(info.category), 'should be N/A or Volunteer');
    }
  }

  @isTest
  public static void getRelatedFiles_ReturnsRelatedRecords_ForTrainer() {
    RelatedObjects related = getRelatedFilesWithGroups(new List<string>{ 'Trainer' });

    System.assertEquals(6, related.items.size(), 'should have 6 files returned');
    System.assertEquals(10, related.total, 'should have 10 total');
    Set<String> cats = new Set<String>{ 'N/A', 'Trainer' };
    for (Object obj : related.items) {
      FileInfo info = (FileInfo)obj;
      System.assert(cats.contains(info.category), 'should be N/A or Trainer');
    }
  }

  @isTest
  public static void getRelatedFiles_ReturnsRelatedRecords_ForTeam() {
    RelatedObjects related = getRelatedFilesWithGroups(new List<string>{ 'Team' });

    System.assertEquals(6, related.items.size(), 'should have 6 files returned');
    System.assertEquals(24, related.total, 'should have 24 total');
  }

  @isTest
  public static void getRelatedFiles_ReturnsRelatedRecords_ForBoardTrainer() {
    RelatedObjects related = getRelatedFilesWithGroups(new List<string>{ 'Board', 'Trainer' });

    System.assertEquals(6, related.items.size(), 'should have 6 files returned');
    System.assertEquals(15, related.total, 'should have 15 total');
  }

}