force-app/main/default/objects/Contact/fields/Positions__c.field-meta.xml
<CustomField>
    <fullName>Positions__c</fullName>
    <description>Positions available</description>
    <label>Positions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Positions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ShareWithBoard__c.field-meta.xml
<CustomField>
    <fullName>ShareWithBoard__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Share this contact with users in the Board group</description>
    <label>Share With Board</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ShareWithPuppyRaiser__c.field-meta.xml
<CustomField>
    <fullName>ShareWithPuppyRaiser__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Share this contact with users in the Puppy Raiser group</description>
    <label>Share With Puppy Raiser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ShareWithStaff__c.field-meta.xml
<CustomField>
    <fullName>ShareWithStaff__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Share this contact with users in the Staff group</description>
    <label>Share With Staff</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ShareWithStandalonePrograms__c.field-meta.xml
<CustomField>
    <fullName>ShareWithStandalonePrograms__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Share this contact with users in the Standalone Programs group</description>
    <label>Share With Standalone Programs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ShareWithTeam__c.field-meta.xml
<CustomField>
    <fullName>ShareWithTeam__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Share this contact with users in the Team group</description>
    <label>Share With Team</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ShareWithTrainer__c.field-meta.xml
<CustomField>
    <fullName>ShareWithTrainer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Share this contact with users in the Trainer group</description>
    <label>Share With Trainer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ShareWithVolunteer__c.field-meta.xml
<CustomField>
    <fullName>ShareWithVolunteer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Share this contact with users in the Volunteer group</description>
    <label>Share With Volunteer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contacts.recordType-meta.xml
<RecordType>
    <fullName>Contacts</fullName>
    <active>true</active>
    <label>Contacts</label>
</RecordType>

force-app/main/default/objects/npe4__Relationship__c/fields/npe4__Status__c.field-meta.xml
<CustomField>
    <fullName>npe4__Status__c</fullName>
    <description>Status of the Relationship.</description>
    <inlineHelpText>Status of the Relationship.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
                <default>true</default>
                <label>Current</label>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe4__Relationship__c/fields/npe4__Type__c.field-meta.xml
<CustomField>
    <fullName>npe4__Type__c</fullName>
    <description
  >Field that describes how the Related Contact is connected to the Contact.</description>
    <inlineHelpText
  >Field that describes how the Related Contact is connected to the Contact.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Friend</fullName>
            </value>
            <value>
                <fullName>Family</fullName>
            </value>
            <value>
                <fullName>Coworker</fullName>
            </value>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Son</fullName>
            </value>
            <value>
                <fullName>Daughter</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Aunt</fullName>
            </value>
            <value>
                <fullName>Uncle</fullName>
            </value>
            <value>
                <fullName>Husband</fullName>
            </value>
            <value>
                <fullName>Wife</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Cousin</fullName>
            </value>
            <value>
                <fullName>Grandmother</fullName>
            </value>
            <value>
                <fullName>Grandfather</fullName>
            </value>
            <value>
                <fullName>Grandparent</fullName>
            </value>
            <value>
                <fullName>Grandson</fullName>
            </value>
            <value>
                <fullName>Granddaughter</fullName>
            </value>
            <value>
                <fullName>Grandchild</fullName>
            </value>
            <value>
                <fullName>Employer</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Facilitator</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Team Faciliator</fullName>
            </value>
            <value>
                <fullName>Team Facilitator Lead</fullName>
            </value>
            <value>
                <fullName>Volunteer Lead</fullName>
            </value>
            <value>
                <fullName>Primary Emergency Contact</fullName>
            </value>
            <value>
                <fullName>Secondary Emergency Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Positions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Volunteer</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Board Member</fullName>
    </customValue>
    <customValue>
        <fullName>Trainer</fullName>
    </customValue>
    <customValue>
        <fullName>Client</fullName>
    </customValue>
    <customValue>
        <fullName>Donor</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
        <label>Staff/Contractor</label>
    </customValue>
    <customValue>
        <fullName>Puppy Raiser</fullName>
    </customValue>
    <customValue>
        <fullName>Standalone</fullName>
    </customValue>
    <customValue>
        <fullName>TSiM</fullName>
    </customValue>
    <description>Positions a contact can have</description>
    <masterLabel>Positions</masterLabel>
</GlobalValueSet>

force-app/main/test/TestContactSharing.cls
/*
 * This test class verifies code in ContactTrigger, RelationshipTrigger, and ContactService.
 * Because these three classes inter-relate so much (like Relationships),
 * Test for the desired combined behavior is here.
 */
@isTest
public with sharing class TestContactSharing    {
    // Test that the triggers produce the desired sharing
    static testMethod void shareContactBasedOnPositions_sharesClient() {
        // Arrange / Act
        setupBradyBunch();

        // Assert
        // Get the contacts with lastest sharing fields
        cindy = getContactWithShares(cindy.Id);
        marsha = getContactWithShares(marsha.Id);
        mike = getContactWithShares(mike.Id);
        carol = getContactWithShares(carol.Id);
        // check ShareWithTeam
        System.assert(cindy.ShareWithTeam__c);
        System.assert(marsha.ShareWithTeam__c);
        System.assert(mike.ShareWithTeam__c);
        System.assert(carol.ShareWithTeam__c);
    }

    static testMethod void shareContactBasedOnPositions_updatesShareForVolunteer() {
        // Arrange
        setupBradyBunch();
        ContactService.shareContactBasedOnPositions(cindy);
        cindy.Positions__c = 'Volunteer';

        // Act
        update cindy;

        // Assert
        // Get the contacts with lastest sharing fields
        cindy = getContactWithShares(cindy.Id);
        marsha = getContactWithShares(marsha.Id);
        mike = getContactWithShares(mike.Id);
        carol = getContactWithShares(carol.Id);
        // check ShareWithVolunteer
        System.assert(cindy.ShareWithVolunteer__c);
        System.assert(marsha.ShareWithVolunteer__c);
        System.assert(mike.ShareWithVolunteer__c);
        System.assert(carol.ShareWithVolunteer__c);
        // check ShareWithTeam
        System.assert(!cindy.ShareWithTeam__c);
        System.assert(!marsha.ShareWithTeam__c);
        System.assert(!mike.ShareWithTeam__c);
        System.assert(!carol.ShareWithTeam__c);
    }

    private static Contact getContactWithShares(Id contactId) {
        return [SELECT Id, ShareWithBoard__c, ShareWithPuppyRaiser__c, ShareWithStaff__c, ShareWithStandalonePrograms__c,
        ShareWithTeam__c, ShareWithTrainer__c, ShareWithVolunteer__c
        FROM Contact WHERE Id = :contactId];
    }

    private static Contact cindy;
    private static Contact marsha;
    private static Contact mike;
    private static Contact carol;
    private static Contact bobby;

    private static void setupBradyBunch() {
        TestUtilities.insertCategoryRules();

        // Select users for the test.
        List<User> users = [SELECT Id FROM User WHERE IsActive = TRUE LIMIT 2];

        // Create new Client
        cindy = new Contact(
            FirstName = 'Cindy',
            LastName = 'Brady',
            Email = 'janet@brady.com',
            Positions__c = 'Client'
        );

        // Create Emergency Contacts
        marsha = new Contact(
            FirstName = 'Marsha',
            LastName = 'Brady',
            Email = 'marsha@brady.com'
        );
        mike = new Contact(
            FirstName = 'Mike',
            LastName = 'Brady',
            Email = 'mike@brady.com'
        );

        // Create Guardian
        carol = new Contact(
            FirstName = 'Carol',
            LastName = 'Brady',
            Email = 'carol@brady.com'
        );

        // insert the contacts
        insert new List<Contact>{ cindy, marsha, mike, carol };

        // create the relationships
        npe4__Relationship__c emergency1 = new npe4__Relationship__c(
            npe4__Contact__c = marsha.Id,
            npe4__RelatedContact__c = cindy.Id,
            npe4__Type__c = 'Primary Emergency Contact',
            npe4__Status__c = 'Current'
        );
        npe4__Relationship__c emergency2 = new npe4__Relationship__c(
            npe4__Contact__c = mike.Id,
            npe4__RelatedContact__c = cindy.Id,
            npe4__Type__c = 'Secondary Emergency Contact',
            npe4__Status__c = 'Current'
        );
        npe4__Relationship__c guardian = new npe4__Relationship__c(
            npe4__Contact__c = carol.Id,
            npe4__RelatedContact__c = cindy.Id,
            npe4__Type__c = 'Guardian',
            npe4__Status__c = 'Current'
        );
        insert new List<npe4__Relationship__c>{
            emergency1,
            emergency2,
            guardian
        };
    }
}