force-app/main/default/objects/Contact/fields/Positions__c.field-meta.xml
<CustomField>
    <fullName>Positions__c</fullName>
    <description>Positions available</description>
    <label>Positions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Positions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ShareBoard__c.field-meta.xml
<CustomField>
    <fullName>ShareBoard__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Share this contact with users in the Board group</description>
    <label>Share With Board</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SharePuppyRaiser__c.field-meta.xml
<CustomField>
    <fullName>SharePuppyRaiser__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Share this contact with users in the Puppy Raiser group</description>
    <label>Share With Puppy Raiser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ShareStaff__c.field-meta.xml
<CustomField>
    <fullName>ShareStaff__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Share this contact with users in the Staff group</description>
    <label>Share With Staff</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ShareStandalonePrograms__c.field-meta.xml
<CustomField>
    <fullName>ShareStandalonePrograms__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Share this contact with users in the Standalone Programs group</description>
    <label>Share With Standalone Programs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ShareTeam__c.field-meta.xml
<CustomField>
    <fullName>ShareTeam__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Share this contact with users in the Team group</description>
    <label>Share With Team</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ShareTrainer__c.field-meta.xml
<CustomField>
    <fullName>ShareTrainer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Share this contact with users in the Trainer group</description>
    <label>Share With Trainer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ShareVolunteer__c.field-meta.xml
<CustomField>
    <fullName>ShareVolunteer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Share this contact with users in the Volunteer group</description>
    <label>Share With Volunteer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/ContentVersion/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Board</fullName>
            </value>
            <value>
                <fullName>Na</fullName>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Client</fullName>
                <label>Team Client</label>
            </value>
            <value>
                <fullName>TeamDog</fullName>
                <label>Team Dog</label>
            </value>
            <value>
                <fullName>TeamDog</fullName>
                <label>Team Dog</label>
            </value>
            <value>
                <fullName>Standalone</fullName>
                <label>Standalone Programs</label>
            </value>
            <value>
                <fullName>ADSiM</fullName>
                <label>Assistance Dogs Set in Motion</label>
            </value>
            <value>
                <fullName>Facilitator</fullName>
                <label>Team Facilitator</label>
            </value>
            <value>
                <fullName>Puppy</fullName>
                <label>Puppy Raiser</label>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
                <label>Staff/Contractor</label>
            </value>
            <value>
                <fullName>Dog</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Document Date</description>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Positions__c.field-meta.xml
<CustomField>
    <fullName>Positions__c</fullName>
    <description>Positions the Course is Applicable to</description>
    <label>Positions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Positions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PreApplication</fullName>
                <label>Pre Application</label>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>ContactForm</fullName>
                <label>Contact Form</label>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>CoI</fullName>
                <label>Conflict of Interest</label>
            </value>
            <value>
                <fullName>ToN</fullName>
                <label>Transmission of Notices</label>
            </value>
            <value>
                <fullName>LOMI</fullName>
                <label>Medical Provider Form</label>
            </value>
            <value>
                <fullName>Media</fullName>
                <label>Media Release</label>
            </value>
            <value>
                <fullName>VAPW</fullName>
                <label>Veteran Paperwork</label>
            </value>
            <value>
                <fullName>Survey</fullName>
                <label>Certification Survey</label>
            </value>
            <value>
                <fullName>Reference</fullName>
                <label>Reference Letter</label>
            </value>
            <value>
                <fullName>ClientReference</fullName>
                <label>Client Reference Letter</label>
            </value>
            <value>
                <fullName>ProfReference</fullName>
                <label>Professional Reference Letter</label>
            </value>
            <value>
                <fullName>ProgAgreement</fullName>
                <label>Program Agreement</label>
            </value>
            <value>
                <fullName>CertAgreement</fullName>
                <label>Certification Agreement</label>
            </value>
            <value>
                <fullName>Practicum</fullName>
            </value>
            <value>
                <fullName>InfrNotice</fullName>
                <label>Infraction Notice</label>
            </value>
            <value>
                <fullName>HealthForm</fullName>
                <label>Vet Health Form</label>
            </value>
            <value>
                <fullName>Notes</fullName>
                <label>Interview Notes</label>
            </value>
            <value>
                <fullName>Xray</fullName>
                <label>Vet Xray Report</label>
            </value>
            <value>
                <fullName>VacExams</fullName>
                <label>Vaccinations and Exams</label>
            </value>
            <value>
                <fullName>Resume</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
                <label>Offer Letter</label>
            </value>
            <value>
                <fullName>W4</fullName>
            </value>
            <value>
                <fullName>I9</fullName>
            </value>
            <value>
                <fullName>W9</fullName>
                <label>Contractor W9</label>
            </value>
            <value>
                <fullName>ApplicationVideo</fullName>
                <label>Application Video</label>
            </value>
            <value>
                <fullName>CGCForm</fullName>
                <label>CGC Form</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Positions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Volunteer</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator</fullName>
    </customValue>
    <customValue>
        <fullName>Team Facilitator Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Board Member</fullName>
    </customValue>
    <customValue>
        <fullName>Trainer</fullName>
    </customValue>
    <customValue>
        <fullName>Client</fullName>
    </customValue>
    <customValue>
        <fullName>Donor</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
        <label>Staff/Contractor</label>
    </customValue>
    <customValue>
        <fullName>Puppy Raiser</fullName>
    </customValue>
    <customValue>
        <fullName>Standalone</fullName>
    </customValue>
    <customValue>
        <fullName>TSiM</fullName>
    </customValue>
    <description>Positions a contact can have</description>
    <masterLabel>Positions</masterLabel>
</GlobalValueSet>

force-app/main/test/TestFileControllerRestrictions.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 *
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestFileControllerRestrictions {
    class MyPickListInfo {
        public Boolean active;
        public Boolean defaultValue;
        public String label;
        public String validFor;
        public String value;
    }
    public static Map<String, List<String>> getCategoryTypeDependencies() {
        Map<String, List<String>> controllingInfo = new Map<String, List<String>>();

        Schema.SObjectType objType = Schema.getGlobalDescribe()
            .get('ContentVersion');

        Schema.DescribeSObjectResult describeResult = objType.getDescribe();
        Schema.DescribeFieldResult controllingFieldInfo = describeResult.fields.getMap()
            .get('Category__c')
            .getDescribe();
        Schema.DescribeFieldResult dependentFieldInfo = describeResult.fields.getMap()
            .get('Type__c')
            .getDescribe();

        List<Schema.PicklistEntry> controllingValues = controllingFieldInfo.getPicklistValues();
        List<Schema.PicklistEntry> dependentValues = dependentFieldInfo.getPicklistValues();

        for (Schema.PicklistEntry currControllingValue : controllingValues) {
            controllingInfo.put(
                currControllingValue.getValue(),
                new List<String>()
            );
        }

        for (Schema.PicklistEntry currDependentValue : dependentValues) {
            String jsonString = JSON.serialize(currDependentValue);

            MyPickListInfo info = (MyPickListInfo) JSON.deserialize(
                jsonString,
                MyPickListInfo.class
            );

            String hexString = EncodingUtil.convertToHex(
                    EncodingUtil.base64Decode(info.validFor)
                )
                .toUpperCase();

            Integer baseCount = 0;

            for (Integer curr : hexString.getChars()) {
                Integer val = 0;

                if (curr >= 65) {
                    val = curr - 65 + 10;
                } else {
                    val = curr - 48;
                }

                if ((val & 8) == 8) {
                    controllingInfo.get(
                            controllingValues[baseCount + 0].getValue()
                        )
                        .add(currDependentValue.getValue());
                }
                if ((val & 4) == 4) {
                    controllingInfo.get(
                            controllingValues[baseCount + 1].getValue()
                        )
                        .add(currDependentValue.getValue());
                }
                if ((val & 2) == 2) {
                    controllingInfo.get(
                            controllingValues[baseCount + 2].getValue()
                        )
                        .add(currDependentValue.getValue());
                }
                if ((val & 1) == 1) {
                    controllingInfo.get(
                            controllingValues[baseCount + 3].getValue()
                        )
                        .add(currDependentValue.getValue());
                }

                baseCount += 4;
            }
        }

        return controllingInfo;
    }
    public static List<ContentVersion> insertRecords() {
        // get a map of the category and type labels
        Map<String, List<String>> allCategories = getCategoryTypeDependencies();
        List<ContentVersion> documents = new List<ContentVersion>();
        Integer count = 1;
        for (String category : allCategories.keySet()) {
            List<String> types = allCategories.get(category);
            for (String docType : types) {
                List<Object> parameters = new List<Object>{ count };
                documents.add(
                    new ContentVersion(
                        Title = String.format('TestDocument{0}', parameters),
                        PathOnClient = String.format(
                            'TestDocument{0}.jpg',
                            parameters
                        ),
                        Origin = 'H',
                        VersionData = Blob.valueOf('Document Body'),
                        Category__c = category,
                        Type__c = docType,
                        Date__c = Date.today().addDays(-count)
                    )
                );
                count = count + 1;
            }
        }

        insert documents;

        // We need to do the query here to get the ContentDocumentId's
        documents = [
            SELECT
                Id,
                ContentDocumentId,
                Title,
                PathOnClient,
                Origin,
                VersionData,
                Category__c,
                Type__c,
                Date__c
            FROM ContentVersion
        ];
        return documents;
    }

    // This method is used to setup the getRelatedFilesWith... tests.  The file records have all category/type combinations
    private static RelatedObjects getRelatedFilesWithGroups(string[] groups) {
        TestUtilities.insertCategoryRules();

        List<ContentVersion> documents = insertRecords();

        // Get the ids of all these documents
        List<Id> ids = new List<Id>();
        for (ContentVersion cv : documents) {
            ids.add(cv.ContentDocumentId);
        }
        Contact ronan = new Contact(
            FirstName = 'Ronan',
            LastName = 'Dax',
            email = 'ronan@test.com',
            Positions__c = 'Board Member;Client;Puppy Raiser;Standalone;Staff;Team Facilitator;Team Facilitator Lead;Trainer;Volunteer',
            ShareBoard__c = true,
            SharePuppyRaiser__c = true,
            ShareStaff__c = true,
            ShareStandalonePrograms__c = true,
            ShareTeam__c = true,
            ShareTrainer__c = true,
            ShareVolunteer__c = true
        );
        insert ronan;
        FileController.relateFiles(ids, ronan.Id);

        User testUser = TestUtilities.createUser('Standard User');
        TestUtilities.addUserToGroups(testUser, groups);
        RelatedObjects related = new RelatedObjects();
        Test.startTest();
        System.runAs(new User(Id = testUser.Id)) {
            related = FileController.getRelatedFiles(ronan.Id, 6);
        }
        Test.stopTest();

        return related;
    }

    @isTest
    public static void getRelatedFiles_ReturnsRelatedRecords_ForAll() {
        RelatedObjects related = getRelatedFilesWithGroups(
            new List<string>{ 'Board', 'Volunteer', 'Trainer' }
        );
        System.assert(related.items.size() < 6);
        System.assertEquals(3, related.total);
    }

    @isTest
    public static void getRelatedFiles_ReturnsRelatedRecords_ForBoard() {
        RelatedObjects related = getRelatedFilesWithGroups(
            new List<string>{ 'Board' }
        );

        System.assertEquals(1, related.items.size());
        System.assertEquals(1, related.total);
        System.assertEquals('Board', ((FileInfo) related.items[0]).category);
    }

    @isTest
    public static void getRelatedFiles_ReturnsRelatedRecords_ForVolunteer() {
        RelatedObjects related = getRelatedFilesWithGroups(
            new List<string>{ 'Volunteer' }
        );

        System.assertEquals(1, related.items.size());
        System.assertEquals(1, related.total);
        System.assertEquals(
            'Volunteer',
            ((FileInfo) related.items[0]).category
        );
    }

    @isTest
    public static void getRelatedFiles_ReturnsRelatedRecords_ForStaff() {
        RelatedObjects related = getRelatedFilesWithGroups(
            new List<string>{ 'Trainer' }
        );

        System.assertEquals(1, related.items.size());
        System.assertEquals(1, related.total);
        System.assertEquals('Trainer', ((FileInfo) related.items[0]).category);
    }

    @isTest
    public static void getRelatedFiles_ReturnsRelatedRecords_ForNone() {
        RelatedObjects related = getRelatedFilesWithGroups(
            new List<string>{ 'Team' }
        );

        System.assertEquals(0, related.items.size());
        System.assertEquals(0, related.total);
    }

    @isTest
    public static void getRelatedFiles_ReturnsRelatedRecords_ForBoardTrainer() {
        RelatedObjects related = getRelatedFilesWithGroups(
            new List<string>{ 'Board', 'Trainer' }
        );

        System.assertEquals(2, related.items.size());
        System.assertEquals(2, related.total);
    }
}