force-app/main/default/objects/Contact/fields/TSiMApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>TSiMApplicationReceived__c</fullName>
    <description>The date the most recent version of a Standalone Program Application was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last TSiM Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TSiMProgAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>TSiMProgAgreementReceived__c</fullName>
    <description
    >The date the most recent version of Teams Set in Motion Program Agreement was uploaded</description>
    <label>Last TSiM Program Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/ContentVersion/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Board</fullName>
            </value>
            <value>
                <fullName>Na</fullName>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Client</fullName>
                <label>Team Client</label>
            </value>
            <value>
                <fullName>TeamDog</fullName>
                <label>Team Dog</label>
            </value>
            <value>
                <fullName>TeamDog</fullName>
                <label>Team Dog</label>
            </value>
            <value>
                <fullName>Standalone</fullName>
                <label>Standalone Programs</label>
            </value>
            <value>
                <fullName>ADSiM</fullName>
                <label>Assistance Dogs Set in Motion</label>
            </value>
            <value>
                <fullName>Facilitator</fullName>
                <label>Team Facilitator</label>
            </value>
            <value>
                <fullName>Puppy</fullName>
                <label>Puppy Raiser</label>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
                <label>Staff/Contractor</label>
            </value>
            <value>
                <fullName>Dog</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PreApplication</fullName>
                <label>Pre Application</label>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>ContactForm</fullName>
                <label>Contact Form</label>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>CoI</fullName>
                <label>Conflict of Interest</label>
            </value>
            <value>
                <fullName>ToN</fullName>
                <label>Transmission of Notices</label>
            </value>
            <value>
                <fullName>LOMI</fullName>
                <label>Medical Provider Form</label>
            </value>
            <value>
                <fullName>Media</fullName>
                <label>Media Release</label>
            </value>
            <value>
                <fullName>VAPW</fullName>
                <label>Veteran Paperwork</label>
            </value>
            <value>
                <fullName>Survey</fullName>
                <label>Certification Survey</label>
            </value>
            <value>
                <fullName>Reference</fullName>
                <label>Reference Letter</label>
            </value>
            <value>
                <fullName>ClientReference</fullName>
                <label>Client Reference Letter</label>
            </value>
            <value>
                <fullName>ProfReference</fullName>
                <label>Professional Reference Letter</label>
            </value>
            <value>
                <fullName>ProgAgreement</fullName>
                <label>Program Agreement</label>
            </value>
            <value>
                <fullName>CertAgreement</fullName>
                <label>Certification Agreement</label>
            </value>
            <value>
                <fullName>Practicum</fullName>
            </value>
            <value>
                <fullName>InfrNotice</fullName>
                <label>Infraction Notice</label>
            </value>
            <value>
                <fullName>HealthForm</fullName>
                <label>Vet Health Form</label>
            </value>
            <value>
                <fullName>Notes</fullName>
                <label>Interview Notes</label>
            </value>
            <value>
                <fullName>Xray</fullName>
                <label>Vet Xray Report</label>
            </value>
            <value>
                <fullName>VacExams</fullName>
                <label>Vaccinations and Exams</label>
            </value>
            <value>
                <fullName>Resume</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
                <label>Offer Letter</label>
            </value>
            <value>
                <fullName>W4</fullName>
            </value>
            <value>
                <fullName>I9</fullName>
            </value>
            <value>
                <fullName>W9</fullName>
                <label>Contractor W9</label>
            </value>
            <value>
                <fullName>ApplicationVideo</fullName>
                <label>Application Video</label>
            </value>
            <value>
                <fullName>CGCForm</fullName>
                <label>CGC Form</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/test/files/TestClearDateServiceTSiMFields.cls
@isTest
public with sharing class TestClearDateServiceTSiMFields {

    @isTest
    public static void clearDate_TSiMApplication_SetsDateToNull() {
        ContentVersion cv = new ContentVersion(Category__c = 'TSiM', Type__c = 'Application');
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert record;
        ClearDateService.clear(cv, record.Id);

        record = [
            SELECT TSiMApplicationReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            null,
            record.TSiMApplicationReceived__c,
            'TSiMApplicationReceived__c not cleared'
        );
    }

    @isTest
    public static void clearDate_TSiMProgAgreement_SetsDateToNull() {
        ContentVersion cv = new ContentVersion(Category__c = 'TSiM', Type__c = 'ProgAgreement');
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert record;
        ClearDateService.clear(cv, record.Id);

        record = [
            SELECT TSiMProgAgreementReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            null,
            record.TSiMProgAgreementReceived__c,
            'TSiMProgAgreementReceived__c not cleared'
        );
    }
}