force-app/main/default/objects/Contact/fields/TSiMApplicationReceived__c.field-meta.xml
<CustomField>
    <fullName>TSiMApplicationReceived__c</fullName>
    <description>The date the most recent version of a Standalone Program Application was uploaded</description>
    <inlineHelpText>Set at the time of file upload. Do not edit directly.</inlineHelpText>
    <label>Last TSiM Application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TSiMProgAgreementReceived__c.field-meta.xml
<CustomField>
    <fullName>TSiMProgAgreementReceived__c</fullName>
    <description
    >The date the most recent version of Teams Set in Motion Program Agreement was uploaded</description>
    <label>Last TSiM Program Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/test/files/TestFileServiceTSiMFields.cls
@isTest
public with sharing class TestFileServiceTSiMFields {


    @isTest
    public static void updateDate_TSiMApplication_SetsDateWhenNull() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('TSiM', 'Application', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT TSiMApplicationReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.TSiMApplicationReceived__c,
            'TSiMApplicationReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_TSiMApplication_SetsDateWhenNewer() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', TSiMApplicationReceived__c = Date.today().addDays(-1));
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('TSiM', 'Application', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT TSiMApplicationReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.TSiMApplicationReceived__c,
            'TSiMApplicationReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_TSiMApplication_LeavesDateWhenOlder() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', TSiMApplicationReceived__c = Date.today());
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('TSiM', 'Application', Date.today().addDays(-1), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT TSiMApplicationReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.TSiMApplicationReceived__c,
            'TSiMApplicationReceived__c set to an older date'
        );
    }

    @isTest
    public static void updateDate_TSiMProgAgreement_SetsDateWhenNull() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com');
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('TSiM', 'ProgAgreement', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT TSiMProgAgreementReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.TSiMProgAgreementReceived__c,
            'TSiMProgAgreementReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_TSiMProgAgreement_SetsDateWhenNewer() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', TSiMProgAgreementReceived__c = Date.today().addDays(-1));
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('TSiM', 'ProgAgreement', Date.today(), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT TSiMProgAgreementReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.TSiMProgAgreementReceived__c,
            'TSiMProgAgreementReceived__c not set'
        );
    }

    @isTest
    public static void updateDate_TSiMProgAgreement_LeavesDateWhenOlder() {
        Contact record = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'abc@abc.com', TSiMProgAgreementReceived__c = Date.today());
        insert record;
        ContentVersion cv = TestFileServiceFields.createLink('TSiM', 'ProgAgreement', Date.today().addDays(-1), record.Id);
        FileService.updateDate(cv, record.Id);

        record = [
            SELECT TSiMProgAgreementReceived__c
            FROM Contact
            WHERE Id = :record.Id
            LIMIT 1
        ];
        system.assertEquals(
            Date.today(),
            record.TSiMProgAgreementReceived__c,
            'TSiMProgAgreementReceived__c set to an older date'
        );
    }
}