force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contacts.recordType-meta.xml
<RecordType>
    <fullName>Contacts</fullName>
    <active>true</active>
    <label>Contacts</label>
</RecordType>

force-app/main/default/objects/ContinuingEducationUnit__c/ContinuingEducationUnit__c.object-meta.xml
<CustomObject>
    <description>Continuing Education Units</description>
    <label>CEU</label>
    <nameField>
        <label>CEU Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEUs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ContinuingEducationUnit__c/fields/Authority__c.field-meta.xml
<CustomField>
    <fullName>Authority__c</fullName>
    <label>CUE Authority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Atlas</fullName>
                <default>true</default>
                <label>Atlas</label>
            </value>
            <value>
                <fullName>KPA</fullName>
            </value>
            <value>
                <fullName>CCPDT</fullName>
            </value>
            <value>
                <fullName>IAABC</fullName>
            </value>
            <value>
                <fullName>CBCC</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContinuingEducationUnit__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/ContinuingEducationUnit__c/fields/DateCompleted__c.field-meta.xml
<CustomField>
    <fullName>DateCompleted__c</fullName>
    <label>Date Completed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ContinuingEducationUnit__c/fields/DateSubmitted__c.field-meta.xml
<CustomField>
    <fullName>DateSubmitted__c</fullName>
    <label>Date Submitted</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ContinuingEducationUnit__c/fields/ProgramDate__c.field-meta.xml
<CustomField>
    <fullName>ProgramDate__c</fullName>
    <label>Program Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ContinuingEducationUnit__c/fields/ProgramHours__c.field-meta.xml
<CustomField>
    <fullName>ProgramHours__c</fullName>
    <label>Program Hours</label>
    <precision>5</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContinuingEducationUnit__c/fields/ProgramTitle__c.field-meta.xml
<CustomField>
    <fullName>ProgramTitle__c</fullName>
    <label>Program Title</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContinuingEducationUnit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContinuingEducationUnit__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Trainer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CEUs</relationshipLabel>
    <relationshipName>CEUs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trainer__c/Trainer__c.object-meta.xml
<CustomObject>
    <label>Trainer</label>
    <nameField>
        <label>Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/test/TestCeuController.cls
@isTest
public with sharing class TestCeuController {

    private static Contact ace;
    private static Contact cookie;
    private static ContinuingEducationUnit__c aceCeu;
    private static ContinuingEducationUnit__c cookieCeu1;
    private static ContinuingEducationUnit__c cookieCeu2;

    static void setup() {
        List<Contact> contacts = new List<Contact>();
        ace = new Contact(FirstName = 'Ace', LastName = 'GSD');
        cookie = new Contact(FirstName = 'Cookie', LastName = 'Monster');
        contacts.add(ace);
        contacts.add(cookie);
        insert contacts;

        List<ContinuingEducationUnit__c> ceus = new List<ContinuingEducationUnit__c>();
        aceCeu = new ContinuingEducationUnit__c(
            Authority__c = 'Atlas',
            Comments__c = 'Comments1',
            DateCompleted__c = Date.today().addMonths(-1),
            DateSubmitted__c = Date.today().addMonths(-1),
            ProgramDate__c = Date.today().addDays(-22),
            ProgramHours__c = 20,
            ProgramTitle__c = 'A Day in the Life of a Dog',
            Quantity__c = 20,
            Role__c = 'Presenter',
            Status__c = 'Approved',
            Trainer__c = ace.Id);
        ceus.add(aceCeu);

        cookieCeu1 = new ContinuingEducationUnit__c(
            Authority__c = 'KPA',
            Comments__c = 'Comments2',
            DateCompleted__c = Date.today().addMonths(-2),
            DateSubmitted__c = Date.today().addMonths(-2),
            ProgramDate__c = Date.today().addDays(-20),
            ProgramHours__c = 10,
            ProgramTitle__c = 'A Day in the Life of a Trainer',
            Quantity__c = 2,
            Role__c = 'Attendee',
            Status__c = 'Pending',
            Trainer__c = cookie.Id);
        ceus.add(cookieCeu1);

        cookieCeu2 = new ContinuingEducationUnit__c(
            Authority__c = 'CCPDT',
            Comments__c = 'Comments3',
            DateCompleted__c = Date.today().addMonths(-3),
            DateSubmitted__c = Date.today().addMonths(-3),
            ProgramDate__c = Date.today().addDays(-30),
            ProgramHours__c = 30,
            ProgramTitle__c = 'A Day in the Life of a Cookie',
            Quantity__c = 3,
            Role__c = 'Attendee',
            Status__c = 'Denied',
            Trainer__c = cookie.Id);
        ceus.add(cookieCeu2);

        insert ceus;
    }

    private static void ceusMatch(ContinuingEducationUnit__c expected, ContinuingEducationUnit__c actual) {
        System.assertEquals(expected.Authority__c, actual.Authority__c);
        System.assertEquals(expected.Comments__c, actual.Comments__c);
        System.assertEquals(expected.DateCompleted__c, actual.DateCompleted__c);
        System.assertEquals(expected.DateSubmitted__c, actual.DateSubmitted__c);
        System.assertEquals(expected.ProgramDate__c, actual.ProgramDate__c);
        System.assertEquals(expected.ProgramHours__c, actual.ProgramHours__c);
        System.assertEquals(expected.ProgramTitle__c, actual.ProgramTitle__c);
        System.assertEquals(expected.Quantity__c, actual.Quantity__c);
        System.assertEquals(expected.Role__c, actual.Role__c);
        System.assertEquals(expected.Trainer__c, actual.Trainer__c);
    }

    @isTest
    public static void getRelatedCeus_ReturnsRelated() {
        setup();
        List<ContinuingEducationUnit__c> ceus = ContinuingEducationUnitController.getRelatedCeus(ace.Id);

        System.assertEquals(1, ceus.size(), 'Wrong number of CEUs');
        ContinuingEducationUnit__c ceu = ceus[0];
        ceusMatch(aceCeu, ceu);
    }
    
    @isTest
    public static void getRelatedCeus_ReturnsRelatedList() {
        setup();
        List<ContinuingEducationUnit__c> ceus = ContinuingEducationUnitController.getRelatedCeus(cookie.Id);

        System.assertEquals(2, ceus.size(), 'Wrong number of CEUs');
        ceusMatch(cookieCeu1, ceus[0]);
        ceusMatch(cookieCeu2, ceus[1]);
    }

    @isTest
    public static void createCeu_ReturnsError() {
        ContinuingEducationUnit__c ceu = new ContinuingEducationUnit__c();
        Boolean hasError = false;
        try {
            ContinuingEducationUnit__c newCeu = ContinuingEducationUnitController.createCeu(ceu, null);
        } catch (Exception exc) {
            hasError = true;
        }
        System.assert(hasError);
    }
    
    @isTest
    public static void createCeu_LinksDocument() {
        setup();
        List<ContentVersion> cvs = TestFileController.insertRecords();
        ContinuingEducationUnit__c ceu = new ContinuingEducationUnit__c(
            Authority__c = 'IAABC',
            Comments__c = 'Comments4',
            DateCompleted__c = Date.today().addMonths(-4),
            DateSubmitted__c = Date.today().addMonths(-4),
            ProgramDate__c = Date.today().addDays(-44),
            ProgramHours__c = 4,
            ProgramTitle__c = 'A Day in the Life of a Cookie4',
            Quantity__c = 4,
            Role__c = 'Attendee',
            Status__c = 'Approved',
            Trainer__c = ace.Id
        );
        List<Id> documentIds = new List<Id>();
        for (ContentVersion cv: cvs) {
            documentIds.add(cv.ContentDocumentId);
        }
        ContinuingEducationUnit__c newCeu = ContinuingEducationUnitController.createCeu(ceu, documentIds);

        RelatedObjects relatedCvs = FileController.getRelatedFiles(newCeu.Id, 6);
        System.assertEquals(cvs.size(), relatedCvs.items.size());
        System.assertEquals(cvs.size(), relatedCvs.total);

        for (Integer idx = 0; idx < cvs.size(); idx++) {
            ContentVersion expected = cvs[idx];
            ContentVersion actual = (ContentVersion)relatedCvs.items[idx];
            //system.assertEquals(expected.ContentDocumentId, actual.ContentDocumentId);
        }
    }

    @isTest
    public static void updateCeu_Updates() {
        setup();
        string COMMENT = 'constant comment';
        aceCeu.Comments__c = COMMENT;

        ContinuingEducationUnit__c ceu = ContinuingEducationUnitController.updateCeu(aceCeu);

        ceusMatch(aceCeu, ceu);
    }

    @isTest
    public static void updateCeu_ReturnsError() {
        setup();
        aceCeu.Status__c = 'Wrong';
        Boolean hasError = false;
        try {
            ContinuingEducationUnit__c ceu = ContinuingEducationUnitController.updateCeu(aceCeu);
        }
        catch (Exception exc) {
            hasError = true;
        }
        System.assert(hasError);
    }

    @isTest
    public static void deleteCeu_Deletes() {
        setup();
        ContinuingEducationUnitController.deleteCeu(aceCeu.Id);
        List<ContinuingEducationUnit__c> remaining = [SELECT Id FROM ContinuingEducationUnit__c WHERE Id = :aceCeu.Id];
        System.assertEquals(0, remaining.size());
    }

    @isTest
    public static void deleteCeu_ReturnsError() {
        setup();
        Boolean hasError = false;
        try {
            ContinuingEducationUnitController.deleteCeu('InvalidId');
        }
        catch (Exception exc) {
            hasError = true;
        }
        System.assert(hasError);
    }
}