force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description
    >Records detailing information about dogs being utilized by clients and trainers</description>
    <label>Dog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dog__c/fields/PhysicalExamDue__c.field-meta.xml
<CustomField>
    <fullName>PhysicalExamDue__c</fullName>
    <description>Date the next physical examination is due</description>
    <label>Physical Exam Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/VaccineDueDistemper__c.field-meta.xml
<CustomField>
    <fullName>VaccineDueDistemper__c</fullName>
    <description>Date next Distemper vaccination is due</description>
    <label>Distemper Vaccine Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/VaccineDueHepatitis__c.field-meta.xml
<CustomField>
    <fullName>VaccineDueHepatitis__c</fullName>
    <description>Date next Hepatitis/Adenovirus vaccination is due</description>
    <label>Hepatitis/Adenovirus Vaccination Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/VaccineDueParainfluenza__c.field-meta.xml
<CustomField>
    <fullName>VaccineDueParainfluenza__c</fullName>
    <description>Date next Parainfluenza vaccine is due</description>
    <label>Parainfluenza Vaccine Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/VaccineDueParvovirus__c.field-meta.xml
<CustomField>
    <fullName>VaccineDueParvovirus__c</fullName>
    <description>Date next Parvovirus vaccination is due</description>
    <label>Parvovirus Vaccine Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/VaccineDueRabies__c.field-meta.xml
<CustomField>
    <fullName>VaccineDueRabies__c</fullName>
    <description>Date next Rabies vaccination is due</description>
    <label>Rabies Vaccine Due</label>
    <type>Date</type>
</CustomField>

force-app/main/test/TestDogController.cls
@isTest
public with sharing class TestDogController {
    public TestDogController() {
    }

    @isTest
    public static void getVaccinations_ReturnsVaccinations() {
        // Arrange
        Date exam = Date.newInstance(2021, 1, 10);
        Date due = exam.addYears(1);
        Dog__c saved = new Dog__c(
            VaccineDueDistemper__c = due,
            VaccineDueHepatitis__c = due,
            VaccineDueParainfluenza__c = due,
            VaccineDueParvovirus__c = due,
            VaccineDueRabies__c = exam.addYears(2)
        );
        insert saved;

        // Act
        Test.startTest();
        Dog__c dog = DogController.getVaccinations(saved.Id);
        Test.stopTest();
    }

    @isTest
    public static void getVaccinations_ReturnsNulls_WhenNoVaccinations() {
        // Arrange
        Dog__c saved = new Dog__c(Name = 'Labrador');
        insert saved;

        // Act
        Test.startTest();
        Dog__c dog = DogController.getVaccinations(saved.Id);
        Test.stopTest();

        System.assertEquals(null, dog.VaccineDueDistemper__c);
        System.assertEquals(null, dog.VaccineDueHepatitis__c);
        System.assertEquals(null, dog.VaccineDueParainfluenza__c);
        System.assertEquals(null, dog.VaccineDueParvovirus__c);
        System.assertEquals(null, dog.VaccineDueRabies__c);
        System.assertEquals(null, dog.PhysicalExamDue__c);
    }

    @isTest
    public static void getVaccinations_ReturnsNotFound_WhenNoDog() {
        // Arrange
        Contact joe = new Contact(FirstName = 'Joe', LastName = 'Blow');
        insert joe;

        // Act
        Test.startTest();
        String message;
        try {
            Dog__c dog = DogController.getVaccinations(joe.Id);
        } catch (AuraHandledException exc) {
            message = exc.getMessage();
        }
        Test.stopTest();

        System.assertEquals('Dog not found.', message);
    }
}